### ISSUE TITLE
Crostini (Chromebook)

### ISSUE THREAD

**Issue by Nefcairon** [exercism/cli#1019]
Hello,

Is there a way to install exercism-cli on Crostini (Linux of Chromebooks)?

**Comment by kotp** [comment]
Sent out a ping on [gitter/exercism] to maybe get this heard by more people.

[gitter/exercism]: https://gitter.im/exercism/support

**Comment by ynfle** [comment]
@Nefcairon Have you tried? What issues have you come across?

**Comment by Nefcairon** [comment]
I've been at https://github.com/exercism/cli/releases/tag/v3.0.13 but there's no version for Debian 10.

**Comment by ynfle** [comment]
You don't need a version for Debian 10. The linux versions should work, just pick the correct cpu you are on

**Comment by Nefcairon** [comment]
I tried it with exercism-linux-64bit.tgz 
I could open it via ```tar -zxvf exercism-linux-64bit.tgz```
but then I didn't know what to do with the decompressed files.

**Comment by ynfle** [comment]
Have you taken a look https://exercism.org/cli-walkthrough

**Comment by Nefcairon** [comment]
Argh, thanks for pointing at that.
I missed to continue from "Getting the Executable"... Sorry for that.

**Comment by ynfle** [comment]
No problem! Happy it was resolved
