### ISSUE TITLE
Exercise download, connection refused

### ISSUE THREAD

**Issue by rogermungo** [exercism/cli#1029]
Earlier today, this worked fine
`exercism download --exercise=raindrops --track=bash`

But now when I try
`exercism download --exercise=hamming --track=bash`

I get the following:
Error: Get https://api.exercism.io/v1/solutions/latest?exercise_id=hamming&track_id=bash: dial tcp: lookup api.exercism.io on 10.0.2.2:53: read udp 10.0.2.15:35638->10.0.2.2:53: read: connection refused

This appears the same or similar to #390 
But I dont think it applies to me
1) It worked the first time I downloaded an exercise
2) I'm running Debian not Ubuntu
3) The solution was to remove /etc/resolv.conf (a regular file) and replace it by a symlink to /run/systemd/resolve/stub-resolv.conf .. My system does not have this 'resolve' folder let alone the stub-resolv.conf file

The system I am on is a VirtualBox VM

Any help would be appreciated

**Comment by rogermungo** [comment]
I found the problem..
My /etc/resolv.conf file had reverted back..
Added 
nameserver 8.8.8.8
and now it works

**Comment by rogermungo** [comment]
And here some solutions to prevent resolv.conf reverting back
https://www.vultr.com/docs/stop-dhcp-from-changing-resolve-conf/
Method 3 looks the cleanest

**Comment by ForensicITGuy** [comment]
If you happen to have installed exercism via the Snap package this may also be an issue. There are potential issues with snap packages on systems using systemd-resolved https://github.com/nextcloud-snap/nextcloud-snap/issues/881#issuecomment-615760548
