### ISSUE TITLE
Token is invalid error. Tried multiple ones

### ISSUE THREAD

**Issue by dzalf** [exercism/cli#1043]
Hi guys

I am facing this issue despite trying with multiple tokens

![image](https://user-images.githubusercontent.com/3759916/172052604-5cde13e0-2f56-48a4-9fc3-47ec50db8262.png)

I attempted using both Powershell and strangely on cmd is even worse:

![image](https://user-images.githubusercontent.com/3759916/172052734-e0283184-04f1-4589-ab5d-aaa63a823499.png)

I am using the latest version of the cli. Here is the debug results screen:

![image](https://user-images.githubusercontent.com/3759916/172053114-ec797b78-0b07-4a98-9e80-46c6e7f97d05.png)

Am I missing something? I have the feeling that I am doing something _really_ dumb in here.

Thank you, guys!

**Comment by NobbZ** [comment]
On top of what andrerfcsantos said, please make sure you have reset your token once again, such that it is not equal to any you have in the screenshots here, the token should be kept secret like a password!

**Comment by dzalf** [comment]
Geez! What a n00b thing I was doing...

Thanks for your help guys

@NobbZ suer thing, I will change it right away!

**Comment by dzalf** [comment]
Apologies for not closing this earlier. It worked just fine as you instructed

:wink:
