### ISSUE TITLE
Is the file size restriction still correct?

### ISSUE THREAD

**Issue by m-dango** [exercism/cli#1047]
I'm experimenting with bundling dependencies with solutions. The CLI flagged that having a file larger than 65535 bytes is a problem, but it looks like its possible to upload larger files without issue (one I uploaded was 142049 bytes).

Is 65535 bytes still a necessary restriction for V3?

Relating to https://github.com/exercism/cli/issues/717.

**Comment by iHiD** [comment]
I've continued the conversation in the forum: https://forum.exercism.org/t/request-to-add-modules-to-the-test-runner/1686/3
