### ISSUE TITLE
Installation should use some kind of package manager

### ISSUE THREAD

**Issue by erikbgithub** [exercism/cli#105]
Otherwise how would I update? Nobody reinstalls tools again and again, if they are already installed once. Like, how do I install a go program usually as a go developer? Is there a way like with python and pip?

**Comment by Tonkpils** [comment]
This has been resolved with the `upgrade` command.

**Comment by erikb85** [comment]
Could you link issues, commits or something? Haven't been following closely enough to know about this command.

**Comment by Tonkpils** [comment]
Sure, I'll go ahead and do it once I have access to a computer.

**Comment by kytrinyx** [comment]
Here you go: https://github.com/exercism/cli/pull/196 https://github.com/exercism/cli/issues/61

**Comment by erikb85** [comment]
Cool thanks!

**Comment by educastro** [comment]
Why there is not .deb package available? Is there any restriction? 

This semester I have a class that requires a final project and I am thinking about use this opportunity to create something to exercism, maybe the debian package. What do you think about it?

**Comment by kytrinyx** [comment]
Hi @educastro, there's no restriction. It's mostly a matter of what people have requested and what we have documented. If you would like to work on this, would you help figure out what it would take to release the .deb package every time we release a new version of the CLI?

We've had trouble in the past when we either don't know how to release new versions of the CLI to 3rd party package managers, or we simply don't have access.

**Comment by educastro** [comment]
@kytrinyx Amazing! So I'll work on this during the next weeks and try to figure out this issue with updates! Any updates or doubt I'll post it here :)

**Comment by kytrinyx** [comment]
Yay, thank you @educastro! :heart:

**Comment by jtigger** [comment]
Here there, @educastro!  Any updates?

**Comment by kytrinyx** [comment]
I accidentally reopened this. It's actually resolved.
