### ISSUE TITLE
Broken links in CLI repo's contributing guide

### ISSUE THREAD

**Issue by resnickmicah** [exercism/cli#1055]
In the [CLI repo's contributing guide](https://github.com/exercism/cli/blob/main/CONTRIBUTING.md), there are two broken links to the docs repo: https://github.com/exercism/docs/blob/master/about/glossary.md and https://github.com/exercism/docs/blob/main/about/architecture.md

I thought maybe they were moved to different folders in this repo, but after searching all filenames via Github's "go to file" I didn't see any docs with a similar name. I can open a PR in the CLI repo to remove those links if you'd like.

**Comment by SleeplessByte** [comment]
Closed by #1064
