### ISSUE TITLE
Setup goreleaser to update homebrew

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/cli#1102]
See https://goreleaser.com/customization/homebrew/

**Comment by baduker** [comment]
If this is still required, I'd be more than willing to take this on, given that I have some spare time and am already collaborating with @nywilken on this #1117.

**Comment by ErikSchierboom** [comment]
Yes, please!

**Comment by baduker** [comment]
@ErikSchierboom I've opened a PR for the requested changes. One section of the code is prefilled with dummy values.

```
    commit_author:
      name: goreleaserbot
      email: goreleaserbot@exercism.org
```

Can you please tell me what the correct `name` and `email` values should be?

**Comment by ErikSchierboom** [comment]
That would be:

GIT_USERNAME: "Exercism Bot"
GIT_EMAIL: "66069679+exercism-bot@users.noreply.github.com"

**Comment by baduker** [comment]
Thanks @ErikSchierboom! I've answered your question in the PR, too.

**Comment by baduker** [comment]
@ErikSchierboom Thanks for merging this! I'm so excited that I've contributed to `exercism`. I'd be happy to help out more!

**Comment by baduker** [comment]
@ErikSchierboom Thanks for merging this! So excited that I've contributed to `exercism`. I'd be happy to help more!
