### ISSUE TITLE
Hard to tell which problems have been solved, which problem you are on

### ISSUE THREAD

**Issue by ccnp123** [exercism/cli#130]
I came across this issue organically... I banged out a bunch of Haskell exercises, fetched the next one, went away for a few days, and when I came back and saw the list of exercise directories, I realized I had no clue which exercise I was supposed to be working on. I had to go through each folder and jog my memory.

Thankfully, I had not created a solution file so it was easy to tell which problem I was on. However, if I had already created my solution file, you can imagine how difficult it would be then... I guess I would have to try submitting everything until it doesn't whine that I have already submitted that file.

Solving this issue takes a little bit of thought, and there are a number of potential solutions that I was brainstorming:

 - Organize the top level into two folders: "Solved" and "Unsolved", move problems around as appropriate
 - Append ".solved" to the folder name after submitting (but then the program doesn't understand the path, this would be easy to tweak though)
 - Make a copy of the folder with ".solved" appended (but then the list of folders will get very large and ugly)
 - Do a folder rename/copy thing using numbers instead of "solved" so that the problems will sort ( but double digit numbers don't sort well :( )
 - Implement a cli command to display the path to the current problem "exercism haskell current"
 
These are the things I was going to play around with in my fork. Let's brainstorm some more and figure out an appropriate solution.

**Comment by Tonkpils** [comment]
On this note, with #155 the `fetch` command now returns a list of problems that have not been submitted.  I think we could still benefit from having a `current` command as per #137. @ccnp123 did you have any other ideas you wanted to share or solutions from your fork?

**Comment by kytrinyx** [comment]
Thanks, @ccnp123 for taking the time to work on this, and for sparking the discussion that led to a fix. I'm going to close this, but do feel free to open a new issue if you have further thoughts/ideas.
