### ISSUE TITLE
Add a "current" command?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#137]
https://github.com/exercism/exercism.io/issues/1972

When working in multiple languages, or when you come back to exercism after a spell away from it, it can be tricky to figure out what you were working on.

It's possible to sort directories by date (`ls -ct`), but it would be handy to be told directly what's still in the works.

**Comment by Carpetsmoker** [comment]
If you use `fetch, it actually shows you which one to use:

    Not Submitted: 21 problems
                   Bob (clojure) /home/martin/exercism/clojure/bob
              Bob (coffeescript) /home/martin/exercism/coffeescript/bob
                       Bob (cpp) /home/martin/exercism/cpp/bob
	[...]

I think it would help a lot to just change the output slightly:

    Not Submitted: 21 problems
        clojure (Bob)            /home/martin/exercism/clojure/bob
        coffeescript (Bob)       /home/martin/exercism/coffeescript/bob
        cpp (Bob)                /home/martin/exercism/cpp/bob
	[...]

This makes it a lot easier to scan for the language you want, that's the first thing I usuaully want to know, I don't care so much about the text name.

Perhaps it could also be extended to show the test number, for example maybe like:

    Not Submitted: 21 problems
        clojure (Exercise 2: Bob)            /home/martin/exercism/clojure/bob
        coffeescript (Exercise 5: Bob)       /home/martin/exercism/coffeescript/bob
        cpp (Exercise 1: Bob)                /home/martin/exercism/cpp/bob
	[...]

**Comment by kytrinyx** [comment]
The exercises aren't actually numbered (you can do them out of order by asking for them directly, and the order can change, and these changes aren't tracked).

I think we could sort them by the date of when the directory was created, which can work as a sort of proxy.

I think it makes a lot of sense to change the display to put the language first.

**Comment by fluxusfrequency** [comment]
That will work in some cases, but not if someone has their exercises on github and clones them down to a second machine.

**Comment by kytrinyx** [comment]
Yeah, that's true. I won't bother with the sorting thing.

Having thought about it, I still think that "current" would be useful, but I think that improving the ability to scan for language will help, so I'll fix that.

**Comment by NobbZ** [comment]
I just skipped some exercises in various languages and now came to a point where I skipped the last exercise in a track. The cli seems to think that I have finished that track, and doesn't show it any more after I do `exercism f`. Perhaps display the first skipped exercise of the track again as the current unsubmitted one?

Or extend the cli, so that it can show a list of all skipped exercises?

**Comment by kytrinyx** [comment]
Yeah--we should probably do both of those things. I'll add an issue for the skipped command.

**Comment by carlisia** [comment]
Do we still want to add the `current` command?

**Comment by kytrinyx** [comment]
I think we still do. I suspect that it's probably time to take a step back and think a little bit about the overall user experience with the CLI, but providing a way to give the user a good idea of what's currently going on would be really great.

**Comment by carlisia** [comment]
I've read this issue and a couple others requiring the same thing. What is the definition of `current`? Is it: the very last exercise that the user saved on their machine but did not submit?

**Comment by Tonkpils** [comment]
> What is the definition of current? Is it: the very last exercise that the user saved on their machine but did not submit?

I'm not 100% sure on what we would want `current` to be but I don't think we can assume it's the last exercise saved on the machine as they may have other machines with different `current` exercises saved. 

What are the current states an exercise can be in? It may help us understand if `current` is a single or multiple exercises.

**Comment by kytrinyx** [comment]
I think the original idea with `current` was _help me figure out where I left off_.

How about:

- only include languages where you have submitted at least one iteration of something
- tell you what you most recently submitted (one per language)
- tell you what you have fetched but not submitted (could be multiple per language)

**Comment by kytrinyx** [comment]
Closing. Superseded by #223
