### ISSUE TITLE
[discussion] How can we improve the output of 'fetch'

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#150]
On several occasions I've gotten support requests (usually by email, but sometimes also in GitHub issues, e.g. https://github.com/exercism/exercism.io/issues/2160) where they can't fetch more exercises, even though they've presumably done all of the ones that they've fetched.

Usually what seems to have happened is that they fetched:

```
unchanged: 22, updated: 0, new: 0 
```

It turns out that there's one problem that is unsubmitted, but they have no way of figuring that out.

What would be some ways to let them know what to do next or figure out what problem they have fetched but not worked on or submitted?

[edit: this relates to #130]

**Comment by Tonkpils** [comment]
We could use some sort of indicator from the API that lets us know which problems have not been completed or submitted. Once we have that we'd be able to give feedback on unfinished problems.  Does the API have that information available?

**Comment by kytrinyx** [comment]
The ExercismIO API does, the XAPI does not. That's fine -- we can ask both places, or XAPI can ask ExercismIO.

**Comment by Tonkpils** [comment]
I have something working for this. We can iterate over the message being displayed but it looks something like this.

```sh
$ out/exercism fetch ruby

                    New: 11 problems
          Anagram (ruby) /Users/tonkpils/exercism/ruby/anagram
        Beer Song (ruby) /Users/tonkpils/exercism/ruby/beer-song
              Bob (ruby) /Users/tonkpils/exercism/ruby/bob
     Grade School (ruby) /Users/tonkpils/exercism/ruby/grade-school
          Hamming (ruby) /Users/tonkpils/exercism/ruby/hamming
 Nucleotide Count (ruby) /Users/tonkpils/exercism/ruby/nucleotide-count
     Phone Number (ruby) /Users/tonkpils/exercism/ruby/phone-number
Rna Transcription (ruby) /Users/tonkpils/exercism/ruby/rna-transcription
       Robot Name (ruby) /Users/tonkpils/exercism/ruby/robot-name
       Word Count (ruby) /Users/tonkpils/exercism/ruby/word-count
       Gigasecond (ruby) /Users/tonkpils/exercism/ruby/gigasecond

unchanged: 0, updated: 0, new: 11

The following exercises have not been completed:
Gigasecond (ruby)
```

```sh
% out/exercism fetch ruby

unchanged: 11, updated: 0, new: 0

The following exercises have not been completed:
Gigasecond (ruby)
```

Right now I'm just displaying the output of the `Problem` struct but of course this can be improved. I haven't thought of a different way to display this. If you have any suggestions that'd be great. 

We can also tag that list of uncompleted items as not accepted or submitted. 

I'm going to clean up the code a bit and submit a pull request but meanwhile any feedback on the current message is appreciated.

**Comment by kytrinyx** [comment]
> We can also tag that list of uncompleted items as not accepted or submitted.

I'm not sure what you mean, can you elaborate?

> any feedback on the current message is appreciated. 

I think we should include the path to where that problem lives, since at the very start of doing exercism stuff people don't have any reason to know where to look for the test suites.

**Comment by Tonkpils** [comment]
Apologies for the misunderstanding, what I meant was that currently it just displays the name of an uncompleted exercise. But you can end up with something like this:

```sh
out/exercism fetch ruby

unchanged: 12, updated: 0, new: 0

The following items have not been submitted
Gigasecond (ruby)
Raindrops (ruby)
```

Where the Gigasecond was submitted but hasn't been accepted as complete and the Raindrops was just fetched and it has not been submitted.

What I meant was that we could also specify next to the exercise wether its been submitted for acceptance or not submitted yet. But now that I think about it I guess it would be ok to not specify it and let the user figure it out on their own. What do you think?

As for the path, I'll include it no problem!

**Comment by kytrinyx** [comment]
Oh, right! Thanks.

> Another option would be to only show the one that is holding them back from fetching the next one which means the unsubmitted one. What do you think?

Yeah, this is the most important thing.

**Comment by Tonkpils** [comment]
With #155 we ensure the user knows which problems have not been submitted from the fetched ones. This helps when the user is not sure why new problems are not being fetched. If this is still an issue, we can revisit. Closing this for now.

**Comment by kytrinyx** [comment]
Thanks, yeah I think this is good for now!
