### ISSUE TITLE
Even after deleting an exercise it's considered solved

### ISSUE THREAD

**Issue by magthe** [exercism/cli#156]
In testing stuff related to #152 I found this slightly strange behaviour:

1. Fetch a new exercise.  (It gave me `clojure/beer-song`.)
2. Solve the exercise.
3. Submit the solution.
4. Log in on the web site and delete the solution.
5. Go back to the command line and remove all solutions for the language. (`rm -fr clojure` for me.)
6. Restore gives all the solved exercises, and as expected the deleted one is *not* included.  (`exercism r`)
7. Fetch a new exercise and you now get two!

*Observed behaviour*

The final step gives me two new exercises to solve, in my case both `clojure/beer-song` and `clojure/nucleotide-count`.

*Expected behaviour*

I was expecting to get only the next unsolved exercise, i.e. the one I just deleted `clojure/beer-song`.

**Comment by kytrinyx** [comment]
I've implemented it this way on purpose. Essentially if you've unlocked an exercise, then we'll never lock it back up for you.

I'm happy to discuss pros/cons of both choices.

**Comment by magthe** [comment]
As long as it's deliberate.  I just surprised *me*, but that is far from the same that the behaviour is wrong ;)

**Comment by kytrinyx** [comment]
Ok cool :) I'll leave it for now, then. Thanks for bringing it up.
