### ISSUE TITLE
Should we delete accidental binaries from git history?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#158]
I am working on creating the changelog for the project, and realised that in the early days I accidentally committed the entire exercism binary. It got removed in 63094ebe6a221d7c7b06842ec57dfc0fceb73397 but this still means that a checkout of the project is going to be much, much bigger than it has to be.

If we do this, then everyone who wants to contribute would need to do a hard reset on the master branch before continuing. I don't see it as being a huge deal, as we don't get that many people contributing regularly, but it could be frustrating/confusing.

For what it's worth here's what I would run:

```
# ensure this happens on an up-to-date master
git checkout master && git fetch origin && git reset --hard origin/master

# delete from history
git filter-branch --index-filter 'git rm -r --cached --ignore-unmatch go-exercism' --prune-empty

# clean up
rm -rf .git/refs/original/
git reflog expire --all
git gc --aggressive --prune

# push up the new master, force override existing master branch
git push -fu origin master
```

And the commands that each contributor would need to run is

```
git checkout master
git fetch upstream master
git reset --hard upstream/master
git push -fu origin master
```

We could @ mention each person who is watching the repo (26 people at the time of writing this) and everyone who has a fork (74 people).

What do you think?

/cc @Tonkpils, @lcowell

**Comment by lcowell** [comment]
I'm up for doing this, but I don't have any experience with this sort of thing other than a small team. This trimmed my `.git` folder from `12MB` to `2MB` - `10MB` savings. If it was `100MB` savings, it would be really easy to justify this. 10MB just isn't that much. If we proceed, it would be better to notify people. It's easy to delete an email, and someone could waste time trying to figure out why their pull request has 355 extra commits in it.

**Comment by kytrinyx** [comment]
10 MB isn't a whole lot... but it's over 80% of the size of the repo. That feels kind of significant to me.

When you say _notify people_, do you mean send individual emails? Mentioning them in this thread would notify them either by email or on GitHub.

I'm not saying I have my heart set on it, I just wanted to bring it up.

**Comment by Tonkpils** [comment]
I like the idea of downsizing the repo size. Under normal conditions 10 MB wouldn't be that big but on slow connections this could take quite some time. Mentioning people here would be good. 

I'm :+1: for this though.

**Comment by lcowell** [comment]
Yeah, I meant just to mention them in the thread and let github figure out how they want to be contacted.

I would also :+1:  this.

**Comment by kytrinyx** [comment]
OK, cool, I'll do it in the morning when my brain is fresh. Thanks, all!

**Comment by kytrinyx** [comment]
Eh, I overslept. I'll try again tomorrow!

**Comment by kytrinyx** [comment]
FYI - we're rewriting the history of this repository in order to remove an accidentally committed binary, causing the repository to be far larger than necessary.

If you're mentioned below it's because you're either watching the repository, or because you currently have a fork.

If you are going to contribute a patch, then you'll need to jump through a couple of hoops to get in sync with the upstream:

```
git checkout master
git fetch upstream master
git reset --hard upstream/master
git push -fu origin master
```

Or, you could delete your local repository and your fork and fork/clone again.

/cc @1nv4d3r5 @BarristanSelmy @BhanuprakashVc @DaddyJack @Darkpaw95 @EECE-310-14-Project @Egimba @ForbesLindesay @FriarTech @Gankedbym0m @IbrahimOluwadamilare @JLCeasar @KaiKogure @Rosalita @SaiVardhan @SierraS @Spinarooni @Thaymes @Tonkpils @Wolfmaster013 @an0nym0use @andrewsardone @anoo @arminrez @arvind-sim @atonb117 @autodidacticon @bgrooven @briehman @ccnp123 @codepolish @confoundedjoe @corylanou @craignicol @csbruun @cyniu @damorton @davidyang @derekparker @dpritchett @drueck @ebautistabar @eccstartup @ekul81 @elberskirch @elimisteve @espears @falsifian @firefl1es @franksmithworld @gojobis @harimp @hucky8 @icehofman @janderse @jeminlee @jish @johnnyRose @kenny-chen @kms617 @ksolo @laranea @lcowell @marcosvm @markwhiskey @mattetti @mewkiz84 @mkeesey @morphatic @mothercode @mrdougwright @mstrstvns @myappleguy @nf @ngpestelos @nick11roberts @orendon @pilou15 @pminten @pombredanne @rajibmitra @rax313 @ricardillo @rprouse @rsslldnphy @scalp42 @simonjefford @snasikkar @speedymaan @srt32 @subbub @wgriffiths @wobh @ziahmiller

**Comment by scalp42** [comment]
:+1:
