### ISSUE TITLE
disambiguate debug command from debug flag

### ISSUE THREAD

**Issue by lcowell** [exercism/cli#160]
I'm wondering if we should rename the debug flag from `--debug` to `--verbose`. The reason I'm suggesting this is that we also have a `exercism debug` command. This seems unnecessarily confusing.

The shorthand of debug is `-d` and so we'd also want to add a shorthand of verbose, but setting it to `-v` would conflict with the `--version, -v` flag. So, we'd have to eliminate the shorthand for version or come up with some alternate shorthand.

Does anyone have any thoughts on this ?

**Comment by Tonkpils** [comment]
I'm not opposed to removing the shorthand version of `--version` option. For most CLIs that use `-v` for verbose they use either `-V` for version shorthand or just require `--version`.

**Comment by kytrinyx** [comment]
Yeah, let's require `--version`, and have `--verbose` and `-v` for verbose.
