### ISSUE TITLE
respect $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#161]
@JulianAndrews makes a good point about supporting XDG_CONFIG_HOME on systems where it's set.

See https://github.com/exercism/exercism.io/issues/2212

**Comment by joneshf** [comment]
:+1: anything we can do to move this along?

**Comment by kytrinyx** [comment]
No need to apologize--it's a tiny fix, we've just been swamped. The fix would need to go here: https://github.com/exercism/cli/blob/master/config/config.go#L70

To support the XDG_CONFIG_HOME if available, and fall back to regular env, which then falls back to a default in the home directory.

**Comment by Tonkpils** [comment]
I've been a bit swamped with work. I have one feature almost complete here and I can move onto this issue if no one has gotten to it by then.

**Comment by joneshf** [comment]
Well, I was going to attempt to tackle this, but I can't get passed step 5. `go get` just tells me:

```
can't load package: package github.com/exercism/cli: no buildable Go source files in /home/joneshf/programming/go/stuff/src/github.com/exercism/cli
```

I've no experience with go, so I'll probably just wait for the change.

**Comment by Tonkpils** [comment]
@joneshf if you're running into any issues on the setup following the README, I'd be glad to help out. are you running `go get` from within the project's directory?

**Comment by joneshf** [comment]
Yep, just copy paste and modify for my username in step 4.

Everything else ran normally.

**Comment by Tonkpils** [comment]
Use `go get ./...`

That will go into every sub-package in the project and fetch each of the dependencies. The README will need to be updated to reflect this. 

Let me know how it works and if you run into any other issues.

**Comment by joneshf** [comment]
Got to the point of running `glitch`, it fails with the following information:

```
2015/03/23 13:33:24 glitch: building
2015/03/23 13:33:24 glitch: build OK - vetting
2015/03/23 13:33:24 glitch: vet OK - testing
# github.com/exercism/cli/api
api/api_test.go:12:2: cannot find package "github.com/stretchr/testify/assert" in any of:
	/usr/lib/go/src/github.com/stretchr/testify/assert (from $GOROOT)
	/home/joneshf/programming/go/stuff/src/github.com/stretchr/testify/assert (from $GOPATH)
FAIL	github.com/exercism/cli/api [setup failed]
# github.com/exercism/cli/config
api/api_test.go:12:2: cannot find package "github.com/stretchr/testify/assert" in any of:
	/usr/lib/go/src/github.com/stretchr/testify/assert (from $GOROOT)
	/home/joneshf/programming/go/stuff/src/github.com/stretchr/testify/assert (from $GOPATH)
FAIL	github.com/exercism/cli/config [setup failed]
ok  	github.com/exercism/cli/cmd	0.002s
?   	github.com/exercism/cli/exercism	[no test files]
ok  	github.com/exercism/cli/user	0.002s
2015/03/23 13:33:24 glitch: failed
```

**Comment by joneshf** [comment]
In any case, after installing  (just copying what the travis file does) I get more errors when I run `glitch` or `go test ./...`:

```
2015/03/23 13:36:43 glitch: building
2015/03/23 13:36:43 glitch: build OK - vetting
2015/03/23 13:36:43 glitch: vet OK - testing
ok  	github.com/exercism/cli/api	0.009s
ok  	github.com/exercism/cli/cmd	0.002s
--- FAIL: TestLoad (0.00s)
	config_test.go:21: link /home/joneshf/programming/go/stuff/src/github.com/exercism/cli/fixtures/config.json /tmp/877770574/config.json: invalid cross-device link
FAIL
FAIL	github.com/exercism/cli/config	0.003s
?   	github.com/exercism/cli/exercism	[no test files]
ok  	github.com/exercism/cli/user	0.002s
2015/03/23 13:36:44 glitch: failed
```

Same error either way.

**Comment by Tonkpils** [comment]
`go get` by default doesn't not pull test dependencies. Run `go get -t ./...` If you're running Go v1.4. Otherwise you'll need to go get testify manually according to the README.

**Comment by kytrinyx** [comment]
I'll fix the README. Glitch is handy but not necessary.

**Comment by kytrinyx** [comment]
This is fixed in master, but has gone into a release yet.
