### ISSUE TITLE
GetAddrInfoW: A non-recoverable error occurred during a database lookup

### ISSUE THREAD

**Issue by horatius83** [exercism/cli#168]
Error: 2015/03/13 12:14:24 Get http://x.exercism.io/v2/exercises/haskell?key=[secret api key]: dial tcp : GetAddrInfoW: A non-recoverable error occurred during a database lookup.

I recently upgraded to a new computer and I moved the location of the exercism.exe file. When I type the url "http://x.exercism.io/v2/exercises/haskellkey=<secret api key>" into Chrome I get JSON data as expected, so I can connect.

The issue seems to be with where the executable is located. If I run off the C drive like so (powershell):

```
Q:\exercism> $exercism = "C:\Users\horatius83\Desktop\exercism.exe"
Q:\exercism> & $exercism fetch haskell
```

It runs fine, but when I run off a networked drive I get the error above. 

```
Q:\exercism> .\exercism.exe fetch haskell
2015/03/13 12:14:24 Get http://x.exercism.io/v2/exercises/haskellkey=<secret api key>: dial tcp :       
GetAddrInfoW: A non-recoverable error occurred during a database lookup.
```

**Comment by kytrinyx** [comment]
What do you get if you say `exercism debug` -- is it able to connect?

Apparently DNS resolution involves environment variables on Windows, but I don't understand the details of this yet.

**Comment by horatius83** [comment]
This is what it produced:

**** Debug Information ****
Exercism CLI Version: 2.0.0
OS/Architecture: windows/amd64
Home Dir: C:\Users\horatius83
Config file: C:\Users\horatius83\.exercism.json
API Key: <secret>
API: http://exercism.io [Get http://exercism.io: dial tcp: GetAddrInfoW: A non-recoverable error occurred during a database lookup.]
XAPI: http://x.exercism.io [Get http://x.exercism.io: dial tcp: GetAddrInfoW: A non-recoverable error occurred during a database lookup.]
Exercises Directory: Q:\exercism

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).

**Comment by Tonkpils** [comment]
You're running the binary from a network drive correct?

**Comment by horatius83** [comment]
That is correct.

**Comment by kytrinyx** [comment]
What does debug say if you configure it to look at an IP address directly?

```
exercism configure --api=http://54.235.95.213/
```

How about a famous/common domain, e.g. google.com?

```
exercism configure --api=http://google.com/
```

**Comment by kytrinyx** [comment]
Do you have any firewall software running? Or any anti-virus stuff that might be interfering?

**Comment by horatius83** [comment]
PS Q:\exercism> .\exercism configure --api=http://54.235.95.213
The configuration has been written to C:\Users\horatius83\.exercism.json
Your exercism directory can be found at Q:\exercism
PS Q:\exercism> .\exercism debug

**** Debug Information ****
Exercism CLI Version: 2.0.0
OS/Architecture: windows/amd64
Home Dir: C:\Users\horatius83
Config file: C:\Users\horatius83\.exercism.json
API Key: [secret]
API: http://exercism.io [Get http://exercism.io: dial tcp: GetAddrInfoW: A
non-recoverable error occurred during a database lookup.]
XAPI: http://54.235.95.213 [Get http://54.235.95.213: dial tcp
54.235.95.213:80: An invalid argument was supplied.]
Exercises Directory: Q:\exercism

If you are having trouble and need to file a GitHub issue (
https://github.com/exercism/exercism.io/issues) please include this
information (except your API key. Keep that private).
PS Q:\exercism> .\exercism configure --api=http://google.com
The configuration has been written to C:\Users\horatius83\.exercism.json
Your exercism directory can be found at Q:\exercism
PS Q:\exercism> .\exercism debug

**** Debug Information ****
Exercism CLI Version: 2.0.0
OS/Architecture: windows/amd64
Home Dir: C:\Users\horatius83
Config file: C:\Users\horatius83\.exercism.json
API Key: [secret]
API: http://exercism.io [Get http://exercism.io: dial tcp: GetAddrInfoW: A
non-recoverable error occurred during a datab
ase lookup.]
XAPI: http://google.com [Get http://google.com: dial tcp: GetAddrInfoW: A
non-recoverable error occurred during a databa
se lookup.]
Exercises Directory: Q:\exercism

If you are having trouble and need to file a GitHub issue (
https://github.com/exercism/exercism.io/issues) please includ
e this information (except your API key. Keep that private).

I tried specifically adding exercism.exe to the allowed programs list of
windows firewall but I got the same result. Also the fact that it will run
off the C drive but not the networked drive makes me think it's not a
firewall / antivirus issue.

**Comment by kytrinyx** [comment]
>  Also the fact that it will run off the C drive but not the networked drive makes me think it's not a
firewall / antivirus issue.

Yeah, that does seem likely. Thanks for the extra information, I'll see what I can figure out.

**Comment by lcowell** [comment]
The error is originating from a function called `newLookupPort` or `newLookupIP` in `src/net/lookup_windows.go` in the go source. There are both called from `sysInit` in `fd_windows.go`. This is first called from `init` in `ipsock.go`.

I'm wondering if windows has some rules about what an executable running from a remote drive can do.

**Comment by lcowell** [comment]
My previous analysis was a bit off. The function is only assigned in sysInit/init, not called.

I found the identical error text here:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx#WSANO_RECOVERY

This seems like this could be related:
http://stackoverflow.com/questions/4368877/net-proccess-failing-dns-lookup-with-windows-7

**Comment by kytrinyx** [comment]
I'm giving this the 'bug' label, though I'm still not quite sure how to address it.

**Comment by Tonkpils** [comment]
I was digging through a bit of searches on Google for this issue.  It's pretty dated, but this https://github.com/golang/go/issues/5694#issuecomment-66080983 caught my attention. It's possible that running the binary from a network drive doesn't allow DNS resolution because of that? 

In any case, this seems to be an issue we can't fix from the CLI point of view. If it's ok with @horatius83 , I'd say the fix would be to just move the binary to a local drive and close this issue.

**Comment by kytrinyx** [comment]
That sounds reasonable to me. If we don't hear back within 7 days, let's close this anyhow (can always reopen later if we need to).

**Comment by Tonkpils** [comment]
Closing this since we haven't heard any feedback

**Comment by kytrinyx** [comment]
I accidentally re-opened this; re-closing.
