### ISSUE TITLE
Provide a useful error message if the config JSON is invalid

### ISSUE THREAD

**Issue by davidalpert** [exercism/cli#170]
just installed manually into my path on a Win64 machine running Windows 7.

````
$ exercism list
2015/03/22 19:51:00 invalid character 'e' in string escape code

$ exercism -v list
2015/03/22 19:51:51 invalid character 'e' in string escape code

$ exercism --version
exercism version 2.0.0

$ exercism configure
2015/03/22 20:04:44 invalid character 'e' in string escape code
````

**Comment by kytrinyx** [comment]
wow, that's kind of awful!

Is the binary actually called `exercism.exe` or something weird like that?

**Comment by davidalpert** [comment]
![image](https://cloud.githubusercontent.com/assets/43332/6773171/fe84b04e-d0da-11e4-9e37-4b0db5ed7756.png)

in my path.

**Comment by lcowell** [comment]
@davidalpert can you provide us with an `exercism debug` ?

**Comment by davidalpert** [comment]
````
$ exercism debug

**** Debug Information ****
Exercism CLI Version: 2.0.0
OS/Architecture: windows/amd64
Home Dir: D:\Users\David
2015/03/25 18:51:47 invalid character 'e' in string escape code

$ 
````

**Comment by kytrinyx** [comment]
Weird, it dies in the middle of the output, and it doesn't even log a failure.

Could you copy/paste the output of the json config file? It's usually called `.exercism.json` in the home directory.

**Comment by davidalpert** [comment]
well, now I feel silly.

that error message about an `invalid character 'e' in string escape code` was the result of a key-pair in my json config file that looked like this:

```
{... "dir":"D:\\Users\\David\\dev\exercism" ...}
```

notice the unescaped single backslash in the path? that was the invalid `\e` character complained about by the error message; I fixed it:

```
{... "dir":"D:\\Users\\David\\dev\\exercism" ...}
```

and it works fine.

I haven't worked with Go yet or I'd submit a pull request with the fix, or at least a failing test.

As a test case, run a command using a config file with an invalid path (e.g. an invalid `\e` escape code).

Perhaps wrapping that error in something more descriptive that points to the "dir" configuration entry?

**Comment by kytrinyx** [comment]
Yeah we should complain about invalid json in the config.
