### ISSUE TITLE
EXERCISM_CONFIG_FILE env should handled in app configuration

### ISSUE THREAD

**Issue by lcowell** [exercism/cli#172]
We have logic in the config package to check the `EXERCISM_CONFIG_FILE` environment variable and the provided path to determine when the config file lives. This is actually something that we can get for free from codegangsta/cli. This would clean up the config package and expose the environment variable in the app help output.

Any thoughts on this before I implement it ?

**Comment by Tonkpils** [comment]
I'd have to see the implementation to see what you mean. Or maybe point me in the direction of the pice of the CLI package the functionality that you're looking to implement?

Aside from that, I'm all for simplicity and readablilty and if this effort improved that, then I'm all for it!

Might this also be a good time to tackle #161 for the XDG_CONFIG_HOME?

**Comment by kytrinyx** [comment]
Yeah, if we can lean on existing functionality in codegangsta/cli, that would be great.

**Comment by lcowell** [comment]
@Tonkpils I'm referring to adding this type of option to our app config: https://github.com/codegangsta/cli#values-from-the-environment

```go
cli.StringFlag{
	Name:  "config, c",
	Usage: "path to config file",
	EnvVar: "EXERCISM_CONFIG_FILE",
},
```

I've built a couple of cli apps using it and it would work like this:
`command line option > environment variable > defaults`


I think the XDG_CONFIG_HOME would require a different approach. My understanding is that env variable points to a directory, so we'd still need to resolve it to a file path. These are closely related, so I think it only makes sense to move ahead with #172 if it doesn't complicate moving ahead with #161

I think this is doable because `cli` gives us the chance to process input flags before calling a command.

**Comment by Tonkpils** [comment]
Looks good to me :+1:

**Comment by kytrinyx** [comment]
Yepp, me too. Go for it.
