### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by rstackhouse** [exercism/cli#174]
Mon Mar 30 22:03:47:Downloads rstackhouse$ exercism fetch cpp

panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
strings.Repeat(0x38c6b0, 0x1, 0xfffffffffffffffb, 0x0, 0x0)
	/usr/local/go/src/strings/strings.go:458 +0x68
github.com/exercism/cli/user.(*Homework).heading(0xc20800ade0, 0x3, 0x1, 0x9)
	/Users/kytrinyx/code/go/src/github.com/exercism/cli/user/homework.go:115 +0x25e
github.com/exercism/cli/user.(*Homework).Report(0xc20800ade0, 0x3)
	/Users/kytrinyx/code/go/src/github.com/exercism/cli/user/homework.go:84 +0xbe
github.com/exercism/cli/user.(*Homework).Summarize(0xc20800ade0, 0x0)
	/Users/kytrinyx/code/go/src/github.com/exercism/cli/user/homework.go:137 +0x64
github.com/exercism/cli/cmd.Fetch(0xc20805a160)
	/Users/kytrinyx/code/go/src/github.com/exercism/cli/cmd/fetch.go:39 +0x709
github.com/codegangsta/cli.Command.Run(0x397270, 0x5, 0x3970f0, 0x1, 0x43cb30, 0x65, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/kytrinyx/code/go/src/github.com/codegangsta/cli/command.go:101 +0xe42
github.com/codegangsta/cli.(*App).Run(0xc208070000, 0xc20800a000, 0x3, 0x3, 0x0, 0x0)
	/Users/kytrinyx/code/go/src/github.com/codegangsta/cli/app.go:130 +0xb81
main.main()
	/Users/kytrinyx/code/go/src/github.com/exercism/cli/exercism/main.go:149 +0xb3f

goroutine 8 [IO wait]:
net.(*pollDesc).Wait(0xc208010290, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010290, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010230, 0xc2080a0000, 0x1000, 0x1000, 0x0, 0x711b88, 0xc20802b100)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802e060, 0xc2080a0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7131f0, 0xc20802e060, 0xc20805a318, 0xc2080a0000, 0x1000, 0x1000, 0x2e8460, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20801e760, 0xc2080a0000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20805c660)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20805c660, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20805a2c0)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 9 [select]:
net/http.(*persistConn).writeLoop(0xc20805a2c0)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 12 [runnable]:
net/http.(*persistConn).readLoop(0xc20805a580)
	/usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 13 [select]:
net/http.(*persistConn).writeLoop(0xc20805a580)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

**Comment by kytrinyx** [comment]
Thanks! What does `exercism debug` output?

**Comment by rstackhouse** [comment]
Tue Mar 31 22:25:15:~ rstackhouse$exercism debug

**** Debug Information ****
Exercism CLI Version: 2.0.1
OS/Architecture: darwin/amd64
Home Dir: /Users/rstackhouse
Config file: /Users/rstackhouse/.exercism.json
API Key: #############################
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: /Users/rstackhouse/exercism

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).
Tue Mar 31 22:25:23:~ rstackhouse$

**Comment by rstackhouse** [comment]
I ran `exercism demo` before `exercism fetch cpp`. Not sure if that has anything to do with this.

**Comment by lcowell** [comment]
I get the same error if I call `exercism fetch cpp`. Could this be a regression in multi-file support ?

**Comment by jamescowie** [comment]
I get the same issue as above. Mac OSX. Installed using homebrew

**Comment by kytrinyx** [comment]
I don't get the error. Weird. I suppose I might have built 2.0.1 with different code.

> Could this be a regression in multi-file support ?

Yeah, it could be.

I need to go to work, but I'll see about sorting this out tonight.

**Comment by kytrinyx** [comment]
I believe I have a fix for this. @lcowell would you mind building this locally and checking if it works for you?

**Comment by lcowell** [comment]
Looks good to me.

**Comment by kytrinyx** [comment]
Sweet. Cutting a release now.

**Comment by kytrinyx** [comment]
The release is up here: https://github.com/exercism/cli/releases/tag/v2.0.2 I'm submitting a fix to homebrew, but that tends to take a few days to go in.
