### ISSUE TITLE
Provide a useful error message if the EXERCISM_CONFIG_FILE points to a directory

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#176]
Someone reported the following:

> I get a message saying 'The handle is invalid' when doing anything

It turns out they had put a folder as the EXERCISM_CONFIG_FILE instead of the actual file

**Comment by lcowell** [comment]
I think I can take this on. I'll be using the same mechanism to turn XDG_CONFIG_HOME in to a full config path.

**Comment by kytrinyx** [comment]
nice, thanks
