### ISSUE TITLE
exercise download directory defaults to home dir

### ISSUE THREAD

**Issue by evelynmitchell** [exercism/cli#180]
This should be ask where you want them, then update config file. This should happen if there is no config file.

**Comment by evelynmitchell** [comment]
Note this is from the command line client, Linux binary.

**Comment by kytrinyx** [comment]
I don't want to default to having an interaction. Perhaps the default behavior could be to put it in /tmp if the CLI is unconfigured.

**Comment by Tonkpils** [comment]
If I understand correctly, `download` currently defaults to storing the files in the home directory?

What if instead we don't allow using the `download` command until you have the CLI configured? Otherwise, I like the `tmp` solution.

**Comment by kytrinyx** [comment]
How about the demo? It uses download, right?

**Comment by Tonkpils** [comment]
> How about the demo? It uses download, right?

Demo doesn't seem to use download.

**Comment by kytrinyx** [comment]
Ok, cool. It's probably simpler if we make you configure the client before downloading, in that case.

**Comment by Tonkpils** [comment]
@kytrinyx the problem is that configure actually defaults the exercism directory to the home directory if a directory is not provided during configuration.

**Comment by kytrinyx** [comment]
Oh, right. Hm. Should configure just not have a default and return an error if a dir is missing?

**Comment by Tonkpils** [comment]
Maybe a bit more verbosity on the steps during configure would be good? Specifying that any fetched/downloaded exercises will be stored in your exercism directory.

I think that having the default be the home directory is ok. 

@evelynmitchell are you sure that the configuration file didn't exist when you attempted to download? The latest version of the CLI should fail when calling `download` if the configuration doesn't exist. If it did exist then it would use the directory specified in it.

**Comment by evelynmitchell** [comment]
"@evelynmitchell are you sure that the configuration file didn't exist when you attempted to download?" Yes. The first activity I tried was the demo. No configuration.

**Comment by kytrinyx** [comment]
Yeah, the `demo` command definitely works without a config.

How about adding an optional `--dir` flag to the demo so that people can specify where the problems get written to?

**Comment by Tonkpils** [comment]
> How about adding an optional --dir flag to the demo so that people can specify where the problems get written to?

I think that's a good solution.
