### ISSUE TITLE
http://cli.exercism.io/install should be hosted on github and available over TLS

### ISSUE THREAD

**Issue by zmanian** [exercism/cli#183]
The default installation instructions  

```
curl -O http://cli.exercism.io/install
chmod +x install
./install
```
are unsafe. They permit an MITM to attack a user by modifying the install script in transit. As we've seen, developer machines are a high value target for attackers.

Install scripts should be hosted on an TLS server. 

Remedies

- Acquire an TLS cert for cli.exerercism.io subdomain

or.

- Host the install script on github

**Comment by kytrinyx** [comment]
The install script is already hosted on github, technically: https://raw.githubusercontent.com/exercism/cli-www/master/public/install

We can point to that instead of having it on the cli.exercism.io domain.

**Comment by kytrinyx** [comment]
I've updated the docs to point to the install script that is hosted on GitHub.

Thanks for the suggestion.
