### ISSUE TITLE
Loosen restriction of --test flag

### ISSUE THREAD

**Issue by Tonkpils** [exercism/cli#191]
From https://github.com/exercism/exercism.io/issues/2381#issuecomment-100293890

We should allow test files and exercise files to be submitted together if `--test` is enabled. 

Would it also make sense to rename the flag to `--with-test-files` or something similar?

**Comment by Tonkpils** [comment]
Another approach we could take is to have `--test` flag actually just be a flag to denote that the value of it its a test submission and we could do

```bash
exercism submit myfile.go --test extra_test.go --test another_test.go anotherfile.go
```

Thoughts?

**Comment by kytrinyx** [comment]
I prefer to simply loosen the restriction as with your first suggestion. I like the short `--test` flag rather than the longer one, but I'm open to discussing pros/cons there.

**Comment by Tonkpils** [comment]
The only con that I can see with the current name is that, as you saw in the issue in the exercism.io repo, the user thought the flag was meant to be used with an argument of the test file during multiple file submission. A pro of making the flag more descriptive be that it shows the intent of the flag in allowing test files to be submitted. 

Again this may be a one off issue so it may not be a big priority to make the flag more descriptive. I'll work on loosening up the restriction leaving the same flag name.

**Comment by kytrinyx** [comment]
Cool, yeah, this looks good. Let's see how that works before tweaking it.
