### ISSUE TITLE
Cannot configure directory with path relative to `~`

### ISSUE THREAD

**Issue by amar47shah** [exercism/cli#193]
After installing the exercism cli, I couldn't configure the exercism directory without specifying an absolute path.

In particular, I couldn't configure a path from the home directory using `~`, as in the example given in the configuration [instructions](http://help.exercism.io/configuring-the-cli.html).

(Using zsh on OS X.)
```
➜  ~  exercism configure —key=<my_key>
The configuration has been written to /Users/amar/.exercism.json
Your exercism directory can be found at /Users/amar/exercism

➜  ~  exercism configure --dir="~/my_awesome_exercism_submissions"
The configuration has been written to /Users/amar/.exercism.json
Your exercism directory can be found at ~/my_awesome_exercism_submissions
```
I expected this to set my exercism directory as `/Users/amar/my_awesome_exercism_submissions`.

Instead it created a subdirectory actually called `~` in my home folder, as the parent of my exercism directory.
```
➜  ~  cd ./\~/my_awesome_exercism_submissions 
➜  my_awesome_exercism_submissions  pwd
/Users/amar/~/my_awesome_exercism_submissions
```

This is what I had in `~/.exercism.json`:
```
{
  ...
  "dir": "~/my_awesome_exercism_submissions",
  ...
}
```

Using the absolute path fixed the problem:
```
➜  ~  exercism configure --dir="/Users/amar/my_awesome_exercism_submissions"
The configuration has been written to /Users/amar/.exercism.json
Your exercism directory can be found at /Users/amar/my_awesome_exercism_submissions
➜  ~  cat .exercism.json 
...
	"dir": "/Users/amar/my_awesome_exercism_submissions",
...
➜  ~  exercism fetch

Not Submitted:               23 problems
clojure (Bob)                /Users/amar/my_awesome_exercism_submissions/clojure/bob
...
```

Thanks, and sorry for being so verbose.

**Comment by kytrinyx** [comment]
Verbose is very useful, thanks for reporting this. I would have expected the code to replace `~/` correctly as well.

What version of exercism do you have? (`exercism -version`)

**Comment by Tonkpils** [comment]
I've confirmed the issue and have a patch ready. Updating a configuration wasn't expanding the home path.

**Comment by kytrinyx** [comment]
Ah, nice find!

**Comment by kytrinyx** [comment]
This is fixed in master, I'll put out a build in the next couple of days.

**Comment by amar47shah** [comment]
Thanks so much!
