### ISSUE TITLE
`exercism upgrade` throws an error

### ISSUE THREAD

**Issue by tejasbubane** [exercism/cli#202]
This is the error:

```
tejas@tejas-Presario-CQ62-Notebook-PC:~|
⇒  exercism --version
exercism version 2.2.0
tejas@tejas-Presario-CQ62-Notebook-PC:~|
⇒  exercism upgrade
2015/07/29 00:12:39 unable to get latest CLI release: Get https://api.github.com/repos/exercism/cli/releases/latest: net/http: request canceled while waiting for connection
```

I think it should display that I am running on the latest version if no upgrades are available.

**Comment by tejasbubane** [comment]
cc: @Tonkpils

**Comment by Tonkpils** [comment]
The issue seems to be Github is not responding within the specified timeout. We need to check the latest release version in order to assert you do have the latest version. 

I'll fix up the message to ensure it explains what is actually happening.

**Comment by Tonkpils** [comment]
It seems the timeout set for checking the latest release version was too low. I'll be releasing a new version which makes improvements to the upgrade command.
