### ISSUE TITLE
Instructions to submit exercise could be improved.

### ISSUE THREAD

**Issue by kotp** [exercism/cli#205]
I was trying exercism in the morning, submitting doesn't work.
 I had a relative path to the exercism folder
Maybe put a message when you set a path that it should be a full path and not a relative path.

**Comment by Tonkpils** [comment]
relates to #197

**Comment by Tonkpils** [comment]
Could you give me the output of the `exercism debug` without your API key and the error you were getting? If I'm not mistaken, if written correctly, the CLI should expand out relative paths.

**Comment by kotp** [comment]
Sorry, it was not my error, reported for someone else.  I will see if we can get more details.  @felipe-

**Comment by Tonkpils** [comment]
No problem, I'll work with the info you gave me for now. Thanks for the report!

**Comment by felipe-** [comment]
I had the issue. When submitting an exercise I got the following message: 
```
2015/07/27 07:55:45 lstat Desarrollo: no such file or directory I installed the exercism directory under my user/Desarrollo instead of the default path.
```
This is the conf I had at the moment.
```javascript
{                                                                                                                     
        "apiKey": "myapikey",                                                           
        "dir": "Desarrollo/exercism",                                                                                 
        "api": "http://exercism.io",                                                                               
        "xapi": "http://x.exercism.io"                                                                               
}
```
I replaced the dir value with a full path and now it works.

**Comment by kytrinyx** [comment]
@felipe- what does `exercism --version` give you? I think we fixed this at some point, but I want to be certain.

**Comment by felipe-** [comment]
2.2.0

**Comment by kytrinyx** [comment]
Thanks @felipe- it looks like we have a bug.

**Comment by kytrinyx** [comment]
@Tonkpils I think the issue is that the path was given relative to the present working directory rather than relative to the home directory:

```plain
exercism configure --dir=Something/exercism
```

as opposed to

```plain
exercism configure --dir=~/Something/exercism
```

**Comment by lcowell** [comment]
Do you think we need to change the behaviour to understand the location of the directory or do a better job of guarding against bad input?

Making a guess about what the user really means when they say `Something/exercism` seems like it opens us to future issues. Did the user mean `/home/user/Something/exercism` or did they mean `/home/Something/exercism`? I think we guard against bad input and help the user to correct the issue.

@kytrinyx you are correct. If I  changemy `dir` from `/Users/lukec/exercism` to `lukec/exercism`, I can reproduce the issue.

**Comment by kytrinyx** [comment]
I would say that if they don't add the `~` and it doesn't start with a `/`, then we would probably want to assume that it is relative to the current directory.

**Comment by lcowell** [comment]
If we check for those values at runtime, wouldn't it lead to issues like: "exercism only works when I'm in a particular directory" ? It could also lead to a user having 2 exercism directories which could be really confusing. I think it's better to catch the error early so we don't need to consider this edge case later one.

I'd agree with your suggestion if we did that check while the user was configuring exercism.

**Comment by kytrinyx** [comment]
> I'd agree with your suggestion if we did that check while the user was configuring exercism.

That's what I meant, actually :)
