### ISSUE TITLE
Short verbose flag '-v' doesn't work

### ISSUE THREAD

**Issue by zabawaba99** [exercism/cli#206]
If you specify the global option `-v` on any command it prints the version

```bash
$ exercism -v debug
exercism version 2.2.0
$ exercism -v submit
exercism version 2.2.0
```

I dug around a little it and it looks like [codegansta/cli](https://github.com/codegangsta/cli) checks for a few flags (`-v`) included when it [runs the app](https://github.com/codegangsta/cli/blob/master/app.go#L130). I don't see any way to support the `-v` at the moment without changes to codegansta/cli.

I'd be more than happy to make a PR to remove `-v` from the verbose option.

**Comment by zabawaba99** [comment]
It seems like the long flag name doesn't work either

```bash
$ exercism --verbose debug
exercism version 2.2.0
```

**Comment by Tonkpils** [comment]
Good catch, it seems that the references to the `debug` flag, now `verbose`, were not updated. We should update all the references to use the new "verbose" flag.

**Comment by zabawaba99** [comment]
There is actually an open issue for it on codegansta/cli https://github.com/codegangsta/cli/issues/254
