### ISSUE TITLE
Error parsing API response

### ISSUE THREAD

**Issue by jveiga** [exercism/cli#209]
Just after submitting a Clojure exercise, I did 
``` bash
exercism f
2015/08/09 19:44:21 error parsing API response - invalid character '<' looking for beginning of value```

**Comment by kytrinyx** [comment]
Thanks, looking into this now!

**Comment by kytrinyx** [comment]
This is a problem in the linux flavoured lisp track. To work around it until we can get it sorted, you can say `exercism f clojure` to get the next exercise.

**Comment by kytrinyx** [comment]
I've deployed a temporary fix until the LFE track maintainers can put in a proper fix. Thanks again for reporting this!
