### ISSUE TITLE
List skipped exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#210]
We should have a way to show you which exercises you've skipped. This could be as a separate section in the `current` command, perhaps, or a new command.

**Comment by carlisia** [comment]
I'm poking through this, first time looking at this code base. I looked and searched (including a `git log -S`) and did not see a `current` command (https://github.com/exercism/cli/tree/master/cmd), is it still there somewhere?

**Comment by carlisia** [comment]
Nvm, I found a discussion that answers my questions here: https://github.com/exercism/cli/issues/137

**Comment by kytrinyx** [comment]
Yeah, the `current` command hasn't been implemented (yet?).

**Comment by carlisia** [comment]
How about we add a `skipped` column to the `UserExercise` table on `exercism.io` and an endpoint to make this data update to the `Iterations` class? Then, the next time the user sends a submission for that exercise, the `skipped` column gets set to `false`. Would this work?

And, of course, a `skip` command needs to be added to the CLI, which would call that endpoint.

**Comment by kytrinyx** [comment]
Yepp, that's a great idea. In fact... what do you think about putting the `skipped` status on the website, and then, instead of implementing `current` and `skipped` commands in the CLI, we implement a single `status` command which lists skipped exercises in addition to what we discussed in the discussion about `current`?

**Comment by carlisia** [comment]
I think this is moving in a very useful direction.

Let me see if I got what you're saying:

- The CLI will have a new command named `status`.
- Typing `exercism status x` will output a listing of different statuses for the specified language x.
- The statuses would be `skipped` and `current` (definition in progress.)

Is this ^ right?

Any other existing (I'm still getting familiar with the code base) or desired statuses to list?

**Comment by kytrinyx** [comment]
That sounds right, though I think just `exercism status` is fine, not `exercism status x`, though we can have language as an option to narrow down output.

I'll define a new issue summarizing this, and then close these two.

**Comment by carlisia** [comment]
I thought `exercism status x` would be consistent with existing commands, like `exercism list x`. Otherwise, yes, there is no reason or, better, we can make the language optional to narrow things down.

**Comment by kytrinyx** [comment]
Agreed. Consistency is a very good thing!

Closing; see issue #223
