### ISSUE TITLE
$XDG_CONFIG_HOME Custom Subdirectories for CLI

### ISSUE THREAD

**Issue by masters3d** [exercism/cli#219]
Any way to give the CLI a custom subdirectory to move/point the ``$XDG_CONFIG_HOME/.exercism.json`` file to? 
``$XDG_CONFIG_HOME/<Custom>/.exercism.json``

I love the option that already have to point the problems folder to something custom.

https://github.com/exercism/cli/pull/215/
https://github.com/exercism/exercism.io/issues/1819

**Comment by kytrinyx** [comment]
I suppose we could have another config variable. I don't know. What would make sense?

**Comment by masters3d** [comment]
I prefer to have it in one spot, same as $EXERCISM_CONFIG_FILE

or something along these lines (at least for my mac set up)
~/user/Documents/exercism/

This wont be platform agnostic though.

**Comment by kytrinyx** [comment]
> I prefer to have it in one spot, same as $EXERCISM_CONFIG_FILE

I'm not sure what you mean. Could you elaborate?

> This wont be platform agnostic though.

Yeah, we need to be platform agnostic.

**Comment by masters3d** [comment]
I was thinking everything should be in the same folder as $EXERCISM_CONFIG_FILE

After looking more into this and also on being platform agnostic, I don't think my request is valid. 

Im closing this. Thanks for the input!

![image](https://cloud.githubusercontent.com/assets/6539412/10118549/a1c0deda-642f-11e5-8e77-1a4f12009d66.png)

**Comment by kytrinyx** [comment]
Thanks for taking the time to think this through with me!
