### ISSUE TITLE
restore adds subfolders to some submissions and not others

### ISSUE THREAD

**Issue by masters3d** [exercism/cli#220]
![image](https://cloud.githubusercontent.com/assets/6539412/10107929/1378a214-6373-11e5-9f76-960c0e9ed2f9.png)
![image](https://cloud.githubusercontent.com/assets/6539412/10107934/21c8c40c-6373-11e5-80b9-5439071e0e0a.png)

**Comment by kytrinyx** [comment]
Oh, wow. That's an interesting one. If you visit your `clock` exercise on the website, is the file path weird?

**Comment by masters3d** [comment]
interesting is the same
![image](https://cloud.githubusercontent.com/assets/6539412/10108443/c576d75e-6375-11e5-8d15-9a761ec46fc2.png)
![image](https://cloud.githubusercontent.com/assets/6539412/10108476/eab5e0aa-6375-11e5-92d1-a4eb614d5812.png)

**Comment by kytrinyx** [comment]
I suspect that we ended up with a wonky data migration here. I'll comb through the data in production and see if I can detect these and clean them up.

**Comment by masters3d** [comment]
Cool. Thanks!

**Comment by kytrinyx** [comment]
Closing, since this needs to be solved elsewhere.
