### ISSUE TITLE
fetch always adds a new exercise

### ISSUE THREAD

**Issue by sjfloat** [exercism/cli#221]
Scenario: I am using exercism on several different boxes. Every time I setup on a box, it increments the exercise number so that the number of fetch exercises keeps increasing. Is there a way to reset this?

To exacerbate the matter, I'm working up a docker container for running exercism. Each iteration of the development results in another exercise added to the list. Soon, they'll all be fetched.

**Comment by kytrinyx** [comment]
Ah, that's no good! Yeah, definitely a bug. I'll fix that and reset the numbers.

I'm not sure I understand what's going on with the docker setup. Would you mind elaborating a bit with a specific example?

**Comment by sjfloat** [comment]
Well, that it's docker is not itself, directly relevant. What *is* relevant
is that in developing the docker container, I am essentially creating
everything from scratch as I iterate. So I have to repeatedly do 'exercism
configure' and 'exercism fetch'. Each time I do, another exercise appears
in the fetch. It's as though I'm rebuilding my box over and over. Think of
it as though I were developing a special-purpose exercism machine.
ᐧ

On Sun, Oct 4, 2015 at 11:05 AM, Katrina Owen <notifications@github.com>
wrote:

> Ah, that's no good! Yeah, definitely a bug. I'll fix that and reset the
> numbers.
>
> I'm not sure I understand what's going on with the docker setup. Would you
> mind elaborating a bit with a specific example?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exercism/cli/issues/221#issuecomment-145356441>.
>



-- 
"I have delusions of grandeur. I believe myself to be Steve Jones"

**Comment by kytrinyx** [comment]
It's fetching a new exercise, as in... the first time it fetches `hamming` (or whatever), then you rebuild and fetch and it fetches `leap`, then the next time, maybe `bob`?

**Comment by kytrinyx** [comment]
I was just able to confirm this behavior without docker.

Reproduction steps:

```
for i in {1..5}; do exercism fetch ruby; done
```

Expected behavior: only fetch the next exercise when you've submitted at least one iteration to the previous one.

**Comment by sjfloat** [comment]
Exactly. Each time I fetch for the first time on a new box, it pulls down the entire list of exercises plus one more. So, the first time, it was just 'accumulate' or something. On the next machine, my first fetch pulled down 'accumulate' and , say 'leap'. First time on the next machine, it pulled down three exercises.

**Comment by sjfloat** [comment]
Yes, exactly. I've not submitted anything yet, but my exercise list keeps growing.

**Comment by kytrinyx** [comment]
Yepp, this is definitely a bug in the web backend. I'll fix it and report back here.

Thanks for the help clarifying it.

**Comment by sjfloat** [comment]
Not a problem, thanks!

**Comment by kytrinyx** [comment]
Deploying now.

**Comment by Tonkpils** [comment]
:+1:

**Comment by sjfloat** [comment]
Thanks! I'll give it a try first chance I get!
ᐧ

On Wed, Oct 7, 2015 at 5:16 PM, Leo Correa <notifications@github.com> wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exercism/cli/issues/221#issuecomment-146331955>.
>



-- 
"I have delusions of grandeur. I believe myself to be Steve Jones"

**Comment by sjfloat** [comment]
Just verifying your fix. Thanks!
