### ISSUE TITLE
Submit attempt fails with strange error message

### ISSUE THREAD

**Issue by sjfloat** [exercism/cli#222]
When I try to submit:

    $ exercism submit LeapYear.hs 

it fails with:

    2015/10/04 20:50:48 unable to submit solution - error parsing API response - invalid character '<' looking for beginning of value

Is this error message intended for an end user?

**Comment by sjfloat** [comment]
In case it has to do with my submission:

```Haskell
module LeapYear (isLeapYear) where

divisibleBy :: Integer -> Integer -> Bool
divisibleBy x y = x `mod` y == 0

isLeapYear :: Integer -> Bool
isLeapYear     y
     |         y `divisibleBy` 100 
       && not (y `divisibleBy` 400) = False
     |         y `divisibleBy` 4    = True
     | otherwise                    = False
```

(actually, looking at it again, I don't think it's correct, even though it passes the tests :/ )

**Comment by sjfloat** [comment]
Trying again:

    $exercism submit LeapYear.hs                          

I now get:

    2015/10/04 21:07:46 unable to submit solution - an internal server error was received.
    Please file a bug report with the contents of 'exercism debug' at: https://github.com/exercism/exercism.io/issues 


```
**** Debug Information ****
Exercism CLI Version: 2.2.1
Exercism CLI Latest Release: 2.2.1
OS/Architecture: linux/amd64
Build OS/Architecture linux/amd64
Home Dir: /home/steve
Config file: /home/steve/.exercism.json
API Key: <excised>
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: /home/steve/exercism

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).
```

**Comment by Tonkpils** [comment]
This is usually due to an issue with the API endpoint. @kytrinyx could give us a bit more insight as to what happened or how to debug it.

**Comment by kytrinyx** [comment]
I'm looking into it. Usually the errors on submit have to do with submitting a file that is not in the expected location, but we fixed the error message to be more helpful, so I think this is something different.

**Comment by kytrinyx** [comment]
What's the preset working directory when you run the submit command?

**Comment by sjfloat** [comment]
/home/steve/exercism/haskell/leap

**Comment by kytrinyx** [comment]
That looks exactly right :/

I'll see if I can pull down the data locally to simulate your setup.

**Comment by sjfloat** [comment]
BTW, for more information, I was later able to submit the above exercise. So it seems to be intermittent.

**Comment by kytrinyx** [comment]
Darn, that makes it even harder to track down.

**Comment by Tonkpils** [comment]
> Darn, that makes it even harder to track down.

We could improve the ability to track failed requests. Are we returning the Request ID header on the response? We could start logging that as part of the failed responses and it would help track the issue on the backend much better.

**Comment by kytrinyx** [comment]
We're running on a free heroku dyno, so logs are very, very limited. That said, we're sending things to bugsnag, maybe there's more information that can be sent there.

**Comment by Tonkpils** [comment]
> We're running on a free heroku dyno, so logs are very, very limited. That said, we're sending things to bugsnag, maybe there's more information that can be sent there.

I think the request ID already gets sent as part of the headers but I'm not sure that you can search for it. Not too familiar with Bugsnag

**Comment by kytrinyx** [comment]
I have only a passing familiarity with it, myself. I'll dig in and see what I can find.

**Comment by kytrinyx** [comment]
OK, it turns out we were sending only the error to bugsnag, not the request information. I've changed that, and am deploying it now.

**Comment by kytrinyx** [comment]
I'm closing this, since we added more logging. If the error occurs again, would you please open a new issue?

**Comment by sjfloat** [comment]
Sure
ᐧ

On Mon, Nov 16, 2015 at 2:59 PM, Katrina Owen <notifications@github.com>
wrote:

> I'm closing this, since we added more logging. If the error occurs again,
> would you please open a new issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exercism/cli/issues/222#issuecomment-157153074>.
>



-- 
"I have delusions of grandeur. I believe myself to be Steve Jones"
