### ISSUE TITLE
Implement new command: exercism status [$language]

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#223]
Instead of implementing a `current` and a `skipped` command, let's have a `status` command that lists the following:

For each language where you have submitted at least one iteration of one exercise:

* list the (one) exercise that you most recently submitted, and when
* list the exercises that you have fetched but not submitted (could be multiple)
* list the exercises that you have skipped

We will need to implement an endpoint in the exercism/exercism.io api (currently at `lib/api/routes/...`).

If someone calls `exercism status $language` for a language where they have not submitted anything, we should explicitly tell them that they've not submitted anything in that language.

This issue supersedes #210 and #137.

**Comment by devonestes** [comment]
I might be interested in taking this one on! Considering this is dependent on the API endpoint, and that's in a different repo, would it be better to take care of that endpoint first and then develop the CLI command once the endpoint is merged?

**Comment by Tonkpils** [comment]
@devonestes you could also implement the API and then develop on the CLI against your local instance of exercism with the API changes.

If you have any questions don't hesitate reaching out.

**Comment by kytrinyx** [comment]
This is now implemented, and will be a part of the next release.
