### ISSUE TITLE
Stop using timestamps in the log.Fatal messages

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#224]
Since we are not logging to anything, and each command is a very short-lived one, I don't think that the timestamp for the failure in log.Fatal is helping. If anything it makes the output from errors seem noisier (which is more intimidating to beginners).

We could use log.SetPrefix("") to remove the timestamp, but I wonder if it's better to just print to STDERR directly and then call `os.Exit` since we really don't need any of the log-specific functionality.

```
fmt.Fprintf(os.Stderr, msg)
os.Exit(1)
```

Thoughts?

**Comment by Tonkpils** [comment]
I believe @lcowell was doing some work on the way we did outputs. If anything this may be a good time to re-evaluate it?

**Comment by lcowell** [comment]
I was looking to build something like this: https://github.com/constabulary/gb/blob/master/log/log.go
I still think this could be a good approach. 

Building on the original idea, we could use `os.Stderr` for debugging information and `os.Stdout` for normal output. When the app starts up if the don't have the verbose flag enabled, we can set `os.Stderr` to `ioutil.Discard`.

**Comment by kytrinyx** [comment]
@lcowell that sounds good to me.

**Comment by Tonkpils** [comment]
:+1: looking forward to see this :smile:

**Comment by lcowell** [comment]
See https://github.com/exercism/cli/pull/248

**Comment by kytrinyx** [comment]
Fixed in #248
