### ISSUE TITLE
testing the config package fails when /tmp is on another partition

### ISSUE THREAD

**Issue by frenata** [exercism/cli#227]
The error is showing up in lines 20-23 (and 24-27, 106-108) of [config_test.go](https://github.com/exercism/cli/blob/master/config/config_test.go#L20-L23):

```
configPath := filepath.Join(tmpDir, "config.json")
if err := os.Link(fixturePath(t, "config.json"), configPath); err != nil {
    t.Fatal(err)
}
```

 `os.Link` is returning the following error:

```
--- FAIL: TestLoad (0.00s)
        config_test.go:22: link /home/frenata/go/src/github.com/exercism/cli/fixtures/config.json /tmp/021609116/config.json: invalid cross-device link
```

This behavior occurs because `os.Link` creates a hard link and hard linking is not permitted across partitions.

I'm not sure of the appropriate fix since I'm not yet certain why the tests are creating links.

**Comment by kytrinyx** [comment]
The tests are creating links because we previously had a bug where people were using symlinks for their exercism directory, and we weren't following symlinks.

I'm not sure what the right answer is here.

**Comment by lcowell** [comment]
You should be able to set the environment variable `TMPDIR` to something on the same partition. Not the greatest solution, but it should get things working for now.

**Comment by kytrinyx** [comment]
Since we've not heard anything further on this one, I'm going to go ahead and close it.
