### ISSUE TITLE
How to use with OSX?

### ISSUE THREAD

**Issue by desult** [exercism/cli#249]
I've downloaded the version for 64bit mac, and it seemed to install ok. When I type exercism in terminal, I got "-bash: exercism: command not found" . Are there PATH variables that I need to edit is OSX? I'm using 10.10.5 Yosemite.

**Comment by Tonkpils** [comment]
You need to extract the binary file out of the tar that you downloaded and place that binary file somewhere in your PATH. If this seems confusing to you, I'd highly suggest using looking into using [homebrew](http://brew.sh/) to get the CLI. 

Simply follow the instructions to install `homebrew` and then do `brew install exercism`. You should be able to use the CLI then.

There's detailed instructions on how to install the CLI here http://help.exercism.io/installing-the-cli-on-mac.html

**Comment by desult** [comment]
Thanks for the reply, that clears it up for me. I should be able to now get it going using one of those methods. Thanks again.

**Comment by Tonkpils** [comment]
No problem! Feel free to re-open this if you have any further questions
