### ISSUE TITLE
Clarify domain concepts throughout the codebase

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#252]
We've spent some time coming up with terminology that works for the project. Here's what we've landed on:
- **Track** -  track is in a language (e.g. C++) and has an ID (e.g. `cpp`)
- **Problem** - a generic description of a problem to be solved, can be implemented in any language
- **Exercise** - a language-specific implementation of a problem. It has a test suite in that language.
- **Solution** - an author's worked answer to an exercise. It may have 1 or more iterations.
- **Iteration** - a single version of an author's solution to an exercise.

At the moment we've got some old names in the codebase. I think `Problem` is used in the old sense (it should now be `Exercise`) and `Submission` should become `Iteration`. There might be other confusing things in there as well.

**Comment by devonestes** [comment]
I might be able to take this one on. Would it be better to submit commits one at a time rather than all at once? For example, one commit would update all instances in the codebase where something should be called a Track, the next commit for Problem, etc.

I'm thinking it might be easier to review the code if each commit only focused on one change. I could of course squash them down before merging.

**Comment by kytrinyx** [comment]
Yes -- please take little bits and pieces at a time. I might even suggest adding a comment here to say which piece you're tackling, then if someone else wants to grab another piece meanwhile they could.

It's much, much easier to review if each commit is one type of change, and I would not want them to be squashed. I might even suggest having different pull requests (much easier to review that way).

It wouldn't even have to be all about the same name, but perhaps all about one name in one area of the code, or all about one struct throughout the codebase.

I've got a lot of experience with refactoring and overwhelmingly, smaller is better unless it's a very straight-forward change that just happens to be in 800 places.

**Comment by devonestes** [comment]
Sounds good! The first thing that's jumped out at me is the use of `Submission` instead of `Iteration` in `api.go`, so I'll start there with the updating.

**Comment by kytrinyx** [comment]
+1 sounds great

**Comment by bordeltabernacle** [comment]
Is this something that still needs looking at?

**Comment by kytrinyx** [comment]
I've actually been thinking that it would be nice to review the entire CLI user interface, normalize it, tweak the API endpoints to also be normalized, and then use spf13/cobra as the framework. If I have time to think through it more thoroughly I'll open an issue to start a discussion about what that might look like.

**Comment by bordeltabernacle** [comment]
@kytrinyx @Tonkpils Ok, I'll keep an eye open for that, I did notice talk of re-writing the CLI. I'm learning Go and would love to get involved. I'll still have a look through the current codebase, as much for my learning as anything else, and see if I can help clarify anything. Though just let me know if any issues/PR's are creating extra work/effort for you that can be better spent on the re-write.

**Comment by kytrinyx** [comment]
Since we are rewriting the CLI from scratch in the `nextercism` branch, I'm going to go ahead and close this.
