### ISSUE TITLE
Version is broken

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#263]
Right now if you say `exercism --version` it outputs the entire usage message.

This changed in f999e69e

```
    disambiguate debug and verbose flags
    
    The debug boolean flag and the debug command were ambiguous. Changing
    the `debug` boolean flag to `verbose` makes which options you're
    referring to more obvious.
```

@lcowell You deliberately added the app.HideVersion here. Is it safe to take it back off?

I'm thinking this would make sense:

````
--version, v
--verbose # no shorthand
```

**Comment by Tonkpils** [comment]
We had talked about this when the --verbose was originally implemented and we said it would be good to have `--v` shorthand for verbose. However, `--v` was later removed because of conflicts with the CLI package. I think it makes sense for the `--v` to simply be part of version.

**Comment by kytrinyx** [comment]
I agree. If you're going to be verbose, it's kind of poetic justice that you have to type out the whole flag name.
