### ISSUE TITLE
exercism cli fails to communicate to API: http://exercism.io

### ISSUE THREAD

**Issue by tejasbubane** [exercism/cli#267]
This might be related to #202 

I just downloaded the latest linux 64-bit binary from https://github.com/exercism/cli/releases/tag/v2.2.3

```
⇒  exercism debug

**** Debug Information ****
Exercism CLI Version: 2.2.3
2016/01/03 19:06:00 unable to fetch latest release: Get https://api.github.com/repos/exercism/cli/releases/latest: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
OS/Architecture: linux/amd64
Build OS/Architecture linux/amd64
Home Dir: /home/tejas
Config file: /home/tejas/.exercism.json
API Key: <MY API KEY>
API: http://exercism.io [Get http://exercism.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)]
XAPI: http://x.exercism.io [connected]
Exercises Directory: /home/tejas/exercism_submissions

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).

⇒  exercism upgrade
2016/01/03 19:06:46 unable to check latest release version: Get https://api.github.com/repos/exercism/cli/releases/latest: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

⇒  cat .exercism.json 
{
  "apiKey": "<MY API KEY>",
  "dir": "/home/tejas/exercism_submissions",
  "api": "http://exercism.io",
  "xapi": "http://x.exercism.io"
}
```

**Comment by kytrinyx** [comment]
If you downgrade are you able to connect?

**Comment by tejasbubane** [comment]
Tested with `2.2.2` and `2.2.1` and getting same error with both `debug` and `upgrade` commands. This is on 64-bit linux.

I also went ahead and tested on my macbook (`v2.2.3` installed via `brew`), there is the same error in `exercism debug` but strangely no error for `exercism upgrade`.

**Comment by kytrinyx** [comment]
Here's what I'm getting on mac 64-bit

```
~ $ exercism --version
exercism version 2.2.3

~ $ exercism debug

**** Debug Information ****
Exercism CLI Version: 2.2.3
Exercism CLI Latest Release: 2.2.3
OS/Architecture: darwin/amd64
Build OS/Architecture /
Home Dir: /Users/kytrinyx
Config file: /Users/kytrinyx/.exercism.json
API Key: [redacted]
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: /Users/kytrinyx/exercism

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).
```

**Comment by tejasbubane** [comment]
Strange, here is what I am getting:

```
tejas@Tejass-MacBook-Air:~|⇒  uname -a
Darwin Tejass-MacBook-Air.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64
tejas@Tejass-MacBook-Air:~|⇒  exercism debug

**** Debug Information ****
Exercism CLI Version: 2.2.3
Exercism CLI Latest Release: 2.2.3
OS/Architecture: darwin/amd64
Build OS/Architecture /
Home Dir: /Users/tejas
Config file: /Users/tejas/.exercism.json
API Key: <MY_API_KEY>
API: http://exercism.io [Get http://exercism.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)]
XAPI: http://x.exercism.io [Get http://x.exercism.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)]
Exercises Directory: /Users/tejas/exercism

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).
```

**Comment by kytrinyx** [comment]
I wonder if this has a personal component that is related to performance of the API. I'll take a look into that possibility.

**Comment by Tonkpils** [comment]
We could build a new binary for @tejasbubane without timeout and see if that fixes the issue. It may be a slow client connection?

**Comment by kytrinyx** [comment]
Could be a slow connection, or a really slow response from the API.

**Comment by kytrinyx** [comment]
Also: yeah, let's build one without the timeout. Do you have time to do that?

**Comment by Tonkpils** [comment]
Sure, I'll go ahead and do it in a couple of minutes. Just getting settled back home.

**Comment by Tonkpils** [comment]
@tejasbubane I've gone ahead and cut out a release with the client timeout removed from both the debug and upgrade command. https://github.com/exercism/cli/releases/tag/v2.2.4.beta.1 

You can also check the code that generated the binaries here https://github.com/exercism/cli/commit/89e102595c1546b82b9aff30f135f057be30aad0

It'd be interesting to see if this fixes the issue and if so, how long the commands took to execute successfully. Maybe we could adjust the timeouts to a better value.

**Comment by tejasbubane** [comment]
That removes the error:
```
**** Debug Information ****
Exercism CLI Version: 2.2.4.beta.1
Exercism CLI Latest Release: 2.2.3
OS/Architecture: darwin/amd64
Build OS/Architecture darwin/amd64
Home Dir: /Users/tejas
Config file: /Users/tejas/.exercism.json
API Key:<MY_API_KEY>
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: /Users/tejas/exercism

A newer version of the CLI (v2.2.3) can be downloaded here: https://github.com/exercism/cli/releases/tag/v2.2.3

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).

⇒  ./exercism upgrade
Downloading exercism-mac-64bit.tgz
Successfully upgraded!
```

I went ahead and put `time` for both commands:

* with timeout (`2.2.3`)
```
exercism debug  0.01s user 0.02s system 0% cpu 10.585 total
```
* without timout (`2.2.4.beta-1`)
```
exercism_beta debug  0.07s user 0.03s system 0% cpu 14.529 total
```

This is definitely my internet. We usually have latency issues here in India. 
Is there a way I can check how much time a single request needs to complete rather than the whole command?

**Comment by Tonkpils** [comment]
We could add debug lines to the code to measure the time it took to actually make the request. In any case, I think bumping the timeout to a sensible default would be best. 
Currently, none of the other commands have timeouts for the HTTP client. For debug it would be good to have a timeout since there can possibly be issues with the network. As for upgrade, I'm open for it having a high timeout or not having one at all, it seems at this point since it just calls to the GitHub API and issues are likely to be with the client's connection rather than the API. 

One thing I'm going to do is possibly add some sort of latency check to the debug command which will surface these issues.

**Comment by Tonkpils** [comment]
@tejasbubane did the latest release of the CLI fix this issue for you?

**Comment by Tonkpils** [comment]
Closing this, if you are still running into this issue, feel free to reopen
