### ISSUE TITLE
Guard against submitting the wrong file

### ISSUE THREAD

**Issue by daveyarwood** [exercism/cli#272]
I was moving a little too fast tonight and [accidentally submitted `hamming_spec.lua` instead of `hamming.lua`](http://exercism.io/submissions/7f35bb6eb9684a48ae17583c929f9888). It would be nice if the CLI tool were smart enough to know if the user is accidentally submitting a README or test cases in lieu of a solution.

Would it make sense for the CLI tool to check the filename of the file you're submitting and guard against certain filenames? We could check for things like: 

- anything containing "README"
- (name of the exercise) + "_spec.lua"
- (name of the exercise) + "_test.clj"

**Comment by daveyarwood** [comment]
Another idea: include a hidden file in each folder with a list of "bad filenames," and have the CLI tool check the submitted filename against the list in the hidden file and throw an exception if it's one of them.

**Comment by Tonkpils** [comment]
We actually guard against file names that include `test` in the name unless you use the `--test` flag. We can expand that current guard to test for `spec` which is also used to describe test files. We can completely block off submitting READMEs but if we start blocking off submission of all other files then we run into situations where there's multiple other files for other languages that should not be submitted.

**Comment by daveyarwood** [comment]
I think including `spec` and `README` in the guard might be helpful. I could take a stab at a PR, if you'd like?

**Comment by Tonkpils** [comment]
Sure, if you have any questions feel free to reach out!

**Comment by daveyarwood** [comment]
Cool :+1:
