### ISSUE TITLE
should files from `download` be created non-executable instead of executable?

### ISSUE THREAD

**Issue by petertseng** [exercism/cli#276]
Currently they're created executable, as https://github.com/exercism/cli/blob/master/cmd/download.go#L42 and https://github.com/exercism/cli/blob/master/cmd/download.go#L49 would have it. Need to think about whether that should be the case. Is the idea that some language tracks' submission files are meant to be executed directly?

However, when doing `fetch`, files are written 0644: https://github.com/exercism/cli/blob/master/user/item.go#L71 . And given that the Ruby track has an [automated feedback for when Rubys submissions have shebangs](https://github.com/exercism/rikki/blob/master/comments/analyzer/ruby/shebang/shebang.md), it makes it seem more likely those 0755 should be change to 0644.

Any specific reason to keep at 0755?

**Comment by kytrinyx** [comment]
I know in Ruby the test files are executable so that people have the option of saying `ruby path/to/testfile` or just `path/to/testfile`. But I don't actually have very strong feelings about it.

We could use the shebang to check whether a file should be 0644 or 0755.

**Comment by petertseng** [comment]
So you are thinking "if first line in file is shebang, make it 0755, else make it 0644?"

I could see that making sense. If we are in agreement, I can probably make it happen, though I'm a bit unclear on how I'd test.

**Comment by petertseng** [comment]
My tentative test plan is: Make my change, build client from git, and just download a few submissions and see if they get created with the right modes.

Any place where it'd be appropriate to add an automated test for this?

**Comment by kytrinyx** [comment]
Yeah, that was what I was thinking. Building from git is how I change things that I don't have automated tests for. If we move the code that writes the file out of `cmd/download.go` and onto a method on `Submission` then it should be fairly straight forward to write a test for it.

**Comment by Tonkpils** [comment]
I don't like to encourage people to simply run an executable they've fetched from a remote. I think we should remove the shebang and simply have them execute the file with `ruby /path/to/test`. Thoughts?

**Comment by kytrinyx** [comment]
Yeah, good point.

I can't remember the arguments for adding it in Ruby. I think if they want to make it executable, they're welcome to do it themselves.

OK, for now, let's make it 0644 on everything, and then I'll open a ticket on the Ruby track to remove the shebangs and add some documentation to let people know they can chmod and shebang themselves if they want.

**Comment by petertseng** [comment]
OK, everything 0644 then. In that case since there's no new logic added I am not really motivated to add new automated tests; I'll just test by building from git.

Will set reminder for myself to do this since I won't be getting to it immediately. Remind me if you haven't heard back in 24 hours. Assign the ticket to me?

**Comment by Tonkpils** [comment]
@petertseng would you like to make a PR to fix this? If not I can probably get to it for the weekend. 

Assignment of tickets can only be done for members of the team. In any case, you can see this issue on Github under your created issues.

**Comment by petertseng** [comment]
@Tonkpils : I expect I can do it sometime tomorrow, but I would have no objection at all if you (or anyone else watching this issue) beats me to it. I will comment here if I begin work.

**Comment by petertseng** [comment]
Should have said I was beginning work. Well not much use in saying it now, since PR's open.
