### ISSUE TITLE
Allow retrieval of current exercise

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/cli#279]
I'd love the `exercism` CLI to have a command that indicates what is my current "unsolved" problem, ideally with an option to limit it to a single language. So for example:

`exercism current scala` would output: `current scala exercise: forth`

**Comment by kytrinyx** [comment]
Have you tried the `status` command? `exercism status scala`

**Comment by ErikSchierboom** [comment]
Whoops, that does it. I had an older version of the CLI, I'm so sorry.

**Comment by kytrinyx** [comment]
No worries!
