### ISSUE TITLE
cli doesn't track which Exercises have been submitted

### ISSUE THREAD

**Issue by degustaf** [exercism/cli#287]
When I run `exercism status python` all of the exercises that I have submitted are listed under `
Exercises fetched but not submitted:`

**Comment by AlexWheeler** [comment]
Hey @degustaf are the submitted exercises displaying correctly on your dashboard? i.e. they're _not_ listed under:
You've fetched these problems. Now solve them!

Also, what's the output when you run ```exercism --version```?

**Comment by degustaf** [comment]
@AlexWheeler In the dashboard the are listed under `Keep working on these problems, or archive them.`

I have version 2.2.4

**Comment by kytrinyx** [comment]
There's definitely something odd going on here. I get:

```
Your status on the go track:

Most recently submitted exercise:
 - clock (submitted on January 23, 2016)

Exercises fetched but not submitted:
 - clock

Exercises skipped:

```

**Comment by cjbottaro** [comment]
I got the same issue:

```
$ exercism status go

Your status on the go track:

Most recently submitted exercise:
 - food-chain (submitted on February 3, 2016)

Exercises fetched but not submitted:
 - clock
 - difference-of-squares
 - food-chain
 - gigasecond
 - leap
 - raindrops
 - secret-handshake
 - triangle

Exercises skipped:
```

```
$ exercism -v
exercism version 2.2.4
```

**Comment by ErikSchierboom** [comment]
Same here:

<pre>
exercism status haskell

Your status on the haskell track:

Most recently submitted exercise:
 - point-mutations (submitted on March 13, 2016)

Exercises fetched but not submitted:
 - lens-person
 - point-mutations
 - pov

Exercises skipped:
</pre>

However, my dashboard correctly notes that I am at 100%:

![image](https://cloud.githubusercontent.com/assets/135246/13728191/123f1996-e910-11e5-9138-230f51a1b775.png)

**Comment by kytrinyx** [comment]
Definitely a bug! Thanks for adding these details, @ErikSchierboom

**Comment by Tonkpils** [comment]
There seems to be a bug with the backend or there's fields that aren't properly filled out. 

```bash
./exercism fetch go poker

Not Submitted: 1 problem
Go (Poker) /Users/leo/code/exercisms/go/poker

New:       1 problem
Go (Poker) /Users/leo/code/exercisms/go/poker

unchanged: 0, updated: 0, new: 1
```

```bash
./exercism status go

Your status on the go track:

Most recently submitted exercise:
 - gigasecond (submitted on January 19, 2015)

Exercises fetched but not submitted:


Exercises skipped:
```

```bash
curl http://exercism.io/api/v1/tracks/go/status?key=<mykey>
{"track_id":"go","recent":{"problem":"gigasecond","submitted_at":"2015-01-19T17:43:27.666Z"},"skipped":[],"fetched":[]}
```

**Comment by kytrinyx** [comment]
Closed in favor of https://github.com/exercism/exercism.io/issues/2804
