### ISSUE TITLE
exercism status returns an internal server error when there's no api key set locally

### ISSUE THREAD

**Issue by mrageh** [exercism/cli#296]
When a user does not have their api key set and `exercism debug` returns:
```
**** Debug Information ****
Exercism CLI Version: 2.2.4
Exercism CLI Latest Release: 2.2.4
OS/Architecture: darwin/amd64
Build OS/Architecture /
Home Dir: /Users/Adam
Config file: /Users/Adam/.exercism.json
API Key:
Exercises Directory: /Users/Adam/programming/cisms/
Testing API endpoints reachability
	* API: http://exercism.io [connected] 170.057673ms
	* GitHub API: https://api.github.com/ [connected] 322.724326ms
	* XAPI: http://x.exercism.io [connected] 649.753655ms
```

If that user tries to check the status of a language with `exercism status language`, the server returns a 500 I think:
```
2016/03/03 09:36:45 an internal server error was received.
Please file a bug report with the contents of 'exercism debug' at: https://github.com/exercism/exercism.io/issues
```

Is this a bug and should we fix it?

I'd be happy to take a stab at it by making changes to `exercism/cli`.

**Comment by Tonkpils** [comment]
The server should definitely not blow up with an internal server error if the API key is not provided. It should return with an unauthorized or something similar in which case the error message on our end would be that response. 

One thing I noticed, if the API Key is not set, `exercism debug` should probably display a message stating that it should be set to access some functionality. 

As far as ensuring all the commands that require API key on the server end have an API key present, I believe was discussed. The consensus was that we should let the server tell us that in case the API endpoints change requirements for API key presence or not.

**Comment by kytrinyx** [comment]
Yeah, the server side needs to be fixed for this. I'm not sure what's going on, because the API supposedly checks for the presence of the key. I'm looking into this now.

**Comment by kytrinyx** [comment]
OK, that was quick.

```
http://localhost:4567/api/v1/tracks/ruby/status # status 401
```

```
http://localhost:4567/api/v1/tracks/ruby/status?key= # status 500
```

**Comment by kytrinyx** [comment]
Fixed in exercism/exercism.io@d0c061575be65f03ceddcf096d7577f9351663e7

**Comment by mrageh** [comment]
Wow @kytrinyx that was quick :+1: 
Closing this issue as it was just (fixed)[https://github.com/exercism/exercism.io/commit/d0c061575be65f03ceddcf096d7577f9351663e7]

**Comment by Tonkpils** [comment]
@mrageh if you would like to contribute to the CLI we would accept a PR to enhance the output of `exercism debug` to display a message when the API key is not present and that the user should set it to access some of the CLI features.

**Comment by kytrinyx** [comment]
Yeah +1 for @Tonkpils' suggestion. That would be sweet!

**Comment by mrageh** [comment]
I'll work on it tonight, thanks for the quick responses
