### ISSUE TITLE
Submit should warn users that try to check in a directory

### ISSUE THREAD

**Issue by mhelmetag** [exercism/cli#300]
Brought up in [exercism.io#2802](https://github.com/exercism/exercism.io/issues/2802).

It could be a good idea to give users a heads up when they try to submit a directory.

This could help funnel new users towards the correct usage of the cli (along with the existing control flow in [submit](https://github.com/exercism/cli/blob/master/cmd/submit.go) already).

**Comment by kytrinyx** [comment]
Agreed, this would be a very nice fix. It also shouldn't be difficult to implement.

**Comment by alebaffa** [comment]
I can take care of this one :) it would be my first PR here on exercism.

I took a look and it seems pretty simple to implement. 
I think I could add a new check in cli/cmd/submit.go along with these existing ones:

if isTest(filename) ...
if isREADME(filename)...
I see two solutions, but I would like to hear your opinion:

1) to create a new function (which will be stored in /cmd/cmd.go)

if isDirectory(filename)
2) To use the function

func IsDir(path string) bool
which is already implemented and stored in paths/paths.go

The 1) allows to stay coherent with the previous coding style (isTest, isREADME), the 2) allows to reuse an existing function.

What do you suggest?

**Comment by kytrinyx** [comment]
I would suggest using the IsDir function, since it already does what you need.

**Comment by mhelmetag** [comment]
@alebaffa , thanks for this :D
