### ISSUE TITLE
`exercism fetch <nonexistent track>` gives unhelpful message

### ISSUE THREAD

**Issue by petertseng** [exercism/cli#310]
I tried to do this recently:

```
$ exercism fetch hello-world

unchanged: 0, updated: 0, new: 0

$ exercism --version
exercism version 2.2.5
```

Well, obviously I forgot to include what track's `hello-world` I want. Obviously it should have been `exercism fetch <track-id> hello-world`. But the response could probably be more helpful on that front instead of telling me that nothing changed.

**Comment by kytrinyx** [comment]
Yeah, definitely. This shouldn't be too hard--I think that if the API returns a 404 with a helpful error message, the CLI will automatically do the right thing.

**Comment by aranair** [comment]
Took a jab at it at x-api, but it seems like I might be missing a few things there, would be great if someone could take a look :D

**Comment by kytrinyx** [comment]
This should now be fixed. Would you mind double-checking?

**Comment by petertseng** [comment]
```$ exercism fetch hello-world
2016/08/05 23:13:03 unable to fetch problems (HTTP: 404) - No track 'hello-world'
```

Seems good.

By the way I didn't need to change my exercism client for this, so I confirm that "if the API returns a 404 with a helpful error message, the CLI will automatically do the right thing." is true.

```$ exercism --version
exercism version 2.2.5
```

**Comment by petertseng** [comment]
Thanks @aranair.
