### ISSUE TITLE
"exercism 2" is damaged..

### ISSUE THREAD

**Issue by andy-young** [exercism/cli#311]
..and can't be opened. You should move it to the Trash.

Getting this message when I download the latest version and try to open. Not sure what to do here.

**** Debug Information ****
Exercism CLI Version: 2.2.0
Exercism CLI Latest Release: 2.2.5
OS/Architecture: darwin/amd64
Build OS/Architecture darwin/amd64
Home Dir: /Users/andyyoung
Config file: /Users/andyyoung/.exercism.json
API Key: xxxxxxxxxxxxxxxxxxxxxxxxxxx
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: /Users/andyyoung/exercism

**Comment by Tonkpils** [comment]
Are you trying to update your current CLI through `exercism upgrade`?

**Comment by andy-young** [comment]
No.
Just did it. Got a permission denied. Should I sudo?

**Comment by andy-young** [comment]
I got it working thank you much!🤓

**Comment by Tonkpils** [comment]
great! glad you got it figured out! If you run into anything else, feel free to open another issue. 👍
