### ISSUE TITLE
Pass explicit list of track ids to exercism fetch

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#313]
At the moment, `exercism fetch` calls the global fetch endpoint with no arguments (`api/api.go:48`). This causes the fetch endpoint to return the first exercise on all of the tracks. Then the CLI filters based on which directories are present locally.

Let's change this so that we're only asking for directories that are present locally:

```
$HOST/v2/exercises?key=$KEY&tracks=javascript,ruby,go
```

We should probably also add a message to explain which tracks were fetched, and why, and how to fix it if this is unexpected.

**Comment by cshutchinson** [comment]
Thank you for pointing me in the right direction. Will take a look.

**Comment by kytrinyx** [comment]
Awesome! Let us know if you have any questions. We're still trying to figure out how to best organize things, so sometimes this gets a bit confusing.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, as I'm rewriting the CLI for nextercism, which should launch in a few weeks.
