### ISSUE TITLE
Show current and next exercise

### ISSUE THREAD

**Issue by kotp** [exercism/cli#321]
Related to exercism/exercism.io#2780 where I think we should show current and next exercises.

**Comment by tejasbubane** [comment]
I think this can be a part of the `exercism status`. 
The purpose of this command is being thought over here: https://github.com/exercism/discussions/issues/13

**Comment by kotp** [comment]
For sure, I think 2780 should be linked to that discussion.  (I probably wouldn't have made this one if it had.)

**Comment by kytrinyx** [comment]
I'm going to close this until we've gotten the details of a new status command sorted out (since nothing here will be actionable until then).
