### ISSUE TITLE
Problems with symlinked directories

### ISSUE THREAD

**Issue by cyplo** [exercism/cli#325]
Hi !

Thanks a lot for this awesome tool !
While using it I found something curious:
I have symlinked `rust` subdirectory of exercism's main directory and it casues the CLI to complain:

```
 exercism submit src/lib.rs
2016/05/28 22:25:03 Unable to submit - Unable to identify track and file.

It seems like you've tried to submit a solution file located outside of your
configured exercises directory.

Current directory:	/home/cyryl/dev/katas/rust/anagram
Configured directory:	/home/cyryl/exercism

Try re-running "exercism fetch". Then move your solution file to the correct
exercise directory for the problem you're working on. It should be somewhere
inside /home/cyryl/exercism

For example, to submit the JavaScript "hello-world.js" problem, run
"exercism submit hello-world.js" from this directory:

/home/cyryl/exercism/javascript/hello-world

You can see where exercism is looking for your files with "exercism debug".

 ✘   pwd
/home/cyryl/exercism/rust/anagram

 ls -hal /home/cyryl/exercism 
lrwxrwxrwx  1 cyryl cyryl   26 May 23 07:21 rust -> /home/cyryl/dev/katas/rust 
```

let me know if this is a non-issue, or whether there is some workaround.
I'm also happy to help to provide any details if needed

thanks !

**Comment by kytrinyx** [comment]
I think the easiest workaround would be to configure the client to look at `/home/cyryl/dev/katas`:

```
exercism configure --dir=/home/cyryl/dev/katas
```

**Comment by cyplo** [comment]
Hello !
The tip indeed solves my immediate issue, thanks a lot for that !

**Comment by kytrinyx** [comment]
@exercism/cli-committers I think we should go ahead and close this rather than trying to reverse-detect symlinks to the directory that someone is in. This workaround seems straight-forward enough. What do you think?

**Comment by lcowell** [comment]
I agree. The workaround seems pretty simple.

**Comment by cyplo** [comment]
Seems alright for me :) The only case I could think of where this would be not enough, if someone would want to have separate outside directories per e.g. language supported. But I do not feel that need, so probably you can close this one. thanks again !

**Comment by kytrinyx** [comment]
Thanks!
