### ISSUE TITLE
requiring exercises to live in exercises directory

### ISSUE THREAD

**Issue by lcowell** [exercism/cli#329]
We have a policy that users keep their exercism exercises in preconfigured directory (eg `$HOME/exercism`) and we refuse to submit files that live outside that directory. I'm wondering if this is a policy worth continuing to enforce. If a user points us to a file to submit, would it be a better experience for the user to just submit the file instead of refusing based on its location.

Pros
* user can submit a exercise file from wherever they want
* simplify CLI code as we don't have to check the file location

Cons
* could confuse users as to why their test file didn't update when they were expecting it to.
* could introduce new unforeseen support issues

@exercism/cli-committers any thoughts on this?

**Comment by Tonkpils** [comment]
I was honestly thinking about this over the weekend when I saw this issue https://github.com/exercism/cli/issues/325

I think it would be nice to be able to submit a file in any directory but agree that it could be confusing when doing fetches or restores. 

I'd actually give a +1 for this since the user experience would be better by allowing them to submit files outside of the directory. We can give it a try and see if we get any issues on usability or confusions?

**Comment by kytrinyx** [comment]
We need to figure out what track and exercise it is when it's submitted. Currently we do that by looking at the path: `$DIR/$TRACK_ID/$EXERCISE_SLUG`.

If we could unambiguously determine what track and exercise they're submitting, then I would have no problem with this.

The restores thing is potentially confusing, but perhaps if they don't have a configured directory we can restore to some directory (tmp?) and tell them to put it wherever they want.

**Comment by lcowell** [comment]
The only other way I can think to handle determining the full slug would be for each exercise directory to contain some configuration. This could be provided by the server or generated by the cli when the exercises are written out.

The restore thing would definitely become more confusing, even if we could restore to the directory the user submitted from.

This seems like it would be a lot of work to implement and would trade one set of problems for another. I think this should be closed unless anyone sees any use in further discussion.

**Comment by kytrinyx** [comment]
> This seems like it would be a lot of work to implement and would trade one set of problems for another.

I agree. This sounds like a measurable amount of complexity for what feels like kind of dubious value.

I'm still open to discussing it if someone has strong opinions about it, but I would also vote to close the issue.

**Comment by Tonkpils** [comment]
Closing, if someone else has strong opinions about this feel free to re-open 👍
