### ISSUE TITLE
Link for related solutions broken.

### ISSUE THREAD

**Issue by nearbycoder** [exercism/cli#332]
On the output that gets returned from running `exercism submit` there is an issue where the link is invalid due to missing a forward slash. The link below is the line with the issue.
https://github.com/exercism/cli/blob/56b4be81216a7272a09d78879069e0abcd758388/cmd/submit.go#L104

Example output
`http://exercism.iotracks/elixir/exercises/acronym`
![screenshot at jun 05 08-34-46](https://cloud.githubusercontent.com/assets/10525357/15805732/62de0798-2af8-11e6-84dc-adac8bf154dd.png)

**Comment by kytrinyx** [comment]
What version of the CLI are you using? (`exercism -version` or `exercism debug` will tell you)

If you recently upgraded, you might need to kick the tires:

```
$ exercism configure --host=http://exercism.io --api=http://x.exercism.io
```

**Comment by nearbycoder** [comment]
exercism version 2.2.5

upgraded to 2.2.6 and that fixed the issue. Closing thanks and sorry for inconvenience.

**Comment by kytrinyx** [comment]
No problem at all, thanks for reporting it!
