### ISSUE TITLE
exercism fetch TRACK_ID --all

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#335]
I've gotten a few requests for the ability to download all the exercises for a languages before getting on a long flight.

What do you think of adding a flag `--all` to the fetch command?

This wouldn't have to be fancy; I'd be totally OK with a first iteration that just loops through the full list.

**Comment by guilhermeepaixaoo** [comment]
This flag is for download all exercises from the language ?

**Comment by Tonkpils** [comment]
@guilhermeepaixaoo from the implementation it seems like it

**Comment by Tonkpils** [comment]
Fixed by #336
