### ISSUE TITLE
Feature request:  'download'  should accept full Exercism URLs

### ISSUE THREAD

**Issue by Insti** [exercism/cli#341]
Feature request: The download option should accept full Exercism URLs

`exercism download http://exercism.io/submissions/45aaa580ea91452bb34076ade70511f2`

Currently it's necessary to copy/paste just the uuid hex digits from the full URL.

**Comment by kytrinyx** [comment]
I like this suggestion.

**Comment by Insti** [comment]
Should this change happen in the CLI or the API?

**Comment by kytrinyx** [comment]
Trade-offs:

In the CLI feels cleaner. In the API means we don't need to release a new CLI.

**Comment by kotp** [comment]
Alternatively, having the digits shown with a command like `exercism dl 45aaa580ea91452bb34076ade70511f2` for each submission page means that you can copy and paste to your terminal/command line.

**Comment by Insti** [comment]
I'd like there to be a button that just let me download the file directly from the webpage.

**Comment by kotp** [comment]
Wouldn't that require registering an "application type" to be able to use the cli in that way?  Send a message to it while the exercise is being requested.

**Comment by kytrinyx** [comment]
> Wouldn't that require registering an "application type" to be able to use the cli in that way?

We wouldn't have to use the CLI to download—we could zip up the exercise+solution and it would download to the default location that the browser uses for downloads.

**Comment by kotp** [comment]
Yes, but would it be able to put it in the location as I am used to it being now?  I think this is based on the local config... Of course I could just choose not to use the button... I like how it works at the moment, though having the hexadecinal number easily placed on my clipboard would be nice. (It works well in my terminal based browser, so really have no strong feelings on this personally.)

**Comment by Insti** [comment]
Just wanted to clarify, my "button to download directly from the webpage" would be a button on the solution page on the website implemented in the exercism.io repository and NOT as an addition to the cli.

**Comment by kytrinyx** [comment]
> Yes, but would it be able to put it in the location as I am used to it being now? 

No, I think that would be fine though.

> having the hexadecinal number easily placed on my clipboard would be nice.

Yeah, having the full command that could be copied to the clipboard with a click would be really nice.

**Comment by blueelvis** [comment]
We can have application specific URLs (for example - exercism://fetch ) and it will open via Exercism. That's all good and easy as well. Read this - https://msdn.microsoft.com/en-us/library/aa767914(v=vs.85).aspx


But, there could be security issues as well. Read this over here - http://stackoverflow.com/a/389271

I also think that having the command being copied to the clipboard would be best.

**Comment by kotp** [comment]
:+1: for having the command copied to the clipboard.   That is how i do it now, with a tool I wrote called cdx, which takes the hex part of the url, and applies that to the exercism download (clipboard content here), and then it changes directory to the exercism/solutions/(appropriate folder).

**Comment by Insti** [comment]
This is old, but still desired.

**Comment by kotp** [comment]
I would pin it, but not enough access to do so.

**Comment by kytrinyx** [comment]
This behavior is planned for the nextercism CLI.

I'm going to close this issue in favor of https://github.com/exercism/cli/issues/411
