### ISSUE TITLE
MacOSX install issues - mis-matched versions... maybe conflicting old install?

### ISSUE THREAD

**Issue by bunnymatic** [exercism/cli#342]
Hi

I used exercism a long while ago.  I recently installed via Brew on a machine that probably had the cli installed (but i'm not totally sure). 

I followed the docs, and I am now in a place where the cli doesn't appear to work.  And it's version doesn't match (even remotely) the brew package version.  Is that expected?  Shouldn't the brew version match the cli version?  I don't recall the old install process but maybe i've got libraries sitting around somewhere that are getting picked up?  I cleared out my `GOPATH` but that didn't help.

Any pointers?

```bash

% brew update && brew upgrade exercism
Already up-to-date.
Error: exercism 2.2.6 already installed
% exercism -v
exercism version 1.4.0
% which exercism
/usr/local/bin/exercism
% ll /usr/local/bin/exercism
lrwxr-xr-x  1 jon  staff  37 Aug  3 18:56 /usr/local/bin/exercism -> ../Cellar/exercism/2.2.6/bin/exercism
% exercism login
Your GitHub username: bunnymatic
Your exercism.io API key: b...............
What is your exercism exercises project path?
Press Enter to select the default (/projects/whatever):
> ~/exercism
Your credentials have been written to /Users/jon/.exercism.go
% exercism f java
Usage: exercism fetch
   or: exercism fetch LANGUAGE EXERCISE
% exercism f
Error fetching assignments. HTTP Status Code: 404
% exercism f java 1
Error fetching assignments. HTTP Status Code: 404
% exercism f java "Hello World"
Error fetching assignments. HTTP Status Code: 404
% brew info exercism
exercism: stable 2.2.6 (bottled), HEAD
command-line tool to interact with exercism.io
http://cli.exercism.io
/usr/local/Cellar/exercism/2.2.6 (2 files, 11.5M) *
  Poured from bottle on 2016-08-03 at 18:56:49
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/exercism.rb
==> Dependencies
Build: go ✘

```

Side note: i love that you've moved to a `brew` package.  Super stuff (if it worked ;) )

**Comment by bunnymatic** [comment]
Ack!  my bad.

I'd put an alias in for `exercism` to point to my locally installed version `~/exercism/exercism`.  This seems to hide nicely.  `which exercism` returns nothing but `exercism` runs (the old version). 

Sorry to bother you guys.

Keep up the good work.

**Comment by kytrinyx** [comment]
I'm so glad this turned out to not be a bug, and sorry it was messy/confusing there for a bit!
