### ISSUE TITLE
Restore not working in one case.

### ISSUE THREAD

**Issue by Insti** [exercism/cli#343]
@borkabrak had the following issue (copied from https://github.com/exercism/exercism.io/issues/2295)

> When running `exercism restore` into a new install on a different computer, the first php challenge does not update.  (The problem is calculating the hamming distance between two DNA strings).
> 
> The other work I've done is, indeed, downloaded, but hamming.php remains in its initial state instead of being overwritten with my solution.  
> 
> My guess is that the system is checking for the _existence_ of the solution files instead of looking at their contents, and since that file is provided for you in just the first case, nothing further is done.

**Comment by kytrinyx** [comment]
This is going to be resolved with the v2 redesign. Closing.
