### ISSUE TITLE
fetch --all gives no initial indication of progress.

### ISSUE THREAD

**Issue by Insti** [exercism/cli#345]
On running: `exercism fetch --all ruby`
It did nothing for a long time (tens of seconds) before displaying all the exercises it had downloaded/updated/etc.

I assume it was doing something networky and fetching a lot of things.

It would be nice if there was a helpful message that appeared immediately that said something reassuring like: `fetching all ruby exercises from the website...`

**Comment by lcowell** [comment]
You can use `exercism --verbose fetch ruby` to see the individual steps being taken. The output isn't super friendly, but could be useful if you're debugging a network issue.

**Comment by jtigger** [comment]
@Insti, is that sufficient for what you were wanting?  (looking to see if there's more to explore, here, or if we should close this issue)

**Comment by Insti** [comment]
Using the --verbose option is not the solution I was hoping for.
I wanted a helpful message indicating progress to be provided in the default case.

**Comment by kytrinyx** [comment]
How about implementing something like this? http://whipperstacker.com/2015/10/05/silence-noisy-output-from-command-line-tools-by-monitoring-progress-with-siginfo/

**Comment by Insti** [comment]
All I'm requesting is that before it starts fetching all the exercises, it prints a single line telling you it's going to do this, it should be a 1 line change. (Plus a couple more for tests..)

**Comment by Tonkpils** [comment]
Seems reasonable to me, I'll try to get to it this week 👍

**Comment by Insti** [comment]
Many thanks @Tonkpils :heart:
