### ISSUE TITLE
debug output is missing build os/arch

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#348]
The debug output from my machine says:

```
...
Build OS/Architecture /
...
```

I would expect this to say

```
...
Build OS/Architecture darwin/amd64
...
```

**Comment by 0xmohit** [comment]
This is because [`github.com/exercism/cli/cmd.BuildOS` and so on](https://github.com/exercism/cli/blob/master/cmd/debug.go#L44-L47) need to be passed to the link tool which would not happen when using go get.

**Comment by kytrinyx** [comment]
OK, that totally makes sense. I'm going to close this.
