### ISSUE TITLE
No CLI binary available for the ARMv8 architecture

### ISSUE THREAD

**Issue by fuzzytern** [exercism/cli#349]
The [installation page](http://exercism.io/cli/linux) doesn't offer any option for the ARMv8 architecture.

Also, there is not any build for ARMv8 available on the [Github release page](https://github.com/exercism/cli/releases/tag/v2.3.0).

A new build or instructions to compile the CLI from source on this platform would be helpful.
Help I got [here](https://github.com/exercism/exercism.io/issues/3157), got me to the stage where I get the following error when running `go install github.com/exercism/cli/exercism` : 

    /tmp/go-build626712024/github.com/exercism/cli/exercism/_obj/_go_.o: In function `main.main':
    /home/alarm/.go/src/github.com/exercism/cli/exercism/main.go:42: undefined reference to `github_com_urfave_cli.

## UPDATE
I get the same error when doing  `go get github.com/exercism/cli/exercism` 

Additional information:
Distribution: Arch Linux ARM
Architecture: aarch64
Note: also tried the AUR package, which doesn't build.

**Comment by NobbZ** [comment]
Ad far as I understand the go eco system, install does only build and install locally available stuff. Try go get and then install the cli.

**Comment by mhelmetag** [comment]
I was able to install `exercism` on my raspberry pi running AArch by:
```sh
$ su root
$ pacman -S go
$ su <previous_username>
$ mkdir ~/go
$ # add export GOPATH=$HOME/go and PATH=$PATH:$GOPATH/bin to my ~/.bashrc
$ source ~/.bashrc
$ go get github.com/exercism/cli/exercism
$ go install github.com/exercism/cli/exercism
```

Worked like a charm. So in essence I agree with @NobbZ , in saying that you need to `go get` first.

**Comment by Tonkpils** [comment]
I'm wondering if it's as simple as adding `GOARCH=arm64` to the release build script similar to https://github.com/exercism/cli/blob/master/bin/build-all#L76 without the 3rd argument as per https://github.com/golang/go/wiki/GoArm#supported-architectures.

**Comment by mhelmetag** [comment]
@Tonkpils , I would think it is that easy.

**Comment by fuzzytern** [comment]
@mhelmetag When I run the `get` command I get errors of type `../../.go/src/github.com/exercism/cli/vendor/golang.org/x/text/runes/cond.go:10:29: error: import file ‘golang.org/x/text/transform’ not found`

I run that command from the place where I cloned the repo. My GOPATH is set to `~/.go`.

If I then install that missing dependency with a Go Get, I am able to go one step further but running `go get github.com/exercism/cli/exercism` would fail with another missing dependency error (`import file xxx not found`). If I repeat manually installing all dependencies, I then reach the stage of my first post, getting the `undefined reference to `github_com_urfave_cli` whenever I do `go get` or `go install`  (I had done all this before posting here).

**Comment by Tonkpils** [comment]
@fuzzytern I'll be cutting out a release for ARMv8 for the 2.3.0 version. I'll ping back when that's done and see if that works for you

**Comment by fuzzytern** [comment]
Thanks @Tonkpils :)

**Comment by Tonkpils** [comment]
@fuzzytern could you give the arm-v8 binary a try? https://github.com/exercism/cli/releases/tag/v2.3.0 Let me know if everything works as expected. If it does I'll go ahead and merge the release script changes so the new releases take effect

**Comment by fuzzytern** [comment]
Thank you @Tonkpils! 
It works fantastically :D
