### ISSUE TITLE
Provide support for submitting multiple files

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#35]
```json
{
    "files": [
    {
      "filename": "path/to/file.ext",
      "code": "# code goes here...",
    },
  ]
}
```

See related issue: exercism/exercism.io#1165

**Comment by kytrinyx** [comment]
The backend supports accepting multiple files (see https://github.com/exercism/exercism.io/issues/1165), so this one can be bumped to the top.

**Comment by lcowell** [comment]
Would the usage now be that I would specify multiple files from the command line eg:
`exercism submit AbstractBobPresenter.java Bob.java`

The `Iteration` struct, is what is used with `client.Submit`. Currently it has a File attribute, so we would need to change it to be a slice of Files and update the code that works with iterations to handle multiple files. Does that sound about right so far as what's involved in completing this?

**Comment by kytrinyx** [comment]
> Would the usage now be that I would specify multiple files from the command line eg:

Yeah, that's what I was thinking.

Right now the API expects a JSON map of filename to contents. That would mean using a `map[string]string` serialized to `json:"solution"`, but I could change it to expect the serialized `[]File` if that seems cleaner.

It's a small change in one place, so really no big deal either way.

**Comment by ClashTheBunny** [comment]
Just to make sure, the the path of the file would be nice to preserve in
the metedata.  Some languages give significance to deep directories.

**Comment by kytrinyx** [comment]
Yeah, the path of the file is currently being preserved, and we need to continue to do so.

**Comment by kytrinyx** [comment]
Closed in https://github.com/exercism/cli/pull/166
