### ISSUE TITLE
Config file: <not configured> 

### ISSUE THREAD

**Issue by MustafaUW** [exercism/cli#351]
hello, 

I had installed exercism manually in windows 7 and each time i try to configure the client with my exercism API key i get an error "Error creating exercism directory mkdir C:\Users\user\exercism: The system cannot find the path specified"
the below line are the result of runing debug cmd: 

C:\Users\user>exercism debug

**** Debug Information ****
Exercism CLI Version: 2.3.0
Exercism CLI Latest Release: 2.3.0
OS/Architecture: windows/amd64
Build OS/Architecture windows/amd64
Home Dir: C:\Users\user
Config file: <not configured>
API Key: Please set your API Key to access all of the CLI features
Exercises Directory: C:\Users\user\exercism
Testing API endpoints reachability
        * GitHub API: https://api.github.com/ [connected] 90.0052ms
        * API: http://exercism.io [connected] 126.0073ms
        * XAPI: http://x.exercism.io [connected] 282.0162ms

If you are having trouble and need to file a GitHub issue (https://github.com/ex
ercism/exercism.io/issues) please include this information (except your API key.
 Keep that private).
Thank you in advance!

**Comment by kytrinyx** [comment]
Hi @MustafaUW I'm so sorry I didn't see this before now!

Does the `C:\Users\user` directory exist on your machine?

**Comment by MustafaUW** [comment]
Hello @kytrinyx , no worries! i solved the problem! was a problem with the directory and the where i set exercism path. thank you again :).

**Comment by kytrinyx** [comment]
Oh, that's great news! Thanks @MustafaUW
