### ISSUE TITLE
submit: Doesn't respect symbolic links.

### ISSUE THREAD

**Issue by Insti** [exercism/cli#354]
I submitted a solution I thought was called `simple_linked_list.rb` 

```
$ exercism submit ruby/simple-linked-list/simple_linked_list.rb 
Your Ruby solution for Simple Linked List has been submitted. View it here:
http://exercism.io/submissions/b2a39967e4a749abacaef53dbfda2cd3

See related solutions and get involved here:
http://exercism.io/tracks/ruby/exercises/simple-linked-list
```

However `simple_linked_list.rb` is a symbolic link to a file called `simple_linked_list_better.rb`.

In [the submitted solution](http://exercism.io/submissions/b2a39967e4a749abacaef53dbfda2cd3) the file shows up with the name of the link target 
`simple_linked_list_better.rb` rather than the expected filename.

Edit: OS: linux

**Comment by Tonkpils** [comment]
Your expectation is for the file contents to be of the linked file but the file path/name to be of the file you used during submit?

**Comment by Insti** [comment]
> Your expectation is for the file contents to be of the linked file but the file path/name to be of the file you used during submit? 

Yes.

I submitted `simple_linked_list.rb` that is the file I edited, that is the file the tests run against.
That it is a symbolic link should be irrelevant.

**Comment by lcowell** [comment]
I'm interested in adding this if no one else is already working on it.

**Comment by Insti** [comment]
@lcowell that would be great. I'm not aware of anyone else currently working on this.

**Comment by Insti** [comment]
Thanks for fixing this @lcowell :heart:
