### ISSUE TITLE
submit: should not follow symbolic links and add a flag to do so

### ISSUE THREAD

**Issue by jtigger** [exercism/cli#355]
There's something to be said for Exercism being self-sandboxed.  By default, we only submit files from your computer that live under the exercism exercises directory.  You, the user have the control to change that root directory, but we never venture out of that space.  

Symbolic links break out of that sandbox.  If followed, it should be under the direction of the user.

```bash
$ exercism submit -L simple_linked_list.rb
```

and/or

```bash
$ exercism submit --follow-symlinks simple_linked_list.rb
```

**Comment by Tonkpils** [comment]
This can probably be tackled along with #354. However, I don't use this feature of using symbolic links often so I'm not sure if I can give some input on this particular issue. 

@Insti maybe you have better input on whether this is a good change to have. My first thought is we'd have to think about the error messages to display to the user in the case they do try to submit a symbolic link without the explicit flag.

**Comment by Insti** [comment]
> If followed, it should be under the direction of the user.

That is why I created the symbolic link in the first place.

Which files are submitted **is** under control of the user, and if I ask it to submit `simple_linked_list.rb` `exercism` should not have an opinion on whether that is a "real" file, a symbolic link, or a file on a fuse filesystem mapped to twitch stream.

**Comment by Tonkpils** [comment]
I'm not sure if you're agreeing with this issue, do you think we need an explicit flag to ensure symlinks are followed or not? I don't really use this feature so I can't be of much help other than to implement it though I don't see the need for an explicit flag.

**Comment by Insti** [comment]
Sorry. I disagree with the proposal.

The default behaviour should be to follow symlinks.

(I would be fine with an option to not follow them.)

**Comment by lcowell** [comment]
I think the cli is already sandboxed enough without needing to control whether we follow symlinks or not. The user controls what's being put in that folder and if they put a symlinked file in there, it's implied that they want the cli reading it. My 2c.

**Comment by jtigger** [comment]
Okay, I'm withdrawing the proposal.

The main thing that flipped in my head is that for commands that potentially operate on a symlink, the default is to not follow the symlink; commands that do not create/modify symlinks typically follow/respect symlinks by default.

The Exercism CLI is in the latter group.

**Comment by Insti** [comment]
Thanks @jtigger, that sounds reasonable. I agree with the read/write distinction.
