### ISSUE TITLE
Feature request: Default redact API key from debug output

### ISSUE THREAD

**Issue by Insti** [exercism/cli#357]
The `exercism debug` command lists a lot of useful information and a request that people post this to a Github issue if they are having problems. If they just copy/paste this information it exposes their full API key. 

By redacting the central characters of the API key, it allows copy/pasting and basic verification that the api key is there and that the first and last characters look correct, without exposing the full key, and doesn't require the user to manually obscure the API key.

**Proposal:**

By default, redact the central characters of the API key so that the full API key is not available.

```bash
$ exercism debug

<debug output>
API Key: 5771------------------------b58c
<more debug output>

```

Add a command line option to show the full api key if this really is necessary.

```bash
$ exercism debug --full-api-key

<debug output>
API Key: 5771a11609868802615775105cccb58c
<more debug output>

```

**Comment by Insti** [comment]
The `--full-api-key` option might not even be required since we can presumably look in the config file for this once we confirm via `exercism debug` that the config file is working properly.

**Comment by kytrinyx** [comment]
I think this suggestion makes a lot of sense.

I would like to include the `--full-api-key` option, since I think this would let people not have to worry about where the config file is and how to view it (cat, open in editor, whatever... some people are less comfortable on the command line).

**Comment by jtigger** [comment]
@Insti, did you mean to omit the flag in your first example?

like this...

```
$ exercism debug

<debug output>
API Key: 5771------------------------b58c
<more debug output>
```

**Comment by Insti** [comment]
> @Insti, did you mean to omit the flag in your first example?

Yes, thanks. I've edited the OP.

**Comment by Insti** [comment]
Thanks @Tonkpils :heart:
