### ISSUE TITLE
Create Windows installer

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#36]
If it could set up the path and everything, that would be brilliant.

**Comment by roseaboveit** [comment]
@kytrinyx given Dangthrimble's link above, is this issue resolved or is this still an active feature request for the future?

**Comment by Tonkpils** [comment]
@roseaboveit I can still see this being useful. On OSX we have homebrew for installing the CLI. I'm not familiar with similar tools for Windows or how complicated it would be to write an installer for it.

**Comment by kytrinyx** [comment]
I'd also like to keep this open. It would be fantastic to have people double-click something and it would put everything in the right place and fix the registry or whatever else needs to happen. I simply don't know what type of work would be involved at the moment.

**Comment by roseaboveit** [comment]
Is this the sort of thing that someone who did know how to make Window's Installers could pick up and work on it?

If not, what would need to be done to make this ticket actionable so we can label it with a todo tag?

**Comment by Tonkpils** [comment]
> Is this the sort of thing that someone who did know how to make Window's Installers could pick up and work on it?

Yup, I'm assuming for someone with some knowledge of windows programming it'd be fairly straight forward.

**Comment by kytrinyx** [comment]
Yeah, presumably someone who knows windows development would be able to do this without knowing much (or anything) about Go or exercism.

**Comment by roseaboveit** [comment]
@kytrinyx I am not able to add labels in this repo still. Could you apply a todo tag so that someone perusing with the skill could easily find this?

**Comment by kytrinyx** [comment]
Done. Also, fixed the permissions for this repository.

**Comment by blueelvis** [comment]
@kytrinyx - I have created an installer. Could you please test it? It downloads the version automatically depending on the architecture of system. Feedback would be appreciated :)

https://github.com/blueelvis/ExercismWinSetup/releases/tag/1.0

**Comment by kytrinyx** [comment]
Yay :sparkles:

I don't have access to windows machine to test on, unfortunately. I've retweeted your tweet about it, so perhaps someone will jump in. I'll also stick this in the newsletter on Sunday.

**Comment by blueelvis** [comment]
@kytrinyx :dancer:

The setup is working fine on my system. I would need someone to test on different systems and languages to make sure it is working properly. Let's see who jumps in ^_^

I wonder if it is ready to be included in the newsletter since I am wondering if it needs more polish. On the bright side, you include it and people would hopefully provide feedback.

**Comment by kytrinyx** [comment]
The newsletter isn't about polish—it's really more of an "insiders" newsletter than anything, I think. People who like to know what's going on, what's not working, where do we need help, etc.

I will include it and a link to the installer.

Would you put a description in the latest release of the exact steps to install and what you would want feedback on?

**Comment by blueelvis** [comment]
@kytrinyx - Yes, I will update the description with screenshots and the whole process tonight once I am back from college.

Have a nice day ^_^

**Comment by blueelvis** [comment]
@kytrinyx - I have updated the documentation as well. Released a new executable (Under Releases section). Please let me know if there is anything else which needs to be done ;)

Regarding the feedback, I would be really glad if someone could guide me on writing unit tests for a project like this (More under the contributing section). :D

**Comment by kytrinyx** [comment]
@blueelvis this is great!

Would you be interested in moving this into the exercism organization? You would of course be the maintainer of the project/repo, but it would make it easier to find.

**Comment by blueelvis** [comment]
@kytrinyx - I would love to do that ^_^. I don't know the process of moving a repository to an organization though.

**Comment by kytrinyx** [comment]
@blueelvis it turns out it's a bit complicated to move something to an org, but if you transfer it to my user (`kytrinyx`) then I can transfer it to the exercism org (since I have admin rights on the organization, it will let me do that).

Then I'll make a team for the installer and add you to it.

**Comment by blueelvis** [comment]
@kytrinyx - I have initiated the transfer of repository. Please let me know when you have moved it to Exercism :)

**Comment by kytrinyx** [comment]
It's been moved. It's now at https://github.com/exercism/windows-installer and you've got access. Let me know if you want to add anyone else to the maintainer team at any point.

**Comment by Tonkpils** [comment]
I am going to go ahead and close this! Thanks for the great work @blueelvis and @kytrinyx

**Comment by kytrinyx** [comment]
@blueelvis did all the work!

**Comment by blueelvis** [comment]
@Tonkpils - You are welcome ^_^.

@kytrinyx - Thanks! I will let you know in case of any issue :)
