### ISSUE TITLE
Feature Request: Option to silence the output from 'exercism configure'

### ISSUE THREAD

**Issue by dmmulroy** [exercism/cli#365]
I think it would be useful to have an option with `exercism configure` command to silence its output.  My main use case for this feature is that I  would like to have all of my exercises running on a travis ci build and currently it would be publicly outputting my api key when it builds.

**Comment by dmmulroy** [comment]
PR opened here: https://github.com/exercism/cli/pull/366

**Comment by kytrinyx** [comment]
That's a great idea.
