### ISSUE TITLE
i/o timeout whilst fetch [Duplicated from exercism.io repo #3358]

### ISSUE THREAD

**Issue by alex-bender** [exercism/cli#367]
During `fetch` I got this error:
```
$ exercism fetch c   
2017/01/25 17:41:03 Get http://x.exercism.io/v2/exercises/c?key=REDACTED: dial tcp: lookup x.exercism.io on 217.20.184.1:53: dial udp 217.20.184.1:53: i/o timeout
```
Would be better to have well described reason of this error;
Not sure if it is issue, or if it is already opened.

```
$ exercism --version
exercism version 2.3.0
$ uname -a
Linux bender 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux
```

**Comment by kytrinyx** [comment]
Thanks @alex-bender, I'm open to this. Especially if we can also suggest what people might try.

**Comment by alex-bender** [comment]
@kytrinyx As far as I understand it is DNS issue (port 53), isnt'it?

**Comment by kytrinyx** [comment]
Weird, you're right. I'm pretty terrible at debugging DNS issues... why port 53? The website runs on port 80.

**Comment by kishorekumar522** [comment]
@alex-bender Try modifying /etc/resolv.conf file with below name server and fetch
`nameserver 8.8.8.8`
It worked for me like charm

**Comment by alex-bender** [comment]
@kishorekumar522 Thanks, but in my case it's works with and without 8.8.8.8
