### ISSUE TITLE
Documentation on submitting exercises contains an error 

### ISSUE THREAD

**Issue by stevejb71** [exercism/cli#368]
It says : "At the moment each exercise must be solved in a single file." 

But I can submit multiple files in one call to the client and they all get posted.

**Comment by kytrinyx** [comment]
Oh, wow. Yeah, that's pretty old.

Where did you see this, exactly?

**Comment by stevejb71** [comment]
Ah yes, a link would have been helpful :). 

It's on http://cli.exercism.io, under the submitting exercises heading.

**Comment by kytrinyx** [comment]
Thanks! That codebase is in https://github.com/exercism/cli-www

**Comment by robphoenix** [comment]
I believe this PR https://github.com/exercism/cli-www/pull/30 closes this issue?

**Comment by stevejb71** [comment]
It's fixed
