### ISSUE TITLE
wishlist: exercism fetch $PROBLEM

### ISSUE THREAD

**Issue by petertseng** [exercism/cli#369]
Currently, the one-argument form of `exercism fetch` assumes the single argument is a track slug, then fetches the first problem you haven't done in that track.

But, what if, given that my current working directory is `$EXERCISM_DIR/c`, I could do `exercism fetch leap` and it will fetch the leap exercise for the c track? In other words, accept an exercise slug as the only argument in the one-argument form.

This item is only on the wislist because it raises a significant design question that must be solved before it can be implemented.

**How will we determine, given a one-argument form, whether the single argument is a track slug or a exercise slug?**

* Call into e.g. http://x.exercism.io/tracks to see whether the single argument is a valid track slug. Only if it isn't, assume it's an exercise slug.
    * Disadvantage: incurs an additional network call per usage of the one-argument form.
    * Open question: Okay, so can we cache the track list to reduce the cost? For how long will we consider our cached list to be effective before we decide to fetch a new list?
* Hard-code a list of tracks into the exercism CLI at compile-time.
    * Disdavantage: students will have to update the entire CLI when a new track is added and they want to fetch an exercise for it using this one-argument form.
    * Disdavantage: the CLI maintainers will have to release a new CLI whenever a new track is added
* Include a list of tracks with the exercism CLI that the CLI reads from at run-time.
    * Open question: But where will it be placed? How will exercism CLI know where to look for it?
    * Disdavantage: students will have to update this list when a new track comes out and they want to fetch an exercise for it using this one-argument form.
* Always assume it is an exercise slug. No need to check.
    * Disadvantage: breaks backward compatibility
    * Disadvantage: breaks the workflow of anyone who uses `exercism fetch $TRACK`
    * Disadvantage: the website explicitly mentions `exercism fetch $TRACK` at http://exercism.io/languages/c/about which means the website would hvae to be updated
    * (This is the correct choice **for me personally**, since I know that I will only use the `exercism fetch $PROBLEM` form and never the `exercism fetch $TRACK` form)
    * Implementation at https://github.com/petertseng/exercism-cli/commit/becf4b8f1b7624fabb8840737a3012d7dc58c803 (If that link expires because I rebase commits, look in https://github.com/petertseng/exercism-cli/commits/personal)
* Other idea that I am missing

**Comment by petertseng** [comment]
For me, I'm also going to make the zero-arg form infer both problem and track. I can't see this break from compatibility (of previous behaviour) being suitable for others, but it's the right choice for me - I don't want to fetch one problem per active track; for me `fetch` should only fetch one problem. https://github.com/petertseng/exercism-cli/commit/8bc80fab17a8f92a4ec20ec35b1d637de3178dca

**Comment by kytrinyx** [comment]
> How will we determine, given a one-argument form, whether the single argument is a track slug or a exercise slug?

I'd like to suggest that we completely change the way we think about fetching (backwards-incompatible, meaning a v3 of the CLI).

I think that we should always act only on one track at a time, and always infer the track. If we can't infer it we should error and ask people to specify the track with a flag.

I'm expanding on all of these thoughts in https://github.com/exercism/discussions/issues/129 and we may want to close this issue in favor of the broader discussion.

**Comment by petertseng** [comment]
I am going to bring up my wishlist items in https://github.com/exercism/discussions/issues/129 - I'm sure that once there is agreement on what the features shall be, the appropriate issues will be opened in this repo.
