### ISSUE TITLE
wishlist: exercism submit $DIR

### ISSUE THREAD

**Issue by petertseng** [exercism/cli#370]
Currently, `exercism submit` refuses to act on directories.

What if, however, I could specify an exercise directory (such as `$EXERCISM_DIR/c/leap`, and `exercism submit` would automatically do the right thing?

* Determine what track + exercise that directory refers to
* Based on the track, determine what files within that directory to submit.

This item is only on the wislist because it raises a significant design question that must be solved before it can be implemented.

**Given an exercise directory and track, how do we determine what files to submit?**

* Look at `test_pattern` for the language. Find the files matching the `test_pattern`, and find their extension. **Submit all other files with that extension**.
    * Disadvantage: Does not work for the perl5 track, Their test files are e.g. `anagram.t` and implementation files are `Anagram.pm`. Different extension.
* A hard-coded rule for each language that the CLI is made aware of at compile-time
    * Disdavantage: students will have to update the entire CLI when a new track is added and they want to submit a solution for it using this form.
    * Disdavantage: the CLI maintainers will have to release a new CLI whenever a new track is added
* A rules file containing rules for each language that the CLI is made aware of at run-time
    * Open question: But where will this rules file be placed? How will exercism CLI know where to look for it?
    * Open question: What will the specification language for this rules file look like?
    * Disdavantage: students will have to update this list when a new track comes out and they want to fetch an exercise for it using this one-argument form.
* Other idea that I am missing

Regarding the two possibilities that involve per-language rules: My list of the per-language rules known to me is at https://gist.github.com/petertseng/e3e88bf1c383865ff67f4095413993b2. They're pretty much all expressed as "glob files with this extension, but exclude test files". For tracks that separate out their test files and implementation files into separate directories, I don't even need to do exclusions.

**Comment by kytrinyx** [comment]
I think this would be a great improvement in the user experience.

Also, I'd like to support `exercism submit` without a dir, which would assume the current directory.

> A rules file containing rules for each language that the CLI is made aware of at run-time

I think that the rules file could be defined in the _global_ directory that we support. We'd have to work out the details of how people would get the rules file if they don't already have it.

E.g. Should all tracks have an empty rules file by default? That way if you don't have a rules file, the CLI could run the `setup` command (or whichever gets the global files).

**Comment by petertseng** [comment]
I am going to bring up my wishlist items in https://github.com/exercism/discussions/issues/129 - I'm sure that once there is agreement on what the features shall be, the appropriate issues will be opened in this repo.
