### ISSUE TITLE
Potential compatibility issue when running in Virtual Machine

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#371]
In https://github.com/exercism/exercism.io/issues/1906 someone is trying to use the CLI built for Mac (64-bit) in a virtual machine on Windows.

Once the configuration was sorted out, there was an error when fetching:

```
Ganesh$ exercism fetch swift
2017/02/22 15:00:58 Get http://x.exercism.io/v2/exercises/swift?key=***redacted***: EOF
```

@kotp observed:

> The EOF part of the two lines and the information that you are using a virtual machine on windows, tells me that the line endings (or specifically EOF characters) that are not compatible on your file system may be causing the problem, and the operating system, maybe causing the problem.

This does not affect a lot of users, and so should not be a high priority to fix, but if someone needs a puzzle for a holiday or something, it is a thing to troubleshoot.

**Comment by NobbZ** [comment]
I'm not quite sure how the native lineending format of some system should affect anything on another system. And thats what HOST and GUEST are, two different systems.

**Comment by kotp** [comment]
```
Testing API endpoints reachability
* XAPI: http://x.exercism.io [Get http://x.exercism.io: EOF] 822.244458ms
* API: http://exercism.io [Get http://exercism.io: EOF] 1.318212594s
* GitHub API: https://api.github.com/ [connected] 1.544939383s
```
Specifically the EOF indicated on these two lines.  But I am not totally convinced.

@guru-teja Can you install exercism on the host system (Your windows system) and do the fetch?  This will help to confirm it is the guest/host combination causing the problem.

**Comment by guru-teja** [comment]
@kotp I am sorry to tell you that due to some restrictions and privileges I am unable to install Chocolately in my host system, I will try in my personal PC.

**Comment by kotp** [comment]
Thanks.  I hope the experience is more pleasant on your home PC.

I wish I could say I knew how to do a "User" based install of Chocolaty but I don't.  Perhaps someone does though, it may be the way for you to go.

**Comment by NobbZ** [comment]
Even if there are rumors about people who managed to do an unpriviliged install of Chocolatey, it is not recommended to do so. At the end, most of the packages are just wrappers around the usual install program but starting it in a headless mode, but still requiring that installer to have priviliges.

But perhaps you can use the method described as [windows manual installation](http://exercism.io/cli/linux#windows-manual-installation) @guru-teja

**Comment by kytrinyx** [comment]
> Even if there are rumors about people who managed to do an unpriviliged install of Chocolatey, it is not recommended to do so.

I think that this is legitimately a 'wontfix'. I've opened an issue to address this with a documentation change: https://github.com/exercism/exercism.io/issues/3494

**Comment by kotp** [comment]
Fighting with @probot-stale againwith the labels?
