### ISSUE TITLE
Deprecated urfave/cli signature used

### ISSUE THREAD

**Issue by nilbus** [exercism/cli#376]
Building and running locally with the latest version of [urfave/cli] (1.19.1) produces this error:

    ERROR unknown Action error: reflect: Call using *cli.Context as type *cli.Context.
    See https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature

urfave's [CHANGELOG] suggests that this has been deprecated since 1 year ago, and that the most recent 1.19.x releases have also made related changes.

[urfave/cli]: https://github.com/urfave/cli
[CHANGELOG]: https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature

Thoughts on what might be wrong here? Can others reproduce the problem?

**Comment by Tonkpils** [comment]
What version of Go are you using? We use `Godeps` to vendor our dependencies and from the `Godeps.json`, we're using `1.17.0`. I'm assuming the later releases of `cli` package caused this incompatibility.

If you're using the later versions of Go, it should automatically use the vendored deps and shouldn't cause any issues.

**Comment by nilbus** [comment]
I'm on 1.8, so in theory, that should be working. I didn't know about `Godeps`, so I assumed the newer version in `GOPATH/src/github.com/urfave/cli/` was what it was using.

After poking around a bit more, I discovered that this problem doesn't occur with the exercism source in `$GOPATH/src/github.com/exercism/cli`, only in my fork's `$GOPATH/src/github.com/nilbus/cli`. Considering now that I can just add a remote in the `exercism/cli` path and have everything work, I think this is a non-issue.
