### ISSUE TITLE
Submit doesn't work inside a symbolically linked directory

### ISSUE THREAD

**Issue by rolfb** [exercism/cli#384]
Example:
Actual path: `/some/long/path/where/exercism`
Symbolic path: `/playground/exercism`

If you submit from a sub-directory of the symbolic path `/playground/exercism` it won't matter if you've configured the exercism directory to be actual path or symbolic path. It will always compare symbolic path to actual path and fail.

It's basically trying to match `pwd` with `pwd -P` from a shell perspective.

Fetch works however.

**Comment by kytrinyx** [comment]
This should be fixed in https://github.com/exercism/cli/releases/latest
