### ISSUE TITLE
Respect TRACK_ID and SLUG options on restore command

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#389]
The restore command currently has one behavior: restore absolutely everything.

This is not going to work when people have done lots of exercises in lots of tracks.

A better behavior would be to respect passed in arguments for track and exercise:

```
exercism restore javascript
```

and

```
exercism restore rust leap
```

If you have not done the exercise, the API will return a 404 and an error message that we can display.

If someone says `exercism restore` with no arguments, I think we should return an error message and ask them to specify which track to restore.

**Comment by NobbZ** [comment]
@probot-stale[bot] please leave this open. I'm willing to contribute a PR over the course of the next three weeks if my real life doesn't get even more in the way ;)

**Comment by kytrinyx** [comment]
I've added the 'pinned' label so probot won't touch it.

**Comment by kytrinyx** [comment]
Selectively downloading the latest solution to an exercise is going to be the default behavior of the `download` command in the new nextercism CLI. I'm going to close this issue in favor of https://github.com/exercism/cli/issues/411
