### ISSUE TITLE
Hint that --all might be a possible parameter to fetch.

### ISSUE THREAD

**Issue by Insti** [exercism/cli#392]
From: https://github.com/exercism/exercism.io/issues/3545

> Is there a way to download all exercises?
> ...
> Nevermind there's a --all flag. Don't see it anywhere in the --help

`exercism help fetch` will tell you about --all but `exercism --help` will not.

Todo:

Update `exercism --help` to mention the possibility of fetching all exercises.

**Comment by Insti** [comment]
Will this still be possible with nextercism?

**Comment by Tonkpils** [comment]
Yeah, we should implement this to make it a bit more clear. I'll have some more time in the next couple of weeks to tackle this.

**Comment by kytrinyx** [comment]
With nextercism the exercises will become available to you when you solve the prerequisites. If you want to download an entire track this would not be possible via the CLI. You would need to clone the repo and work from that.

I think we need to better understand what the use case is and see how this fits with the new design (not visual design, but progression design) before implementing this for the nextercism CLI.

**Comment by kytrinyx** [comment]
I've added a note to https://github.com/exercism/cli/issues/411 about this.

I'm going to go ahead and close this in favor of that issue.
