### ISSUE TITLE
Provide status command

### ISSUE THREAD

**Issue by stevensonmt** [exercism/cli#395]
I would suggest enabling `status` for `fetch` such that it is easy to find the most recent exercise.  Either that or organize the exercises by order of curriculum rather than alphabetically so that one can see what is next after the most recently submitted exercise.

**Comment by kotp** [comment]
Can you show an example of where it is listed alphabetically?  When I do:

`exercism list ruby`

I see:

<details>

```plain
hello-world
hamming
gigasecond
rna-transcription
raindrops
difference-of-squares
pangram
sieve
roman-numerals
nth-prime
leap
grains
word-count
bob
run-length-encoding
binary
accumulate
sum-of-multiples
grade-school
series
phone-number
prime-factors
strain
etl
trinary
beer-song
bowling
space-age
anagram
binary-search-tree
crypto-square
clock
alphametics
rail-fence-cipher
acronym
scrabble-score
nucleotide-count
flatten-array
hexadecimal
say
meetup
robot-name
queen-attack
palindrome-products
bracket-push
food-chain
matrix
saddle-points
triangle
atbash-cipher
house
secret-handshake
proverb
ocr-numbers
pig-latin
simple-linked-list
luhn
simple-cipher
wordy
allergies
poker
kindergarten-garden
linked-list
pythagorean-triplet
robot-simulator
twelve-days
circular-buffer
largest-series-product
binary-search
two-bucket
pascals-triangle
custom-set
minesweeper
scale-generator
protein-translation
perfect-numbers
connect
list-ops
diamond
all-your-base
isogram
transpose
tournament
dominoes

In order to fetch a specific assignment, call the fetch command with a specific assignment.

exercism fetch ruby hello-world
```
</details>
</br>

When I do `exercism status ruby` I see:

```plain

Your status on the ruby track:

Most recently submitted exercise:
 - leap (submitted on June 5, 2017)

Exercises fetched but not submitted:
 - sorry, tracking disabled for fetching

Exercises skipped:

```

The last one is not helpful for indicating what is next, for sure.

**Comment by NobbZ** [comment]
`ls`

Victor Goff <notifications@github.com> schrieb am Mo., 12. Juni 2017, 00:29:

**Comment by kotp** [comment]
@NobbZ  I used "listed" instead of "listing" and in reference of "it" to mean "exercism" as a command.

**Comment by NobbZ** [comment]
Well, the directory listing was exactly the "thing" we talked about when
this was in the chat a few days ago.

But independently of the command you run, there is currently no way to see
which exercises on my harddisk are not submitted to exercism, and that is
what this proposal is about.

Victor Goff <notifications@github.com> schrieb am Mo., 12. Juni 2017 um
07:21 Uhr:

**Comment by stevensonmt** [comment]
I was not actually aware of the `exercism list` command, but even still @NobbZ is correct that the information regarding what exercises were submitted is not available.

**Comment by kotp** [comment]
Indeed, @stevensonmt it is a valid issue, for sure.  I was fishing to see what else you had tried.  It wasn't clear in the original post (at the top of this page) where the alphabetical listing was coming from.  Or where `status` or `fetch` were being used from, if at all.

**Comment by stevensonmt** [comment]
@kotp I ran `exercism status ruby` from terminal, but the listing I referred to was the "curriculum" listed on the [exercism website](http://exercism.io/languages/ruby/exercises).

**Comment by kotp** [comment]
Does this translate to the normal order of fetching?  Perhaps armed with that information, and what is on the hard drive, a solution could be made that you want.

**Comment by NobbZ** [comment]
As we do know the order may change, also I might have skipped some
exercises.

Also the following may occur: I might sit at my office desk and have some
spare time and want to do exercism. Here I do only have fetched some
exercises randomly, because I solve most of the things from home. So having
an exercise NOT on disk does not actuially mean that I hadn't solved it
already. Even having an exercise on disk but not having submitted it from
HERE means not to have it not submitted at all.


Victor Goff <notifications@github.com> schrieb am Di., 13. Juni 2017 um
06:31 Uhr:

**Comment by stevensonmt** [comment]
That's exactly it.  I have four machines that I sometimes work exercises from, so none of them has the complete set of fetched OR submitted exercises.

**Comment by kotp** [comment]
OK.  I am seeing that "the most recent exercise" from the introduction post means "The last exercise that was submitted"?  Though is this always the case?  When you submit a new iteration, should this be the last exercise submitted?  Or is it always the last one before the one that hasn't been fetched?

And what if all of them have been fetched?

**Comment by kytrinyx** [comment]
We're going to be changing how the site works so that we always know who fetched what, and will be able to tell you that.

**Comment by stevensonmt** [comment]
@kytrinyx  Will there be a way to see "fetched but not submitted"?
@kotp "most recent exercise" was intended to refer to "last exercise fetched but not submitted".  If all exercises have been fetched, they would presumably have been fetched in order, so "last exercise fetched but not submitted" would likely be the same as the last exercise in the track.  This could be avoided by checking the list of submitted exercises against all exercises in the track and then querying if the next exercise in the track after the most recently submitted exercise has been fetched.  Of course people can fetch specific exercises out of order, so you would keep querying until you found an exercise that had been fetched.

**Comment by kytrinyx** [comment]
@stevensonmt yes, there will

**Comment by NobbZ** [comment]
@kotp most recent exercise is roughly to understand as "that exercise that
would have been fetched for this track if I had an empty track directory on
the current machine."

Katrina Owen <notifications@github.com> schrieb am Di., 13. Juni 2017,
18:20:

**Comment by kotp** [comment]
@stevensonmt I have fetched all exercises, more than once, but in between have done individual ones as I go back, or update the tests that are received.  I had not assumed the initial state after the first `fetch --all`, but rather, after some history, with the addition and removal of exercises over time.

This is further complicated, of course, when multiple machines are used.  So, good news from @kytrinyx that this is in the works.

**Comment by stevensonmt** [comment]
@kotp when fetching all, doesn't it still fetch them individually in some sequence?  I assume `fetch --all` does not bring in some zip archive that has to be expanded on the local machine, but I have never tried it.

**Comment by kotp** [comment]
It does, and it seems to do so in the `config.json` order of the track.  Which means that sometimes it changes.

**Comment by kytrinyx** [comment]
We're completely reworking the user experience in V2, and I think that this problem will be solved much better through the web interface.

After launch, if there's still a strong need for something like this via the command-line client, let's discuss in a new issue. 🌷
