### ISSUE TITLE
Suggestion: print hints about exercise

### ISSUE THREAD

**Issue by Smarticles101** [exercism/cli#396]
So over in xjava, there is a problem where people's programs they submit don't pass all test cases because they forget to remove `@Ignore` annotations on test cases. I have an idea for a feature of the cli where is a `HINT.md` or an `INFO.md` file exists in an exercise being fetched, it will print it to the screen where the user will see it. This could be used for any sort of information the user might need to remember when doing the exercise.

**Comment by NobbZ** [comment]
Whoever does not see that there are X pending or skipped tests in the suite, will also not see a message printed while fetching the exercise, which also stays the same for every exercise. And even if he reads it, he will have forgotten until the time he submits.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this one, as with v2 we are going to be working towards ensuring that everyone gets feedback. If we see that this continues to be problematic, we'll work with the product team to solve it.
