### ISSUE TITLE
Support the XDG Base Directory Specification

### ISSUE THREAD

**Issue by tengwar** [exercism/cli#400]
Currently exercism's cli client puts its config file in my `$HOME`. This creates a mess. The config file should go into `$XDG_CONFIG_HOME`. (Usually it means `~/.config/`, `~/Library/Preferences/` or `%APPDATA%` on Linux, macOS and Windows respectively.)

The specification may seem complex, but there are simple Go libraries that implement it. For example the first google result is [this lib](https://github.com/casimir/xdg-go).

**Comment by Tonkpils** [comment]
@tengwar are you not seeing this behavior when using the CLI? Which version of the CLI are you using? We added XDG_CONFIG_HOME support and if it's not working as expected it is a bug, notice we are adding the config file to the XDG_CONFIG_HOME path https://github.com/exercism/cli/blob/master/paths/paths.go#L31-L42

**Comment by tengwar** [comment]
I'm using exercism version 2.4.0. I installed it and on first run it created .exercism.json in my home folder. I noticed that I forgot to set the `XDG_*` variables after reinstall, but the config file should still go to `~/.config/` according to the spec:

> If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

**Comment by Tonkpils** [comment]
I feel like the behavior in place is correct. If you set the variables after you created the config file in the home folder, we would have to fallback to home every time when attempting to read the config file if it's not at the specified place. The spec says if the variable isn't defined it'll use that and not default to home. It will only default to home if it is not set or empty. 

You'd need to either copy the configuration file into your XDG path if you have that variable set, or unset that variable.

**Comment by tengwar** [comment]
Normally you shouldn't touch home at all, but you already did. So yes, you would need a fallback to home for at least few releases - for backward compatibility.

I realize I now have to move this file myself, but this bug is about 2 things:

- For new users create the config in ~/.config/ (or in $XDG_CONFIG_HOME if it's set and not empty).
- For existing users use the file from (from most to least preferred) `$XDG_CONFIG_HOME`, `~/.config/` or `$HOME`. Perhaps also deprecate the `$HOME` location and warn if the config file is there.

**Comment by kytrinyx** [comment]
I'm working a rewrite of the CLI for the new site launch, and will use the following configuration options, from most to least preferred:

- `EXERCISM_CONFIG_HOME` environment variable
- `XDG_CONFIG_HOME` environment variable
- `~/.config/exercism/config.json`

**Comment by kytrinyx** [comment]
I think we've got this right in the pre-release for the 3.0.0 client. https://github.com/exercism/cli/releases/tag/v3.0.0-alpha.2

There's still a fair amount to be done before we actually launch it, but if you have a moment to verify that it does what you would expect, I'd appreciate it!

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this one, as we've solved it for the `nextercism` client.
