### ISSUE TITLE
Error on misspelled command is different

### ISSUE THREAD

**Issue by tejasbubane** [exercism/cli#401]
I misspelled the submit command and saw the error was a little different:

```
❯ exercism submmit hello_world.ml
No help topic for 'submmit'
```

I think this can be handled in a better way - eg. `Invalid command <command name>` followed the entire help section.

* cli version `2.4.1`

**Comment by Tonkpils** [comment]
Thanks for reporting this! It does seem like we should handle invalid cases a bit better.

**Comment by kytrinyx** [comment]
I suspect that this will be handled better in the nextercism CLI, as we're using Cobra, which has some pretty snazzy help functionality.

TODO: build a local version of the `nextercism` branch (in https://github.com/exercism/cli/pull/410) and see if the suggestions are better.

**Comment by kytrinyx** [comment]
@tejasbubane would you see if this is handled better in https://github.com/exercism/cli/releases/tag/v3.0.0-alpha.2?

**Comment by tejasbubane** [comment]
@kytrinyx Yup, its better now. 

But I see two issues there: 
* The error is shown twice.
* Error message says `for ""`. Should it be `for nextercism` (or `for exercism`)? 

```
➜ nextercism version
exercism version 3.0.0-alpha.2

➜ nextercism submmit hello-world/hello_world.ml
Error: unknown command "submmit" for ""

Did you mean this?
	submit

Run ' --help' for usage.
unknown command "submmit" for ""

Did you mean this?
	submit
```

**Comment by kytrinyx** [comment]
```
➜ nextercism version
exercism version 3.0.0-alpha.2
```

Ah. We should use the binary name for this, rather than hard-coding Exercism. I'll fix that.

The other thing is weird, I'm not sure why it's happening. It should definitely not show it twice, and it should also use the binary name rather than "".

**Comment by tejasbubane** [comment]
The main issue here seems to be fixed with improved error message:
`Error: unknown command "submmit"`

Should the duplication thing be moved to a separate issue?

**Comment by kytrinyx** [comment]
Yeah, would you mind opening a new issue for the duplication thing? I'll close this one.
