### ISSUE TITLE
Add note to upgrade documentation and caveats

### ISSUE THREAD

**Issue by Tonkpils** [exercism/cli#403]
There's a caveat on windows upgrades that can be a bit unexpected and the workaround leaves an old binary on the system. It'd be good to add some documentation around this caveat.

See https://github.com/exercism/cli/issues/402

**Comment by kytrinyx** [comment]
@Tonkpils what if we put a note in the config during upgrade on windows systems with the path to the old binary, and then the next time any command with the CLI is called, go delete it if it's still around? Technically this would make all commands slower, but in practical terms I doubt that it would be noticeable.

**Comment by kytrinyx** [comment]
I'm going to take off the good-first-patch label temporarily since I'm not quite sure yet what the best solution to this one is.

**Comment by Tonkpils** [comment]
I believe the file it leaves around is marked as hidden so I don't see leaving the old binary in place as a big issue. The old binary just keeps getting overwritten with every upgrade anyway. Do you feel this is an issue that needs to be address or could it be possibly just documented?

**Comment by kytrinyx** [comment]
If it's hidden I feel more OK about it. Let's document it as part of the usage output for the upgrade command.

**Comment by kytrinyx** [comment]
Closed by #455
