### ISSUE TITLE
"\" or "\\" for "dir" in Windows CLI?

### ISSUE THREAD

**Issue by rpottsoh** [exercism/cli#406]
The Windows Installer for the CLI passes the install `dir` with double `\` characters in path when invoking configure.  
```
exercism configure --dir=C:\\Exercism
```

Will paths with with `\` for `dir` break CLI?
```
exercism configure --dir=c:\Exercism
```

**Comment by kytrinyx** [comment]
They shouldn't. We should be using the Go `filepath` package which handles all paths in a cross-platform way. If we're not, then that would explain it.

**Comment by rpottsoh** [comment]
Thanks @kytrinyx.  That is what I assumed.  It isn't idiomatic to type:
```
exercism configure --dir=c:\\exercism
```
at the command prompt in windows.  I re-checked my `.exercism.json` file.  Yup, if I enter just single `\` the CLI writes 2 to the json file.

I tried a more boneheaded thing:
```
exercism configure --dir=c:\\\exercism
```
The json file ended up with `"dir": "c:\\\\\\exercism",`

At this point `configure --dir` crashes if I try to fix the problem.  `exercism st ruby` is also broken if `dir` is bogus.  The only solution is to modify the json file by hand.  Not a big deal for some, others might have a hard time locating the file.

Could `configure --dir` test what is coming in before storing the change permanently?  Should I open a new issue for this and close this one?

**Comment by kytrinyx** [comment]
Go ahead and leave this open. I think it would make a ton of sense to test what is coming in before writing it.

**Comment by kytrinyx** [comment]
(also `"c:\\\\\\exercism"` is pretty hilariously bad)

**Comment by NobbZ** [comment]
>  I re-checked my .exercism.json file. Yup, if I enter just single \ the CLI writes 2 to the json file.

Which is correct. On the MS Terminal and Powershell `\` can be used directly, in JSON strings it is a special char which forms a meaning with the character comming next. To actually surpress this meaning and get a single `\` after reading the JSON file, you have to escape it by prepending a `\`.

**Comment by kytrinyx** [comment]
Yes, it's likely that we're getting this wrong when we're reading it back out.

**Comment by kytrinyx** [comment]
@rpottsoh would you check the nextercism CLI to see if you can reproduce this behavior?

**Comment by rpottsoh** [comment]
>@rpottsoh would you check the nextercism CLI to see if you can reproduce this behavior?

I'll try to take some time this evening and look into this.

**Comment by rpottsoh** [comment]
@kytrinyx I tried the following:
```example
nextercism configure --token {pasted my token} --workspace c:\\\nextercism
```
I received no error messages.  I also do not know what was stored for `workspace` either.  Where is Nextercism storing its settings?

I went ahead and tried to download hello-world from Delphi...  I will open another issue about that experience.

**Comment by kytrinyx** [comment]
> Where is Nextercism storing its settings?

I'm trying to follow the XDG specification, so I'm storing it in `%APPDATA%` which I _think_ means that it's in AppData\Roaming inside your user directory.

**Comment by kytrinyx** [comment]
Also, I added a `--show` flag to the configure command, but I haven't cut a new prerelease yet. That should also help.

**Comment by rpottsoh** [comment]
@kytrinyx I found `user.json` @ `%APPDATA`.  The content was correct.  My attempt to fool it failed. :+1: 

```example
{"Workspace":"c:\\nextercism","Token":"removed my token","Home":"C:\\Users\\Ryan Potts"}
```

**Comment by kytrinyx** [comment]
@rpottsoh I think that means we can close this. If I'm wrong about that would you let me know so we can figure out what to investigate?

**Comment by rpottsoh** [comment]
I think closing is fine.  If I notice something peculiar along these lines I'll let you know here.

**Comment by kytrinyx** [comment]
That's perfect, thank you.
