### ISSUE TITLE
nextercism: implement upgrade command

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#414]
_To be merged into the nextercism branch in https://github.com/exercism/cli/pull/410_

Command name: `upgrade` (alias `u`).
File: `cmd/upgrade.go`

Reimplement the Upgrade command in the nextercism CLI. The current functionality (https://github.com/exercism/cli/blob/master/cmd/upgrade.go) should be directly portable.

**Comment by nywilken** [comment]
@kytrinyx @robphoenix I'm going to start looking into this command.

**Comment by nywilken** [comment]
@kytrinyx  a quick heads up, I have this ported over to nextercism already. I'm working on testing and smoothing out any oddities I come across. I'll try to have the PR by this weekend - for review and tests.

**Comment by kytrinyx** [comment]
Yay 🎉 I look forward to seeing it!
