### ISSUE TITLE
nextercism: implement troubleshoot command

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#415]
_To be merged into the nextercism branch in https://github.com/exercism/cli/pull/410_

Command name: `troubleshoot` (alias `t`).
File: `cmd/troubleshoot.go`.

I chose the name `troubleshoot` rather than `debug` so that we can have a single-letter alias without crashing into the `download` command.

The current implementation (https://github.com/exercism/cli/blob/master/cmd/debug.go) is probably almost directly portable. The only difference would be that you can get a user configuration with `config.NewUserConfig()` instead of making one from scratch and populating it.

**UPDATE** There is a second difference. We'll have an explicit `/ping` endpoint to call for the Exercism API.

**Comment by robphoenix** [comment]
I'd be up for looking into implementing this next week?

**Comment by kytrinyx** [comment]
Closed by #443
