### ISSUE TITLE
Provide "hooks" for easy customability of the behaviour of the CLI

### ISSUE THREAD

**Issue by NobbZ** [exercism/cli#438]
After some discussion in #429 about synchronisation of users workspaces across different workstations, I'd suggested to wrap some `nextercism` subcommands to some `git` commands to keep a local repository up to date which can be pushed on the users behalf.

This proposal was denied for the usual reasons, which I am not mad about but fully understand. But at least I was able to have some deeper thoughts when I drove to work this morning.

What if we were providing a way to hook into (some) of the `nextercism` commands, as we are able to with `git`?

After a quick skim over the current issues with the label [`nextercism`](https://github.com/exercism/cli/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Anextercism%20), I felt that only `download` and `submit` and maybe `prepare` will need hooks.

I think for `download` and `submit` it would make sense to provide a mechanism that runs a per-track hook and a global one in order.

Also especially for `submit` I think it would also make sense to allow a pre- and an after-hook, e.g. to run tests before submitting and not submit at all when the hook exits with non-zero status code, while the after hook could be used for VCS management.

The hook for `prepare` though does make only sense globally and as an global after-hook. We simply can't provide a way to have a hook per track and I can't think of any checks that one want to make and eventually cancel the preparation of the track which weren't done by the CLI itself.

**Comment by kytrinyx** [comment]
This is a great idea. I'm going to think a little bit about implementation, but I think we should absolutely implement some form of hook behavior.
