### ISSUE TITLE
nextercism: usage statements

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#442]
@nywilken @robphoenix both of you have worked with usage statements in Cobra—would the two of you take the lead on figuring out what our guidelines/pattern/best practices should be?

I'd love it if we had a simple overview of "do this, do that, name it like this, put this other bit in a method, call it when this happens".

**Comment by nywilken** [comment]
@kytrinyx more than happy to. I haven't had much time this weekend to get to anything on the project but will definitely think about this a bit and sync up with @robphoenix to hash out ideas and details.

**Comment by robphoenix** [comment]
Sure, no problem @kytrinyx. I've been away, so going to catch up and will start hashing something out with @nywilken here.

**Comment by kytrinyx** [comment]
Did this one get fixed in #54?

**Comment by robphoenix** [comment]
https://github.com/exercism/configlet/pull/54 is from configlet, we haven't yet outlined usage statement best practices for the cli, whether specifically or across both tools.
