### ISSUE TITLE
nextercism: links in release info are 404

### ISSUE THREAD

**Issue by NobbZ** [exercism/cli#450]
Some links on the release info are 404, I've tested especially the last ones (issues and further info about launch)

**Comment by kytrinyx** [comment]
We haven't made the feedback repo public yet—should happen soon.

**Comment by NobbZ** [comment]
Then I understood the announcement of the pre-release wrong. I thought that all related information should be available with that announcement.

So I'll wait a while and try to figure out how to deal with slots in emerge so that parallel installation of both executables is possible using my overlay…

**Comment by kytrinyx** [comment]
@NobbZ I didn't realize that cutting a CLI would send any notifications. I needed to test the prerelease stuff with the Thalamus team.

It's announced now, though, so those links should work.

**Comment by kytrinyx** [comment]
Since the links are now working I'm going to go ahead and close this one. I apologize for the trouble, @NobbZ!
