### ISSUE TITLE
Add interactive diff to download command

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#457]
If you download an exercise and there are already files there, it should interactively ask whether or not the CLI should overwrite the file (each file individually). We'll show a diff to help make the decision.

If you run the download command with `--force` (or `-f`), it will automatically overwrite any existing files.

As part of this change we should add a flag to `configure` that lets people set "overwrite by default" to true in the UserConfig.

**Comment by alebaffa** [comment]
Question: do you mean showing the diff like `git diff` interactively on each potential overwritten file?

**Comment by kytrinyx** [comment]
I'm reworking the specification for the CLI to lock down what the minimal adequate specification is.

As part of this process, I am going to close this issue, as it describes a more ambitious enhancement, and I'm not even sure we'll want to do this. After we launch v2 and get some experience with the new CLI, we will spend some time looking at what enhancements we'd like to implement.
