### ISSUE TITLE
Allow submitting an exercise directory without submitting temp files, build artifacts, and other undesirable files

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#458]
When people submit an entire directory, e.g. `exercism submit hello-world`, we filter out a few things:

- the metadata file which caches some information from the site locally for the CLI to use
- any markdown files (e.g. README.md, GETTING_STARTED.md, etc)
- the test files (we get the pattern from the `prepare` command when called for a track)

In addition, we should let people have files that we ignore.

I think we should store this value in the `CLIConfig` rather than the `UserConfig`, however we need to be careful that we don't overwrite this when we auto-update a track.

**Comment by JoelQ** [comment]
For Elm projects, we should ignore the `./elm-stuff/` directory that contains all the build artifacts.

**Comment by NobbZ** [comment]
Instead of user specified, shouldn't it be track specified? Or even both?

Why should every user specify on his/her own, that he do not wan't to submit build-artifacts, and even force him to figure out how to do so?

For erlang/hello-world, there are 32 files, which the CLI wants to submit.

* 29 are build artifacts, thank to the buildsystem used the all live in a sub folder
* 2 are project config needed by the buildsystem (which are the same through all exercises, besides version information and project-name)
* 1 is the actual solution

I can safely delete the `_build` folder prior to submission to get rid of those files, but I also do not want to submit the metadata.

**Comment by ErikSchierboom** [comment]
I think this should definitely be track specified. What are the use cases where people would want to determine for themselves what files to submit? I think letting users decide for themselves would lead to a lot of submissions that are "off": they don't contain the requested files, they contain many useless files, etc. Just from a storage point of view, it would seem wasteful to allow users to submit their intermediate or final build files (DLL's, etc.).

In the Slack channel a suggestion was made to use the `.gitignore` file for this. In my opinion, we should not be using the `.gitignore` file to determine what files to submit for the following reasons:

1. We are mixing responsibilities.
2. It is non-intuitive to users (what does git have to do with Exercism?).
3. It will allow the user to customize what files to send (see my previous argument).

In my view, the best option would be to allow each track to specify an exclude- and/or include pattern, either as a string containing a globbing pattern or a regular expression, or as a file similar to the `.gitignore` file. My preference would be to have a `exercism-ignore` (or similarly named) file in the track's `config` directory, which would then be used when submitting data to filter the files to be submitted. 

Regardless of how this is implemented, I do think it is quite important to get this right as soon as possible. We really want the user experience to be as frictionless as possible, so just running `exercism submit` in the directory of an exercise should submit the right files, and only those files.

**Comment by iHiD** [comment]
How about an . exercise_ignore file that's included with each solution when it's downloaded? It can be made from track specific rules but customised to each exercise either by the maintainers or by the user.

The added work would be:
- cli needs to look for this file and ignore things in it
- track maintainers provide a default file (if they don't then we just don't ignore anything)
- track maintainers provide any exercise specific files (if they don't we don't ignore anything extra)
- API concatenates and sends the file down with the rest of the solution.

**Comment by ErikSchierboom** [comment]
I like it @iHiD! Maybe we can put the `exercise_ignore` file in a `.exercism` sub-directory within the solution directory? I think I would also like the `.solution.json` file to be in a `.exercism` sub-directory. This is similar to how many IDE's hide their files, e.g. VS Code uses a `.vscode` sub-directory and IntelliJ IDEA uses `.idea`.

**Comment by NobbZ** [comment]
I like the layered ignore-file approach. That might come in handy for exercises that can't easily control the name of generated executables.

I do also support the meta-folder, as soon as we add another exercism specific file to the exercises root. The exercises might get cluttered if everything is thrown into its root.

**Comment by yeongsheng-tan** [comment]
How about a pre-defined set of directories to be ignored much in the likes of how Github generates .gitignore files based on tech stack / language type detected.

And it must allow user to over-write. E.g. node_modules (for javascript track), vendor/bundle or bundle (for ruby track), elm-stuff (for elm-lang track), build or classes (for java track - depends on build tooling too), etc.

**Comment by 4d47** [comment]
Stumbled on this issue and was wondering which tracks or exercises requires multiple files to be submitted ? It's just that since I started on exercism I never felt the need to submit more than one file per exercise (and neither I've seen others) so I'm curious.

**Comment by NobbZ** [comment]
C and C++ regularly need 2 files (on file containing definitions, the other declarations).

For erlang it makes the `zypper` exercise easier to read when the student splits it up (its not a requirement enforced by the tests though) into a module for the tree and one for the actual zypper.

**Comment by iHiD** [comment]
Could we standardise those? I think it's an interesting question as to
whether we could specify default files that the client uses with a flag to
do more. Ie rather than defaulting to everything, default to the one file
(or two in c) that are named in a specific manner? I don't know enough
about all the tracks to know if this would work but it might be a simple
approach.

How did v1 do this differently?

**Comment by NobbZ** [comment]
Well, for most languages the files that had to get submitted have a static ending and do not match the testpattern.

Still, that's not enough. Some build systems as `cmake` for C++ copy all source files into a build folder and compile from there. Rebar for Erlang does similar.

Often that build folder is below the project root.

We still need a way to ignore those.

For Erlang the name of this folder is configurable AFAIK but the default `_build` works out pretty well.

For `cmake` it's common to use `build` but that's in theory the choice of the user/student. But if we tell them to use `_build` and explain why that should work.

For Erlang such a letter could look like `*.[eh]rl`, C were `*.[ch]` and C++ `*.{h,cpp}`.

At least for C and C++ are many more possible, but those above are used and expected by the used build systems.

**Comment by rbasso** [comment]
In the Haskell track I usually submit `package.yaml`, if I change it to use additional libraries in a solution. This way everybody reading the solution will know exactly which packages where used and how to do it.

The same goes for `stack.yaml`.

Sometimes I break a solution in modules, just to mimic how a real app would be written.

Also, TemplateHaskell forces a few things to be in distinct modules I guess.

**Comment by NobbZ** [comment]
So as I understand you, usually only haskell source files (but perhaps multiple of them) get submitted, at least those that do not match the testpattern?

But if (and only if) you changed your "build config" you want to send it as well?

Where is your build tool saving object (or other auxiliary) files? As far as I remember, the default is a dotted subdirectory?

Does this auxiliary folder contain copies of the sources (or generated files matching the regular haskell pattern) that could get submitted accidentally when blindly applying the pattern?

**Comment by nywilken** [comment]
The layered approach seems very promising. Having a standard set defined by the track will help keep out cruft, and having a user defined ignore would allow users to ignore any specific files that we don’t know about. 

An alternative to a standard ignore list could be  a standard set of allowed file extensions in a config that gets pulled down when a user downloads an exercise (self updating). This list, I think, might be smaller and easier to maintain. Upon submit the cli would only submit the allowed files. 

The user defined list would be an ignore list which would be skipped by the cli when trying to submit. Which may not be needed if the allowed list is a viable solution. 

Just thinking out loud here.

**Comment by NobbZ** [comment]
> Upon submit the cli would only submit the allowed files.

I still think this is not what we want. Whitelisting `*.erl` for the erlang track without the possibility to blacklist the `_build` folder will submit temporary files from the build location.

Allowing only `src/*.erl` on the other hand side would make it impossible to leverage the full power of the build system and the language.

If I only were able to whitelist in erlang, a proper whitelist that should work most of the time for default configured projects as they are laid out in the downloaded stubs were `include/*.hrl` and `src/*.erl` (in theory nested arbitrarily deep but usually flat).

If we only allowed flat patterns that would make it hard for Java and Haskell, where the location of a file in the filesystem actually has a meaning.

**Comment by jgomo3** [comment]
I would say Keep it Simple, and ask the user so select explicitly the files to upload. I don't have the numbers, but I bet: 99% of solutions would be 1 file solution and the rest 99% of the rest would be 2 files.

This means to avoid the folder upload feature from submit.

Even if desired, make that feature a flag on the submit command (like -a or -d), or make it another command like sumbit-pkg or submit-dir.

**Comment by ErikSchierboom** [comment]
I've given this some thought, and I think that for many languages, we could probably make this work intuitively by simply having a whitelist (instead of a blacklist).

Consider the C# and Kotlin languages. In C#, people will almost always have a single `<slug>.cs` file that will contain the solution. What if there would be a track-wide include pattern like "**/*.cs"? For C#, this would work fine in almost all situations. If a user decides to use multiple sources files, they will automatically get included. Note that we do have to still prevent the test file from being submitted, as that also is a `.cs` file.

Such a simple include pattern would also work for Kotlin, only in that case it would be "src/**/*.kt". In that case, having a nice default where you can just run `mentorcism submit` in a folder provides an even greater benefit than the C# track, as the user then doesn't have to enter the full path to the solution file, which is three directories deep.

**Comment by kytrinyx** [comment]
Thank you for considering all the implications here!

After reading through this carefully, I'd like to suggest the following:

- by default, operate with a track-level _allow list_ of allowed extensions. We need to add extensions to each of the Track's `config.json` files anyway, in order to more easily support the Prism syntax highlighting.
- continue to include a blocklist to exclude things that should not be submitted despite having the correct extension
- if submitting an explicit list of files, do not check the allow/block lists
- _if we find that we need to have more granular control_, add a configuration file to the `exercises/:slug/.meta/*` directory which lets us extend the default allow/block lists for the track for just that exercise

Getting this right will require a bit of work, so I am going to _only support an explicit file list_ for the v2 launch, and then follow-on with allow/block behavior in the following weeks.

**Comment by NobbZ** [comment]
It seems as if it is not that easy.

exercism/exercism.io#3871 shows, that there are files which we do not consider beeing part of the tests, but also not necessarily part of the solution.

Lets call those "build-descriptions".

Those build descriptions might still be of interest if the student changed them to pull in a certain library/dependency. But usually we do not want to display them prominently on the solutions page.

So I do currently see the following groups of files:

* **Testfiles**: Those are already covered by the testpattern (in theory) and should get uploaded with the solution and displayed on the testsuite tab. They needs to get downloaded in exactly the version that the student had run when (re-)downloading using ``--uuid``. As far as I can tell they are currently not uploaded at all.
* **Solution files**: Their names are hard to predict, but at least often have a common prefix throughot a languages track. Obviously they need to be downloaded on ``--uuid`` as submitted by the student. They are the most interesting part of a submission and currently specified explicitely on the command line and as far as I can tell, they are the only files submitted at all.
* **Build descriptions**: Those are not available in every track, but as far as I can tell so far, their name is usually static. It should get downloaded when using ``--uuid`` and accessible via the web interface. I'm not sure where to put them though, as I do not consider them part of the testsuite, nor do I consider them part of the solution. Often they are the glue that patches testsuite and solution together.
* **Buildartifacts**: We do not want to submit them and also we do not want to download them on ``--uuid``. Often they either have a common suffix (eg. ``.o`` files for C) or reside in a subdirectory (eg. ``_build`` for erlang). Especially the later may contain files that would be valid solution files which we still want to ignore when submitting. A tracks maintainer should be able to provide `.gitignore` like patterns to ignore those.
* **Editor temporary files**: This do depend on the user and are completely out of control for us, but we are not interested in them.
* **Problem descriptions**: These includes READMEs and HINTs, but I'm not sure if we want to upload them for reproducing the students environment or not, but I tend to preserve them to see the same problem description as the student did.

**Comment by kytrinyx** [comment]
I'm moving this to exercism/exercism.io so that we can discuss this in terms of the product rather in terms of the CLI behavior, since in order to get it right we have to update individual tracks, the website, the API, _and_ the CLI.

**Comment by kytrinyx** [comment]
_This issue has been imported to the https://github.com/exercism/exercism.io repository._
