### ISSUE TITLE
Interactively ask for workspace if missing

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#461]
**This issue is for the `nextercism` client. Branch off of the `nextercism` branch, and submit the pull request to `nextercism` as the base branch, rather than to `master`.**

If someone is downloading an exercise and they haven't yet configured a workspace, interactively ask where to put it.

We can default to `$HOME/$BINARYNAME` (so that people don't mix exercism and nextercism during the beta).

Show the following message

> By default we will install exercism exercises into a new directory in your user account (`$HOME/$BINARYNAME`).
> - If you would like to stick with the default just press return to continue.
> - If you would like to change this (advanced), type a different directory below:

So, once the person presses return or enters a new directory, then output: "You can always find out where things are downloaded to by running `$BINARYNAME workspace`."

Once we have this value we need to write it to the `UserConfig` (see `cmd/configure.go` for how we're doing that).

**Comment by berryhill** [comment]
@kytrinyx Cool if I take this one?

**Comment by kytrinyx** [comment]
That would be awesome, thank you 🎉
