### ISSUE TITLE
Interactively ask for token if missing

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#462]
If we don't have a token during download (`cmd/download.go`) then

* print "Please paste your Exercism API token here: " to the terminal and wait for input
* use `browser.Open` (like in `cmd/open.go`) to open a browser to https://v2.exercism.io/my/settings
* On enter, read the token, store it in the user settings.

## Notes

We will eventually change this to https://v2.exercism.io/my/settings/token which will contain just the token, but that page doesn't exist yet.

The `token` lives on the `config.UserConfig`. Here's an example of accessing that config: https://github.com/exercism/cli/blob/51af16d8ff2ab1783c10860d4620c90d32fdb31d/cmd/open.go#L26-L29

We have a package to handle interactive stuff (`comms`). See it in action here: https://github.com/exercism/cli/blob/51af16d8ff2ab1783c10860d4620c90d32fdb31d/cmd/submit.go#L148-L160

We already have logic for storing the token in the configure command. It might be easiest to defer to that command, like we do here: https://github.com/exercism/cli/blob/51af16d8ff2ab1783c10860d4620c90d32fdb31d/cmd/download.go#L37-L40

**Comment by 0sc** [comment]
Hey @kytrinyx, is this still up for grabs? I'll like to try my hands with it

**Comment by neil-hickey** [comment]
Hey @kytrinyx, @0sc , I was having a quick look at this also. What benefit does requiring the API token give, if the endpoint to download does not require it? 

e.g GET to http://exercism.io/api/v1/submissions/<submission_id> does not require the token to access the information.

**Comment by kytrinyx** [comment]
The `nextercism` branch, which this refers to is for v2.exercism.io, which does require the token.

It's up for grabs still, and all contributions are much appreciated!

**Comment by kytrinyx** [comment]
I'm reworking the specification for the CLI to lock down what the minimal adequate specification is.

As part of this process, I am going to close this issue, as it describes a more ambitious enhancement, and I'm not even sure we'll want to do this. After we launch v2 and get some experience with the new CLI, we will spend some time looking at what enhancements we'd like to implement.
