### ISSUE TITLE
[nextercism] any with folders: “open .../<folder>/<file>: not a directory” during download

### ISSUE THREAD

**Issue by NobbZ** [exercism/cli#465]
I tried to download erlangs hello world, but no success, it fails with an error:

```plain
$ nextercism download hello-world --track=erlang
2017/08/18 19:41:50 open /home/nobbz/nextercism/erlang/hello-world/include/exercism.hrl: not a directory
```

As it seems there is no equivalent of the debug subcommand, nor is there a `--verbose` option for download. So I am not able to provide more details.

**Comment by NobbZ** [comment]
Oh, I took a closer look into what already got downloaded:

```
$ % ll $(nextercism w)/erlang/hello-world
total 16K
drwxr-xr-x 2 nobbz nobbz 4.0K Aug 18 19:39 .
drwxr-xr-x 3 nobbz nobbz 4.0K Aug 18 19:39 ..
-rw-r--r-- 1 nobbz nobbz  205 Aug 18 19:41 .solution.json
-rw-r--r-- 1 nobbz nobbz 2.1K Aug 18 19:41 README.md
-rw-r--r-- 1 nobbz nobbz    0 Aug 18 19:41 include
```

As you can see `include` is a plain and empty file whereas it should be a directory, which then shall contain `exercism.hrl`.

Probably simiral problems will occur on other tracks that use directories to structure the exercise. In the case of Erlang, Java, and Rust those structures are enforced/needed by the build tools used.

**Comment by NobbZ** [comment]
Tested with Java, similar problem:

```plain
$ nextercism d hello-world --track java
2017/08/18 20:41:42 open /home/nobbz/nextercism/java/hello-world/src/main: not a directory

$ ll $(nextercism w)/java/hello-world/
total 36K
drwxr-xr-x 2 nobbz nobbz 4.0K Aug 18 20:41 .
drwxr-xr-x 3 nobbz nobbz 4.0K Aug 18 20:41 ..
-rw-r--r-- 1 nobbz nobbz  203 Aug 18 20:41 .solution.json
-rw-r--r-- 1 nobbz nobbz  161 Aug 18 20:41 HINTS.md
-rw-r--r-- 1 nobbz nobbz 1.2K Aug 18 20:41 README.md
-rw-r--r-- 1 nobbz nobbz 8.8K Aug 18 20:41 TUTORIAL.md
-rw-r--r-- 1 nobbz nobbz  256 Aug 18 20:41 build.gradle
-rw-r--r-- 1 nobbz nobbz    0 Aug 18 20:41 src
```

Similar symptom with `src`-folder.

**Comment by kytrinyx** [comment]
@NobbZ Would you post this in the v2-feedback repo? We will need to track down whether it's in the API or the CLI.

**Comment by NobbZ** [comment]
Issue moved to [exercism/v2-feedback #9](https://github.com/exercism/v2-feedback/issues/9) via [**ZenHub**](https://www.zenhub.com/)

**Comment by NobbZ** [comment]
Okay, done.
