### ISSUE TITLE
Add confirmation messaging on auto-approve

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#469]
**This issue is for the `nextercism` client. Branch off of the `nextercism` branch, and submit the pull request to `nextercism` as the base branch, rather than to `master`.**

When downloading a new exercise, the payload contains an `exercise` key whose value is an object. One of the keys in this object is `auto_approve`, which is a boolean. This value is stored into the `.solution.json` file in https://github.com/exercism/cli/blob/nextercism/cmd/download.go#L178

During submission, we load the contents of `.solution.json` into a value of type `workspace.Solution`.

When an exercise that is marked with `AutoApprove: true` is submitted, then the CLI should conclude with:

> Your solution has been submitted successfully and has been auto-approved.
> You can complete the exercise and unlock the next core exercise at $URL.

where $URL is the solution URL from `.solution.json`.

That gives a really clear route for someone getting started and makes sure they don't end up in limbo of "what do I do now??".

**Comment by berryhill** [comment]
cool if I give this one a shot?

**Comment by kytrinyx** [comment]
@berryhill I would be so very happy if you do! 🎉 💛 🎉 💛 🎉

**Comment by berryhill** [comment]
@kytrinyx Awesome! on it

**Comment by robphoenix** [comment]
Hi @berryhill, thanks for taking this on! :+1: :+1: 

I saw you opened & closed a PR for this. So you know, we've got two main branches currently. `master` is the current incarnation of the `cli`, and the `nextercism` branch is where we're developing the new `cli` for v2 of Exercism. If you branch your PR off the `nextercism` branch, or rebase it on the `nextercism` branch, then when you open a PR, change the base branch to `nextercism`. That should avoid the long list of extra commits! :smile: 

Holler if you've any questions!

**Comment by berryhill** [comment]
@robphoenix No worries! Yes, I did open a PR and realized that I forgot to rebase it off of nextercism. I'm gonna untangle my branches here right now, and throw the PR back up and feel free to let me know whats good and what is not.

Thanks for the support!

**Comment by berryhill** [comment]
https://github.com/exercism/cli/pull/489
