### ISSUE TITLE
Error from fetch alias: error parsing API response - invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by cartothemax** [exercism/cli#471]
After beginning a new `csharp` course on a new machine that had fresh install of the CLI tool (-v 2.4.1) and ran into an error.  

I first issued the the command `|> exercism fetch csharp` to get started on a the C# course.  This successfully fetched and setup the directory structure.  After passing the tests of the "Hello World" example and submitting the exercise I attempted to fetch the next exercise with the following command `|> exercism f csharp`.  After this attempted fetch I ran into the following error.

![screen shot 2017-08-21 at 10 36 17 am](https://user-images.githubusercontent.com/413224/29527009-152be3f0-865d-11e7-87f9-cfa41f932ce2.png)

I was able to get around this error by fully typing out `fetch`.  

![screen shot 2017-08-21 at 10 36 27 am](https://user-images.githubusercontent.com/413224/29527067-36e80b9a-865d-11e7-9d4e-8f52f9599f22.png)

Next I attempted to use `|> exercism f ruby` shorthand for language tracks I have previously started and was successful.  After that I used `|> exercism f go` on a language track I had not started and again ran into the same error.

![screen shot 2017-08-21 at 10 56 18 am](https://user-images.githubusercontent.com/413224/29527753-67bc5210-865f-11e7-81e3-bc94e7097270.png)

**Comment by kytrinyx** [comment]
Thanks for opening this, I'll dig into it in a moment.

Just a quick note—this typically happens because we get an error from the API (404 or 500) and the API fails to send back JSON, and so the CLI is trying to parse HTML as JSON.

**Comment by kytrinyx** [comment]
Quick question—you've configured the CLI with your api key, right?

**Comment by cartothemax** [comment]
I did configure the CLI with my api key by copying and pasting the command from the API Key page on exercism.io.  Thanks for the speedy response!

**Comment by kytrinyx** [comment]
@cartothemax Are you still able to reproduce this with the tracks you've not joined?

I am not able to trigger the error.

**Comment by cartothemax** [comment]
@kytrinyx I am not able to... I just tried with the Crystal track and it did not error out.  I am going to close this issue and will test with some other language tracks to see if I can make it happen again.  If I am able to would it be alright if I reopened this issue?

**Comment by kytrinyx** [comment]
Oh, absolutely! That would be very helpful.
