### ISSUE TITLE
Prevent people from submitting empty files

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#472]
**This issue is for the `nextercism` client. Branch off of the `nextercism` branch, and submit the pull request to `nextercism` as the base branch, rather than to `master`.**

We haven't worked out the messaging, but we should probably bail from the entire submit with a complaint that the file is empty, rather than skipping the file silently.

We might run into things like `.keep` files which would need to be filtered out.

**Comment by AdhirRamjiawan** [comment]
Is this check to validate that the method/function to be implemented has any logic in the body or is it to ensure that at least some file with some content is submitted? I would imagine the former being a real effort to implement as it would probably need to have some sort of logic per language (reflection or something). Maybe the results of the test cases could provide some clue as to whether or not code has been written?

**Comment by kytrinyx** [comment]
> Is this check to validate that the method/function to be implemented has any logic in the body or is it to ensure that at least some file with some content is submitted?

No, we only care that they're not trying to submit a completely empty file. If there's any content whatsoever, we'll submit it.
