### ISSUE TITLE
Evaluate alternate interactive libraries

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#477]
This is to replace some of the logic in the nextercism comms package.

E.g.

- https://github.com/AlecAivazis/survey
- https://github.com/c-bata/go-prompt

**Comment by kytrinyx** [comment]
Note from @robphoenix in #474 

> This looks good for now, and we can easily jazz it up later once the dust has settled a bit on a working version of the CLI. The Survey package looks quite good for this, whereas go-prompt looks interesting more for REPL type stuff. It's based off a Python package that's been used for some interesting projects like an improved Python REPL, rather than simpler Q&A prompts. Though at a future date it might be interesting to use for some kind of interactive stats command for users.

**Comment by robphoenix** [comment]
here's another one https://github.com/marcusolsson/tui-go

**Comment by kytrinyx** [comment]
We've currently removed any need for interactivity in the commands (see https://github.com/exercism/cli/pull/696).

I'm going to close this and we can reconsider if we add back interactive behavior.
