### ISSUE TITLE
Interactive confirmation when submitting entire directory

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#485]
If someone uploads an entire directory during submit (`cmd/submit.go`) we need to

* show them a list of the files that will be selected (we use the IgnorePatterns from `config/CLIConfig.go` to filter things out)
* give the user two options: hit enter to accept or ctrl-C to cancel, then submit specific files.

**Comment by aldraco** [comment]
I've started working on this one. Once I figure out how string formatting works in Go, I hope to have something to PR soon.

**Comment by NobbZ** [comment]
There is the [`fmt`](https://golang.org/pkg/fmt/) package, providing a bunch of functions that work similar to Cs `printf` family of functions, also there is a good description in the packages documentation.

**Comment by kytrinyx** [comment]
Closing this, as it's resolved in #503
