### ISSUE TITLE
removing exercism?

### ISSUE THREAD

**Issue by JonBarnett** [exercism/cli#486]
How do I remove exercism?

Very basic level of knowledge here, apologies.

**Comment by NobbZ** [comment]
What do you mean by "removing"?

**Comment by karuppiah7890** [comment]
I think he wants to know how to uninstall or remove the tool

**Comment by kytrinyx** [comment]
It depends on what operating system you have. The instructions should be in the correct tab here: http://exercism.io/clients/cli under "Removing Exercism CLI"

**Comment by NobbZ** [comment]
Well, its only "removing" on the mac isntruction, linux and windows use the term "uninstall" in slightly different phrased section titles...

Perhaps we should unify that about those 3 texts?

**Comment by TinsideStudios** [comment]
Thank you Kytrinix.

Norbert, removing, uninstall, my opinion is it's quite useful to have both words bandied around. If one word seems unclear, then the other may be clearer. Lawyers do this often when they re-state questions, for instance. If you want precision then you need the mathematical language maybe. And what do you mean when you say mean, anyway, etc, etc.

**Comment by NobbZ** [comment]
I do understand what you mean, but in the current situation, if you are a mac user and do a page search of the mac installation page, you'll find nothing if you search for uninstall, while it will help you when you are a windows or linux user on the corresponding pages, but on none of these pages you'll find remove.

Perhaps have all the same caption “removing exercism CLI” while starting with the sentence “to uninstall exercism you have to…”

**Comment by kytrinyx** [comment]
> Perhaps have all the same caption “removing exercism CLI” while starting with the sentence “to uninstall exercism you have to…”

That would help, I think.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this. Once we launch v2, we can take another look at how best to improve the experience for those wanting to uninstall the CLI.

**Comment by T1mL3arn** [comment]
So for now using `SHIFT + DEL` key combo on exercism-cli folder is the only way to remove it from Windows ?

**Comment by NobbZ** [comment]
@T1mL3arn totally depends on how you initially installed `exercism`, if you used chocolate, then you should use chocolate to remove it, if you did a manual installation, then you need to manually delete it, if you used the graphical installer, then there should be an option to uninstall in your software list.

Though you do not need to use <kbd>Shift</kbd>+<kbd>del</kbd>, you can also use a terminal and use `delete` (or however that command is called in windows) when manually removing…

**Comment by T1mL3arn** [comment]
@NobbZ I installed it with graphical installer, but my OS (win 8.1) does not show it in the software list.

**Comment by NobbZ** [comment]
Then this is a bug in the installer to not provide the un-install information to the system, can you please open a bug report at https://github.com/exercism/windows-installer?

**Comment by T1mL3arn** [comment]
[Done](https://github.com/exercism/windows-installer/issues/60)

**Comment by Anas966** [comment]
is this a safe uninstall file?
https://drp.su/en/catalog-soft/other/exercism.io-cli-2086308998/uninstall

**Comment by rpottsoh** [comment]
@Anas966 I am not familiar with this uninstaller so cannot claim it is safe to run.  As I stated in https://github.com/exercism/windows-installer/issues/60#issuecomment-670183094, simply delete the file `exercism.exe` from the folder where it was installed.
