### ISSUE TITLE
Order of checks when submitting

### ISSUE THREAD

**Issue by NobbZ** [exercism/cli#500]
In the current version of the CLI (2.x), it seems as if the `submit` subcommand does some checks on the provided filenames in order:

1. Seems one of them to match a test-name? If yes, print error
2. If the file does exist, is it in a proper exercise folder? If no, print error
3. Check if the given file exists, if not, print error.

This order has lead to some confusion in exercism/exercism.io#3662 (and probably earlier issues as well).

Shouldn't we check and complain the other way round?

Users trying to submit from `~` or `~/exercism` would possibly realize their error much earlier if they were told that the file isn't there, instead of "the file you want to submit is at the wrong place" (this is even a “lie”!), we actually do not know where the file is…

**Comment by kytrinyx** [comment]
This is a good observation, @NobbZ, I think making this change would make a ton of sense.

**Comment by NobbZ** [comment]
I do not know about the internals of the CLI though, so is this easy enough to change, or will it not be worth the effort, since nextercism and CLI 3.0 are upfront which use a completely different way of submitting solutions?

That I did this post was more to be visible and to have something to point to when there are new students with similar problems. I didn't actually meant to have this fixed ;)

If though its worth the effort, I'm eager to update my overlay ;)

**Comment by kytrinyx** [comment]
> If though its worth the effort, I'm eager to update my overlay ;)

I actually think the effort would be low. I've not got the spare brainpower right now to look at it, but if someone does have the time and energy I think it would be a good change to make, even with Nextercism right around the corner.

**Comment by kytrinyx** [comment]
I've made a note of this for `nextercism`; I have come to accept that I have no bandwidth to get this fixed in the current CLI. Thanks for bringing it up, as I think it will make the experience smoother!
