### ISSUE TITLE
Fetching exercise puts it in home directory

### ISSUE THREAD

**Issue by kylesethgray** [exercism/cli#504]
It seems despite my working directory, when using a command such as `exercism fetch swift hello-world`, it puts it on my home directory instead of my working directory.

**Comment by NobbZ** [comment]
Where exactly are the files downloaded to? They should be downloaded to `$exercismdir/$lang/$exercise` where `$exercismdir` defaults to `$HOME/exercism`.

**Comment by kytrinyx** [comment]
Since we've not heard back on this one I'm going to go ahead and close it.

@kylesethgray if you're still having trouble, would you mind opening a new issue, including the output of `exercism debug`?
