### ISSUE TITLE
Download Problem

### ISSUE THREAD

**Issue by Jehanramadhan** [exercism/cli#505]
When i want to download exercism,
i got this 'This XML file does not appear to have any style information associated with it. The document tree is shown below.'
can someone tell me, what must i do?

**Comment by NobbZ** [comment]
Where do you try to download the exercism CLI from? Which operating system
are you using?

Jehan Ramadhan <notifications@github.com> schrieb am Di., 12. Dez. 2017,
01:21:

**Comment by Jehanramadhan** [comment]
I download from page : https://github.com/exercism/cli/releases/tag/v2.4.1
i found that in website instruction for download CLI package.
my operating system Linux Mint 17.3.

**Comment by NobbZ** [comment]
Where do you get the message about XML not having stylesheet information, that reads a bit as if it were given from a browser?

Here, I do follow the link and click the downlaod link for `exercism-linux-64bit.tgz` which is appropriate for my system, then I get a save-dialog. Download goes well and I can `tar xvzf exercism-linux-64bit.tgz`.

**Comment by Jehanramadhan** [comment]
When i click download link  for exercism-linux-64bit.tgz

**Comment by NobbZ** [comment]
So its in your browser?

Have you tried downloading via `wget` or `curl`? What does the XML say? Are you maybe in a corporate or otherwise secured network that blocks certain media types, file endings or whatnots?

**Comment by kytrinyx** [comment]
> Oh, and since I just realised, that AWS is responding with correct content, but media type "application/xml" have you tried to right click and "save as"?

I get:

```
$ curl -I "https://github.com/exercism/cli/releases/download/v2.4.1/exercism-linux-64bit.tgz"
...
Content-Type: text/html; charset=utf-8
...
```

**Comment by NobbZ** [comment]
> I get:

Which is fine here, since its pre-redirect.

**Comment by kytrinyx** [comment]
Ah! Of course. Thanks :)

**Comment by kytrinyx** [comment]
As we've not heard back on this one for a few months, I'm going to go ahead and close it.
