### ISSUE TITLE
Install from src instructions

### ISSUE THREAD

**Issue by jungle-boogie** [exercism/cli#509]
Hi All,

As this is a go project, I suspect I can do some `go get github.com/exercism/cli`, but instead I get:
`no Go files in /home/jungle/gopath/src/github.com/exercism/cli`

What's the proper way to install from src?

Asking because I run openBSD and freeBSD, I don't see binaries of those available.

thanks!

**Comment by ferhatelmas** [comment]
@jungle-boogie try `go get -u -t github.com/exercism/cli/exercism` where `-t` for test libraries if you want to hack on it.

**Comment by jungle-boogie** [comment]
Thanks, @ferhatelmas! Perhaps these steps can be posted on the site for reference.

**Comment by ferhatelmas** [comment]
@jungle-boogie Since generally people just want to get a binary and don't bother with its code, installation doc doesn't mention about it but it's already documented in [Contributing Guide](https://github.com/exercism/cli/blob/nextercism/CONTRIBUTING.md). However, we might make it clearer in readme.

**Comment by jungle-boogie** [comment]
> generally people just want to get a binary

That's me, but as I said above - no freebsd or openBSD binary is available:
https://github.com/exercism/cli/releases/tag/v3.0.0-alpha.3

Thank you for pointing me to the contrib guideline, though.

Happy new year!

**Comment by ferhatelmas** [comment]
@jungle-boogie My pleasure and thank you for your interest in exercism. Happy new year and hacking too!

@kytrinyx any idea for binaries in other platforms ?

**Comment by kytrinyx** [comment]
I'm completely open to adding other binaries. The build is in https://github.com/exercism/cli/blob/nextercism/bin/build-all, if you want to submit a pull request.
