### ISSUE TITLE
Unable to fetch exercises after update

### ISSUE THREAD

**Issue by navneeth** [exercism/cli#511]
Since last week, I am unable to fetch new exercises. 
The client gives up with this error:
>exercism fetch python
gives:
2018/01/16 13:04:26 Get http://x.exercism.io/v2/exercises/python?key=<removed_on_purpose>: proxyconnect tcp: dial tcp: lookup http on 125.0.1.1:53: server misbehaving

Typing:
>exercism debug 
gives:
**** Debug Information ****
Exercism CLI Version: 2.4.1
2018/01/16 13:02:00 unable to fetch latest release: Get https://api.github.com/repos/exercism/cli/releases/latest: proxyconnect tcp: dial tcp: lookup http on 125.0.1.1:53: server misbehaving
OS/Architecture: linux/amd64
Build OS/Architecture linux/amd64
Home Dir: /home/nav
Config File: /home/nav/.exercism.json
API Key: a1ba*************************19e
Exercises Directory: /home/navneeth/exercism
Testing API endpoints reachability
	* XAPI: http://x.exercism.io [Get http://x.exercism.io: proxyconnect tcp: dial tcp: lookup http on 125.0.1.1:53: server misbehaving] 6.272003ms
	* GitHub API: https://api.github.com/ [Get https://api.github.com/: proxyconnect tcp: dial tcp: lookup http on 125.0.1.1:53: server misbehaving] 6.427533ms
	* API: http://exercism.io [Get http://exercism.io: proxyconnect tcp: dial tcp: lookup http on 125.0.1.1:53: server misbehaving] 6.385522ms

I am behind a proxy server requiring authorization.
However, my http_proxy & https_proxy variables exported on bash take care of this.

Please help. Exercism is my coffee substitue. Feeling deprived now :)

**Comment by kytrinyx** [comment]
> Since last week, I am unable to fetch new exercises.

Dang, that's no good! I'm not aware of anything particular which changed in the past couple of weeks.

> Please help. Exercism is my coffee substitue. Feeling deprived now :)

💙 I'm not sure exactly what to try first. I know that we've seen issues with proxy servers, but if your shell config is set up to handle it, that should usually be fine.

@NobbZ @Tonkpils do either of you have any ideas what to try to figure out if the proxy configuration needs tweaking or to narrow it down to something else?

**Comment by NobbZ** [comment]
Sorry for beeing late to the party... I have some backlog built up in my
mails...

Port 53 is usually DNS, please ask your IT department of they added some
DNS filtering or changed something else in network/proxy configuration.

Katrina Owen <notifications@github.com> schrieb am Di., 16. Jan. 2018,
06:34:

**Comment by kytrinyx** [comment]
@navneeth did adding Google DNS to your resolve.conf fix this?

**Comment by navneeth** [comment]
Katrina - unfortunately No.
if I could help with uploading a debug dump. Pl let me know how.

Thanks
Navneeth

**Comment by kytrinyx** [comment]
@navneeth Sorry I missed this :(

@nywilken, @Tonkpils would either of you have any suggestions on how to proceed?

**Comment by nywilken** [comment]
@kytrinyx @navneeth this is more of a user  environment issue as Go’s dnsclient is returning  this error when trying to resolve the names. There have been changes to the Go code base where this error is being returned so we could check if moving to a new version of Go helps resolve the issue. But we would need some more details around the environment to figure out how to best test and find the root issue. 

@navneeth have you tried connecting to the endpoints directly via curl? Do you encounter any issues?

**Comment by navneeth** [comment]
`> exercism fetch python`
Returns the error
2018/06/21 10:48:23 Get <foo-link>: proxyconnect tcp: dial tcp: lookup http on <foo-server>: server misbehaving
@nywilken , @kytrinyx 
Thanks for reviving this.
Regarding your suggestion:
> have you tried connecting to the endpoints directly via curl? Do you encounter any issues?

My original issue with the CLI was that 
`exercism fetch python`
returns the error:
Get <foo-link>: proxyconnect tcp: dial tcp: lookup http on <foo-ip>: server misbehaving

So I pass the foo-link directly to curl as:
`curl <foo-link>` 
that retuns some garbled text (xml?).

So I think it is not a connection issue.

(IT responded that there were no changes made).

Does this help debug deeper ?

thanks,
navneeth

**Comment by nywilken** [comment]
I'm not sure what link you tried to curl but XML doesn't seem right to me. Looking at your original issue it seems like you had the same issue when trying to connect to https://api.github.com. What do you see when you try to curl that URL? You should see something like the JSON response below. Is there anyway you can share your curl output. Below are two sample curl runs

```
> curl https://api.github.com/repos/exercism/cli/releases/latest
{
  "url": "https://api.github.com/repos/exercism/cli/releases/6902445",
  "assets_url": "https://api.github.com/repos/exercism/cli/releases/6902445/assets",
  "upload_url": "https://uploads.github.com/repos/exercism/cli/releases/6902445/assets{?name,label}",
  "html_url": "https://github.com/exercism/cli/releases/tag/v2.4.1",
  "id": 6902445,
  "node_id": "MDc6UmVsZWFzZTY5MDI0NDU=",
  "tag_name": "v2.4.1",
  "target_commitish": "3968e887bae5e6ff32e1f29f19e5830c9721da44",
  "name": "Fix upgrade command on Windows",
  "draft": false,
  "author": {
    "login": "kytrinyx",
    "id": 276834,
    "node_id": "MDQ6VXNlcjI3NjgzNA==",
    "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kytrinyx",
    "html_url": "https://github.com/kytrinyx",
    "followers_url": "https://api.github.com/users/kytrinyx/followers",
    "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
    "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
    "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
    "repos_url": "https://api.github.com/users/kytrinyx/repos",
...
```



```
> curl https://api.github.com
{
  "current_user_url": "https://api.github.com/user",
  "current_user_authorizations_html_url": "https://github.com/settings/connections/applications{/client_id}",
  "authorizations_url": "https://api.github.com/authorizations",
  "code_search_url": "https://api.github.com/search/code?q={query}{&page,per_page,sort,order}",
  "commit_search_url": "https://api.github.com/search/commits?q={query}{&page,per_page,sort,order}",
  "emails_url": "https://api.github.com/user/emails",
  "emojis_url": "https://api.github.com/emojis",
  "events_url": "https://api.github.com/events",
  "feeds_url": "https://api.github.com/feeds",
  "followers_url": "https://api.github.com/user/followers",
  "following_url": "https://api.github.com/user/following{/target}",
  "gists_url": "https://api.github.com/gists{/gist_id}",
  "hub_url": "https://api.github.com/hub",
  "issue_search_url": "https://api.github.com/search/issues?q={query}{&page,per_page,sort,order}",
  "issues_url": "https://api.github.com/issues",
  "keys_url": "https://api.github.com/user/keys",
  "notifications_url": "https://api.github.com/notifications",
  "organization_repositories_url": "https://api.github.com/orgs/{org}/repos{?type,page,per_page,sort}",
  "organization_url": "https://api.github.com/orgs/{org}",
  "public_gists_url": "https://api.github.com/gists/public",
  "rate_limit_url": "https://api.github.com/rate_limit",
  "repository_url": "https://api.github.com/repos/{owner}/{repo}",
  "repository_search_url": "https://api.github.com/search/repositories?q={query}{&page,per_page,sort,order}",
  "current_user_repositories_url": "https://api.github.com/user/repos{?type,page,per_page,sort}",
  "starred_url": "https://api.github.com/user/starred{/owner}{/repo}",
  "starred_gists_url": "https://api.github.com/gists/starred",
  "team_url": "https://api.github.com/teams",
  "user_url": "https://api.github.com/users/{user}",
  "user_organizations_url": "https://api.github.com/user/orgs",
  "user_repositories_url": "https://api.github.com/users/{user}/repos{?type,page,per_page,sort}",
  "user_search_url": "https://api.github.com/search/users?q={query}{&page,per_page,sort,order}"
}
```

**Comment by navneeth** [comment]
This is my curl output for 
`> curl https://api.github.com/repos/exercism/cli/releases/latest`
`{
  "url": "https://api.github.com/repos/exercism/cli/releases/6902445",
  "assets_url": "https://api.github.com/repos/exercism/cli/releases/6902445/assets",
  "upload_url": "https://uploads.github.com/repos/exercism/cli/releases/6902445/assets{?name,label}",
  "html_url": "https://github.com/exercism/cli/releases/tag/v2.4.1",
  "id": 6902445,
  "node_id": "MDc6UmVsZWFzZTY5MDI0NDU=",
  "tag_name": "v2.4.1",
  "target_commitish": "3968e887bae5e6ff32e1f29f19e5830c9721da44",
  "name": "Fix upgrade command on Windows",
  "draft": false,
  "author": {
    "login": "kytrinyx",
    "id": 276834,
    "node_id": "MDQ6VXNlcjI3NjgzNA==",
    "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kytrinyx",
    "html_url": "https://github.com/kytrinyx",
    "followers_url": "https://api.github.com/users/kytrinyx/followers",
    "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
    "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
    "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
    "repos_url": "https://api.github.com/users/kytrinyx/repos",
    "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
    "type": "User",
    "site_admin": true
  },
  "prerelease": false,
  "created_at": "2017-07-01T18:45:36Z",
  "published_at": "2017-07-01T18:51:44Z",
  "assets": [
    {
      "url": "https://api.github.com/repos/exercism/cli/releases/assets/4232613",
      "id": 4232613,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDQyMzI2MTM=",
      "name": "exercism-linux-32bit.tgz",
      "label": null,
      "uploader": {
        "login": "kytrinyx",
        "id": 276834,
        "node_id": "MDQ6VXNlcjI3NjgzNA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kytrinyx",
        "html_url": "https://github.com/kytrinyx",
        "followers_url": "https://api.github.com/users/kytrinyx/followers",
        "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
        "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
        "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
        "repos_url": "https://api.github.com/users/kytrinyx/repos",
        "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
        "type": "User",
        "site_admin": true
      },
      "content_type": "application/gzip",
      "state": "uploaded",
      "size": 3170627,
      "download_count": 709,
      "created_at": "2017-07-01T18:50:46Z",
      "updated_at": "2017-07-01T18:50:52Z",
      "browser_download_url": "https://github.com/exercism/cli/releases/download/v2.4.1/exercism-linux-32bit.tgz"
    },
    {
      "url": "https://api.github.com/repos/exercism/cli/releases/assets/4232614",
      "id": 4232614,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDQyMzI2MTQ=",
      "name": "exercism-linux-64bit.tgz",
      "label": null,
      "uploader": {
        "login": "kytrinyx",
        "id": 276834,
        "node_id": "MDQ6VXNlcjI3NjgzNA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kytrinyx",
        "html_url": "https://github.com/kytrinyx",
        "followers_url": "https://api.github.com/users/kytrinyx/followers",
        "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
        "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
        "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
        "repos_url": "https://api.github.com/users/kytrinyx/repos",
        "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
        "type": "User",
        "site_admin": true
      },
      "content_type": "application/gzip",
      "state": "uploaded",
      "size": 3356261,
      "download_count": 359865,
      "created_at": "2017-07-01T18:50:47Z",
      "updated_at": "2017-07-01T18:50:57Z",
      "browser_download_url": "https://github.com/exercism/cli/releases/download/v2.4.1/exercism-linux-64bit.tgz"
    },
    {
      "url": "https://api.github.com/repos/exercism/cli/releases/assets/4232618",
      "id": 4232618,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDQyMzI2MTg=",
      "name": "exercism-linux-arm-v5.tgz",
      "label": null,
      "uploader": {
        "login": "kytrinyx",
        "id": 276834,
        "node_id": "MDQ6VXNlcjI3NjgzNA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kytrinyx",
        "html_url": "https://github.com/kytrinyx",
        "followers_url": "https://api.github.com/users/kytrinyx/followers",
        "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
        "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
        "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
        "repos_url": "https://api.github.com/users/kytrinyx/repos",
        "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
        "type": "User",
        "site_admin": true
      },
      "content_type": "application/gzip",
      "state": "uploaded",
      "size": 3163896,
      "download_count": 32,
      "created_at": "2017-07-01T18:50:47Z",
      "updated_at": "2017-07-01T18:51:15Z",
      "browser_download_url": "https://github.com/exercism/cli/releases/download/v2.4.1/exercism-linux-arm-v5.tgz"
    },
    {
      "url": "https://api.github.com/repos/exercism/cli/releases/assets/4232615",
      "id": 4232615,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDQyMzI2MTU=",
      "name": "exercism-linux-arm-v6.tgz",
      "label": null,
      "uploader": {
        "login": "kytrinyx",
        "id": 276834,
        "node_id": "MDQ6VXNlcjI3NjgzNA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kytrinyx",
        "html_url": "https://github.com/kytrinyx",
        "followers_url": "https://api.github.com/users/kytrinyx/followers",
        "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
        "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
        "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
        "repos_url": "https://api.github.com/users/kytrinyx/repos",
        "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
        "type": "User",
        "site_admin": true
      },
      "content_type": "application/gzip",
      "state": "uploaded",
      "size": 3143965,
      "download_count": 26,
      "created_at": "2017-07-01T18:50:47Z",
      "updated_at": "2017-07-01T18:51:01Z",
      "browser_download_url": "https://github.com/exercism/cli/releases/download/v2.4.1/exercism-linux-arm-v6.tgz"
    },
    {
      "url": "https://api.github.com/repos/exercism/cli/releases/assets/4232617",
      "id": 4232617,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDQyMzI2MTc=",
      "name": "exercism-linux-arm-v7.tgz",
      "label": null,
      "uploader": {
        "login": "kytrinyx",
        "id": 276834,
        "node_id": "MDQ6VXNlcjI3NjgzNA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kytrinyx",
        "html_url": "https://github.com/kytrinyx",
        "followers_url": "https://api.github.com/users/kytrinyx/followers",
        "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
        "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
        "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
        "repos_url": "https://api.github.com/users/kytrinyx/repos",
        "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
        "type": "User",
        "site_admin": true
      },
      "content_type": "application/gzip",
      "state": "uploaded",
      "size": 3142804,
      "download_count": 174,
      "created_at": "2017-07-01T18:50:47Z",
      "updated_at": "2017-07-01T18:51:06Z",
      "browser_download_url": "https://github.com/exercism/cli/releases/download/v2.4.1/exercism-linux-arm-v7.tgz"
    },
    {
      "url": "https://api.github.com/repos/exercism/cli/releases/assets/4232616",
      "id": 4232616,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDQyMzI2MTY=",
      "name": "exercism-linux-arm-v8.tgz",
      "label": null,
      "uploader": {
        "login": "kytrinyx",
        "id": 276834,
        "node_id": "MDQ6VXNlcjI3NjgzNA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kytrinyx",
        "html_url": "https://github.com/kytrinyx",
        "followers_url": "https://api.github.com/users/kytrinyx/followers",
        "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
        "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
        "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
        "repos_url": "https://api.github.com/users/kytrinyx/repos",
        "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
        "type": "User",
        "site_admin": true
      },
      "content_type": "application/gzip",
      "state": "uploaded",
      "size": 3102124,
      "download_count": 156,
      "created_at": "2017-07-01T18:50:47Z",
      "updated_at": "2017-07-01T18:51:10Z",
      "browser_download_url": "https://github.com/exercism/cli/releases/download/v2.4.1/exercism-linux-arm-v8.tgz"
    },
    {
      "url": "https://api.github.com/repos/exercism/cli/releases/assets/4232619",
      "id": 4232619,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDQyMzI2MTk=",
      "name": "exercism-mac-32bit.tgz",
      "label": null,
      "uploader": {
        "login": "kytrinyx",
        "id": 276834,
        "node_id": "MDQ6VXNlcjI3NjgzNA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kytrinyx",
        "html_url": "https://github.com/kytrinyx",
        "followers_url": "https://api.github.com/users/kytrinyx/followers",
        "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
        "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
        "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
        "repos_url": "https://api.github.com/users/kytrinyx/repos",
        "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
        "type": "User",
        "site_admin": true
      },
      "content_type": "application/gzip",
      "state": "uploaded",
      "size": 3161204,
      "download_count": 24,
      "created_at": "2017-07-01T18:50:47Z",
      "updated_at": "2017-07-01T18:51:19Z",
      "browser_download_url": "https://github.com/exercism/cli/releases/download/v2.4.1/exercism-mac-32bit.tgz"
    },
    {
      "url": "https://api.github.com/repos/exercism/cli/releases/assets/4232620",
      "id": 4232620,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDQyMzI2MjA=",
      "name": "exercism-mac-64bit.tgz",
      "label": null,
      "uploader": {
        "login": "kytrinyx",
        "id": 276834,
        "node_id": "MDQ6VXNlcjI3NjgzNA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kytrinyx",
        "html_url": "https://github.com/kytrinyx",
        "followers_url": "https://api.github.com/users/kytrinyx/followers",
        "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
        "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
        "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
        "repos_url": "https://api.github.com/users/kytrinyx/repos",
        "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
        "type": "User",
        "site_admin": true
      },
      "content_type": "application/gzip",
      "state": "uploaded",
      "size": 3343497,
      "download_count": 1373,
      "created_at": "2017-07-01T18:50:47Z",
      "updated_at": "2017-07-01T18:51:24Z",
      "browser_download_url": "https://github.com/exercism/cli/releases/download/v2.4.1/exercism-mac-64bit.tgz"
    },
    {
      "url": "https://api.github.com/repos/exercism/cli/releases/assets/4232621",
      "id": 4232621,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDQyMzI2MjE=",
      "name": "exercism-windows-32bit.zip",
      "label": null,
      "uploader": {
        "login": "kytrinyx",
        "id": 276834,
        "node_id": "MDQ6VXNlcjI3NjgzNA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kytrinyx",
        "html_url": "https://github.com/kytrinyx",
        "followers_url": "https://api.github.com/users/kytrinyx/followers",
        "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
        "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
        "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
        "repos_url": "https://api.github.com/users/kytrinyx/repos",
        "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
        "type": "User",
        "site_admin": true
      },
      "content_type": "application/zip",
      "state": "uploaded",
      "size": 3153780,
      "download_count": 1199,
      "created_at": "2017-07-01T18:50:47Z",
      "updated_at": "2017-07-01T18:51:29Z",
      "browser_download_url": "https://github.com/exercism/cli/releases/download/v2.4.1/exercism-windows-32bit.zip"
    },
    {
      "url": "https://api.github.com/repos/exercism/cli/releases/assets/4232622",
      "id": 4232622,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDQyMzI2MjI=",
      "name": "exercism-windows-64bit.zip",
      "label": null,
      "uploader": {
        "login": "kytrinyx",
        "id": 276834,
        "node_id": "MDQ6VXNlcjI3NjgzNA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/276834?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kytrinyx",
        "html_url": "https://github.com/kytrinyx",
        "followers_url": "https://api.github.com/users/kytrinyx/followers",
        "following_url": "https://api.github.com/users/kytrinyx/following{/other_user}",
        "gists_url": "https://api.github.com/users/kytrinyx/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kytrinyx/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kytrinyx/subscriptions",
        "organizations_url": "https://api.github.com/users/kytrinyx/orgs",
        "repos_url": "https://api.github.com/users/kytrinyx/repos",
        "events_url": "https://api.github.com/users/kytrinyx/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kytrinyx/received_events",
        "type": "User",
        "site_admin": true
      },
      "content_type": "application/zip",
      "state": "uploaded",
      "size": 3342354,
      "download_count": 23367,
      "created_at": "2017-07-01T18:50:47Z",
      "updated_at": "2017-07-01T18:51:33Z",
      "browser_download_url": "https://github.com/exercism/cli/releases/download/v2.4.1/exercism-windows-64bit.zip"
    }
  ],
  "tarball_url": "https://api.github.com/repos/exercism/cli/tarball/v2.4.1",
  "zipball_url": "https://api.github.com/repos/exercism/cli/zipball/v2.4.1",
  "body": "### Exercism Command-Line Interface (CLI)\r\n\r\nExercism takes place in two places: the discussions happen on the website, and you work on exercises locally. The CLI bridges the gap, allowing you to fetch exercises and submit solutions to the site.\r\n\r\nThis is a stand-alone binary, which means that you don't need to install any particular language or environment in order to use it.\r\n\r\nTo install, download the archive that matches your operating system and architecture, unpack the archive, and put the binary somewhere on your path.\r\n\r\nYou will need to configure the CLI with your [Exercism API Key](http://exercism.io/account/key) before submitting.\r\n\r\nFor more detailed instructions, see the [CLI page on Exercism](http://exercism.io/clients/cli).\r\n\r\n#### Recent Changes\r\n\r\n* @Tonkpils fixed the `exercism upgrade` command for Windows! 🎉 \r\n"
}
`

**Comment by kytrinyx** [comment]
@navneeth what is the curl output for

```
curl -v "http://x.exercism.io/v2/exercises/python/hello-world?key=$TOKEN"
```

**Comment by navneeth** [comment]
Hi @kytrinyx,
It is
`*   Trying 150.1.8.7...
* Connected to proxy.abc.com (150.1.8.7) port 10080 (#0)
> GET http://x.exercism.io/v2/exercises/python/hello-world?key= HTTP/1.1
> Host: x.exercism.io
> User-Agent: curl/7.47.0
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 OK
< Server: Cowboy
< Date: Mon, 25 Jun 2018 04:59:00 GMT
< Content-Type: application/json;charset=utf-8
< X-Content-Type-Options: nosniff
< Content-Length: 3168
< Via: 1.1 vegur
< Proxy-Connection: Keep-Alive
< Connection: Keep-Alive
< 
{"problems":[{"id":"python/hello-world","track_id":"python","language":"python","slug":"hello-world","name":"Hello World","files":{"README.md":"# Hello World\n\nThe classical introductory exercise. Just say \"Hello, World!\".\n\n[\"Hello, World!\"](http://en.wikipedia.org/wiki/%22Hello,_world!%22_program) is\nthe traditional first program for beginning programming in a new language\nor environment.\n\nThe objectives are simple:\n\n- Write a function that returns the string \"Hello, World!\".\n- Run the test suite and make sure that it succeeds.\n- Submit your solution and check it at the website.\n\nIf everything goes well, you will be ready to fetch your first real exercise.\n\n## Exception messages\n\nSometimes it is necessary to raise an exception. When you do this, you should include a meaningful error message to\nindicate what the source of the error is. This makes your code more readable and helps significantly with debugging. Not\nevery exercise will require you to raise an exception, but for those that do, the tests will only pass if you include\na message.\n\nTo raise a message with an exception, just write it as an argument to the exception type. For example, instead of\n`raise Exception`, you should write:\n\n```python\nraise Exception(\"Meaningful message indicating the source of the error\")\n```\n\n## Running the tests\n\nTo run the tests, run the appropriate command below ([why they are different](https://github.com/pytest-dev/pytest/issues/1629#issue-161422224)):\n\n- Python 2.7: `py.test hello_world_test.py`\n- Python 3.4+: `pytest hello_world_test.py`\n\nAlternatively, you can tell Python to run the pytest module (allowing the same command to be used regardless of Python version):\n`python -m pytest hello_world_test.py`\n\n### Common `pytest` options\n\n- `-v` : enable verbose output\n- `-x` : stop running tests on first failure\n- `--ff` : run failures from previous test before running other test cases\n\nFor other options, see `python -m pytest -h`\n\n## Submitting Exercises\n\nNote that, when trying to submit an exercise, make sure the solution is in the `$EXERCISM_WORKSPACE/python/hello-world` directory.\n\nYou can find your Exercism workspace by running `exercism debug` and looking for the line that starts with `Workspace`.\n\nFor more detailed information about running tests, code style and linting,\nplease see the [help page](http://exercism.io/languages/python).\n\n## Source\n\nThis is an exercise to introduce users to using Exercism [http://en.wikipedia.org/wiki/%22Hello,_world!%22_program](http://en.wikipedia.org/wiki/%22Hello,_world!%22_program)\n\n## Submitting Incomplete Solutions\n\nIt's possible to submit an incomplete solution so you can see how others have completed the exercise.\n","hello_world.py":"def hello(name=''):\n    pass\n","hello_world_test.py":"import unittest\n\nimport hello_world\n\n\n# Tests adapted from `problem-specifications//canonical-data.json` @ v1.1.0\n\nclass HelloWorldTest(unittest.TestCase):\n    def test_hello(self):\n        self.assertEqual(hello_world.hel* Connection #0 to host proxy.canon.co.jp left intact
lo(), 'Hello, World!')\n\n\nif __name__ == '__main__':\n    unittest.main()\n"},"fresh":false}]}`

**Comment by kytrinyx** [comment]
@navneeth I'm trying to figure out what's going on here, but I don't think we have enough information.

Can you confirm that you are using the most recent version of the Exercism CLI, and that you're using the command that is available on the website on the page for the exercise you're trying to download?

**Comment by navneeth** [comment]
Hi Katrina,
I really appreciate your resolve. Thank you for remembering it. 
However I am now able to use excercism on another machine that is not on the proxy network.

The problem remains on my desktop which is in a proxy based network. So that is most likely the cause.
You can attribute the issue to proxy and close it. 

Thanks !
Navneeth

**Comment by kytrinyx** [comment]
Alright, thanks Naveenth! I hope you get the proxy sorted out.
