### ISSUE TITLE
Newline after download error

### ISSUE THREAD

**Issue by Smarticles101** [exercism/cli#513]
A newline should be inserted after the "need an exercise name or a solution --uuid" error

```
~ $ nextercism version
exercism version 3.0.0-alpha.3
~ $ nextercism download
need an exercise name or a solution --uuid~ $ 
```

**Comment by kytrinyx** [comment]
Thanks for catching this 🌷

**Comment by kytrinyx** [comment]
This is fixed, we've just not made a new release yet.
