### ISSUE TITLE
doc request: compiling from source

### ISSUE THREAD

**Issue by jbodah** [exercism/cli#517]
I recently ran into an instance of this issue: https://github.com/exercism/exercism.io/issues/3724

It took a lot of jumping around to figure out which project I needed to clone, which branch I needed to be on, and which flags I had to set to compile the CLI from source. Upon doing so this fixed my issue but I think it'd be great to have a simple doc explaining the process for non-Go users

**Comment by NobbZ** [comment]
Installation from source is not recommended.

If though you want to contribute to the tool, the [contribution guide](https://github.com/exercism/cli/blob/nextercism/CONTRIBUTING.md) describes how to do so.

**Comment by kytrinyx** [comment]
As @NobbZ observes, compiling from source is generally not how we'd recommend doing it. The easiest would be to download a precompiled binary. If you use Go, then you could also use `go get github.com/exercism/cli/exercism` would would download it and install the binary.

I'm not against having docs to explain how to do it, but I'd like to better understand in what situation this would be better than the existing options.

**Comment by jbodah** [comment]
For clarity I was having issues with the CLI installed through Homebrew. It worked fine when I cloned and built it on my machine though. I didn't try the `go get` approach but maybe that'd be fine as well

**Comment by NobbZ** [comment]
Do not use `go get` when you want to do exercises on version 1 of the page. `go get` will default to the `nexercism`-branch.

**Comment by NobbZ** [comment]
As I am not aware of valid reasons to install from source, therefore everything I said in the other thread applies here as well.

https://github.com/exercism/cli/issues/516#issuecomment-375967506

**Comment by kytrinyx** [comment]
> go get will default to the nextercism-branch.

Ah. Yepp. Good point.

**Comment by kytrinyx** [comment]
How to install from source is described in the contributing documentation as well, I realized.

I'm going to go ahead and close this.
