### ISSUE TITLE
Trying build from source

### ISSUE THREAD

**Issue by villadalmine** [exercism/cli#518]
I trying to building from source

dalmine@ubuntu:~/gotest/cli-3.0.0-alpha.3$ go build -o out/exercsim exercism/main.go
dalmine@ubuntu:~/gotest/cli-3.0.0-alpha.3$ ls
CHANGELOG.md  CONTRIBUTING.md  Gopkg.lock  Gopkg.toml  LICENSE  README.md  RELEASE.md  api  bin  browser  cli  cmd  config  debug  exercism  fixtures  out  visibility  workspace
dalmine@ubuntu:~/gotest/cli-3.0.0-alpha.3$ cd out/
dalmine@ubuntu:~/gotest/cli-3.0.0-alpha.3/out$ ls
exercsim
dalmine@ubuntu:~/gotest/cli-3.0.0-alpha.3/out$ ./exercsim version
exercism version 3.0.0-alpha.1
dalmine@ubuntu:~/gotest/cli-3.0.0-alpha.3/out$ ./exercsim --version
Error: unknown flag: --version
dalmine@ubuntu:~/gotest/cli-3.0.0-alpha.3/out$

why said alpha1 if the version is alpha3.

**dalmine@ubuntu:~/gotest/cli-3.0.0-alpha.3/out$ uname -a
Linux ubuntu 4.4.0-116-powerpc64-smp #140-Ubuntu SMP Mon Feb 12 22:00:40 UTC 2018 ppc64 ppc64 ppc64 GNU/Linux
dalmine@ubuntu:~/gotest/cli-3.0.0-alpha.3/out$**

**Comment by NobbZ** [comment]
Because its hardcoded and someone forgot to bump it:

https://github.com/exercism/cli/blob/a135d1443d300da64d616c137373cffdb6310311/cmd/version.go#L10-L12

**Comment by kytrinyx** [comment]
I would recommend building the `master` branch, not the `nextercism` branch.

**Comment by villadalmine** [comment]
I did it and works very fine, now I can test exercism --version and all command, works fine. no error, Also I did PR

**Comment by kytrinyx** [comment]
I'm going to close this, as it was sorted out.
