### ISSUE TITLE
Exercism CLI completion script not available

### ISSUE THREAD

**Issue by shihlinlu** [exercism/cli#520]
There is a 404 error on the Exercism CLI completion script link: http://cli.exercism.io/exercism_completion.bash

![404](https://user-images.githubusercontent.com/4715629/38167352-04a14cb2-34f1-11e8-8e13-cae27b8a1a14.png)

**Comment by kytrinyx** [comment]
Where is the link? The project was restructured. If you go to http://cli.exercism.io and scroll to the bottom it links to the completion scripts.

**Comment by kytrinyx** [comment]
Ah, I found the links. I'll fix them.

**Comment by kytrinyx** [comment]
Fixed in 1b756a57600361de08df35c8fe97e49a3da93292

**Comment by kytrinyx** [comment]
Thanks for reporting this! 🌷

**Comment by shihlinlu** [comment]
Thanks for fixing this very quickly!
