### ISSUE TITLE
[nextercism] Print error message if no token is configured

### ISSUE THREAD

**Issue by NobbZ** [exercism/cli#522]
The current nextercism client does exit with a status code of `1`, but does only print a single empty line when one tries to download an exercise (eg. `nextercism download hello-world --track haskell`) but has not yet configured a token.

**Comment by kytrinyx** [comment]
If you try to download or submit without having configured a token, we should print a friendly error message.

For now, let's say something like:

```
Welcome to Exercism!

In order to get started, please call `exercism configure`.
You can find your API token at $URL.

Once you've configured, call this command again.
```

We will rework all the messaging before launch.

**Comment by RJacksonm1** [comment]
It looks like 4215d207ce5d4eabe32435a81740c6a1c037f180 has fixed this:

```
➜  cli git:(nextercism) ✗ ./testercism download hello-world
Error: unauthorized request. Please run the configure command. You can find your API token at https://v2.exercism.io/my/settings
```

Unless we want the exact wording @kytrinyx drafted?

**Comment by kytrinyx** [comment]
I think I'd like it to not say "error" (even though technically it is one).

**Comment by kytrinyx** [comment]
I've overhauled all the error messages :)
