### ISSUE TITLE
Go Panic on Fedora 28

### ISSUE THREAD

**Issue by ballPointPenguin** [exercism/cli#534]
I'm not sure how to troubleshoot this further. I have not been able to get exercism to run on my new Fedora 28 installation. I have used exercism without problems on openSuse, MacOS and Windows. I first installed exercism via dnf and the official fedora repo, and now I have removed that and installed it via git/github. The same result occurs in both cases.

➜  ~ go version
```
go version go1.10.2 linux/amd64
```
➜  ~ uname -a
```
Linux rogue-localdomain 4.16.8-300.fc28.x86_64 #1 SMP Wed May 9 20:23:40 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
➜  ~ exercism -v
```
exercism version 2.4.1
```
➜  ~ exercism debug
```
panic: reflect: Call using *cli.Context as type *cli.Context [recovered]
	panic: reflect: Call using *cli.Context as type *cli.Context

goroutine 1 [running]:
github.com/urfave/cli.HandleAction.func1(0xc42007f780)
	/usr/share/gocode/src/github.com/urfave/cli/app.go:478 +0x23b
panic(0x76fe40, 0xc4200ab1e0)
	/usr/lib/golang/src/runtime/panic.go:505 +0x229
reflect.Value.call(0x77e180, 0x81e4f8, 0x13, 0x7fe8c9, 0x4, 0xc42007f740, 0x1, 0x1, 0xc4200be040, 0x7f2d60, ...)
	/usr/lib/golang/src/reflect/value.go:377 +0x1202
reflect.Value.Call(0x77e180, 0x81e4f8, 0x13, 0xc42007f740, 0x1, 0x1, 0x7283d6, 0x7febc9, 0x4)
	/usr/lib/golang/src/reflect/value.go:308 +0xa4
github.com/urfave/cli.HandleAction(0x77e180, 0x81e4f8, 0xc420106500, 0x0, 0x0)
	/usr/share/gocode/src/github.com/urfave/cli/app.go:487 +0x16d
github.com/urfave/cli.Command.Run(0x7ff3ef, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x80e6dd, 0x21, 0x0, ...)
	/usr/share/gocode/src/github.com/urfave/cli/command.go:189 +0x9a9
github.com/urfave/cli.(*App).Run(0xc4200bc180, 0xc4200c0000, 0x2, 0x2, 0x0, 0x0)
	/usr/share/gocode/src/github.com/urfave/cli/app.go:240 +0x546
main.main()
	/builddir/build/BUILD/cli-2.4.1/exercism/main.go:188 +0xcbf
```

**Comment by kytrinyx** [comment]
If you download and untar the linux 64-bit release here, does the same problem occur? https://github.com/exercism/cli/releases/tag/v2.4.1

I wonder if we have problem due to the unpinned version of the urfave dependency.

**Comment by ballPointPenguin** [comment]
Thanks https://github.com/kytrinyx that totally worked. I thought I had already done that, but I hadn't fully removed the official fedora package(s).

**Comment by kytrinyx** [comment]
*whew* very relieved that worked since I am not sure what I would have suggested next!
