### ISSUE TITLE
Switch to Go modules for dependency management

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#535]
The vgo proposal has been accepted, I'd love to start using it sooner rather than later for the nextercism CLI:

 https://github.com/golang/go/issues/24301#issuecomment-390766926

**Comment by nywilken** [comment]
@kytrinyx I'm changed the title of this issue to `Switch to Go modules for dependency management` as vgo is not officially a thing yet, but Go modules are for 1.11 which is the first step to vgo.
