### ISSUE TITLE
Empty error message when wrong token is configured with nextercism

### ISSUE THREAD

**Issue by FabienTregan** [exercism/cli#536]
How to reproduce :

```
d:\nextercism>nextercism c -t <token from the V1 instead of V2 :^/ >
d:\nextercism>nextercism download hello-world --track=rust
Error:

d:\nextercism>

```

**Comment by NobbZ** [comment]
I was able to reproduce on a linux system. The only difference is that I do not get a line ``Error:``, but only a single empty line.

Exit code of `nextercism` is `1` in this case.

My version of nextercism is `3.0.0-alpha.3`

**Comment by kytrinyx** [comment]
Thanks for the report -- this is a problem across all platforms.

**Comment by kytrinyx** [comment]
Looking through all the open issues today I realized that we have this one in duplicate. I'm closing this in favor of https://github.com/exercism/cli/issues/537

**Comment by NobbZ** [comment]
No duplicate!

This is about a missing error message under the circumstance that no token (or an invalid one) is configured.

The other one is about validating the token when setting it.

**Comment by kytrinyx** [comment]
No, this one is about a missing error message when the _wrong_ token is set, which is the same as validating the token.

Not having a token at all is covered in https://github.com/exercism/cli/issues/522
