### ISSUE TITLE
Do not clobber existing directories when configuring workspace dir

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#542]
When configuring the `nextercism` CLI for the first time (e.g. when `workspace_dir` in the config is blank), then we should verify that the workspace directory **does not exist** before setting a default. If it does, then we should exit with an error message saying that the directory already exists, and that if that's the correct directory, please call the command again, explicitly adding --directory="...".

We can print the full command for them to copy (including the token, which they just gave us).

**Comment by NobbZ** [comment]
Why is it not allowed to exist?

I'm using exerercism across several computers and synchronise the exercism folder by a third party tool. Why am I not allowed to do that anymore with nextercism?

Or why do I have to configure nextercism before synchronising the folder for the first time?

**Comment by kytrinyx** [comment]
> Why is it not allowed to exist?

It's allowed, I just don't want us to accidentally use a directory that someone is using for (for example) contributing to Exercism.

I think we can do things to make your use case simpler, if it's painful.

**Comment by NobbZ** [comment]
I think a simple `--force` flag would be sufficient for my usecase.

**Comment by NobbZ** [comment]
No, that's totally fine. When I read the proposal the first time I understood it as to not allow existing folders at all.

**Comment by kytrinyx** [comment]
> When I read the proposal the first time I understood it as to not allow existing folders at all.

Oooh! Yeah, that would be silly and impractical :)
