### ISSUE TITLE
Add `--team` flag to download command

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#546]
We need to support teams on the download command.

The format is:

```
exercism download --exercise=hello-world --track=ruby --team=funfun
```

Call the same API endpoint as the rest of the download command, but with the addition of `&team_id`, passing the slug that was found.

Store the files under:

```
$WORKSPACE/teams/$team/$track/$exercise
```

**Comment by aldraco** [comment]
Since there is no `--exercise` flag on the download command right now, should `download` allow the `--exercise` flag and/or an argument? Or should it move to require the flags, and not allow arguments?
