### ISSUE TITLE
Rework submit to explicitly take --files flag

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#549]
The default behavior of `submit` is to accept an `--exercise` and `--track` flag (and optionally `--team`). This will submit all the exercise files within the exercise directory. If someone wants to only submit some of them, they need to list out the files explicitly.

Currently the submit command accepts files as arguments. This should be changed to explicitly be a `--files` flag (shortflag `-f`).

If the files are not all for the same exercise, we need to exit with an error.

**Comment by aldraco** [comment]
I have been looking at this group of related tickets around `submit` and would like to start working on them -- I'll go ahead and claim this one, if nobody else has yet.

**Comment by kytrinyx** [comment]
@aldraco Thank you 🌻!

**Comment by aldraco** [comment]
status update -- `go test` passes for the 3 new behaviors :fireworks: but it still needs a bit of cleanup, clarification, etc. Also, since #568 came up in the last few days, want to see if it's possible to check that the issue won't affect this command as well.

**Comment by kytrinyx** [comment]
Fixed in #594
