### ISSUE TITLE
Unreachable code

### ISSUE THREAD

**Issue by FabienTregan** [exercism/cli#553]
In workspace/workspace.go, line 187 is not reachable.

I think it can just be deleted, but maybe there is a case I overlooked and there is a break missing for it ?

**Comment by kytrinyx** [comment]
I think you're right that it's unreachable.

One handy GitHub trick is to link directly to a line of code on GitHub:

https://github.com/exercism/cli/blob/73a9898a816557eeb3a916dc7661133da82c590d/workspace/workspace.go#L187

The steps I followed was:

* Go to the main repository page
* type `t`, which takes me into file navigation mode
* start typing part of the filename I want
* hit enter when it's the first item in the list
* scroll to the line I want
* click the little [...] on the left hand side
* select "copy permalink"

The permalink goes straight into the pastebuffer, so I can paste it in a comment somewhere.

<details>
  <summary>Screen recording of linking directly to a line</summary>
![link-to-line-on-github](https://user-images.githubusercontent.com/276834/41391085-eb14bcf8-6f55-11e8-9f9c-1d46c2c584a8.gif)
</details>
