### ISSUE TITLE
Access denied to .solution.json on Windows

### ISSUE THREAD

**Issue by FabienTregan** [exercism/cli#557]
# Environement

* Windows command line (cmd.exe)
* Latest exercism build (from nextercism branch)
* Empty workspace

# Observed behaviour

If you try to download an exercism twice, the second time it will fail because with an access denied. Submiting also gives the same error 👍 
```
D:\code\Exercism>v2 download hello-world --track=rust

D:\code\Exercism>v2 download hello-world --track=rust
Error: open D:\code\Exercism\workspace\rust\hello-world\.solution.json: Access is denied.
```
The problem probably occures anytime the .solution file is modified.

#Expected behaviour

Just working :)

#Analysis

* The problem comes from the fact that go's WriteFile fails on hidden file under windows (see https://github.com/FabienTregan/TestWritingToHiddenFilesInGo ).
* I came accross the problem while trying to make the tests pass on windows, and worked around the problem by deleting old configuration file in the test : https://github.com/FabienTregan/cli/blob/19c10054e0621104f9f53c617946c72329b4864b/cmd/prepare_test.go#L47

# Possible solutions

Since I could not find a way to write to hidden files on windows with go, two possible solutions come to me:
* avoid hiding the file
* delete the file before writting it

**Comment by FabienTregan** [comment]
Is seems that this one won't be easily fixed. We would have to use a modified implemtation of the file write / open functions that would pass proper attributes to syscall on windows (see https://github.com/golang/go/issues/25923#issuecomment-398479073 )

While possible, less tricky solutions could be :
* not hiding the file on windows
* delete the file before writing it, then making it invisible (I dont think we appen anything to the file ?)
* make the file visible, write to it, re-hide it

**Comment by kytrinyx** [comment]
I'm kind of OK with not hiding the file, to be honest.

Another thing we could consider is to only try to write it if it's different from what's there, in which case we could delete and rewrite (for all platforms).

**Comment by nywilken** [comment]
@FabienTregan I am unable to reproduce this issue on Windows following the steps you called out above. 
Looking at PR #630 I see that test are failing diving in a little deeper if I remove the calls to  visibility.Hidefile all the tests pass. 

I need to dive deeper into the issue and visibility package to get a better understanding of what is going on. Is this a limitation of Windows with dot files? I used them, but only ever modify via cli without issue.

**Comment by FabienTregan** [comment]
Te issue is currently workedaround by th following lines : https://github.com/exercism/cli/blob/052030145d92b0777a808b1348b91478cabd77c0/workspace/solution.go#L72-L79
It seems possible that PR #630 allows us to delete those two lines.
