### ISSUE TITLE
Give useful error messages for the error types that the API returns on download

### ISSUE THREAD

**Issue by FabienTregan** [exercism/cli#560]
# Environment

* windows 10, cmd.exe shell
* latest CLI from github nextercism branch

# Observed behaviour

Trying to download from a track you have not joined gives an error message which does not help the user to solve the problem :
```
D:\code\Exercism>v2.exe download hello-world --track=c
Error: Solution not found
```
Repeating the same command after you joined the track works as intended:
```
D:\code\Exercism>v2.exe download hello-world --track=c

Downloaded to
D:\code\Exercism\workspace\c\hello-world
```

**Comment by kytrinyx** [comment]
Agreed!

The response from the server returns an `error[type]` as part of the JSON the 404. It's one of `track_not_found`, `exercise_not_found` or `solution_not_found`. We should give a custom error message for each situation.

**Comment by FabienTregan** [comment]
Testing from the client (I did not have a look at the server's code yet), it seems that `solution_not_found` `"this exercise is not open to you yet because you did not complete at least one of the preceeding exercises", can you confirm ?

**Comment by kytrinyx** [comment]
@FabienTregan, yes, that is correct. But I think that the API should be providing the error message, the CLI shouldn't hard-code it, since it's much easier to deploy the website (once) rather than make (thousands of) people download a new version of the CLI.

**Comment by kytrinyx** [comment]
_This issue has been imported to the https://github.com/exercism/exercism.io repository._
