### ISSUE TITLE
[Mentorcism] Windows: Configuration Failing

### ISSUE THREAD

**Issue by jvarness** [exercism/cli#570]
When I try to configure the token, I get a `Error: CreateFile` error. When I execute `mentorcism -s`:

```
$ mentorcism configure -s

Config dir:      C:\Users\jake\AppData\Roaming\C:\Exercism\mentorcism.exe
-t, --token
-w, --workspace  C:\Exercism\mentorcism.exe
-a, --api        https://mentors-beta.exercism.io/api/v1
```

OS: Windows 10
Shell: Git Bash

**Comment by jvarness** [comment]
Would it helped if I tried executing it on a regular Windows command prompt?

**Comment by kytrinyx** [comment]
D’oh, I think I see what’s going on. Would you try reconfiguring the workspace to be a dir somewhere you have access to? (Sorry, on my phone, so can’t go deep at the moment)

**Comment by kytrinyx** [comment]
Ok, got to a real computer.

Try doing a `mentorcism configure --workspace="C:\Exercism\mentors-beta"` to see if that will work.

**Comment by jvarness** [comment]
I tried creating another folder in my user's directory on Windows and changing the workspace to that. Still no luck :(

**Comment by jvarness** [comment]
When I try it from a regular command prompt the CLI appears to be working just fine. When I use Git Bash  it doesn't.

**Comment by jvarness** [comment]
It appears everything works correctly as long as I'm using a Windows command prompt.

**Comment by NobbZ** [comment]
From git bash you need to use either double backslash or slash as path separator.

Also I do not know if git bash can even use windows pathes or if it needs to see it's posixified path.

**Comment by rpottsoh** [comment]
> Would it helped if I tried executing it on a regular Windows command prompt?

I am not having issues at a CMD prompt in Windows 7.

**Comment by jvarness** [comment]
I tried using all kinds of path patterns on Git Bash but it doesn't appear to work. It thinks that the path to config is `C:\Users\jake\AppData\Roaming\C:\Exercism\mentorcism.exe` when using Git Bash, but when I'm using cmd it appears to be pointing to the correct location.

**Comment by rpottsoh** [comment]
It is interesting to note that `./mentorcism c -s` in bash returns the same information as `mentorcism c -s` does in CMD with the exception that the `token` is missing in bash.

**Comment by rpottsoh** [comment]
If I try to perform `./mentorcism c -t {my token}` it fails:
```bash
$ ./mentorcism c -t 2XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX3e
Error: CreateFile C:\Users\Ryan Potts\AppData\Roaming\C:\nextercism\mentorcism.exe: The filename, directory name, or volume label syntax is incorrect.
```
`CreateFile` has some bogus looking path information.

**Comment by rpottsoh** [comment]
Powershell behaves the same way as bash...

**Comment by kytrinyx** [comment]
Would you try downloading this release and seeing if it fixes the issues you've been seeing? https://github.com/exercism/cli/releases/tag/v3.0.0-alpha.9.mentors

**Comment by kip-13** [comment]
I get the same error on cygwin:

```bash
Error: CreateFile C:\Users\User\AppData\Roaming\C:\cygwin64\bin\mentorcism.exe: The filename, directory name, or volume label syntax is incorrect.
```

I downloaded the last version.

**Comment by FabienTregan** [comment]
Yep, the tests no longer pass, the issue comes from this line of code : https://github.com/exercism/cli/blob/29544e650b41854be3c7e8dba027f281167c9476/config/dir.go#L20
`subdirectoryname` is initialized to "exercism", which should run, but it's later modified with an absolute path then the concatenation should not be done. I may some time to continue working on this tomorrow. The tests already reproduce the issue.

**Comment by kytrinyx** [comment]
@FabienTregan I'm going to try to do the ViperPersister rewrite today. That might fix the tests.

**Comment by FabienTregan** [comment]
I wanted to work on this but definitively won't have any energy today (nothing alarming, just celebrated my cousin's mariage) and won't have much time in the next three days. I should be able to test on windows if you make some changes.

**Comment by rpottsoh** [comment]
> Would you try downloading this release and seeing if it fixes the issues you've been seeing? https://github.com/exercism/cli/releases/tag/v3.0.0-alpha.9.mentors

If anything the output of `c -s` appears worse.  The output is correct from CMD.

```bash
$ ./mentorcism c -s

Config dir:      C:\Users\Ryan Potts\AppData\Roaming\C:\nextercism\mentorcism.exe
-t, --token
-w, --workspace  C:\Users\Ryan Potts/C:\nextercism\mentorcism-1
-a, --api        https://mentors-beta.exercism.io/api/v1
```

**Comment by kytrinyx** [comment]
@rpottsoh Oh, dear. I see what you mean!

**Comment by dcustodio** [comment]
I had the same problem in powershell, I solved it using cmd in administrator mode
