### ISSUE TITLE
[mentorcism] download command panics on macOS Sierra Version 10.12.6

### ISSUE THREAD

**Issue by benreyn** [exercism/cli#571]
```
$ ./mentorcism download hello-world --track=ruby
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x13a1174]
goroutine 1 [running]:
github.com/exercism/cli/workspace.Workspace.Locate.func1(0xc42002a090, 0x27, 0x0, 0x0, 0x150e720, 0xc42037e0c0, 0x0, 0x0)
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/workspace/workspace.go:65 +0x44
path/filepath.Walk(0xc42002a090, 0x27, 0xc4202fc020, 0x0, 0x150e720)
        /usr/local/Cellar/go/1.10.3/libexec/src/path/filepath/path.go:401 +0x6c
github.com/exercism/cli/workspace.Workspace.Locate(0xc42002a090, 0x27, 0xc4202f78c0, 0xb, 0xc42013da28, 0x1096c7a, 0xc42002a090, 0x22, 0x1ed)
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/workspace/workspace.go:100 +0x18c
github.com/exercism/cli/workspace.Workspace.SolutionPath(0xc42002a090, 0x27, 0xc4202f78c0, 0xb, 0xc420383ba0, 0x20, 0x0, 0x1, 0x0, 0x0)
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/workspace/workspace.go:113 +0x59
github.com/exercism/cli/cmd.glob..func2(0x17d7c80, 0xc42011a9c0, 0x1, 0x2, 0x0, 0x0)
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/cmd/download.go:125 +0x79d
github.com/exercism/cli/vendor/github.com/spf13/cobra.(*Command).execute(0x17d7c80, 0xc42011a9a0, 0x2, 0x2, 0x17d7c80, 0xc42011a9a0)
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/vendor/github.com/spf13/cobra/command.go:649 +0x449
github.com/exercism/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x17d7a40, 0x100620c, 0xc42008c058, 0x0)
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/vendor/github.com/spf13/cobra/command.go:728 +0x2d4
github.com/exercism/cli/vendor/github.com/spf13/cobra.(*Command).Execute(0x17d7a40, 0x0, 0xc4200a07a0)
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/vendor/github.com/spf13/cobra/command.go:687 +0x2b
github.com/exercism/cli/cmd.Execute()
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/cmd/root.go:45 +0x2d
main.main()
        /Users/kytrinyx/code/go/src/github.com/exercism/cli/exercism/main.go:6 +0x20
```

**Comment by mattsp1290** [comment]
Likely related to [572](https://github.com/exercism/cli/issues/572)

**Comment by mattsp1290** [comment]
The workspace defaulted to the location of the exectuable for me. Once I ran configure and set the workspace I was able to proceed.

**Comment by benreyn** [comment]
Some further information...
- I downloaded the `mentorcism` binary to my home directory `~/`
- After moving it to my exercism directory `~/code/exercism/` I was able to proceed, with the exercise being downloaded to `~/mentorcism` this was without running `configure --workspace`

**Comment by nickmabry** [comment]
Hopefully not dogpiling, here was my experience with a possibly different issue:
* I downloaded the 64-bit mentorcism binary to OSX 10.13.4
* Ran `mentorcism configure` to setup a token and local workspace folder
* Attempted to download an exercise with `./mentorcism download hello-world --track=ruby
* Was greeted by an error, instead of the exercise.

```shell
➜  Downloads ./mentorcism download hello-world --track=elixir
Error: Solution not found
➜  Downloads ./mentorcism download hello-world --track=ruby
Error: Solution not found
```

**Comment by blj** [comment]
I also had the same problem as @mattsp1290 with default being set to executable. After configuring the workspace to a folder that I created, it worked.

**Comment by unused** [comment]
The `Error: Solution not found` message shows up when the user has not joined the language track yet. I guess the common case is someone joins a language track before downloading some exercise, yet it might be a good point to improve the UX. [slack ref #testing](https://exercism-mentors.slack.com/archives/CBDHAPPLP/p1529686995000140?thread_ts=1529686855.000469&cid=CBDHAPPLP)

**Comment by kytrinyx** [comment]
Note to self: on a Windows machine the executable is named with the `.exe` suffix.
I think https://github.com/exercism/cli/issues/570 is also this same issue.

**Comment by nickmabry** [comment]
My note above was totally the result of trying to download an exercise before joining the language track. All works well on my end now.

**Comment by kytrinyx** [comment]
I think this should be solved in the latest release: https://github.com/exercism/cli/releases/tag/v3.0.0-alpha.9.mentors

**Comment by blj** [comment]
@kytrinyx where does `mentorcism` executable store the configuration? So I can clear and try the newer version for default workspace.

**Comment by nywilken** [comment]
@RJacksonm1 I went ahead and merged your changes, thanks again. As I said in my review I can reproduce the issue by using a non-existent workspace directory https://github.com/exercism/cli/pull/569#issuecomment-399688438

@kytrinyx can you please confirm the fix on your end and release. As I don't want to stomp out any changes you made specifically for the beta mentor site on your end.

**Comment by kytrinyx** [comment]
> where does mentorcism executable store the configuration? 

@blj If you run `mentorcism configure --show` it will tell you where the file is.

@nywilken Yepp, I'm going to make a few changes today based on some of the things we've seen and then cut another release this evening or tomorrow.

**Comment by kytrinyx** [comment]
I think this has been resolved. @benreyn if you're still seeing problems with this please holler!
