### ISSUE TITLE
[mentorcism] Output of download command

### ISSUE THREAD

**Issue by NobbZ** [exercism/cli#576]
We already have the `workspace` command, which lets use do nice things like `cd $(mentorcism workspace)` and `download` already spits out the path to an exercise, but alltogether with some “random” text. It would be nice if we had no output but the path, then we could do `cd $(mentorcism download hello-world --track=erlang)` instead of `cd $(mentorcism download hello-world --track=erlang | tail -n 1)`.

**Comment by RJacksonm1** [comment]
A `-q --quiet` flag would be great for this.

**Comment by kytrinyx** [comment]
Yeah, either a quiet flag or maybe put all the noise to `STDERR`?

**Comment by nywilken** [comment]
I’m late to this party, but I think a quiet flag might add more confusion especially when compared against the verbose flag. 

What about making the default output match the ideal quiet state so that users can script, parse output, with out remembering flags. Then repurposing the verbose flag to output all the information we have now. 

The existing verbose flag has a bit of debug info so maybe we can clean that up a little, but the main point being that the preferred state should not require a flag.

**Comment by kytrinyx** [comment]
I think it's important that what the user sees by default (without any extra flags) is the most friendly, helpful output.

The verbose flag was introduced specifically for the debug output, and I think that still makes sense.

After thinking about this a bit I think I'm leaning more towards having the stuff you wouldn't want to redirect go onto STDERR. It's kind of sort of philosophically aligned with what STDERR originally was for (not sticking stuff in STDOUT that you didn't want to pipe into other programs).

https://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout

**Comment by RJacksonm1** [comment]
The more I think about it, the more using `stderr` makes sense to me 👍

Seems like we could do with reviewing the codebase for each piece of output and determining which stream they belong to, or whether they'll need splitting (like the `download` path output).

To be overcautiously clear, would we agree with the following:

`stderr`: 

* Human friendly information ("usage", "diagnostics", and general friendliness)
* Actual errors

`stdout`: 

* Explicitly requested information (e.g. `help`, `troubleshoot`)
* Parse friendly output (e.g. download location)

**Comment by kytrinyx** [comment]
I've implemented this in https://github.com/exercism/cli/releases/tag/v3.0.0-alpha.10.mentors -- I'm going to close this for now, but am of course happy to tweak this if you all have suggestions for improvement.
