### ISSUE TITLE
[mentorcism] Code is not highlighted in the submitted solution in the common-lisp track

### ISSUE THREAD

**Issue by tushartyagi** [exercism/cli#577]
When I submit a solution for `Common Lisp` track and open the solutions page on the website as a student or as a mentor, then the code is not highlighted in the `Solution` or in the `Test Suite` tab. 

![image](https://user-images.githubusercontent.com/1630265/41821834-2d3dc62c-7804-11e8-857d-1c61c4cea1c9.png)

**Comment by tushartyagi** [comment]
I've seen this only in the common-lisp track. I'm a mentor in the csharp track as well, but this is not replicable over there. 

![image](https://user-images.githubusercontent.com/1630265/41821887-e062a650-7804-11e8-98ec-85c74755d6a7.png)

**Comment by NobbZ** [comment]
What language is this?

Has it already a highlighter specified through exercism/meta#90?

Is your used file extension the same as the one talked about in that issue?

Maybe its already in that issue, but hasn't yet been deployed, but lets make sure its prepared correctly.

**Comment by tushartyagi** [comment]
This is common lisp. The extension is `.lisp`.

The highlighter is not specified and the name doesn't appear in the list which was shared in the link. Although @verdammelt mentioned the missing lisp highlighter in the ticket, there wasn't any more discussion on that.

On 24 June 2018 11:19:04 PM IST, Norbert Melzer <notifications@github.com> wrote:
>What language is this?
>
>Has it already a highlighter specified through exercism/meta#90?
>
>Is your used file extension the same as the one talked about in that
>issue?
>
>Maybe its already in that issue, but hasn't yet been deployed, but lets
>make sure its prepared correctly.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/exercism/cli/issues/577#issuecomment-399774338

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nywilken** [comment]
@NobbZ where’s the right place for this issue?  

@tushartyagi  we should move this issue so that it doesn’t get lost.

**Comment by kytrinyx** [comment]
@tushartyagi would you mind opening this in https://github.com/exercism/v2-feedback/issues?
We have common-lisp in our Prism configuration but there may be something wrong with it.
https://github.com/exercism/prototype/blob/0cc929e548dd2f2e9ab4083f85c4c025ce938dee/config/initializers/prism.rb#L156

**Comment by kytrinyx** [comment]
Closing in favor of https://github.com/exercism/v2-feedback/issues/170
