### ISSUE TITLE
mentorcism: Allow flag to change directory when using download command

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/cli#590]
When I execute the download command, most of the time I want to then change the current directory to that of the downloaded exercise. Maybe it is just me, but maybe more people do this. If so, it might be useful to have a switch that would change the current directory to that of the just downloaded exercise.

**Comment by NobbZ** [comment]
Isn't this covered by #576?

**Comment by ErikSchierboom** [comment]
> Isn't this covered by #576?

Well, yes in the sense that you can achieve the same result with #576. However, I suspect that the code specified there is not that trivial for many users to come up with. Hence why I would still prefer an explicit flag.

**Comment by NobbZ** [comment]
Well, that syntax is quite obvious for those who use linux on a daily base, while I can not see a way to change the parents working dir from a child process on linux.

In other words: I can't see a way to make a flag work...

**Comment by ErikSchierboom** [comment]
@NobbZ Ah okay, you're right of course. I think I'll close this issue then.
