### ISSUE TITLE
500 When uploading hello world kotlin exercise

### ISSUE THREAD

**Issue by mikegehard** [exercism/cli#592]
See https://pastebin.com/L88P9ajB for details.

Mac OSX with IntelliJ as the editor.

**Comment by nywilken** [comment]
@mikegehard I tried submitting a few simple exercises and did not receive a 500 response from the API. You can try submitting with the `-v` to see if it provides any addition API response information. 

None the less, if you jump on Exercism support https://gitter.im/exercism/support someone who has a more insight into the API and possibly the Kotlin track can assist further.

**Comment by NobbZ** [comment]
In the slack there was already the conclusion that one of the binary files was bigger than allowed.

So there should be a proper error message in that case.

Additionally such a scenario would be much less likely to happen if #458 was solved…

**Comment by nywilken** [comment]
@nobbz thanks for the update on this issue. I thought it had something to do with the files being uploaded. I’ll go ahead and close this issue for now. 


#458 is slated for post launch so we will make sure to get to it once we decide on a strategy.

**Comment by mikegehard** [comment]
The slack conversation for future reference:

https://exercism-mentors.slack.com/archives/CAQP7JL3T/p1530199987000056?thread_ts=1530199696.000008&cid=CAQP7JL3T
