### ISSUE TITLE
Unable to submit multiple files

### ISSUE THREAD

**Issue by mikewalker** [exercism/cli#620]
According to the instructions on the new web site inorder to submit I use the command.

exercism submit /path/to/file [/path/to/file2 ...]

However, I am getting the error

Error: accepts at most 1 arg(s), received 2

The exact command I am using is "exercism submit src/beer_song.c src/beer_song.h"

**Comment by nywilken** [comment]
Thanks for reporting @mikewalker

This is a bug on our end. @kytrinyx we need to remove `Args: cobra.MaximumNArgs(1)` from the submit command `cmd/submit.go`

**Comment by mikewalker** [comment]
The CLI will do its best to figure out what to submit.
If you call the command without any arguments, it will
submit the exercise contained in the current directory.
If called with the path to a directory, it will submit it.
If called with the name of an exercise, it will work out which
track it is on and submit it. The command will ask for help
figuring things out if necessary.
`,
Args: cobra.MaximumNArgs(1),

Thanks, I was just doing a bit of digging into things myself and found this comment explaining this. After reading this I tried submit without args and got another error I think this might be a differnent problem though. Maybe related to the fact that this solution came originated from the old site.

Error: open /home/mwalker/exercism/c/beer-song/.solution.json: no such file or directory

**Comment by kytrinyx** [comment]
@mikewalker I need to fix the description comment... that's somewhat optimistic at the moment. I'm planning on implementing a smarter submit command, but at the moment it just takes files.

I fixed the multi-file bug in https://github.com/exercism/cli/pull/622 and cut a release https://github.com/exercism/cli/releases/latest.

**Comment by kytrinyx** [comment]
@mikewalker for the `.solution.json` thing check out this page: https://exercism.io/cli-v1-to-v2

**Comment by Donbosco12345** [comment]
#620submittef

**Comment by Donbosco12345** [comment]
#620submitted
https://github.com/exercism/cli/issues/620

**Comment by Donbosco12345** [comment]
https://github.com/exercism/cli/issues/620
submitted

**Comment by sheriffderek** [comment]
Hi! I'm excited to try this thing out - but I'm also stuck on this submit command.  _Maybe I should have taken the bash track.._ haha - but really / I'm not sure what these paths are all about. I've tried every combination of 1 path, 2 path, no path, blue path. Can you show me the way?

I'm here: `/Users/sheriffderek/exercism/elixir/hello-world` with passing tests. What would the command be to submit this?

**Comment by kytrinyx** [comment]
@sheriffderek Hey! Sorry it's taken me 2 days to get back to you!

We have an issue open for the capitalization thing on Mac. It's a pain in the butt--basically on Mac and Windows the filesystem is case insensitive, but on Linux it is case sensitive, so we need to do something clever to make it work everywhere.

I think we need to add this capitalization thing to the troubleshooting FAQ in the meanwhile!

Glad you got this sorted out ✨
