### ISSUE TITLE
Warning for already populated workspace is very wide and overindended

### ISSUE THREAD

**Issue by NobbZ** [exercism/cli#623]
```
$ exercism configure -t xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx             
Error: 
			The default Exercism workspace is

			  /home/nmelzer/exercism

			There is already something there.
			If it's a directory, that might be fine. If it's a file, you will need to move it first,
			or choose a different location for the workspace.

			You can choose the workspace location by rerunning this command with the --workspace flag.

			  exercism configure --token=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx --workspace=/home/nmelzer/exercism
```

I do understand the warning and comply.

But we have roughly 25 characters of whitespace to the left of the text and also the text itself is very wide with ~100 characters net.

This causes an overal width of ~125 characters.

My suggestions are:

1. Remove the whitespace to the left
2. Wrap the text at 80 characters (or use real terminal width)

**Comment by kytrinyx** [comment]
Ooh! My bad. Thanks for reporting it.

I meant for that to be spaces, not tabs. I'll fix it now.
