### ISSUE TITLE
Provide a way to see status (particularly useful when doing multiple tracks in parallel)

### ISSUE THREAD

**Issue by jave** [exercism/cli#627]
I used "exercism fetch" a lot in the previous version, for its useful status display.
Can I get this status display back somehow?

**Comment by nywilken** [comment]
Fetch was replaced with the download command. We had to revert some functionality as it was not just right at launch so we will review the previous status info and figure out how to best implement. Thanks for opening up this issue.

**Comment by jave** [comment]
thanks. I noticed you need to migrate previous in progress exercisms, and thats okay.

I like doing a lot of tracks in parallell, and therefore I used "exercism fetch" to fetch the status of all the tracks I'm working on atm (20-ish I think). So, it was neat to be able to see which exercise I was working on for a track, and having the client automatically download the next one.

I would like to make my own client in elisp that does this, but I cant seem to find the api documentation for exercism. 

With that said, I like the new version, and good work everyone!

**Comment by kytrinyx** [comment]
> to fetch the status of all the tracks I'm working on atm (20-ish I think).

😍 That's a lot of tracks!!!

> it was neat to be able to see which exercise I was working on for a track

Hm, yes, I can definitely see how this would be useful when working on a lot of tracks in parallel.
Let me think a little bit about how we could best accomplish this.

**Comment by kytrinyx** [comment]
_This issue has been imported to the https://github.com/exercism/exercism.io repository._
