### ISSUE TITLE
Exercism list tracks and problems

### ISSUE THREAD

**Issue by nealot** [exercism/cli#629]
Is there an api to fetch a list of the tracks and the problems? I would like to be able to integrate exercism with my text editor and it would be nice if I could obtain a preview of the tracks/problems to download.

**Comment by jave** [comment]
I also want to do this, for emacs

**Comment by nealot** [comment]
Metadata like the level of difficulty would also be pretty useful to include.

**Comment by daveyarwood** [comment]
There used to be an `exercism tracks` command that listed all of the available tracks, but it seems to have disappeared. That's a bummer, because I had a similar setup where I could run a script to fetch an exercise from a random track, and my script relied on the output of `exercism tracks`.

**Comment by kytrinyx** [comment]
We'll likely be adding back _something_ that will provide more track/exercise data from the API, but it will probably be at least a few weeks until we get it.

**Comment by kytrinyx** [comment]
_This issue has been imported to the https://github.com/exercism/exercism.io repository._
