### ISSUE TITLE
Submit Error: couldn't find it

### ISSUE THREAD

**Issue by NobbZ** [exercism/cli#634]
@janus commented on [Sat Jul 14 2018](https://github.com/exercism/exercism.io/issues/3808)

I got this message each time I try to submit; 
exercism submit isogram.c
~/exercism/c/isogram/src$ tree
.
├── isogram.c
└── isogram.h

0 directories, 2 files

~/exercism/c/isogram/src$ exercism submit isogram.c Error: couldn't find it

When I tried exercise 1 it worked , this issue started after I upgraded  exercism. What is it that I am doing wrong?

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.2
Latest:  3.0.2

Operating System
----------------
OS:           linux
Architecture: amd64

Configuration
----------------
Home:      
Workspace: /home/eva/exercism
Config:    /home/eva/.config/exercism/user.json
API key:   *****************************

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 468.457524ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 6.07206924s

---

@NobbZ commented on [Sat Jul 14 2018](https://github.com/exercism/exercism.io/issues/3808#issuecomment-405014069)

That error means that you are missing the `.solutions.json` (or some other file, but its a dotted-JSON) that gets only created when you download the exercise with the current client.

Make sure you fulfill the preconditions for downloading the exercise, backup your stuff, download via CLI, apply your backup and resubmit.

**Comment by nelsonmfinda** [comment]
I am also facing the same problem.

**Comment by kytrinyx** [comment]
Ah! I thought I had fixed the error messages but this one slipped through. The error message can definitely be improved. Thank you @NobbZ :)

**Comment by kytrinyx** [comment]
I found where I fixed this! It's in a branch on my local copy of the repo that I never pushed up. Also I didn't actually quite finish fixing it. It's been a busy week!
