### ISSUE TITLE
feature request - "I'll pass thanks" behaviour

### ISSUE THREAD

**Issue by soniah** [exercism/cli#636]
As a mentor,
when I click "I'll pass thanks"
it should take me to the next item in the mentor queue, rather than back to the "Solutions you're mentoring" page.

By making it easier for mentors to browse the queue, more comments will be made. In my opinion...

**Comment by nywilken** [comment]
@soniah this request is related to exercism/exercism.io

**Comment by soniah** [comment]
Thanks @nywilken !
