### ISSUE TITLE
Does contain .solution.json any secrets?

### ISSUE THREAD

**Issue by NobbZ** [exercism/cli#638]
Does the `.solution.json` file contain any secrets or can I assume it is safe to put under public version control?

Will this hold even in the future?

**Comment by kytrinyx** [comment]
That's a good question! The `.solution.json` file is safe to put under public version control. It doesn't contain secrets, and we will make sure to not put any secrets in there in the future.

**Comment by kytrinyx** [comment]
I'm going to close this, as there's nothing further actionable on it at this time.
