### ISSUE TITLE
Upgrade command doesn't work

### ISSUE THREAD

**Issue by stevejb71** [exercism/cli#643]
Following the instructions to call upgrade, on using the client tool for the first time after v2:
My client is v2.3.0, running on Ubuntu 16.04

~/exercism/reasonml$ exercism upgrade
Downloading exercism-linux-64bit.tgz
2018/07/15 13:04:00 open /usr/bin/exercism: text file busy

**Comment by nywilken** [comment]
@stevejb71 thanks for the detailed information. It appears that you are trying to upgrade exercism which resides within a system level directory. If you ran the instructions as written then you will get the error above if you try to upgrade without sudo access. 

Please try running `sudo exercism upgrade` to fix the issue. 

You will be happy to know that the latest version gives a proper error `permission denied`. 

Please let us know if you run into any other issue.

**Comment by nywilken** [comment]
Generally speaking, it is assumed that exercism will be installed in a user owned bin directory so that upgrade commands, file replacements, can be executed without the need for elevated permission. I recommend you take a look at the new Exercism [Getting Started guide](https://exercism.io/getting-started)

**Comment by stevejb71** [comment]
Running it under sudo does the upgrade, and have got the latest 3.0.4 version installed now (in the same place).

It didn't remember my API key when I tried to download an exercise, and also gave a path in the error message which could be improved (/my/settings below should probably be https://exercism.io/my/settings)

```
steve@Froggy:~$ exercism download reasonml change
Error: 

    Welcome to Exercism!

    To get started, you need to configure the the tool with your API token.
    Find your token at

        /my/settings

    Then run the configure command:

        exercism configure --token=YOUR_TOKEN
```

**Comment by kytrinyx** [comment]
@stevejb71 Yeah, that URL is not quite right. I'll open a separate issue about that.

**Comment by kytrinyx** [comment]
Alright, we've sorted out the URL issue, and (unfortunately) can't do anything in the CLI for the `sudo` issue. I'm going to close this.

**Comment by NobbZ** [comment]
@kytrinyx I've not looked at the updater code, but, may I suggest the following:

If we are on a linux and the first `exercism` binary in the `PATH` is **not** owned by the current user, we should simply suggest to ask the files owner to do the update. Further if the owner is `root` and the path not prefixed by `/root/`, we can safely assume, that the binary is owned by a package. We should then suggest to remove the package and follow the official installation instructions.

If you want me to, I can open another issue with this draft.

**Comment by nywilken** [comment]
@Nobbz I think what you are proposing could  help things but it may be a bit much for us to do in the CLI. Is there an FAQ or help document that we could add this information to?

All the instructions suggest installing the binary into a users home directory. If a user happens to have their binary in a location where they are not the owner of then calling upgrade would error with a permission denied error. If we add a little more context to the error `encountered the following error when upgrading: <error>. Please check your permissions and try again.` it could help them resolve the issue.

**Comment by NobbZ** [comment]
@nywilken I do understand, its a lot of logic.

Perhaps add a section for installation and updating the CLI in the FAQ and link to it when we encounter errors during upgrade?

```
We were not able to write your file because we had an error:

{{raw error}}

Please check the FAQ on upgrading problems.

https://exercism.io/faq#cli-upgrade
```

Or something along that lines.

Especially, even after I am not a friend of user-level install and still suggest to have packages for major platforms, I understand that it is currently not managable to do so. So we really should drive the FAQ in a way that we get rid of all those packages and/or make clear that we do not support system wide installations, regardless if they happened manually or via package manager.

**Comment by NobbZ** [comment]
PS: The last resort solution in the FAQ should be post an issue. If we do a FAQ, we definitively need this to be part of it, or people will probably give up after trying the FAQ.

**Comment by nywilken** [comment]
> PS: The last resort solution in the FAQ should be post an issue. If we do a FAQ, we definitively need this to be part of it, or people will probably give up after trying the FAQ

Agreed. 

Your FAQs proposal is a great idea.  It is easy to implement and would provide a path forward for users.
