### ISSUE TITLE
Windows 10: Resulting CLI after upgrade broken

### ISSUE THREAD

**Issue by rpottsoh** [exercism/cli#645]
Called `upgrade` from 2.4.1 CLI on Windows 10.  Upgrade was successful:
```
C:\Users\rpott>exercism
NAME:
   exercism - A command line tool to interact with http://exercism.io

USAGE:
   exercism [global options] command [command options] [arguments...]

VERSION:
   2.4.1

COMMANDS:
     configure     Writes config values to a JSON file.
     debug         Outputs useful debug information.
     download, dl  Downloads a solution given the ID of the latest iteration.
     fetch, f      Fetches the next unsubmitted problem in each track.
     list, li      Lists the available problems for a language track, given its ID.
     open, op      Opens exercism.io to your most recent iteration of a problem given the track ID and problem slug.
     restore, r    Downloads the most recent iteration for each of your solutions on exercism.io.
     skip          Skips a problem given a track ID and problem slug.
     status, st    Fetches information about your progress with a given language track.
     submit, s     Submits a new iteration to a problem on exercism.io.
     tracks, t     Lists the available language tracks.
     unsubmit, u   REMOVED
     upgrade       Upgrades the CLI to the latest released version.

GLOBAL OPTIONS:
   --config value, -c value  path to config file [%EXERCISM_CONFIG_FILE%, %XDG_CONFIG_HOME%]
   --verbose                 turn on verbose logging
   --help, -h                show help
   --version, -v             print the version


C:\Users\rpott>exercism upgrade
Downloading exercism-windows-64bit.zip
Successfully upgraded!

C:\Users\rpott>
```
Upon executing `exercism` after the upgrade I am presented with the following dialog:
![image](https://user-images.githubusercontent.com/6978003/42737511-33aab184-8842-11e8-8ad4-d61cf6484ec5.png)

My instinct is to go through, by hand, and remove all remnants of the old CLI and to try again.  I presumed that `upgrade` would be successful.

`exercism version` also yields the same error.

I'll keep my setup as is for the time being until I receive some feedback on what you might like me to try.

**Comment by rpottsoh** [comment]
I installed the CLI into a clean copy of windows 10 (on a VM) and the CLI works fine.  I suspect if I cleaned my system of the older CLI completely it will function properly.

**Comment by rpottsoh** [comment]
The resulting `exercism.exe` is only 1100 bytes in size.

**Comment by rpottsoh** [comment]
Downloading the latest CLI directly from CLI repo or using the Windows Installer has yielded a proper CLI executable.

**Comment by nywilken** [comment]
@rpottsoh thanks for reporting. I was able to repro this issue on Windows 8 as well. This is issue has to do with the shell completion scripts being included in the release binary. Upon extracting the binary you will see an exercism.exe binary and a directory named shell (which has the file size of 1100 bytes).

The upgrade procedure for Windows is replacing the binary being upgraded with the last file within the zip `shell`.

**Comment by rpottsoh** [comment]
I don't have url at my finger tips, but there is a doc that recommends that the CLI be upgraded via `upgrade` or by downloading the latest CLI.  Should this doc be revised to not use `upgrade` or is there something else that can be done to fix this?

**Comment by nywilken** [comment]
@rpottsoh I just opened up a PR for a potential fix. If @kytrinyx is good with it we can roll it out; Otherwise we should remove the shell files from the Windows binaries for now.
