### ISSUE TITLE
32 bit Windows: Resulting CLI after upgrade broken

### ISSUE THREAD

**Issue by rpottsoh** [exercism/cli#657]
This is essentially a repeat of #645 but for 32 bit Windows instead.  Happens to be Windows 7.

Same 1100 byte executable is left in the place of the 2.4.1 exe.  This is the dialog that appears when I try to run the CLI:
![image](https://user-images.githubusercontent.com/6978003/42963520-7a0831c4-8b62-11e8-891d-ffcef61ec6d1.png)

**Comment by NobbZ** [comment]
Please download the appropriate ZIP for your version of windows from https://github.com/exercism/cli/releases/latest.

Extract the `exercism.exe` from that archive over your old one, you can find the path of the old one via `where exercism`.

After you upgraded to 3.0.5 this way, you should be able to use the `exercism upgrade` in the future.

**Comment by rpottsoh** [comment]
I am aware of all that.  I am assuming #646 fixed the issue.  There instructions here will be problematic to Windows user. https://exercism.io/cli-v1-to-v2

**Comment by NobbZ** [comment]
Yeah that fixed the issue, but that is only merged into 3.0.5, you need to get there manually...

But yes, perhaps we should mention the problem in a footnote and link to the well hidden installation guide instead.

**Comment by kytrinyx** [comment]
https://github.com/exercism/website-copy/pull/225
