### ISSUE TITLE
Ensure filepaths are all normalized on submit/download

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#665]
When submitting files on Windows, we need to ensure that the server receives normalized file separators (`/`), and when downloading files on windows, we need to ensure that any file paths are normalized to Windows path separators (`\`).

See https://github.com/exercism/exercism.io/issues/3870 for original report.

**Comment by ptillemans** [comment]
I have an example for this: solution dae72e893ea042729b35608a16584ad1

A student submitted a solution for rust track challenge Pythagorean Triplets.

It displays fine on the site, but when downloading the solution contains:

``` rust
rust/pythagorean-triplet » cat src/lib.rs
pub fn find() -> Option<u32> {
    unimplemented!();
}
```

examining the content of the folder:

``` sh
rust/pythagorean-triplet » ls -al
total 40
drwxr-xr-x  9 pti  staff   288 24 jul 10:46 .
drwxr-xr-x  3 pti  staff    96 24 jul 10:46 ..
-rw-r--r--  1 pti  staff   249 24 jul 10:46 .gitignore
-rw-------  1 pti  staff   233 24 jul 10:46 .solution.json
-rw-r--r--  1 pti  staff    73 24 jul 10:46 Cargo.toml
-rw-r--r--  1 pti  staff  2421 24 jul 10:46 README.md
-rw-r--r--  1 pti  staff  1183 24 jul 10:46 \\src\\lib.rs
drwxr-xr-x  3 pti  staff    96 24 jul 10:46 src
drwxr-xr-x  3 pti  staff    96 24 jul 10:46 tests
```

note the \\src\\lib.rs

**Comment by ptillemans** [comment]
Oops, sorry, didn't saw this was closed already. sorry.

**Comment by kytrinyx** [comment]
This isn't closed -- it's being worked on.

**Comment by Stargator** [comment]
I'm on a MacOS and 1 out of 5 of the first solutions I downloaded were like the one @ptillemans posted. But this is on the Dart track.

**Comment by ErikSchierboom** [comment]
@kytrinyx Just out of curiosity: is this high on the priority list? It is my number one pain when using the CLI (which is otherwise working perfectly).

**Comment by kytrinyx** [comment]
Yes, it's next on my list!

**Comment by ErikSchierboom** [comment]
Fantastic!
