### ISSUE TITLE
MAC: command line wont recognize exercism

### ISSUE THREAD

**Issue by cliffmccrary** [exercism/cli#674]
Hey guys having a little trouble getting exorcism installed on my mac. I have unzipped it and put unix executable in my path. Get command not found when I try to call it. I can open the executable and it launches fine. Also tried it in home path, tried moving all files with executable so they are in same path, tried leaving everything how it was unzipped in the folders, no dice. What am I missing? never had trouble like this installing from command line haha.

**Comment by NobbZ** [comment]
* Where exactly have you put the binary?
* What is the output of `echo $PATH`?
* What do you mean by “[you] can open the executable and it launches fine”?
* Does specifying an absolute path to the call work, eg: `~/bin/exercism version` (assuming you have put the executable to `~bin`).

**Comment by cliffmccrary** [comment]
i put it in my folder pythonthehardway in my home dir. When i echo $path i get blank line and then back to comman prompt at pythonthehardway folder. If I open the executable file it gives me all info about exercism. If i specify and absolute path with version it returns back proper call with version 3.0.5.  If i dont specify path it just says -bash: exercism: command not found

**Comment by NobbZ** [comment]
I asked for `echo $PATH`, not `echo $path`. Environment variables are case sensitive.

Also I doubt that some pythonthehardway folder is in your search path.

Also I asked where **exactly** you put the binary. By this I mean an absolute path.

**Comment by cliffmccrary** [comment]
sorry about that, this is what comes up: /Users/melissaannnunez/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin 

not to sure on second question? when you say binary you mean executable file? if so its in /Users/melissaannnunez/pythonthehardway . How do I get absolute path?

**Comment by cliffmccrary** [comment]
wow i feel really dumb! guess i didn't have it figured out as much as I thought haha, followed the detailed instructions on setting up terminal and got it figured out.

Thanks for the help nobbz sorry for wasting your time :/

**Comment by NobbZ** [comment]
Yeah, `/Users/melissaannnunez/pythonthehardway` is the absolute path. But that is not in your `$PATH`. 

Move it in one of the places that are listed in your `$PATH`, or even better, put it in `~/bin` and add that to your `$PATH`. How to do so, you have to look up in your operating systems manual. I'm not proficient enough with Mac and it's specifics.

**Comment by kytrinyx** [comment]
@cliffmccrary If you're still stuck, let us know. I'm familiar with Mac and PATH. If you're all sorted, would you please close this issue?
