### ISSUE TITLE
Windows CLI install issue - can't click "Next >" after choosing path 

### ISSUE THREAD

**Issue by bostonrwalker** [exercism/cli#684]
I'm trying to install in AppData since I don't have permissions on C:/ on this machine. Unfortunately, the installer won't let me get past the first prompt! I also visited the license agreement link to see if that would help, but the "Next >" button is still greyed out. Shift+ N doesn't work either.

![2018-07-26 17_42_33-exercism cli install](https://user-images.githubusercontent.com/22710070/43290362-dfef3ec6-90fb-11e8-8f86-164ff4686f1c.png)

**Comment by NobbZ** [comment]
I skimmed the code of the installer, and it seems that the button is only enabled when `CheckTLS.TLSok` is `True` as well. It seems as if there is a check made against the TLS version available to your computer and I remember that there have been issues with TLS on some older windows versions (7 and/or 8) in general.

Please check if following the link labeled "Microsoft instructions for updating default TLS settings" and also following instructions given there helps you.

If not please report back.

@exercism/windows-installer if my assumptions are correct, can you make the action that has to be taken by the user more clear? eg a fat red warning, telling the user that his TLS settings are dated and he needs to manually re-configure it?

**Comment by kytrinyx** [comment]
@bostonrwalker If you're on Windows 10, you could try going through the walkthrough and taking the "manual installation" route: https://exercism.io/cli-walkthrough -- that should get you unblocked until @rpottsoh has a chance to update the installer.

**Comment by rpottsoh** [comment]
> can you make the action that has to be taken by the user more clear? eg a fat red warning, telling the user that his TLS settings are dated and he needs to manually re-configure it?

@NobbZ I should be able to do something.  Thanks for the suggestion.

**Comment by rpottsoh** [comment]
@bostonrwalker Did a dialog box also appear indicating an error with TLS on your computer.  It should have been worded similar to this:
```text
TLS Version = %s, must be %0.1f or greater.
GitHub requires at least version 1.2
Please follow the link to Microsoft for instructions on updating Windows.'
```

**Comment by rpottsoh** [comment]
![temp](https://user-images.githubusercontent.com/6978003/43295394-a188785c-9112-11e8-8415-cdea21e16662.gif)

The screen will look like this for the next release when the TLS check fails.

**Comment by rpottsoh** [comment]
I am going to reword the message in the dialog box.

**Comment by rpottsoh** [comment]
I have released an update to the installer https://github.com/exercism/windows-installer/releases/latest

**Comment by bostonrwalker** [comment]
I tried following Microsoft's instructions to update my TLS defaults, but due to security restrictions I couldn't make the required changes on this PC. On the other hand, I was able to install the CLI and submit solutions without TLS 1.2 after following the instructions for Windows manual install at https://exercism.io/cli-walkthrough. So it seems TLS 1.2 is only a requirement of the particular implementation of the installer. Perhaps it would make sense to remove this requirement to make the software more accessible to novice users on their work PCs?

**Comment by rpottsoh** [comment]
The installer is using the default version of TLS available to Windows (not something provided by a 3rd party library).  I agree this is a weakness of the installer.  I need to look into using a 3rd party, OS, library. 
 What version of Windows are you using?  TLS issues, in regards to the installer, are normally only found with versions less than 10.  The installer has been downloaded thousands of times and there have only been a total of two reported instances of the TLS check being an issue, the first was the result of the users locale settings having an unanticipated side effect.  

If you wouldn't mind would you open an issue in [exercism/windows-installer/issues](https://github.com/exercism/windows-installer/issues)?  Your's is a unique case that I cannot duplicate.  I would like to try some things and will need a willing participant to test things for me.  Mention this issue in the new one.

**Comment by rpottsoh** [comment]
@bostonrwalker I think I have worked out an update that will remove the need for updating TLS settings in Windows if they are not up to GitHub requirements.  I would like to put a Pre-release version up for you to try.  I'll assume that you are and will post again when it is ready,

**Comment by kytrinyx** [comment]
Thanks! I'll close this one.
