### ISSUE TITLE
Default workspace directory is next

### ISSUE THREAD

**Issue by tejasbubane** [exercism/cli#689]
Default workspace directory is `exercism_submissions_next`. It can be changed to `exercism_submissions` now that we have v2 site live.

```
exercism version 3.0.6
```

**Comment by nywilken** [comment]
@tejasbubane are you asking if you can change your workspace path now that v2 of the site is live? 

If so, the answer is you can use the `configure` command to change your workspace and all should work as expected. Please keep in mind that the CLI will not move files for you so you will need to create your new directory, copy over your files (rsync for Mac/Linux or robocopy for Windows), before changing the workspace path.  `exercism configure -w <full-path-to-new-workspace-directory>`

If your your are migrating old solutions please refer to the migration guide [here](https://exercism.io/cli-v1-to-v2) for instructions on how to update previous exercises (v2.x.x) to work with the latest v3 CLI.

**Comment by tejasbubane** [comment]
> @tejasbubane are you asking if you can change your workspace path now that v2 of the site is live?

No. I mean the CLI should now use default path as `exercism_submissions` when someone runs the `configure` command for the first time.

**Comment by nywilken** [comment]
I see. The default directory when running configure is not `exercism_submissions_next`, but `exercism` which by default will be relative to the user’s home directory.

**Comment by tejasbubane** [comment]
Ok I think it was being picked up from my old config (the beta release of CLI that I had installed before). After deleting the `~/.config` this looks good:

```
Config dir:                       /Users/tejas/.config/exercism
Token:         (-t, --token)      <token>
Workspace:     (-w, --workspace)  /Users/tejas/Exercism
API Base URL:  (-a, --api)        https://api.exercism.io/v1
```
