### ISSUE TITLE
exercism will not move to /bin Ubuntu 16.04

### ISSUE THREAD

**Issue by BigslimVdub** [exercism/cli#690]
Downloaded latest Linux 64 and extract files to /Downloads folder. I am unable to move or copy exercism.exe to ~/bin with sudo or gksudo. Manually moving causes permissions denied. Yes I have admin privileges. 

The exe does not run so I do not believe this is correct file for ubuntu. 

Do I need to build from source? No cmakelists.txt for use with make.

**Comment by nywilken** [comment]
> Do I need to build from source? No cmakelists.txt for use with make.

Building from source is not necessary. Judging from your comments I would have to say that you may have downloaded the wrong release package. I confirmed that the linux 64 binaries are correct. 

If you download the latest binary directly
```
wget https://github.com/exercism/cli/releases/download/v3.0.6/exercism-linux-64bit.tgz
```
Then view the contents of the tarball `tar tvzf exercism-linux-64bit.tgz` you should see something like the following:
```
drwxr-xr-x kytrinyx/staff    0 2018-07-26 19:37 shell/
-rw-r--r-- kytrinyx/staff 1938 2018-07-26 19:37 shell/exercism_completion.bash
-rw-r--r-- kytrinyx/staff 1091 2018-07-26 19:37 shell/README.md
-rw-r--r-- kytrinyx/staff 1543 2018-07-14 06:55 shell/exercism_completion.zsh
-rwxr-xr-x kytrinyx/staff 8435680 2018-07-26 20:27 ./exercism
```

As for the permission denied error please confirm that you are trying to move the file to your home bin directory and not the system bin directory. If you have the correct directory you should confirm that you have write permission into your own bin directory. Which you can fix with chmod if the directory is owned by you. 

I don't want to give exact instructions without seeing any output. If you need assistance verifying permissions please post the contents of the command `stat ~/bin` removing your username.

**Comment by BigslimVdub** [comment]
My error. I was trying to move to ~/bin not ~/home/user/bin. I retried and it worked properly. Install instructions noted to move to ~/bin not ~/home/user/bin. 

Works great now, thanks!
