### ISSUE TITLE
Error: Patch ___ EOF while submitting

### ISSUE THREAD

**Issue by ianloh** [exercism/cli#691]
Hi,

Am unable to submit exercises, e.g. while attempting to submit the first Go track exercise (Hello, World), I get:
```
╰─ exercism submit ~/Exercism/go/hello-world/hello_world.go
Error: Patch https://api.exercism.io/v1/solutions/683aa7c6c0d145e1aaaa01c0baf9f36b: EOF
```

Troubleshoot's output:
```
╰─ exercism troubleshoot

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.6
Latest:  3.0.6


Operating System
----------------
OS:           darwin
Architecture: amd64


Configuration
----------------
Home:      /Users/xyz
Workspace: /Users/xyz/Exercism
Config:    /Users/xyz/.config/exercism
API key:   8dfb*****************************ac6

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 309.44123ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 1.436495577s
```

Help appreciated. Thanks!

**Comment by nywilken** [comment]
@ianloh quickly looking at the provided error message it looks like encountered an issue communicating with the Exercism server when trying to submit your solution. Have your tried submitting the file again? 

If so can you include the verbose flag `exercism submit -v ~/Exercism/go/hello-world/hello_world.go`

Please make sure to remove any token information (line beginning with Authorization:) before posting any output.

**Comment by ianloh** [comment]
Here's the output with the verbose flag:
```
╰─ exercism submit -v ~/Exercism/go/hello-world/hello_world.go

========================= BEGIN DumpRequest =========================
PATCH /v1/solutions/683aa7c6c0d145e1aaaa01c0baf9f36b HTTP/1.1
Host: api.exercism.io
Authorization: Bearer *****
Content-Type: multipart/form-data; boundary=bb0ae524b51b3068f92b0886d261573ee884396a9f5168d6b91dbefa6dd0
User-Agent: github.com/exercism/cli v3.0.6 (darwin/amd64)

--bb0ae524b51b3068f92b0886d261573ee884396a9f5168d6b91dbefa6dd0
Content-Disposition: form-data; name="files[]"; filename="/hello_world.go"
Content-Type: application/octet-stream

// Package greeting implements a single simple Hello World example.
package greeting

// HelloWorld is the quintessential first function in Go.
// Only English is implemented.
func HelloWorld() string {
	return "Hello, World!"
}

--bb0ae524b51b3068f92b0886d261573ee884396a9f5168d6b91dbefa6dd0--

========================= END DumpRequest =========================

Error: Patch https://api.exercism.io/v1/solutions/683aa7c6c0d145e1aaaa01c0baf9f36b: EOF
```

Thanks!

**Comment by nywilken** [comment]
@ianloh thanks for this output. It looks like the request to the API is throwing and error, but I am not sure why yet. Oddly enough the response time for https://api.exercism.io/v1/ping seems to be very quick; faster than any response time I've seen. 

what is the response of ```curl https://api.exercism.io/v1/ping```?

**Comment by NobbZ** [comment]
> Oddly enough the response time for api.exercism.io/v1/ping seems to be very quick; faster than any response time I've seen.

Nearly one and a half second is quick? I do get response times from 200 to 300 milliseconds there. Meaning beeing ~5 to ~8 times faster...

**Comment by nywilken** [comment]
> Nearly one and a half second is quick? I do get response times from 200 to 300 milliseconds there. Meaning beeing ~5 to ~8 times faster...

@NobbZ good catch. I was reading it as ms. Too many numbers after that decimal 🤦‍♂️
@ianloh disregard that fast comment.

**Comment by ianloh** [comment]
When I `curl https://api.exercism.io/v1/ping`, I get
`{"status":{"website":true,"database":true}}%`

**Comment by nywilken** [comment]
@ianloh was there any progress made here?

**Comment by ianloh** [comment]
Hi Wilken,

Sorry, haven't tried it again since that last post. Will try it tomorrow!

Regards,
*Ian Loh*

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this one.

@ianloh if you continue to have issues, would you post back here and we can reopen it?
