### ISSUE TITLE
Automatically change directory after downloading an exercise

### ISSUE THREAD

**Issue by drwl** [exercism/cli#692]
I've been using the platform a lot recently, I really love it. I've tried searching through the issues to see if this was brought up before but it looks like it hasn't.

As a feature request, would it be possible to add a configuration option or a flag to automatically cd to the exercise directory after downloading it?

**Comment by NobbZ** [comment]
It's not, as we have no clue how we can alter the parents process working directory, but the download command is designed in a way, that you can do `cd $(exerercism download ...)` on Linux and Mac OS.

**Comment by kytrinyx** [comment]
Thanks @NobbZ 

@drwl out of curiosity, if we had added this information to the output of `exercism download -h` would you have discovered it?

I'm going to go ahead and close this.

**Comment by drwl** [comment]
Oh I didn't know you could do that. Yes, I would've discovered it if it was put in `download -h`.
