### ISSUE TITLE
Cannot download hello-world when track in beta - get "solution not found"?

### ISSUE THREAD

**Issue by macta** [exercism/cli#694]
The pharo track has been moved to "beta" mode in V2 exercism, but when you use the command line client you get an error 'solution not found' even though the configlet linter is fine locally and the config.json looks ok? 

e.g.
```
$exercism download -t pharo -e hello-world
Error: Solution not found
```
I would expect the configlet to fail if there was no solution - and there appears to be one that matches the config.json solution regex. So I'm stumped

**Comment by macta** [comment]
This got answered in the other forum for me - it was due to me not being registered in the track I was developing. However I think the cli gives a bad error message for this? It should say - not registered in track?

**Comment by kytrinyx** [comment]
This error message needs to be fixed in the API, as we're taking the message from the HTTP response.

**Comment by nywilken** [comment]
Closing as the issue has been resolved on the API. @kytrinyx if I am mistaken please feel free to reopen.
