### ISSUE TITLE
submit solution responds with missing metadata message

### ISSUE THREAD

**Issue by o1dnik** [exercism/cli#702]
I've migrated from v1 to v2 recently and discovered a completely new UI. The cli version is updated, for python task "Hello world" pytests pass ok, but `exercism submit $(pwd)/solution.py` replies with some default message:

```
Error:

    The exercise you are submitting doesn't have the necessary metadata.
    Please see https://exercism.io/cli-v1-to-v2 for instructions on how to fix it.
```

I can't find anything related to metadata, how it's built and try to debug by myself, so I'd raise this question to be directed correctly from here.
And some additional input:

```
➜  python exercism version
exercism version 3.0.6
➜  python pytest ./hello-world/hello_world_test.py
====================================================== test session starts =======================================================
platform darwin -- Python 3.6.5, pytest-3.7.1, py-1.5.4, pluggy-0.7.1
rootdir: /Users/o1dnik/Exercism/python, inifile:
collected 6 items

hello-world/hello_world_test.py ......                                                                                     [100%]

==================================================== 6 passed in 0.02 seconds ====================================================
```

**Comment by NobbZ** [comment]
From the link in the error message you quoted:

> The new website relies on a metadata file that the old website did not provide. If you don't have this file, you will not be able to submit the exercise.
>
> The easiest way to ensure that you have the file is to copy your old solution somewhere, call exercism download for the exercise again, and then copy your solution back in.
>
> `exercism download --exercise=THE_EXERCISE --track=THE_TRACK`
> Then you will be able call exercism submit with the solution file(s).
>
> `exercism submit path/to/file1 [path/to/file2 ...]`

**Comment by o1dnik** [comment]
Thanks @NobbZ   Well, I don't get the written text unfortunately. Already did download once, so it should have probably updated all tasks... or not. Anyway. here's the additional output:
```
➜  python exercism download --exercise=hello-world --track=python
Error: hello-world not within workspace
➜  python exercism download --exercise=hello_world --track=python
Error: Exercise not found
```

**Comment by o1dnik** [comment]
Since the issue is resolved, I'm closing the issue, but would appreciate any further comments regarding workspace definition and relative/absolute pathnames.

**Comment by kytrinyx** [comment]
@o1dnik There's a bug in the CLI with the paths. I've fixed it, but am waiting on a second fix that I need before I release a new client.

I would recommend running `exercism configure --show` to see what the current configuration is, and update that to be whatever you'd prefer it to be.

To get the directories sorted out, try moving the `hello-world` directory to `backup-hello-world` and `hello-world-2` to `hello-world`.

**Comment by sidharthoomman** [comment]
Since the issue is resolved, I'm closing the issue, but would appreciate any further comments regarding workspace definition and relative/absolute pathnames. -- How was it resolved? Can you please share?
