### ISSUE TITLE
Would it be possible for us to view exercise status through the CLI?

### ISSUE THREAD

**Issue by DamnedScholar** [exercism/cli#707]
In general, I think it would be useful for users to be able to use a command like `exercism view [--track=python]` and see a printout of the status of downloaded exercises (those that match folder names in the `Exorcism/` folder). In my specific use case, I use Atom and would be able to take a feature like that and use it to modify my editor's GUI to integrate information from the CLI.

**Comment by kytrinyx** [comment]
The short answer is: probably, but we don't have a timeline yet.

We have an open issue for this feature request: https://github.com/exercism/exercism/issues/4162

It's going to require some product design discussions before we decide how to implement it, and then we'll need to do work both in the API and the CLI to support it.

I'm closing this in favor of the issue in the exercism repo.
