### ISSUE TITLE
Add option to change to the downloaded directory

### ISSUE THREAD

**Issue by mawis** [exercism/cli#708]
I have a pattern, that repeats with every download of exercises or solutions I do:

* call `exercism download`
* copy the path it was downloaded to
* call `cd <that path>`

That's very frustrating repetition. Wouldn't it be possible to add an option to exercism to change to the directory where the solution was downloaded to automatically? Maybe even as a default or configuration option.

**Comment by NobbZ** [comment]
As a process can't change the working directory of its parent process, no that's not possible, but the output of the CLI is designed in a way that you can do `cd $(exercism download ...)` on most shells.

**Comment by mawis** [comment]
Oh sure, you're right. I didn't think of that.

I guess I have to write a wrapper shell script around `exercism` to implement that.
