### ISSUE TITLE
Can't install/use

### ISSUE THREAD

**Issue by amydpp** [exercism/cli#709]
I initially installed the CLI and tried to configure but kept getting the 'incorrect usage', then I tried to redownload it. And got the following error

![exercismerror](https://user-images.githubusercontent.com/181626/44412467-032f0e80-a537-11e8-8039-321460034e02.PNG)

![exercismerror2](https://user-images.githubusercontent.com/181626/44412477-0f1ad080-a537-11e8-930d-f3a4ae4f85b2.PNG)

I've tried Windows 64 and 32 bit

Any ideas?

**Comment by NobbZ** [comment]
Please remove the version installed by chocolatey completely and then follow the tutorial to do a fresh windows install.

**Comment by amydpp** [comment]
I deleted the files...not sure what else I should do. After deletion tried a fresh install, got the same message.

**Comment by NobbZ** [comment]
You obviously haven't deleted those files, or windows would tell you that it can't find the executable.

Please use chocolatey to uninstall exercism and then check if the directory mentioned in the error message is empty or even better does not exist at all.

**Comment by NobbZ** [comment]
A screenshot that shows that the executable under the path mentioned by the error message does not exist.

Also I want a screenshot that shows that there is no exercism executable left in chocos shim directory.

Also please show the output of `where exercism` from a terminal.

**Comment by amydpp** [comment]
where exercism did it. 

Thank you. 

Once I deleted it all, I was able to reinstall.

**Comment by kytrinyx** [comment]
Glad you got it sorted!
