### ISSUE TITLE
Set new workspace directory on linux

### ISSUE THREAD

**Issue by bippum** [exercism/cli#710]
I would like to use Exercism with Ubuntu CLI on Windows. Unfortunately, modifying any Linux files with a Windows program will cause a cascade of errors. Could it be possible to change the directory in which Exercism operates? I already tried using the `--dir` option, but it seems to have been removed.

**Comment by NobbZ** [comment]
It's `--workspace` now. `exercusm configure --workspace=/foo`.

But we experienced problems in the past using the Linux CLI under WSL. Please make sure that both windows and WSL and the Linux inside are up to date before trying.

**Comment by bippum** [comment]
Thanks for the pointer. Mine seems to be working fine, as long as I only modify files from outside the linux enviornment within `/mnt/c/...` .
