### ISSUE TITLE
Install CLI with Win 7 and behind proxy

### ISSUE THREAD

**Issue by iainism** [exercism/cli#714]
Hi, I have Windows 7 (Version 6.1.7601, 64 Bit), and I am behind a proxy, so the Exercism CLI installer doesn't work, and also the folder structure anticipated by the manual walkthrough ( https://exercism.io/cli-walkthrough ) doesn't exist, since the walkthrough assumes Windows 10 is being used.  Is there an 'older' manual instruction somewhere that I can use please?  Even better, can the Exercism CLI installer be configured to work with a web-proxy?

Thanks!

**Comment by NobbZ** [comment]
Windows 7 has reached its end of life, it's support by Microsoft has been reduced to a bare minimum. I'm not even sure if the binary is runnable on such a system 

If you insist on keeping your dated operating system you need to infer the steps necessary to install on your own, but you will probably not get any guarantees.

But because of the proxy, please file an issue at the repository of the installer.

**Comment by iainism** [comment]
"Windows 7 has reached its end of life"

Windows 7 is being supported by Microsoft until January 2020, so end-of-life is in 16 months time.  It would seem premature to drop support for Win 7 now given that [there are still far more Win 7 users out there than Win 10 users](https://www.computerworld.com/article/3199373/windows-pcs/windows-by-the-numbers-windows-10s-growth-continues.html)

**Comment by NobbZ** [comment]
Thats when the extended supports end, which is near to use less for regular customers that don't pay the extended bills…

Everything not in mainstream support is dead for me.

Still, it seems as if there was no copy of Win 7 available when writing the tutorials, so you need to find the differences and either ask questions how to work around that difference or find out yourself how to do so (and hopefully report the solution here).

But as far as I can tell from glancing over the [installers source repository](https://github.com/exercism/windows-installer), they are only using default HTTP components which again should pick up the proxy on their own if it is set up properly in the operating systems settings (ie IE works).

Still I think the manual installation and setting environment variables `http_proxy` and `https_proxy` correctly for the CLI to work properly is the approach to go, as if you are behind a proxy, you probably do not have administrative rights on your computer as you are propably in a corporate network. In general, if my assumption is true, you should ask your IT department to install/deploy exercism on your machine.

**Comment by iainism** [comment]
"Everything not in mainstream support is dead for me."

So over 63% of Windows users globally (see previous link) aren't relevant to Exercism?

Thanks for letting us know where we stand.

**Comment by NobbZ** [comment]
That's just a personal opinion and might not be what exercism is actually thinking. It's always as I understood Microsoft's support cycles.

But still, there is the point that probably no win7 copy was available (which is a realistic point) when the tutorial where written and it was just assumed that it will work similarly for older versions.

So unless you can't point to the differences we can't change anything, because we simply do not know where to change.

**Comment by kytrinyx** [comment]
> But still, there is the point that probably no win7 copy was available (which is a realistic point) when the tutorial where written

This is the situation we are in. We can support other versions, but we don't have the resources to support older versions until (a) we know that it's necessary, and (b) we can get help figuring out what needs to change.

> can the Exercism CLI installer be configured to work with a web-proxy?

Maybe! @rpottsoh how hard would it be to support this?

If that doesn't work out, then we would greatly appreciate it if you have the bandwidth to help us figure out the details of how we would explain installing for Windows 7!

**Comment by rpottsoh** [comment]
I am not sure how to deal with a proxy server.  I never have had to and have no way to test.  I have quickly scanned the comments above and I am left wondering if the CLI ill work behind the proxy?  If the CLI won't work I don't see much point in looking into this in regards to the Installer.

@iainism  have you downloaded the [latest](https://github.com/exercism/cli/releases/latest) version of the CLI (v3.0.8 at the time of this writing)?  

1. Please do so and unzip it to a folder of your choosing.
1. Open a CMD prompt.
1. CD to the folder where you unzipped the CLI.
1. Execute `exercism troubleshoot`
1. Report back to this issue what is reported by the CLI.

I have Windows 7 on my work computer, so if you are needing help to manually install the CLI I should be able to help.  If you perform the steps above about the only thing you need to complete is adding the folder, where you placed the CLI, to your PATH.  The CLI would need to be configured.  If you follow the Windows 10 walk through instructions it will eventually get to configuring the CLI,, just answer affirmatively to the Windows 10 specific steps.

At this point I don't think there is anything I can do about the Proxy.  The Windows Installer works fine in Windows 7.  I test it on my W7 and W10 systems before every release.  It is how your computer is connected to the internet that is the issue we are working with.

**Comment by rpottsoh** [comment]
> But as far as I can tell from glancing over the installers source repository, they are only using default HTTP components which again should pick up the proxy on their own if it is set up properly in the operating systems settings (ie IE works).

@NobbZ  this is correct.  Which makes it difficult from my perspective to do anything.

**Comment by nywilken** [comment]
@iainism is this issue safe to close? Or are you still encountering issues? 

To confirm the CLI will honor any proxy settings defined by the system as long as HTTP_PROXY is configured on the system.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this. If you're still having trouble, please don't hesitate to add more details here!
