### ISSUE TITLE
Configuring the CLI

### ISSUE THREAD

**Issue by exlibrischimex** [exercism/cli#726]
i have an issue configuring exercism on command line error message token not recognized.

**Comment by nywilken** [comment]
@exlibrischimex can you provide the version of the exercism cli you are running `exercism version`. 

Also please provide the command you are running minus your token.

**Comment by nywilken** [comment]
@exlibrischimex are you still having issues? Otherwise, I will mark this issue as closed.

**Comment by nywilken** [comment]
Closing this issue for now. @exlibrischimex feel free to re-open if you are still having issues.
