### ISSUE TITLE
Running exercism in Ubuntu 16.04

### ISSUE THREAD

**Issue by yehia67** [exercism/cli#731]
hey, I have a problem installing  exercism-linux-64bit.tgz . I make the same steps as the walk-thought but it keep give me "Command not found". After running this command `tar -xf exercism-linux-64bit.tgz` I have one executable file and shell folder. Then I wrote this commands.
![screenshot from 2018-09-06 01-08-26](https://user-images.githubusercontent.com/21314724/45126020-8aa09280-b171-11e8-9aab-d4602c8980a0.png)
And then make next step export path..etc  and make configurations but when I just close the terminal and open it again and write exercism it output "Command not found".

**Comment by nywilken** [comment]
@yehia67 did you confirm that ~/bin is in your PATH? You can echo $PATH to see the full path, if your local bin directory is not in your PATH you should add it to your local bashrc or zshrc. You can find instructions here on how to make PATH changes persist  
https://superuser.com/questions/595818/add-usr-local-sbin-to-the-path-of-a-user

If you modified your rc file already please check that there are no typos in your PATH variable.

**Comment by yehia67** [comment]
the output of my PATH is: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
should it be like : $PATH:" == *":$HOME/bin: ??

**Comment by nywilken** [comment]
In your shell configuration file you should append `:$HOME/bin` to your PATH variable. It should look something similar to  `export PATH=$PATH:$HOME/bin/`

Please note that your PATH variable may vary from what I put above, but if you append `:$HOME/bin` to it and reload your shell it should resolve your issue.

**Comment by yehia67** [comment]
Okay thank you it work

**Comment by ric2b** [comment]
If anyone finds this while having trouble running exercism, I created a snap for it so you can simply run `sudo snap install exercism`, as mentioned in https://github.com/exercism/cli/issues/757#issuecomment-515411178. 

Snap comes pre-installed with Ubuntu, it's a package manager for sandboxed applications and it auto-updates your installed snap packages (applications)

**Comment by NobbZ** [comment]
If it is sandboxed, how well does it work with writing into the users folder to download exercises and persist its configuration?

**Comment by ric2b** [comment]
Snap allows you to request permissions that your application needs to work. 
In this case I'm requesting access to the home directory and removable media, as you can see in the [build file](https://github.com/ric2b/exercism-snap/blob/master/snapcraft.yaml), the `plugs` line.

The user can decide what permissions to allow or deny (home directory access is on by default because it's very common)
