### ISSUE TITLE
dial tcp: lookup api.github.com on 127.0.2.1:53: server misbehaving

### ISSUE THREAD

**Issue by AlexLeSang** [exercism/cli#733]
Command:
exercism -v upgrade

Error message:
Error: Get https://api.github.com/repos/exercism/cli/releases/latest: dial tcp: lookup api.github.com on 127.0.2.1:53: server misbehaving

exercism version 3.0.6

**Comment by NobbZ** [comment]
Quick shot: You are using a local DNS proxy, cache or something, which does some weird stuff.

**Comment by AlexLeSang** [comment]
I'll look into this, thank you for the tip

**Comment by AlexLeSang** [comment]
Problem was with my dns settings
