### ISSUE TITLE
Installing the CLI with the installer for windows, it removes user-defined path's in the environment variables

### ISSUE THREAD

**Issue by hp-e** [exercism/cli#740]
Hi

When I installed the exercism cli on my windows machine today, it removed all the user-defined paths in the environment variables, it should append the exerxism to the list and not replacing the list.

I used the installer from the website (Delphi...?)

hp

**Comment by NobbZ** [comment]
Could you please re-open in https://github.com/exercism/windows-installer?

cc: @exercism/windows-installer

**Comment by hp-e** [comment]
Thanks, I will do that @NobbZ
