### ISSUE TITLE
Error installing Exercism

### ISSUE THREAD

**Issue by CazaBelle** [exercism/cli#741]
Homebrew is installed but when I run code to install exercism I get the following error: 

Error: /usr/local/Cellar is not writable. You should change the
ownership and permissions of /usr/local/Cellar back to your
user account:
  sudo chown -R $(whoami) /usr/local/Cellar

I'm an admin on the computer but still get used to command line preferences. Any help would be much appreciated!

Cheers!

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, as it seems specific to Homebrew.

If you are still stuck after trying the above troubleshooting, holler and we'll see if we can help you get unstuck.

**Comment by CazaBelle** [comment]
@nywilken Many thanks for your advice I managed to get it installed :)
