### ISSUE TITLE
cannot submit solutions 

### ISSUE THREAD

**Issue by hannahsohyoungkim** [exercism/cli#743]
I can't submit solutions. It says "No files found to submit." I did this: exercism download --exercise=hello-world --track=ruby. When I check the directory it lists out my file hello_world.rb but when I try to submit it it says there are no files found. 

> Administrators-MacBook-Pro-2:hello-world hannahkim$ ls
GETTING_STARTED.md	hello_world.rb
README.md		hello_world_test.rb
Administrators-MacBook-Pro-2:hello-world hannahkim$ exercism submit
Error: 

    No files found to submit.

**Comment by kotp** [comment]
What is the command that you used to submit it?

**Comment by kotp** [comment]
And what does `exercism troubleshoot` give you?

**Comment by hannahsohyoungkim** [comment]
I used exercism submit hello_world.rb
I made sure I was in the right folder (hello-world) and that the file was in the directory 


Troubleshooting Information
===========================

Version
----------------
Current: 3.0.9
Latest:  3.0.9


Operating System
----------------
OS:           darwin
Architecture: amd64


Configuration
----------------
Home:      /Users/hannahkim
Workspace: /Users/hannahkim/Exercism
Config:    /Users/hannahkim/.config/exercism
API key:   79c2*****************************a8a

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 109.845342ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 708.528298ms

**Comment by kytrinyx** [comment]
@hannahsohyoungkim Would you try this?

```
exercism submit hello_world.rb
```

I think we need to improve that error message!

**Comment by kotp** [comment]
Hmm... 

> I used exercism submit hello_world.rb
I made sure I was in the right folder (hello-world) and that the file was in the directory

That is indeed puzzling.  Any ideas @kytrinyx ?

**Comment by nywilken** [comment]
@hannahsohyoungkim are you still encountering issues when trying to submit?

**Comment by nywilken** [comment]
@hannahsohyoungkim I am going to close this issue. If you are still having issues please feel free to reopen an issue with the following information: 

- CLI troubleshoot output
- Your workspace path
- Full path to the exercise that you are having trouble submitting.

**Comment by kotp** [comment]
There is nothing to do, if there are no changes.  If you make changes, then it should submit.
