### ISSUE TITLE
cannot use make on C track on WSL

### ISSUE THREAD

**Issue by SeabassW** [exercism/cli#745]
I cannot use the command "make test" at the hello-world exercise in the C track. 
I've run the setup correctly for WSL and I can execute Exercism. I've checked that I'm using the right distribution. 

This is the result from running "make test":
`seabass@ForBash:/mnt/f/exercism/c/hello-world$ make test
Compiling tests.out
make: cc: Command not found
makefile:24: recipe for target 'tests.out' failed
make: *** [tests.out] Error 127`

For extra information, this is the output from exercism debug:

Troubleshooting Information

Version:
Current: 3.0.9
Latest:  3.0.9

Operating System:
OS:           linux
Architecture: amd64

Configuration:
Home:      /home/seabass
Workspace: /mnt/f/exercism
Config:    /home/seabass/.config/exercism
API key:   **nope**

API Reachability:

GitHub:
    * https://api.github.com
    * [connected]
    * 97.417ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 96.35ms

**Comment by nywilken** [comment]
@SeabassW this issue has more to due with your environment missing the the c compiler `cc`. If you jump onto the Exercism support channel on Gitter (https://gitter.im/exercism/support) they can help you out, if you are still having issues
