### ISSUE TITLE
Trying to install on rPi 3 and getting "cannot execute binary file: exec format error"

### ISSUE THREAD

**Issue by khanonfodder** [exercism/cli#747]
Is it possible to install exercism on a Raspberry Pi? I dloaded the ARMv8 tarball and extracted it, but am getting an error that sounds like it's not compiled for my arch. I did double check the file and it comes up as an ARM compiled file.

**Comment by kytrinyx** [comment]
The ARMv* builds are intended for Raspberry Pi, but if it's working then we're likely missing something for your particular build. Do you know exactly what architecture you have?

**Comment by Smarticles101** [comment]
@khanonfodder you should be able to run `cat /proc/cpuinfo` to view your cpu information which includes cpu architecture :)

**Comment by Smarticles101** [comment]
@exercism/cli are we able to close this now? Thanks :)

**Comment by kytrinyx** [comment]
Yepp, good call. Thanks!
