### ISSUE TITLE
Distribute via snap

### ISSUE THREAD

**Issue by SpainTrain** [exercism/cli#757]
To further reduce friction while getting started with Exercism (and other benefits like auto-update), it would be great to distribute via snap (https://docs.snapcraft.io/go-applications/7818).  Snapcraft provides automated build & publish via Github (https://snapcraft.io/build), so this may be as straightforward as creating the `snapcraft.yaml` file.

**Comment by NobbZ** [comment]
I only skimmed the link, and to me it appears as if go needs to be installed on the computer? If so, I think we should avoid it, as this would make it necessary for the student to install a languages toolchain (s)he'll never use again after installing the CLI tool.

Also who should give support when a student is unable to install the CLI because of problems with setting up go or snap? This would put a lot of burden to those who give voluntarily support in the gitter channel, of which only one uses golang at all.

**Comment by SpainTrain** [comment]
Sorry, those are directions for creating a snap, not installing one.  More context from the homepage - "Snaps work across many distributions and versions of Linux. Bundle your dependencies and config, simplifying installs to a single standard command."

The directions for students would be `sudo snap install exercism`.  This works across all popular Linux distros - https://docs.snapcraft.io/installing-snapd/6735

Regarding support, `snapd` comes installed with Ubuntu 16 and 18 and is available via OS package manager in the distros linked above.  This should redeuc support burden as it is simpler to type `sudo snap install exercism` than go to releases page, choose the correct tarball, untar, and copy to a directory in the `PATH`.  Support should be further reduced by the auto-update feature (snap users would automatically receive new app version).  I have not been in the gitter, but I assume (as happens commonly in other projects) that folks often ask about issues that have been fixed but they just haven't updated their app.

I understand scarcity of time, so I would happily create a PR for the `snapcraft.yaml`, but I do not think this would add burden to students or maintainers and ought to reduce the burdens on both.

**Comment by NobbZ** [comment]
> `sudo snap install exercism`

I have a very strickt opinion about 3rd party package managers that require `sudo`. I have often had the "luck" that they messed up those folders that are owned by the systems original package managers, leading to ownership conflicts. 

Aside of that, `exercism` itself shall not require `sudo` at any point in its lifecycle, such that it can be installed by unpriviliged users without the necessity to ask their IT department.

**Comment by SpainTrain** [comment]
Perhaps you are conflating *dependency* managers with *package* managers.  Every popular package manager - apt, yum, portage/emerge, ports, ... - requires superuser privileges for package installation.  I agree that *dependency* managers ought not be run as root.  Regarding being "3rd party", I mentioned above that `snapd` is installed by default in all Ubuntu versions since 16.04.  In fact, Canonical *runs* snapcraft.io and helps maintain snapd.  Further, one of the fundamental design principles of snaps is that they are completely self contained and thus do not interrupt the system on which they are installed[1][2].

"such that it can be installed by unpriviliged users" - that option *already exists* and providing more convenient installation options for users who are not under this very specific constraint does not preclude continuing to offer tarballs.  _**Many**_ projects offer installation manually *and* via package manager.

I am just going to close this because you appear to be predisposed to rejecting this based on conjecture rather than facts.  If others are interested in a snap, they can comment and I will reopen.

[1] https://docs.snapcraft.io/the-system-snap-directory/2817
[2] https://docs.snapcraft.io/the-snap-format/698

**Comment by nywilken** [comment]
@SpainTrain thanks for your interest in wanting to grow the distribution for the Exercism command-line client. As @Nobbz has pointed out installation via snap is not something we are looking to support at this time. The focus is on growing the features of the cli to work with Exercism v2. If things should change in the future we can definetly revisit. 


With that being said, do you mind sharing what issues you ran into when getting started with Exercism “To further reduce friction while getting started with Exercism (and other benefits like auto-update)” in the repo [exercism/exercism](https://github.com/exercism/exercism)

**Comment by ekingery** [comment]
First off, thanks for everyone's work on exercism, it's an excellent project!

I found this issue while looking for a snap for the exercism CLI. I immediately went to look for a snap when I saw that the linux installation instructions included downloading a tarball. If one of your project goals is to make the CLI install process quick and easy for beginners and more palatable for experienced users, in my opinion you'll want to provide a snap and/or a Flatpak(https://flatpak.org). At which point, as @SpainTrain pointed out, the primary linux install instructions could be simplified to `sudo snap install exercism`. No more writing [help articles on figuring out your processor architecture](https://exercism.io/cli-walkthrough) and discussing the [width of CPU registers](https://github.com/exercism/cli/issues/700). I do realize there are other considerations, such as people who don't have sudo access, are not using a distro that supports snaps by default, etc. You may not be able to completely eliminate the build / distribution pains immediately, but providing a snap should make things far simpler and easier for the vast majority of linux users.

Two additional supporting points: As an experienced linux user, it took me 20 commands to get a feel for the installation and get the CLI up and running (see below). Also, as you can see below, the current tarball is a [mini tarbomb](http://www.linfo.org/tarbomb.html), which you might consider fixing if you continue with the .tgz distribution method as primary. Thanks for your consideration!

```
29999  cd ~/Downloads/
30000  mv exercism-linux-64bit.tgz ~/opt
30001  cd ~/opt
30002  tar -xzvf exercism-linux-64bit.tgz 
30003  rm -rf shell/ ./exercism
30004  mkdir exercism
30005  cd exercism
30006  mv ../exercism-linux-64bit.tgz .
30007  tar -xzvf exercism-linux-64bit.tgz 
30008  ls -al
30009  file exercism
30010  ./exercism 
30011  ls -al
30012  ls shell/
30013  cat shell/README.md 
30014  ls -al
30015  mv exercism ~/bin
30016 rm -rf ~/opt/exercism
30017  cd ~/tmp
30018  exercism help
```

**Comment by ric2b** [comment]
So I went ahead and created a snap for exercism, currently for version 3.0.12.

I don't use exercism much so feel free to ping me when there's a new version, as I'll probably miss it.

Building it is super easy since it's just extracting the tarball into the container, as you can see by the [snapcraft.yaml](https://github.com/ric2b/exercism-snap/blob/master/snapcraft.yaml)

**Comment by ekingery** [comment]
Thanks so much, @ric2b! Works like a charm. Single command install, one more for config and we're off and running on Ubuntu.

**Comment by slikts** [comment]
Why isn't the snap mentioned in the install instructions? Currently the instructions are unfriendly for a learning tool.

Also, why is the exercism snap version "SNAPSHOT-ba48dcd" instead of the actual version? That makes it unclear if it's out of date.

**Comment by ekingery** [comment]
> Why isn't the snap mentioned in the install instructions? Currently the instructions are unfriendly for a learning tool.

We have hit some snags getting the documentation updated, but it is on the way / in progress. See:
 * https://github.com/exercism/interactive-cli-walkthrough/pull/83
 * https://github.com/exercism/interactive-cli-walkthrough/pull/85
 * https://github.com/exercism/website-copy/pull/1348
 * https://github.com/exercism/website-copy/pull/1362

> Also, why is the exercism snap version "SNAPSHOT-ba48dcd" instead of the actual version? That makes it unclear if it's out of date.

This was due to a one-time issue with having built the release before the new GoReleaser config / code was actually merged to master. All future releases should have the proper snap version.
