### ISSUE TITLE
Add completion for fish shell

### ISSUE THREAD

**Issue by hellow554** [exercism/cli#758]
I'd like to see a completion for the [fish shell](https://fishshell.com/)

**Comment by kytrinyx** [comment]
Agreed, that would be lovely.
See https://github.com/exercism/cli/issues/666 for reference to the Cobra documentation for completion scripts.

**Comment by olingern** [comment]
@kytrinyx I think this can be closed a la #763

**Comment by kytrinyx** [comment]
Agreed! Thanks so much :-)
