### ISSUE TITLE
Problem with submit solution

### ISSUE THREAD

**Issue by mikym7** [exercism/cli#765]
Hi,
I wrote HelloWorld in go. I've just create a path where I put my file HelloWorld.go and from the root where is installed exercism I run the following command:
exercism submit C:\Exercism\project\directory\go\helloworld\HelloWorld.go
but It says:
Error: FindFirstFile C:\Users\...\Exercism: The system cannot find the file specified.

Do you have any suggestion?
Thanks a lot

**Comment by NobbZ** [comment]
Make sure you leave the files where the were downloaded to, do not move them around.

Your error message sugests, that you try to solve your exercises somewhere in `C:\Exercism` but the CLI expects them in `C:\Users\…\Exercism`

**Comment by mikym7** [comment]
Thanks, I've created a directory where exercism says so and now It's ok.
Subsequently I tried to send the exercise with:
exercism submit /path/to/file (with the new path ;) )
but I'm having another error:
    The exercise you are submitting doesn't have the necessary metadata.
    Please see https://exercism.io/cli-v1-to-v2 for instructions on how to fix it.
Need I to create manually the metadata file?

Thanks

**Comment by NobbZ** [comment]
No, it should have been created on downloading the exercise when done by using the CLI

**Comment by Smarticles101** [comment]
@exercism/cli can we close this now? Thanks :)

**Comment by kytrinyx** [comment]
Thanks, yes, I think it's good to be closed.
