### ISSUE TITLE
Add support for Termux

### ISSUE THREAD

**Issue by TaylorBeeston** [exercism/cli#767]
Every time I try and configure using Termux on my phone, I receive the following error:

`Error: The base API URL 'https://api.exercism.io/v1' cannot be reached.

Get https://api.exercism.io/v1/ping: dial tcp: lookup api.exercism.io on [::1]:53: read udp [::1]:35420->[::1]:53: read: connection refused`

**Comment by NobbZ** [comment]
This is a bug in the go runtime. The only way to get termux supported is to compile on the devices.

As there are only 2 or 3 people per year asking for termux support we can not expect the maintainers of the CLI to go through this or even buy devices they currently do not own.

If you really need to to exercism on your Android device, you need to build the CLI yourself as described in the CLIs contribution guide.

Another possibility were to install it on your computer and SSH into it.

**Comment by TaylorBeeston** [comment]
No worries! I figured it would involve something like that considering it wasnt written for an ARM architecture
