### ISSUE TITLE
Encourage improvement after submission

### ISSUE THREAD

**Issue by dpashkevich** [exercism/cli#77]
The `README` for the beer song exercise has an important section that reminds people of the end purpose of all the exercises:

```
## For bonus points

Did you get the tests passing and the code clean? If you want to, these are some additional things you could try:

* Remove as much duplication as you possibly can.
* Optimize for readability, even if it means introducing duplication.
* If you've removed all the duplication, do you have a lot of conditionals? Try replacing the conditionals with polymorphism, if it applies in this language. How readable is it?

Then please share your thoughts in a comment on the submission. Did this experiment make the code better? Worse? Did you learn anything from it?
```

Why not print it in the CLI tool after the user submits his next exercise?

**Comment by eToThePiIPower** [comment]
Is anyone still interested in this issue? I was directed here from 24pullrequests and this sounds like a good place to start out.

**Comment by kytrinyx** [comment]
Yeah, definitely still interested in this one. Up for grabs if you want it.

**Comment by eToThePiIPower** [comment]
Great. I've got a preliminary version done. For the moment I thought it'd be best to only show it on the first iteration for each exercise (to keep down the annoyance factor), and hard-wrapped the lines to 80 characters.

Still working on a rotation/randomization scheme to keep some variety as you suggested. I think randomization will be easier to implement without having to keep track of the state somewhere.

**Comment by kytrinyx** [comment]
Yeah, I think you're right -- we don't need to show it on subsequent iterations.

**Comment by eToThePiIPower** [comment]
So I've got a simple random rotation going on the "header" to provide some variety (per your suggestion for adding variety). Currently:
* For bonus points
* Don't stop now: The fun's just begun
* Some tips to continue

It should be easy to add more (suggestions for creative phrases would be appreciated)

With enough of a selection of creative header phrases, I feel this would be enough variation. Randomizing the whole tips probably wouldn't be worth the extra complexity, at least at this point.

**Comment by kytrinyx** [comment]
Agreed--let's start with this and see how it feels in action.

**Comment by Tonkpils** [comment]
Going to close this since #262 was merged
