### ISSUE TITLE
Download is not working

### ISSUE THREAD

**Issue by dmateobuitrago** [exercism/cli#772]
Hi,

When I try to download a excercise nothing happens.

I run
`exercism download --exercise=hello-world --track=python`

And I get
 
```
Downloaded to
/Users/dmateobuitrago/Exercism/python/hello-world
```

But nothing happens, no directory nor files are created.

**Comment by NobbZ** [comment]
I have never seen such a behaviour.

Can you please provide the full transcript (minus your API key) of the following commands?

```
exercism troubleshoot
exercism workspace
exercism download --exercise=hello-world --track=python
ls -lhd $(exercism workspace)
ls -lhd $(exercism workspace)/python
ls -lhd $(exercism workspace)/python/hello-world
```

**Comment by NobbZ** [comment]
This feels weird. Can you reproduce this behaviour when using 3.0.10 or 3.0.9?

**Comment by dmateobuitrago** [comment]
How can I downgrade?

**Comment by NobbZ** [comment]
Basically following the manual installation instructions but using an older release.

**Comment by dmateobuitrago** [comment]
I'm not sure how to do that. I installed the latest version with brew

**Comment by dmateobuitrago** [comment]
Sorry NoobZ, I was looking to the wrong directory. Thanks for your help

**Comment by NobbZ** [comment]
How could any of the commands show you the wrong directory?

The correct location is even printed out in the success message.

**Comment by dmateobuitrago** [comment]
I thought I was supposed to create the directory, so I did it in a similar
path, so I assumed it was the one I created.

**Comment by NobbZ** [comment]
Can you explain what made you think that? Do you have an idea how that sentence could have been formulated for less chance of missunderstanding?

**Comment by dmateobuitrago** [comment]
The thing is that with any kind of project I'm used to create a directory
and then run the commands there. I expected that the workspace would be
created there, but to be honest I don't remember where I exactly I run the
commands.

Also I'm not used to read all the messages on the Terminal, when I saw "API
key", "Token", I usually ignore the message (This after setting the token)
*+++*

*Mateo Buitrago Jara*

buitragojara.com <http://bit.ly/2I8vZME>
*m: *(34) 644 83 97 25

*linkedin <http://bit.ly/2KtNk0M>*

**Comment by NobbZ** [comment]
I'm also not used to read the messages ;) But if I'm asked to, or if I have a new tool, or if it doesn't do as I expected it, I take a closer look.

Messages in general are printed to be read, not to be ignored.

**Comment by kytrinyx** [comment]
I'm glad you got it sorted; @NobbZ Thanks for helping work through this.
