### ISSUE TITLE
CLI Isn't Being Recognized (Command Not Found)

### ISSUE THREAD

**Issue by brianboros7** [exercism/cli#789]
You'll see in my one screenshot of the terminal tha tthe CLI downloaded and installed correctly. But when I go to use the command dotnet test, you'll see in my VSC's terminal that it says command not found. Do you have any idea what is going on here? 

<img width="1680" alt="screen shot 2019-01-08 at 9 07 13 pm" src="https://user-images.githubusercontent.com/36462816/50874396-7d96e880-1389-11e9-8173-1861c0c5ec3d.png">
<img width="1680" alt="screen shot 2019-01-08 at 9 07 08 pm" src="https://user-images.githubusercontent.com/36462816/50874429-9acbb700-1389-11e9-899b-b75b556c9e38.png">

**Comment by jdsutherland** [comment]
@brianboros7 it seems like there might be some confusion regarding the relation to `exercism` CLI. Running `dotnet` in the shell is orthogonal (has no relation) to `exercism` (the error is from `dotnet`). Apparently `dotnet` is not in your path. I'd suggest consulting `dotnet` installation instructions.

**Comment by brianboros7** [comment]
Thank you, I'll give it a try.

**Comment by brianboros7** [comment]
I'm curious, why do they have us intal their CLI, and what not, if it has no relation and they want us to run a dotnet command and don't tell us we still need to install netCore?

**Comment by brianboros7** [comment]
Ok, so as I'm getting started with C#, and installing dotnet, using C#, everytime I start a project I need to ceate a new myApp directory? Never did thins with C#. and then the sln and libraries etc.? And with Exercism, I have the Hello-World directory already created and installed and do I createa new myApp directory within there? I'm thinking how do I work on the files in Hello-World if I ahve another directory with dotnet use.... thank you a ton BTW.

**Comment by jdsutherland** [comment]
No, just follow the instructions. You don't have to manually create directories or move things around - the download command gets everything.

**Comment by jdsutherland** [comment]
Assuming it is installed correctly, you probably have to start a new bash instance. Open a new terminal window and try again (or restart vscode).

**Comment by AntHass** [comment]
I have a similar problem but I don't understand any of the advice above. Can someone tell me where I'm going wrong, or what I should be doing?

I used the basic Windows command line terminal (Run "CMD" from Windows menu) to follow the instructions in the Exercism 'walkthrough' and it seemed to work ok.

The 'dotnet test' command is not found - so does that mean that the dotnet sdk is not installed? I've got as far as visiting https://dotnet.microsoft.com/download but I'm not sure what I need to download and install (I am running Windows 7 on a 32-bit system).

Any advice would be much appreciated!

**Comment by brianboros7** [comment]
You need to understand that Exercise has it's own system. You need to
download the C-sharp Packages for your operating system and don't expect
Exorcism to work without it. Download the C-sharp CLI and packages etc. I
did and it worked.

Brian S. Boros

(C):  219-671-0342

(w): http://briansboros.com/

(e): brian.boros7@gmail.com

<https://www.facebook.com/Brian-S-Boros-923097297803806/>
<https://twitter.com/briansboros>
<https://www.linkedin.com/in/brian-boros-020ba957>
<https://plus.google.com/u/0/%20brianborossocialentrepreneur/>

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this as it looks like the core issue is resolved.

@AntHass this is kind of irrelevant to the problem you're describing here, but I highly recommend the CodeNewbie community for figuring out what to do as you are learning programming. They're a wonderful community, very supportive, and they have lots of people learning all sorts of different things, so you'll almost certainly find people who are at a similar stage of learning as you are.
