### ISSUE TITLE
Submit only checks 400 when printing success (404 etc. unhandled)

### ISSUE THREAD

**Issue by jdsutherland** [exercism/cli#790]
Currently, submit only checks for 400 responses before printing a success message. 404s are silent and the resulting output misleadingly indicates that the submission was successful.

Mentioned in https://github.com/exercism/cli/pull/770#issuecomment-445709576.

**Comment by iHiD** [comment]
Hello @exercism/cli :) 

This has come up a couple of times recently. It's been suggested that this commit never got released. If that's so, could we release it? Is there anything else blocking that?

Thanks :)

**Comment by kytrinyx** [comment]
I'll do a release to day!

**Comment by iHiD** [comment]
(cc @Nobbz)
