### ISSUE TITLE
Can't download exercises.

### ISSUE THREAD

**Issue by kerpoople** [exercism/cli#798]
I'm putting in the following in the terminal:
**C:\Exercism>exercism download --exercise=robot-name --track=csharp**

And get the response:
**Downloaded to
C:\Users\Anna\Exercism\csharp\robot-name**

The exercises doesn't get downloaded. I have no files in my directory after download. 

I've created he folders Exercism and csharp to make sure they exist. I use the built in terminal in Visual Studio Code, but have also tried doing this in the CMD. Same issue is present in both cases. The same issue is present no matter what exercise i try to download.

**Comment by NobbZ** [comment]
Could you please show the output of the following?

```text
c:
cd \Users\Anna\Exercism\csharp\robot-name
dir
```

**Comment by NobbZ** [comment]
Also:

\cc @exercism/windows

**Comment by kerpoople** [comment]
Oh, I found the issue. Seems I have 2 folders named Exercism. The files got downloaded to the one I didn't see. Sorry to bother you! My mistake.

**Comment by rpottsoh** [comment]
@kerpoople if you execute `exercism configure` from the CMD prompt, whatever folder is listed as `Workspace:` is where the CLI will place exercises when your `download` them.  The CLI will create folders for you as needed.  Later, when you `submit` solutions, the file(s) you intend to submit should be located at the proper folder location for the exercise in question within the `Workspace`.

**Comment by kytrinyx** [comment]
It looks like this is sorted; closing!
