### ISSUE TITLE
Sub-dependency depending on an old version of fsevents?

### ISSUE THREAD

**Issue by sbrichards** [exercism/cli#800]
Hey folks. First off, thanks for making such a great product.

I'm hitting a bit of an issue when running `yarn` in an exercise directory. E.g.

```
$ exercism download --exercise=queen-attack --track=typescript

Downloaded to
/Users/samrichards/Exercism/typescript/queen-attack

$ cd typescript/queen-attack/
$ pwd
/Users/samrichards/Exercism/typescript/queen-attack

$ yarn
yarn install v1.9.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
warning Error running install script for optional dependency: "/Users/samrichards/Exercism/typescript/queen-attack/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments:
Directory: /Users/samrichards/Exercism/typescript/queen-attack/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.38
node-pre-gyp info using node@10.13.0 | darwin | x64
node-pre-gyp info check checked for \"/Users/samrichards/Exercism/typescript/queen-attack/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.13.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.13.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http Connection closed while downloading tarball file
...
a whole bunch more logs...
```

My node & yarn versions:
```
~/Exercism/typescript/queen-attack « git:(master)
$ node --version
v10.13.0

~/Exercism/typescript/queen-attack « git:(master)
$ yarn --version
1.9.4
```

I found [this yarn issue with fsevents](https://github.com/yarnpkg/yarn/issues/5962) and [this one](https://github.com/yarnpkg/yarn/issues/3926), which indicate it's a sub-dependency issue that relies on an older version of `fsevents`. 

Clearing out node_modules (`rm -rf node_modules/`) then running `yarn upgrade` solves the issue, but I'm wondering if there's a better upstream solution so I don't have to run that every time.

Thanks again!

**Comment by jdsutherland** [comment]
Hey Sam,

This issue seems related to https://github.com/exercism/typescript rather
than the CLI.

**Comment by sbrichards** [comment]
Got it. Opened https://github.com/exercism/typescript/issues/228 over there. Closing this one out.

**Comment by sbrichards** [comment]
Hey @jdsutherland - I believe I've fixed [the issue w/ the typescript repo](https://github.com/exercism/typescript/issues/228) but we're not sure how the release process works. How can we ship the fix? Thanks!

**Comment by jdsutherland** [comment]
@sbrichards I don't know how that works. I imagine either @nywilken or @kytrinyx are the go-to folks.

**Comment by NobbZ** [comment]
As soon as changes are deployed on the tracks master branch the website picks them up within minutes, no additional steps are involved, **but** as soon as you unlock an exercise it gets locked to the current HEAD of the tracks repository. You need to manually update the version through the website. Then redownload through the CLI.
