### ISSUE TITLE
How to submit?

### ISSUE THREAD

**Issue by chrismjx** [exercism/cli#801]
I am trying to go through the javascript track and I can't seem to figure out how to use the command line to submit my work. I have copied the command from the page:  

exercism submit /path/to/file [/path/to/file2 ...]

and I've tried filling out the file paths in a few different ways but none of them are apparently working. Can someone get me straightened out?

**Comment by jdsutherland** [comment]
@chrismjx, can you please share the exact command and output?

**Comment by NobbZ** [comment]
You need to specify the name without the square brackets. The square brackets are common to mark optionality of arguments when describing CL-Interfaces

**Comment by chrismjx** [comment]
ah ok, thanks. I figured it was something like that, I'm a total newb at this. I tried it again and it is still failing but now I'm getting some error about permissions. If I grab the command from your page, what goes into the first path? Is that the exercise file? How is this working when I submit? Is my work being compared to the downloaded exercise file?

`exercism submit /path/to/file [/path/to/file2 ...]`

**Comment by NobbZ** [comment]
On your new try to submit, what was the exact command used and what is the exact error you get?

**Comment by chrismjx** [comment]
Ah, well I moved my own work into the same workspace and tried to run it and now I am getting back:

```
➜  Exercism exercism submit /Users/christopher.johnson/Exercism/javascript/hello-world/hello-world.js /Users/christopher.johnson/Exercism/helloworld.js 
Error: 

    The exercise you are submitting doesn't have the necessary metadata.
    Please see https://exercism.io/cli-v1-to-v2 for instructions on how to fix it.
```

**Comment by jdsutherland** [comment]
`/Users/christopher.johnson/Exercism/helloworld.js` looks wrong based on
the download command output path. You're getting an error because you're
inputting an invalid path. There should be no need to manually move
files/files here. Simply run the download command and use that path.

**Comment by jdsutherland** [comment]
> Downloaded to
**/Users/NAME/Exercism/javascript/hello-world**

> ➜  Exercism exercism submit /Users/NAME/Exercism/javascript/hello-world/hello-world.js **/Users/NAME/Exercism/helloworld.js**

```diff
> /Users/NAME/Exercism/javascript/hello-world/hello-world.js
---
< /Users/NAME/Exercism/helloworld.js
```

You're giving submit 2 arguments. The first one is correct and the second one (bold above) is incorrect.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, as it looks like the core issue is identified. @chrismjx if you continue to have problems, would you please open an issue in https://github.com/exercism/exercism/issues?

**Comment by mroberts8035** [comment]
I am running into a very similar issue. I have the file (in the Python path) and am using Ubuntu. I copied the file path from my IDE, PyCharm, and can verify that the file is there, I see it in both the terminal and in the file manager at the same path. I can navigate to the file via the terminal, but when I try to submit it I get an error. 

here is the copy/paste from my terminal

nice@nice-HP-EliteBook-840-G1:~$ exercism submit /home/nice/PycharmProjects/Exercism.io/01_Hello_World.py
Error: lstat /home/nice/exercism: no such file or directory

nice@nice-HP-EliteBook-840-G1:~$ cd /home/nice/PycharmProjects/Exercism.io/

nice@nice-HP-EliteBook-840-G1:~/PycharmProjects/Exercism.io$ ls
01_Hello_World.py  venv

**Comment by NobbZ** [comment]
Hello @mroberts8035!

Please do not move the file after downloading. The exercism tool expects to find the file in its workspace that it should have created on initial `exercism download …`.

Some metadata is encoded in the relative location of the files to the workspace.

So please move invoke `exercism download …` as described on the exercises page and check the files there. Its best to also edit them there and run the tests. Copying back and forth between that location and some other place is inconvinient and error prone.

**Comment by mroberts8035** [comment]
I am new to exercism.io. So are you stating that I should create the file initially in the file path of:

/home/nice/bin

Is that correct?

Also is there a specific IDE or text editor I should use for it?

**Comment by NobbZ** [comment]
Lets discuss the further problems in #4826 exclusively. Both problems are separate.

**Comment by mroberts8035** [comment]
Fantastic should I re-ask that question there or just wait to see something show up there?

**Comment by mroberts8035** [comment]
I apologize for my noobness

**Comment by rifaimartin** [comment]
I think submitting exercism for beginners is very difficult. Documentation is not very clear in explaining how to submit

**Comment by rifaimartin** [comment]
https://github.com/exercism/java/blob/master/exercises/hello-world/TUTORIAL.md

**Comment by roietik** [comment]
Hi there, I am trying to submit like this but it is the wrong way: exercism submit /Users/name/Exercism/javascript hello-world

**Comment by roietik** [comment]
This is also not working exercism submit /Users/name/Exercism/javascript/hello-world/hello-world.js /Users/name/Exercism/hello-world.js

**Comment by NobbZ** [comment]
Hi @roietik, can you please open a new ticket at github.com/exercism/exercism?

Please also include the output you see.

**Comment by roietik** [comment]
Hi there, what do you mean?

Od: Norbert Melzer <notifications@github.com>
Odpowiedź do: exercism/cli <reply@reply.github.com>
Data: piątek, 28 lutego 2020 06:47
Do: exercism/cli <cli@noreply.github.com>
DW: Radosław Grzymała <radoslaw.grzymala@hotmail.com>, Mention <mention@noreply.github.com>
Temat: Re: [exercism/cli] How to submit? (#801)


Hi @roietik<https://github.com/roietik>, can you please open a new ticket at github.com/exercism/exercism?

Please also include the output you see.

**Comment by NobbZ** [comment]
I mean, please visit https://github.com/exercism/exercism and open a new ticket/issue there.

Include in this ticket a proper description of the problem you have. Include in this description what commands you use, what error message they produce and what operating system you are on, which track you follow, and please also tell us what your current working directory is (`pwd` on mac and linux) and please also provide the output of `exercism debug`.

**Comment by razmatazist** [comment]
**This Works**
Just replace HomeFolder with your Home folder name!
HomeFolderName$ exercism submit /Users/HomeFolderName/Exercism/dart/hello-world/lib/hello_world.dart

Your HomeFolder Name is unique to your device. You can see it in you Finder
![image](https://user-images.githubusercontent.com/70496442/92300829-f2317a00-ef12-11ea-9b72-71ba4c18d129.png)
