### ISSUE TITLE
I don't understand how to use spec.js

### ISSUE THREAD

**Issue by chrismjx** [exercism/cli#804]
I just downloaded leap.spec.js for the javasript track, and my question is a very newbie "How do I use this?"

The first line appears to be importing a file from somewhere. The describe block seems to be describing the gist of the test? The rest of the stuff starting with "xtest" is what I'm really confused by. What is all of this? Is it just showing what the test scenarios should be?

**Comment by NobbZ** [comment]
Hello @chrismjx, your issue is not related to the `exercism`-CLI, therefore I'll move it to the appropriate place.

**Comment by NobbZ** [comment]
Issue moved to [exercism/javascript #602](https://github.com/exercism/javascript/issues/602) via [**ZenHub**](https://www.zenhub.com/)

**Comment by NobbZ** [comment]
Hmmm... Unable to close here. @exercism/cli could you please?

**Comment by nywilken** [comment]
@Nobbz I went ahead and closed for you.
