### ISSUE TITLE
submit two same files goes through the system

### ISSUE THREAD

**Issue by xitanggg** [exercism/cli#805]
Hi, when submitting my two_fer solutions on the Python track, I accidentally submitted two same files using the command: "exercism submit two_fer.py two_fer.py". 

This goes through the system fine. The system simply takes and displays two files. (Link to my solution: https://exercism.io/mentor/solutions/be6d2ccf5a7e4eccad1943de52111f8e) 

I think the system should recognize same files and simply takes and displays it once. Thanks

**Comment by NobbZ** [comment]
Can you please rename the folder and try to redownload the exercise and tell us the outcome?

Whatever happens then might be related.

**Comment by xitanggg** [comment]
Hi. I rename the two-fer folder and redownload the exercise. I again enter the command: "exercism submit two_fer.py two_fer.py", two same instance of two_fer.py is submitted and displayed. I also try to enter the command: "exercism submit two_fer.py two_fer.py two_fer.py", and then three same instance of two_fer.py is submitted and displayed.

**Comment by NobbZ** [comment]
No, how does the freshly downloaded exercise look like for you? Does it have a single file? Does it complain? What happens on download in general?

**Comment by xitanggg** [comment]
Hi. The freshly downloaded exercise looks just as fine as the old one. It contains three files (two_fer.py, two_fer_test.py,  README.md) and one folder (.exercism). Download works fine and nothing complains. Sorry I am not quite sure why might this relates to downloading. It seems to me more of a feature of "exercism submit xxx xxx", which might not check the xxx xxx files appended to it even though they might be the same and simply upload to the system. Thanks.

**Comment by kytrinyx** [comment]
I agree that we should de-duplicate the files in the CLI before submitting them.

Thanks for reporting, @xitanggg

**Comment by NobbZ** [comment]
> Sorry I am not quite sure why might this relates to downloading

I wanted to know how the tool behaves for downloading in this case, to identify a possible secondary bug. But it seems, as if this bug does not happen. The CLI could have canceled the download because of a malformed response completely, or cancel inbetween because of the file it wants to write to is already there, or…
