### ISSUE TITLE
Getting a Workspace Error

### ISSUE THREAD

**Issue by emilianolowe** [exercism/cli#808]
Hey everyone! 

I'm a total newbie here, just started the Ruby path. 
I'm trying to **submit the first exercise** but getting the error message: 

`Error: not in workspace`

Would really appreciate help clearing this up so I can move onto the next challenge.

**Comment by NobbZ** [comment]
This indicates, that the files that you are trying to submit are not living in your configured worksapce.

Depending on your Operating System the workspace is usually one of these:

* Windows: `C:\Exercism`
* Mac: `~/Exercism`
* Linux: `~/exercism`

As a rule of thumb, you should always try to submit the files from where have been downloaded to from the CLI.

**Comment by emilianolowe** [comment]
Thank you for the reply and info!

I was able to fix the problem by renaming the exercism file:

`mv exercim Exercism`

I thought I had already tried renaming the folder with both capital and not capital and had tested it, but I guess I did something wrong. 

Thanks again!

**Comment by NobbZ** [comment]
It is not obvious what you have renamed here. Are you talking about the workspace folder or the `exercism` binary?

If the former, an alternative solution were to reconfigure the workspace to have the same casing as the folder on the filesystem: `exercism configure --workspace=~/exercism`

If the latter, I'm wondering how this helped with your issue.
