### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by Smarticles101** [exercism/cli#810]
Based off the large amount of support related issues, it may be worth having an issue template. This could include a comment explaining that support issues may be better off in the exercism/exercism repo.

**Comment by kytrinyx** [comment]
I agree.

Let's start with something very simple. E.g.:

```
<!--
If you're having trouble, please open an issue in http://github.com/exercism/exercism/issues.

If necessary, we will open actionable issues here with specifics about what needs to change.
-->
```

I'm using HTML comments so that if people don't delete them at least we don't have to look at the boilerplate :-)
