### ISSUE TITLE
UX improvement: error message on submit w/o filename

### ISSUE THREAD

**Issue by dogweather** [exercism/cli#825]
Currently, if a user invokes `submit` without an argument, they're told, "No files found to submit.":

![screen shot 2019-02-28 at 5 28 32 pm](https://user-images.githubusercontent.com/150670/53615018-ccdee580-3b90-11e9-8013-d58e57955d38.png)

I think we can do better by more clearly stating the problem (no _argument_ found, as opposed to no files found), and then showing how to fix it: `exercism submit <filename>`.

**Comment by kytrinyx** [comment]
Thanks, you're absolutely right.

This was fixed in https://github.com/exercism/cli/pull/797 and I need to cut a new release.

**Comment by kenliu** [comment]
@kytrinyx should this be closed now?

**Comment by kytrinyx** [comment]
Yes, thank you!
