### ISSUE TITLE
User can open browser from cli

### ISSUE THREAD

**Issue by srt32** [exercism/cli#83]
I frequently submit an exercise and then go to the browser to see it rendered (sometimes I see things differently in the browser).  I'd love to be able to execute something like `exercism open go anagram` that would take me to my current go anagram submission.  My inspiration comes from the Heroku CLI (https://github.com/heroku/heroku/blob/f5fac5d5031833d77cbc67c763294d9765c4ebc6/lib/heroku/command/apps.rb#L339).

**Comment by kytrinyx** [comment]
This just came up in a conversation again today. We should really prioritize it, since it's such a low-hanging fruit.

**Comment by zabawaba99** [comment]
@Tonkpils pointed me to this issue and I started putting some stuff together to add this command on my fork. However, I couldn't seem to find any APIs that could be used to fetch a submission URL? Anything you could point me towards?

**Comment by kytrinyx** [comment]
Oh, that's probably missing. I'll add it first thing tomorrow morning.

**Comment by zabawaba99** [comment]
Cool deal. I'll keep an eye out and make a PR with the `open` command.

**Comment by kytrinyx** [comment]
Awesome. I'll post back here with some more info.

**Comment by kytrinyx** [comment]
OK, the endpoint is GET http://exercism.io/api/v1/submissions/:track_id/:slug?key=abc123

The key represents the user's exercism API key.

**Comment by kytrinyx** [comment]
Fixed in https://github.com/exercism/cli/pull/162 -- thank's @zabawaba99!
