### ISSUE TITLE
Refactor tests to use subtests

### ISSUE THREAD

**Issue by larson004** [exercism/cli#833]
Subtests make table-driven tests easier to run and debug. Many table-driven tests in `cmd/configure_test`, `cmd/download_test` and other tests are not using this feature.

Can I work on refactoring these to use subtests?

**Comment by kytrinyx** [comment]
@larson004 Would you elaborate on what exactly is hard to debug about them now, and why you feel that subtests would help mitigate that?

That said... one thing that I was going to try to do in the next few days is to pull out any of the test cases in the download file that are specifically about handing funky logic for the solution file paths into a new, much smaller test.

I just merged a PR yesterday that introduced the `solutionFile` type:

https://github.com/exercism/cli/blob/d6ea6a557e7fc09d6a348cfead13ed1125c71884/cmd/download.go#L309-L311

I think this list of files in the test fixture could be simplified to only have `file-1.txt`, `subdir/file-2.txt`, and `file-3.txt`.

https://github.com/exercism/cli/blob/d6ea6a557e7fc09d6a348cfead13ed1125c71884/cmd/download_test.go#L278-L286

All the other ones should really just be tested directly against the new `solutionFile` type, without all the extra download logic.

Want to take a stab at making a (new, table-driven) test that _only_ deals with the `solutionFile` logic?

**Comment by larson004** [comment]
I refactored in TestConfigureToken in config/config_test to use subtests.

This is how the output of `go test -v` looks in master:
```
=== RUN   TestConfigureToken
--- PASS: TestConfigureToken (0.00s)
PASS
ok  	github.com/exercism/cli/cmd	0.003s
```
This is how the output looks with subtests:
```
=== RUN   TestConfigureToken
=== RUN   TestConfigureToken/It_doesn't_lose_a_configured_value
=== RUN   TestConfigureToken/It_writes_a_token_when_passed_as_a_flag
=== RUN   TestConfigureToken/It_overwrites_the_token
=== RUN   TestConfigureToken/It_complains_when_token_is_neither_configured_nor_passed
=== RUN   TestConfigureToken/It_validates_the_existing_token_if_we're_not_skipping_validations
=== RUN   TestConfigureToken/It_validates_the_replacement_token_if_we're_not_skipping_validations
--- PASS: TestConfigureToken (0.00s)
    --- PASS: TestConfigureToken/It_doesn't_lose_a_configured_value (0.00s)
    --- PASS: TestConfigureToken/It_writes_a_token_when_passed_as_a_flag (0.00s)
    --- PASS: TestConfigureToken/It_overwrites_the_token (0.00s)
    --- PASS: TestConfigureToken/It_complains_when_token_is_neither_configured_nor_passed (0.00s)
    --- PASS: TestConfigureToken/It_validates_the_existing_token_if_we're_not_skipping_validations (0.00s)
    --- PASS: TestConfigureToken/It_validates_the_replacement_token_if_we're_not_skipping_validations (0.00s)
PASS
ok  	github.com/exercism/cli/cmd	0.003s
```

As you can see the output with subtests is much more detailed. That is why I felt it would be easier to debug tests using subtests when a test case fails.

@kytrinyx  I would be happy to refactor `download_test` to use the `solutionFile` logic. Let me open a PR with those changes.

**Comment by kytrinyx** [comment]
> As you can see the output with subtests is much more detailed. That is why I felt it would be easier to debug tests using subtests when a test case fails

Interesting. In my experience, I find that having more output is not helpful to me when everything is passing. I'd like to have as little output as possible, as long as everything is fine.

What I want is to have the _right_ information when things fail.

How do the subtests help in the case of failure?

**Comment by larson004** [comment]
I guess it's just personal preference then.
It was good to hear your perspective on this. Closing this.
