### ISSUE TITLE
Boost library directory

### ISSUE THREAD

**Issue by parvpareek** [exercism/cli#839]

**Comment by parvpareek** [comment]
Where should i enter the directory of my boost library. Cmake cannot detect it

**Comment by NobbZ** [comment]
What operating system are you using, how have you installed boost? Perhaps you need to toggle dynamic linking in the CMake file and add a line to the tests?

PS: if you are on windows, try again using a Linux VM until the boost dependency has been removed.

**Comment by parvpareek** [comment]
That problem has now been solved. Now heres the next problem. I am using boost 1.69. And yet visual studio says my boost version is insufficient. I got over it and downloaded  1.66 from source forge.
On Visual Studio... I went to File> Open> Cmake> And then hello-world project. In the terminal... I wrote all the commands but the terminal says there is no cmakelists.txt in build folder. Now i wrote the cmake -G "Visual Studio 15" |boost directory|     command.
Visual studio shows me 2 errors and 2 warnings. I edited the cmakelists.txt file by adding 
SET(CMAKE_INCLUDE_PATH ${CMAKE_INCLUDE_PATH} "C:/win32libs/boost")
SET(CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH} "C:/win32libs/boost/lib")
from 
![image](https://user-images.githubusercontent.com/26191530/55574306-b72d8480-5729-11e9-9bbd-f16138d652f1.png)
[(https://stackoverflow.com/questions/3808775/cmake-doesnt-find-boost.)]
Now it shows one error which says that Visual Studio 15 is not correct. 
`Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error: Error: generator : Ninja
Does not match the generator used previously: Visual Studio 15 2017
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
c:\program files (x86)\microsoft visual studio\2017\professional\common7\ide\commonextensions\microsoft\cmake\CMake\bin\cmake.exe  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\Avi-parv\CMakeBuilds\54b55018-480c-1b33-a81d-1f236c8d7337\install\x64-Debug (default)"  -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe"  -DCMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe"  -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="c:\program files (x86)\microsoft visual studio\2017\professional\common7\ide\commonextensions\microsoft\cmake\Ninja\ninja.exe" "C:\Users\Avi-parv\Exercism\cpp\hello-world" returned with exit code: 1
CMake Error: Error: generator : Ninja
Does not match the generator used previously: Visual Studio 15 2017
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.		C:\Users\Avi-parv\Exercism\cpp\hello-world\Does not match the generator used previously		
`
And the terminal shows me this error-
Unable to find the requested Boost libraries.

  Boost version: 1.69.0

  Boost include path: C:/boost_1_69_0/boost_1_69_0

  Could not find the following static Boost libraries:

          boost_unit_test_framework
          boost_date_time

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:14 (find_package).
Should I set BOOST_LIBRARYDIR and BOOST_ROOT?
Btw... My boost 1.69.0 doesnt contain  lib32-msvc-12.0 or such folder which we were supposed to name as lib. 
![image](https://user-images.githubusercontent.com/26191530/55574401-f065f480-5729-11e9-8e04-c452900b5d35.png)
Please help me. I saw your replies on other issues. You were very helpful to them I just dont wanna use vm. If possible could you tell what should I do now? If you need more details just tell me

**Comment by NobbZ** [comment]
Boost and windows simply don't play well together. But as far as I know there is currently effort going on to remove the dependency on boost during this month.

The easiest ways to get going with the C++ track are currently to wait or to use Linux, either VM, container, WSL or dual boot.

**Comment by parvpareek** [comment]
My man nobbz noooooooooooo please. You gotta save meeeeeeeeeeeeee

**Comment by KevinWMatthews** [comment]
Hi @parvpareek ,

I wonder if running:
```bash
$ cmake -G "Visual Studio 15"
```
doesn't actually work well with Visual Studio.

Judging by the screenshot, Visual Studio is throwing the error:
```bash
Ninja Does not match the generator used previously: Visual Studio 15 2017
```
Correct?

This error message makes it seem like Visual Studio is trying to configure the project using the `Ninja` CMake generator, but it fails because the `Visual Studio 15 2017` generator has already been run from the command line.

Is it possible to configure the project only within Visual Studio?

**Comment by KevinWMatthews** [comment]
Keep in mind that there is a version dependency between CMake and Boost. Boost seems to update and then CMake plays catch-up. If Boost is a newer version than CMake, CMake may struggle to find Boost.

Is your system running CMake 3.12? If so, I think it should play nicely with Boost 1.66. I'm not so sure about 1.69.

There's a more in-depth discussion of this [here](https://github.com/exercism/cpp/issues/217#issuecomment-466452066).

**Comment by parvpareek** [comment]
Update: Apparently I didn't build my boost 1.69 libraries. Once I did. The error in the cmd disappeared.
![image](https://user-images.githubusercontent.com/26191530/55647645-d09f0100-57fb-11e9-891a-c4cbf2e71580.png)
But the error in Visual Studio still persists.
![image](https://user-images.githubusercontent.com/26191530/55647676-e6acc180-57fb-11e9-9422-c865f2d11e65.png)
But a few new files have been added in the directory. Things have settled with boost. But apparently, as you said Visual Studio is having problems with Visual Studio 15 generator. I  didn't quite understand what you meant by configuring the project through visual studio. If it means building and running it, there are 2 options.
![image](https://user-images.githubusercontent.com/26191530/55647895-7c485100-57fc-11e9-8a07-fe34e474315d.png)
When I ran it with CompilerIdCXX.vcxproj, it showed the same error. 
When I ran it with the other one, it shows this->
![image](https://user-images.githubusercontent.com/26191530/55648097-04c6f180-57fd-11e9-976b-9d130cef869c.png)
But in the build log, it says built successfully.
![image](https://user-images.githubusercontent.com/26191530/55648162-32ac3600-57fd-11e9-83a6-00f07dea7c34.png)
I have these new files in my project directory too.
![image](https://user-images.githubusercontent.com/26191530/55648262-756e0e00-57fd-11e9-8003-44776be53380.png)
Hope it gives you enough information. And thanks for attending my problems. Earlier My man nobbz bailed out on me.

**Comment by patricksjackson** [comment]
This is an issue for the cpp track. I'll help in exercism/cpp#250, this issue can be closed.

**Comment by parvpareek** [comment]
Thanks. That will be so easy. I can wait for 1 month. I am learning OpenGL for now. I don't, know what I would have done if it were not for this issue.

**Comment by nywilken** [comment]
Thanks @patricksjackson
