### ISSUE TITLE
Submitting test file breaks future downloads

### ISSUE THREAD

**Issue by KevinWMatthews** [exercism/cli#841]
If a student submits a test file as part of their solution, future calls to `exercism download` won't update the test file. It seems like `exercism download` won't overwrite part of a student's solution.

I encountered this as we're changing the `cpp` track's unit test library from Boost to Catch.
An example is:
```bash
# Complete exercise using old Boost test suite
# Submit with
$ exercism submit leap.h leap.cpp leap_test.cpp

# Upgrade exercise on Exercism website, then
$ exercism download --exercise=leap --track=cpp
# leap_test.cpp is now out of date
```
At this point, the files for configuring the build system (`CMakeLists.txt`) are upgraded to Catch but the test suite itself is out of date, requiring Boost. Compilation fails.

A bit of an edge case, but it was unexpected as an end-user.

Is there history behind this issue? It seems related to #274 .

**Comment by SleeplessByte** [comment]
That is indeed the expected behaviour. There are students who add tests to the suite and submit that (which should be possible). Downside then is that we don't want to destroy their work if they update the suite.

A possibly right approach would probably be a `git merge` or similar.

**Comment by KevinWMatthews** [comment]
Hi @SleeplessByte , makes sense. It would be frustrating to see one's work disappear. Thanks for the response.
