### ISSUE TITLE
ReferenceError: HelloWorld is not defined

### ISSUE THREAD

**Issue by Dastan010** [exercism/cli#842]
Hello, how are you? I didn't find any ways how to solve this problem, can you help me?
I made the HelloWorld tutorial in typescript track.  And when I ran the "yarn test" I got this error: 

> ReferenceError: HelloWorld is not defined

I have 3 files:
hello-world.ts:
```
class HelloWorld {
    static hello(message:string="Hello, World!") {
        return message;
    }
}
export default HelloWorld
```
hello-world.test.ts:
```
it('says hello world with no name', () => {
    expect(HelloWorld.hello()).toEqual('Hello, World!')
})
xit('says hello to bob', () => {
    expect(HelloWorld.hello('Bob')).toEqual('Hello, Bob!')
})
xit('says hello to sally', () => {
    expect(HelloWorld.hello('Sally')).toEqual('Hello, Sally!')
})
```
package.json:
```
{
  "name": "Train",
  "version": "1.0.0",
  "description": "Awesome",
  "main": "index.js",
  "author": "Dastan",
  "license": "MIT",
  "scripts": {
    "build": "babel src -d lib",
    "test": "jest"
  },
  "dependencies": {
    "@types/jest": "^24.0.11",
    "jest": "^24.7.1",
    "lint": "^1.1.2",
    "mocha": "^6.1.3",
    "test": "^0.6.0"
  },
  "devDependencies": {
    "@babel/preset-typescript": "^7.3.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "ts",
      "js",
      "vue"
    ],
    "moduleNameMapper": {
      "^@/(.*)$": "<rootDir>/src/$1"
    },
    "transformIgnorePatterns":["./node_modules/"],
    "moduleDirectories": [
      "node_modules",
      "src"
    ]
  }
}
```

**Comment by NobbZ** [comment]
From what you have pasted here, it seems as if your tests are incomplete, they are missing some `import` and the openeing and closing of a `describe` block. Please delete the folder containing your current solution and redownload the exercise.

Also your `package.json` is different from what usually is used on the TS track. While other files (eg. `yarn.loack`) are missing (or you did not tell us about them at least…

**Comment by Dastan010** [comment]
Now it works! Thank you so much for your help!

**Comment by nywilken** [comment]
@Dastan010 glad to hear you’ve been unblocked. @Nobbz thanks for the help on resolving this issue.

**Comment by Dastan010** [comment]
Thank you so much!
