### ISSUE TITLE
I can't submit my first python exercise 

### ISSUE THREAD

**Issue by BenyamWorku** [exercism/cli#843]

**Comment by BenyamWorku** [comment]
This is the result of exercism debug
onfiguration
----------------
Home:      /Users/benyam
Workspace: /Users/benyam/Exercism
Config:    /Users/benyam/.config/exercism
API key:   **********************************
and I made sure I put the solution of my exercise in this folder as per the instructions /Users/benyam/Desktop/EXERCISM_WORKSPACE
and when running it I am getting this error
Benyams-MacBook-Pro:/ benyam$ exercism submit /Users/benyam/Desktop/EXERCISM_WORKSPACE/python/hello-world/hello_world_test.py
Error: lstat /Users/benyam/Exercism: no such file or directory
 Don't the above two message one of exercism debug and the submission command contradict with each other?

**Comment by NobbZ** [comment]
The exercism workspace is `/Users/benyam/Exercism`, so your solutions have to live exactly below that folder.

Usually `exercism download` should already have created and populated that folder for you. Usually there is no need to manually move files around.

Also, you should not submit your testfiles, but only the solution.

**Comment by BenyamWorku** [comment]
thanks . will attempt it again.

**Comment by kytrinyx** [comment]
It sounds like this is resolved. I'm going to close this, but @BenyamWorku, if you're still having trouble please do not hesitate to add more comments here, and we'll reopen the issue if necessary.
