### ISSUE TITLE
Exercism CLI for aarch64 Linux (Android)

### ISSUE THREAD

**Issue by michaeljprantl** [exercism/cli#850]
I know, this is complaining on a high level, but I felt, I could work may more exercises with Exercism, if I could use it with the Termux Emulator form my Android phone. I already successfully set up my tool chain for my own ordinary coding practice, so all I would likely need is the proper CLI for my architecture (aarch64).

Is it possible that at one point you provide it?

Thanks!

**Comment by NobbZ** [comment]
Due to how termux works it is currently not possible to provide precomputed binaries for that platform. You need to manually set up go on your phone and compile the CLI there.

**Comment by michaeljprantl** [comment]
Ok, thanks a lot for the suggestion. I am not really familiar with go, but I got so far:

```
apt-get install golang
Add GOPATH environment variable
Add GOBIN environment variable
Clone exercism/cli repository (outside GOPATH)
cd into exercism/cli and execute "go install"
```

It started adding dependencies until it ran into this error:
```can't load package: package github.com/exercism/cli: unkown import path github.com/exercism/cli: cannot find module providing package github.com/exercism/cli```

Any idea what I am doing wrong?

**Comment by michaeljprantl** [comment]
I made it work! Thank you again for the suggestion!
