### ISSUE TITLE
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

### ISSUE THREAD

**Issue by Kosarar** [exercism/cli#857]
I am a novice, but I successfully submitted the first exercise. When I try to run a test for the second one "two-fer", I get the following error:

c:\Programs\Exercism>dotnet test
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

I tried to move the content of c:\Users\user\Exercism\csharp\two-fer\ one level up, and it did not help. Now I am stuck. Please help.

**Comment by NobbZ** [comment]
Hello @Kosarar!

It seems as if you had run the `dotnet test` command from within `exercism`s installation directory. You need to run it from within the folder where `exercism.exe` has downloaded the exercise to.

Also please make sure to not move around the code. When submitting the CLI is very strict on the location of the code and you won't be able to submit if the location does not match the CLIs expectations.

**Comment by Kosarar** [comment]
Thank you, NobbZ. It seems to be working now. Can I debug the code with Visual Studio though?

**Comment by NobbZ** [comment]
I do not use VS nor windows, but as far as I know you should be able to open the exercism dotnet projects in VS.

@exercism/csharp @exercism/fsharp @exercism/windows can you confirm?

**Comment by Kosarar** [comment]
What do you use? Yes, I confirm. Should I do it somewhere else?..

**Comment by NobbZ** [comment]
I use Arch Linux and vscodium or emacs, depending on my moods ;)

And do I understand your confirmation correctly, that you actually tried to use VS and it just worked? And what do you want to do somewhere else?

**Comment by Kosarar** [comment]
It worked. Should I confirm the use of tags @exercism/csharp @exercism/fsharp @exercism/windows by clicking somewhere?

**Comment by NobbZ** [comment]
No, I was actually asking the members of the 3 mentioned teams if they can confirm whether or not Visual Studio should be able to open the dotnet related exercises without further config/manual intervention.

**Comment by Kosarar** [comment]
Oh, great. Yes, some more detailed instructions on all steps of using Excercism would be a good thing. But the brevity is fine also.

**Comment by NobbZ** [comment]
To use exercism? Personally I think everything is documented quite understandable and very verbose at times, I'd prefer a more slick set of istructions that does not do so much hand holding…

To use the actual toolstack of the track? Maybe, depends on the track…

**Comment by NobbZ** [comment]
And what I missed to say in the last point, if you feel that bits and pieces in the documentation are not clear or understandable enough, just open an issue at https://github.com/exercism/exercism and pinpoint the part of the documentation that could be improved and try to explain what you do not quite understand with that part.

It will be delegated from there to the proper sub-repository of the project if necessary.

**Comment by Kosarar** [comment]
Got it. Thank you.
