### ISSUE TITLE
Can't start Hello world project as it keeps asking for SDK

### ISSUE THREAD

**Issue by Jack6776** [exercism/cli#858]
Hello,

I am new to exercism so this might be a simple fix but I am completely lost. I managed to set up excersim and managed to download the "Hello world" program.

However once I try to open the C# project i get the following error: The SDK 'Microsoft.NET.sdk' specified could not be found.

I have downloaded the latest version of the SDK but the error keeps showing up. Because of this I can't even attempt the project and I am not sure what else to try now.

**Comment by NobbZ** [comment]
As this is not related to the `exercism` CLI but rather the track specific toolchain, I'll send this issue over there.

Then you can provide additional information in the copied thread.

You'll need probably to add whether you are using Windows, Linux or Mac. Also what do you do (open which program, enter which command, etc?) when you get that error message, and what is the exact error message you see?

**Comment by NobbZ** [comment]
@Jack6776 please continue disussion at exercism/csharp#1288.

@iHiD, @kytrinyx, could one of you close this, or anyone else with access?

PS: There is no @exercism/cli I could ping…

**Comment by iHiD** [comment]
I think GitHub has a bug around completion lists atm. They almost never work for me recently.
