### ISSUE TITLE
You are submitting a directory, which is not currently supported.          D:\CodeBlocksProjects\helloworld\proj      Please change into the directory and provide the path to the file(s) you wish to submit

### ISSUE THREAD

**Issue by NoobCoder14** [exercism/cli#859]
I am unable to submit even hello-world, any help would be welcome

**Comment by NobbZ** [comment]
You need to specify individual files to submit. Also please do not try to submit files that are outside of your `exerciam workspace`, best is to solve exercises where `exerxiam download` stores them and submit them from there, no copy back and forth.

**Comment by NoobCoder14** [comment]
> You need to specify individual files to submit. Also please do not try to submit files that are outside of your `exerciam workspace`, best is to solve exercises where `exerxiam download` stores them and submit them from there, no copy back and forth.

Done, thank you so much!
