### ISSUE TITLE
`--verbose` switch for `submit` leaks users token (perhaps other subcommands as well)

### ISSUE THREAD

**Issue by NobbZ** [exercism/cli#860]
Sometimes when debugging problems, we ask to run `exercism submit --verbose …` and post the full output into chat/github.

Today I realised that this does leak the literal user token.

Please filter/blank the token from the output generated by the `--verbose` flag, also please check for any other output if it leaks the token and filter/blank it there as well.

We should consider to invalidate all current tokens once this is fixed and deployed.

**Comment by kytrinyx** [comment]
We have code to mask the token, so this should be fairly straight-forward to do. If someone submits a PR for it, I will commit to reviewing it, getting it merged, and cutting a new release.

I am not willing to invalidate all the existing tokens, but I agree that we should notify everyone on the site that this has occurred and that if they have ever posted debugging output, they should consider updating their token.

**Comment by kotp** [comment]
It might be helpful to always mask the token, unless an `--unmask-token` option is given.  The accidental exposure would likely automatically be reduced because that would be an extra step to reveal that token anywhere.

**Comment by kytrinyx** [comment]
Yes, I think `--unmask-token` would work. I like how explicit that is. We could make that a global option.
