### ISSUE TITLE
Exercism 3.0.12 no longer reports errors when trying to download a locked exercise

### ISSUE THREAD

**Issue by masliu** [exercism/cli#870]
Steps to reproduce:

1. Try to download an exercise that you have not yet unlocked
2. Notice the output "Downloaded to (exercism-workspace-dir)/users"
3. Check the users directory as well as the track directory and notice no folders have been downloaded

This was working properly before the recent update.

**Comment by kytrinyx** [comment]
Thanks for catching and reporting that, @masliu!
