### ISSUE TITLE
[Feature Request] Add a flag to download that takes you to the newly created directory

### ISSUE THREAD

**Issue by vladciobanu** [exercism/cli#877]
As a mentor, it would be helpful if I could copy the `exercism download <...>` command from the dashboard and add a `--go` flag to also change the current directory to the newly downloaded root.

**Comment by NobbZ** [comment]
This feature has been requested a couple of times and it can't implemented, as the `exercism` tool can't change the working directory of its parent process (your shell).

Thats why the output is designed in a way, that you can do `cd $(exercism download …)` on `sh` compatible shells, `cd (exercism download …)` in `fish` or just copy paste in windows `cmd.exe` and PowerShell.

**Comment by kytrinyx** [comment]
Thanks @NobbZ!

I'm closing this, as we cannot implement it.
