### ISSUE TITLE
exercism CLI have its own directory and not install its top level directory in the ~/bin directory

### ISSUE THREAD

**Issue by vonHabsi** [exercism/cli#879]
When the exercism archive is extracted it places some of its directories in the `~/bin` directory which in my view is a bad design. It may overwrite other directories and it is also difficult to tell which files and directories belong to `exercism` when it has to be moved elsewhere or uninstalled.

It is better to install it in `~/bin/exercism` and the user told to add `~/bin/exercism` to the $PATH.

If something has to go into the `~/bin` directory then it should only be a command to change the $PATH if it is not already there, or create an environment like python's `virtualenv`

**Comment by NobbZ** [comment]
To avoid overwriting we usually recommend to extract in the download folder (I do though think as well, that we shouldn't have the archive contents flat but suggest a folder as well, "tarbomb").

Also in my opinion one should avoid adding more and more single binary folders to the `PATH`, as it will increase the overall search time for executables.

And I don't really get your last statement… Using `~/bin` for "user local" installation of single executable programs and scripts is quite a common practice throughout the linux community…

**Comment by ekingery** [comment]
This seems more-or-less resolved and/or not actionable. Particularly considering that using the snap package is the preferred installation method now for linux. I think it can be closed, but please do re-open if I am mistaken.
