### ISSUE TITLE
 `require_relative': cannot load such file 

### ISSUE THREAD

**Issue by Rhodine** [exercism/cli#882]
1.  **Issue**: Exercism exercise is not running  - Error message below
2. When i input the file path to run the test I received this in the command line:
$ ruby series_test.rb
series_test.rb:2:in `require_relative': cannot load such file -- C:/Users/rorle/Exercism/ruby/series/series (LoadError)
        from series_test.rb:2:in `<main>'

3. Troubleshooting Information
===========================

Version
----------------
Current: 3.0.12
Latest:  3.0.12

Operating System
----------------
OS:           windows
Architecture: amd64

Configuration
----------------
Home:      C:\Users\rorle
Workspace: C:\Users\rorle\Exercism
Config:    C:\Users\rorle\AppData\Roaming\exercism
API key:   2f4a*****************************e9d

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 112.17ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 119.3454ms

**Comment by kotp** [comment]
I am assuming that you have resolved your issue?  It is normal to be in the folder `C:/Users/rorle/Exercism/ruby/series/series` when you run `ruby series_test.rb`.

I am putting this here just in case anyone has a similar problem and finds this issue, but also to confirm this is the way that you have solved your issue.

**Comment by Rhodine** [comment]
The issue isnt resolved, I just thought I was on the wrong thread! I am still experiencing problems running the exercise. I am in C:/Users/rorle/Exercism/ruby/series/series
when running the test but I get the above error message so I can't work on the exercise.

**Comment by kotp** [comment]
OK, this is usually because the `series.rb` file does not exist in the folder where the test is.  The part of the message that is relevant here is: 

> cannot load such file -- C:/Users/rorle/Exercism/ruby/series/series (LoadError)

**Comment by kotp** [comment]
The reason that it doesn't show an extension is because it can be several different extensions, `.rb` being one of them.  In our case, it probably should be.

**Comment by kotp** [comment]
But yes, this is the wrong area, as it is not related to the CLI.  Closing this in preference to exercism/ruby#1003

I believe the solution is valid above, and I will post the same answer in that issue as well, in case someone needs to find it.

**Comment by NobbZ** [comment]
@exercism/triagers please move to exercism/support, then close as double of exercism/ruby#1003.

**Comment by sshine** [comment]
@NobbZ, @iHiD: It seems that the three of us are in @exercism/triagers, but I can't find the function that performs the move of issues in any of the menus, so perhaps this function is not enabled for that group, or @NobbZ and I can't figure out where the button is?

I've marked this issue as closed.
