### ISSUE TITLE
Tests are being ignored

### ISSUE THREAD

**Issue by iliasmertzanos** [exercism/cli#887]
Hi guys,

I am running the gradle test for the Hamming task (Kotlin track) and I get a message that some of them are skipped:

```
`HammingTest > validatesSecondStrandNotLonger SKIPPED

HammingTest > smallDistanceInLongStrand SKIPPED

HammingTest > sameNucleotidesInDifferentPositions SKIPPED

HammingTest > completeDistanceInSingleNucleotideStrand SKIPPED

HammingTest > noDistanceBetweenLongIdenticalStrands SKIPPED

HammingTest > noDistanceBetweenShortIdenticalStrands SKIPPED

HammingTest > smallDistanceInMediumStrand SKIPPED

HammingTest > largeDistanceInOffByOneStrand SKIPPED

HammingTest > largeDistanceInPermutedStrand SKIPPED

HammingTest > validatesFirstStrandNotLonger SKIPPED

HammingTest > completeDistanceInSmallStrand SKIPPED

HammingTest > nonUniqueCharacterInFirstStrand SKIPPED

HammingTest > smallDistanceInSmallStrand SKIPPED

HammingTest > nonUniqueCharacterInSecondStrand SKIPPED`
```

Am I doing something wronge?

I also looked in the gradle class and somehow the test methode have a header of @Ignore.

`
```
@Ignore
    @Test
    fun smallDistanceInMediumStrand() {
        assertEquals(1, Hamming.compute("GGACG", "GGTCG"))
    }

```
    @Ignore
    @Test
    fun smallDistanceInLongStrand() {
        assertEquals(2, Hamming.compute("ACCAGGG", "ACTATGG"))
    }

    @Ignore
    @Test
    fun nonUniqueCharacterInFirstStrand() {
        assertEquals(1, Hamming.compute("AAG", "AAA"))
    }

    @Ignore
    @Test
    fun nonUniqueCharacterInSecondStrand() {
        assertEquals(1, Hamming.compute("AAA", "AAG"))
    }
`

Can you please check that up?

Thank you.

**Comment by iliasmertzanos** [comment]
I just didn't notice under the instructions the following quote:

"In the test suites all tests but the first have been skipped.

Once you get a test passing, you can enable the next one by removing the @Ignore annotation."

**Comment by sshine** [comment]
Yes, this is a workflow that some track maintainers prefer.

Other tracks have the test suite halt on the first failed test, which is sort of equivalent, but not exactly.

Good to hear you figured it out.
