### ISSUE TITLE
Error trying submit

### ISSUE THREAD

**Issue by josealuna** [exercism/cli#901]
Error: The base API URL 'https://api.exercism.io/v1' cannot be reached.

Get https://api.exercism.io/v1/ping: dial tcp: lookup api.exercism.io on [::1]:53: dial udp [::1]:53: connect: network is unreachable

Using snap intallation.

**Comment by kytrinyx** [comment]
Hm, that doesn't sound good.

What do you get if you run `$ curl "https://api.exercism.io/v1/ping"`?

**Comment by NobbZ** [comment]
I think we figured this out in the gitter, according to @josealuna last comment it seemed to be related to some local DNS issue.

**Comment by kytrinyx** [comment]
@NobbZ you're a star, thank you!
