### ISSUE TITLE
Unable to Submit Solution

### ISSUE THREAD

**Issue by tyrantdavis** [exercism/cli#904]
When I execute the command "exercism submit hello_world.rb" I get the error "Not in workspace" despite being in the hello_world directory.  My CLI version is 3.0.13 by the way and states that my CLI version is up to date.

### How to reproduce

1. download exercise per instructions
2. cd into hello_world directory 
3. add solution via editor
4. `$ exercism submit hello_world.rb`

**Comment by tyrantdavis** [comment]
Never mind. Got it working.

**Comment by kotp** [comment]
How did you get it working?  In case someone else has the same problem, they may come here searching for an answer and "Got it working" is probably not going to be helpful for them.
