### ISSUE TITLE
Having issue the CLI

### ISSUE THREAD

**Issue by dhrey112** [exercism/cli#909]
After running the troubleshoot, this is the result below

C:\Program Files\exercism-windows-64bit>exercism troubleshoot

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13

Operating System
----------------
OS:           windows
Architecture: amd64

Configuration
----------------
Home:      C:\Users\USER
Workspace: C:\Users\USER\Exercism
Config:    C:\Users\USER\AppData\Roaming\exercism
API key:   2522*****************************898

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 343.8018ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [Get https://api.exercism.io/v1/ping: dial tcp: lookup api.exercism.io: no such host]
    * 12.0029196s

If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.

**Comment by NobbZ** [comment]
Looks like some DNS weirdnesses.

Can you ping exercism.io and api.exercism.io from your terminal?

Are you perhaps in a corporate network that might whitelist/blacklist some domains?

**Comment by iHiD** [comment]
Hi. If you're still experiencing this problem, please open a new issue in https://github.com/exercism/exercism
