### ISSUE TITLE
Error: The base API URL 'https://api.exercism.io/v1' cannot be reached.

### ISSUE THREAD

**Issue by Segun-Ade** [exercism/cli#910]
Hi I'm getting this error while trying to configure exercism like so `exercism configure --token=a********-*****-*****-****-************1
`
here's the error I get:
`Error: The base API URL 'https://api.exercism.io/v1' cannot be reached.
`
and 

> curl  https://api.exercism.io/v1/ping: 

returns an empty object `{}`

**Comment by iHiD** [comment]
Hi. If you're still experiencing this problem, please open it in https://github.com/exercism/exercism
