### ISSUE TITLE
Add an option to select base directory

### ISSUE THREAD

**Issue by rbUUbr** [exercism/cli#916]
Hi! Thanks for so powerful CLI tool! It's really amazing and works fast, but as for me, there is a needed possibility to provide a base directory to download track's exercises. For example, now I have:
```
exercism download --exercise=hello-world --track=go

Downloaded to
/Users/rbuubr/Exercism/go/hello-world
```
But I want do something like:
```bash
exercism download --exercise=hello-world --track=go --directory=rbuubr/projects

Downloaded to
/Users/rbuubr/projects/Exercism/go/hello-world
```
I would like to do it, but at first, I would like just to discuss this idea at first :)

**Comment by kotp** [comment]
Change the configuration file to reflect your workspace folder to match where you want it to download.

```sh
Exercism help configure
```

Does that mean that this already exists for you?

**Comment by rbUUbr** [comment]
yes, thanks!

**Comment by NobbZ** [comment]
Closing, as configuring the workspace seems to be the solution.
