### ISSUE TITLE
Wrong checksum for exercism-3.0.13-windows-x86-64

### ISSUE THREAD

**Issue by ambitious-newbie** [exercism/cli#917]
I don't know why but powershell shows me different checksum from what's in the file called exercism_checksums.txt, any suggestions ?

**Comment by NobbZ** [comment]
For me it seems to work, are you using the correct hashing algorithm?

```plain
$ sha256sum exercism-3.0.13-windows-x86_64.zip
06fa62c88749b04dfe584c9b6030da3125c4b64ff48057751ab69095764e50cf  exercism-3.0.13-windows-x86_64.zip
$ grep exercism-3.0.13-windows-x86_64.zip exercism_checksums.txt 
06fa62c88749b04dfe584c9b6030da3125c4b64ff48057751ab69095764e50cf  exercism-3.0.13-windows-x86_64.zip
```

**Comment by ambitious-newbie** [comment]
Yes, you are right. I checked .exe not whole zip file. Thank you.

> For me it seems to work, are you using the correct hashing algorithm?
> 
> ```
> $ sha256sum exercism-3.0.13-windows-x86_64.zip
> 06fa62c88749b04dfe584c9b6030da3125c4b64ff48057751ab69095764e50cf  exercism-3.0.13-windows-x86_64.zip
> $ grep exercism-3.0.13-windows-x86_64.zip exercism_checksums.txt 
> 06fa62c88749b04dfe584c9b6030da3125c4b64ff48057751ab69095764e50cf  exercism-3.0.13-windows-x86_64.zip
> ```
