### ISSUE TITLE
 JavaScript track set up problem (hellow-world)

### ISSUE THREAD

**Issue by TCE-1** [exercism/cli#921]
Hello,
Was able to complete most of the setup steps successfully on Ubuntu.  When I get to`npm install` I run into problems.  Below is the output from:

`npm install`
`npm test`
`exercism troubleshoot`

 

`$npm install` which returns:

> $npm install
> npm WARN saveError ENOENT: no such file or directory, open '/home/../../package.json'
> npm WARN enoent ENOENT: no such file or directory, open '/home/../../package.json'
> npm WARN dev No description
> npm WARN dev No repository field.
> npm WARN dev No README data
> npm WARN dev No license field.
> 
> audited 611 packages in 1.001s
> 
> 3 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities

 and `$npm test` returns:

> $npm test
> npm ERR! code ENOENT
> npm ERR! syscall open
> npm ERR! path /home/../../package.json
> npm ERR! errno -2
> npm ERR! enoent ENOENT: no such file or directory, open '/home/../../package.json'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent 
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/../.npm/_logs/2020-03-06T17_36_31_742Z-debug.log

`$exercism troubleshoot` returns:

> $exercism troubleshoot
> 2020/03/06 12:36:43.002693 cmd_run.go:884: WARNING: cannot create user data directory: failed to verify SELinux context of /home/../snap: exec: "matchpathcon": executable file not found in $PATH
> 
> Troubleshooting Information
> ===========================
> 
> Version
> ----------------
> Current: 3.0.13
> Latest:  3.0.13
> 
> 
> Operating System
> ----------------
> OS:           linux
> Architecture: amd64
> 
> 
> Configuration
> ----------------
> Home:      /home/../snap/exercism/5
> Workspace: /home/../snap/exercism/5/exercism
> Config:    /home/../snap/exercism/5/.config/exercism
> API key:   4a82*****************************47d
> 
> API Reachability
> ----------------
> 
> GitHub:
>     * https://api.github.com
>     * [connected]
>     * 69.501891ms
> 
> Exercism:
>     * https://api.exercism.io/v1/ping
>     * [connected]
>     * 537.018972ms
> 
> 
> If you are having trouble please file a GitHub issue at
> https://github.com/exercism/exercism.io/issues and include
> this information.

**Comment by iHiD** [comment]
This isn't anything to do with the CLI so I'm closing this.
