### ISSUE TITLE
Cannot submit solution

### ISSUE THREAD

**Issue by KiriaKasis** [exercism/cli#924]
I am not sure whether this is the same issue as #743, for sure it is similar to #904.

In short the `submit` command is unable to find the submission file, but the file is present at the global path printed in the error message.

Yesterday it worked fine and I was able to submit 2 problems, today I cannot submit neither new nor old problems. I have installed exercism with snap on Debian.

Here follows some more relevant context:

```
Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13


Operating System
----------------
OS:           linux
Architecture: amd64


Configuration
----------------
Home:      /home/afiori/snap/exercism/5
Workspace: /home/afiori/snap/exercism/5/exercism
Config:    /home/afiori/snap/exercism/5/.config/exercism
API key:   1356*****************************f30

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 29.474638ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 227.606967ms
```

```
user@pc/local/home/afiori/snap/exercism/5/exercism/rust/forth$ exercism workspace
/home/afiori/snap/exercism/5/exercism
```
local path to file `src/lib.rs`, global path `/local/home/afiori/snap/exercism/5/exercism/rust/forth/src/lib.rs`

```
user@pc:/local/home/afiori/snap/exercism/5/exercism/rust/forth$ exercism submit src/lib.rs 
Error: 

    The file you are trying to submit cannot be found.

        /var/lib/snapd/void/src/lib.rs
```
There is no file at `/var/lib/snapd/void/src/lib.rs` and if I manually copy  the submission file there then exercism (correctly) notes that `/var/lib/snapd/void/src/lib.rs` is outside the workspace.

```
afiori@lap-21-44:/local/home/afiori/snap/exercism/5/exercism/rust/forth$ exercism submit /local/home/afiori/snap/exercism/5/exercism/rust/forth/src/lib.rs 
Error: 

    The file you are trying to submit cannot be found.

        /local/home/afiori/snap/exercism/5/exercism/rust/forth/src/lib.rs
```
The path `/local/home/afiori/snap/exercism/5/exercism/rust/forth/src/lib.rs` is indeed the correct path to the file I wish to submit.

**Comment by KiriaKasis** [comment]
I have found a fix by simply uninstalling and reinstalling exercism with snap. I do not know what caused the original problem.

**Comment by kytrinyx** [comment]
Glad you got it sorted. I'm going to go ahead and close this. ✨

**Comment by meraxex** [comment]
I suppose I am experiencing almost the same issue. Until just before I added the directory for Java tracks, I was having no issues submitting Python tracks. But now I can't seem to submit Python tracks. Java tracks submissions work perfect.

After adding adding the Java tracks directory to Exercism, I noticed that most of my Python solutions disappeared. When I try to resubmit them, I get `Error: This solution could not be found`. I would guess it's a path problem but I checked multiple times and my workspace is set to `/Users/jbkwizera/Exercism`. The file I am trying to submitting is just there. 

Here is what I get on `exercism troubleshoot`:

`
Troubleshooting Information
===========================

Version
----------------
Current: 3.0.13
Latest:  3.0.13


Operating System
----------------
OS:           darwin
Architecture: amd64


Configuration
----------------
Home:      /Users/jbkwizera
Workspace: /Users/jbkwizera/Exercism
Config:    /Users/jbkwizera/.config/exercism
API key:   ce29*****************************97e

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 178.738481ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 809.555653ms


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.
`

**Comment by NobbZ** [comment]
@meraxex 
> After adding adding the Java tracks directory to Exercism, I noticed that most of my Python solutions disappeared

Disappeared from where? From your local disk or from the website? If the latter, have you perhaps reset your account or created a new one?

Or have you tried to link GitHub account to an account that was email before and accidentally created a second account?

If you still have the python solutions on your disk, please run the following from your workspace root: `find . -name '*.json' | xargs cat | jq '{ track: .track, exercise: .exercise, id: .id, handle: .handle}'`

You might need to install `jq` first. It will print a lot of JSON, the output might help us to identify the problem.

**Comment by meraxex** [comment]
The solutions disappeared from the website. I still have them all on my local disk. I didn't create or attempt to create a new account. When I signed up I used github. I didn't reset my account either, because then all solutions would have disappeared, but there are two that didn't disappear (book store and change). I think those two were my latest, if that may help.

Running the find command in my workspace gives
```
{
  "track": "python",
  "exercise": "book-store",
  "id": "4fd7ac9cf45646d298a8d760973df80e",
  "handle": "meraxex"
}
{
  "track": "python",
  "exercise": "linked-list",
  "id": "6a4deba29f144aa1b46ccbf2cb9c179b",
  "handle": "meraxex"
}
{
  "track": "python",
  "exercise": "change",
  "id": "40a96147312c4a94bdfb731c57c5a03e",
  "handle": "meraxex"
}
{
  "track": "python",
  "exercise": "dot-dsl",
  "id": "be0135ba79d04bc0a4eb32a44e80dfa7",
  "handle": "meraxex"
}
{
  "track": "python",
  "exercise": "bowling",
  "id": "8ed72bcfa11747dbb69696ea4840f99d",
  "handle": "meraxex"
}
{
  "track": "python",
  "exercise": "tournament",
  "id": "6377d8ae38144ffda87987e0ab9e1a41",
  "handle": "meraxex"
}
{
  "track": "python",
  "exercise": "scrabble-score",
  "id": "f26f8a2796c34a5eb1027258face9533",
  "handle": "meraxex"
}
{
  "track": "python",
  "exercise": "twelve-days",
  "id": "9aa6711bcaa445b9b1b94ef9f2fd9603",
  "handle": "meraxex"
}
{
  "track": "python",
  "exercise": "rational-numbers",
  "id": "cc67b6fdc22d4e7d9c681446d692560b",
  "handle": "meraxex"
}
{
  "track": "python",
  "exercise": "grep",
  "id": "7720356928154b9f8ed744bb8e776e85",
  "handle": "meraxex"
}
{
  "track": "python",
  "exercise": "luhn",
  "id": "5147fe1034224f598b6a919f071b4bf2",
  "handle": "meraxex"
}
{
  "track": "java",
  "exercise": "isbn-verifier",
  "id": "2322757dee104142ba3ad133e3ffdc02",
  "handle": "meraxex"
}
{
  "track": "java",
  "exercise": "knapsack",
  "id": "7651784fddbc43f3a01a38929b358985",
  "handle": "meraxex"
}
{
  "track": "java",
  "exercise": "etl",
  "id": "eb32efce837b4173b090e74de80e006c",
  "handle": "meraxex"
}
{
  "track": "java",
  "exercise": "isogram",
  "id": "e9340c1f527f4ebb82234d5db6db0f29",
  "handle": "meraxex"
}
{
  "track": "java",
  "exercise": "sieve",
  "id": "fb68f5398dc747d980a48ab791d12b2e",
  "handle": "meraxex"
}
{
  "track": "java",
  "exercise": "saddle-points",
  "id": "fd4f9f1cb3ee4121b21a2e6dc51f2fb0",
  "handle": "meraxex"
}
{
  "track": "java",
  "exercise": "flatten-array",
  "id": "fd6771079e81498aad49ddb6b47080ec",
  "handle": "meraxex"
}
{
  "track": "java",
  "exercise": "matrix",
  "id": "3b3e5cff7b3b4ca4a975297b9e5cda13",
  "handle": "meraxex"
}
{
  "track": "java",
  "exercise": "binary-search",
  "id": "89d8137729fd44b8b771a67d1af84646",
  "handle": "meraxex"
}
```

**Comment by NobbZ** [comment]
@iHiD can you please check IDs in the database if you can see something?

**Comment by iHiD** [comment]
Your solutions are on exercism and on the website. e.g. https://exercism.io/mentor/solutions/40a96147312c4a94bdfb731c57c5a03e

So I'm not sure what issue you're reporting.

**Comment by meraxex** [comment]
> Your solutions are on exercism and on the website. e.g. https://exercism.io/mentor/solutions/40a96147312c4a94bdfb731c57c5a03e
> 
> So I'm not sure what issue you're reporting.

That's a link for mentors. Perhaps they are visible to mentors and not to me. I am not sure if it could also be because I am in practice mode. Again, the fact that my solutions disappeared is one part of the problem. The other part is  that I cannot resubmit them. I get ```Error: This solution could not be found```, although the file is right there in my workspace path (and this error happens only for Python tracks).

**Comment by iHiD** [comment]
This link will work for you: https://exercism.io/my/solutions/40a96147312c4a94bdfb731c57c5a03e

**Comment by iHiD** [comment]
Are these really old solutions? Maybe they were on your machine from an old version of the CLI and need redownloading since the move to v2?

**Comment by meraxex** [comment]
The solution that that link directs to is one of the two (change.py and book_store.py) that didn't disappear. Some of the solutions that disappeared (or are invisible to me) are grep.py, bowling.py and tournament.py. I just started using exercism not more than a month ago. So I think I have been using v3.0.13 all the time. Reinstalling exercism with ```brew reinstall exercism``` didn't help. Uninstalling and installing again didn't help either.

**Comment by iHiD** [comment]
Have you changed in or out of mentored mode/practice mode for Python?

**Comment by meraxex** [comment]
I have always been in practice mode.

**Comment by iHiD** [comment]
So I honestly have no idea. Those solutions don't appear in the database. I can find no record of them in the logs. You don't have a started solution to `bowling` for Python in the database. 

To fix this, I think you could:
- Go to the Python track
- Click on `bowling`
- Grab the last bit of the URL (hex)
- Replace the id in your config file for `bowling` with that hex.

You should be able to then submit.

Sorry you've had this - I'm thoroughly baffled.
