### ISSUE TITLE
 A mentor has left you a comment.

### ISSUE THREAD

**Issue by layer-eight** [exercism/cli#925]
I have this message showing but I cant find any comment of a mentor 

![grafik](https://user-images.githubusercontent.com/54802248/79450898-ee459f80-7fe5-11ea-916f-6f250495967e.png)

The Mentor Discussion where I expect the message to be looks like the following

![grafik](https://user-images.githubusercontent.com/54802248/79451147-598f7180-7fe6-11ea-9efc-2f9b4a2102ed.png)

Might be I'm blind but please could you explain where I can find mentor answers in future.
Thanks!

**Comment by NobbZ** [comment]
I think the notification refers to the automatic analysis.

**Comment by sudo-luke** [comment]
Thanks for the quick response. Was a bit confusing for me to be honest.
