### ISSUE TITLE
Access Denied, can't build file. GOLANG

### ISSUE THREAD

**Issue by Sagr859** [exercism/cli#926]
I completed nearly 8 exercises until now, using **Visual Studio** Code and **Go extensions**. But recently it started to malfunction. Whenever I start a new terminal and try to run the .go code using `go test` command it hungs up a few seconds and dissappears. I tried the same using CMD in Administrative and returned:
```
open C:\Users\Hp\AppData\Local\Temp\go-.....\..test.exe: Access is denied.
FAIL   program_name [build failed]
 
```
It started to reflect in all other programs too.
I have installed Golang seperately in my system ( Windows 10 ) and it works fine. So its clearly something wrong with Exercism and not GOPATH. 

It started after the completion of nucleotide_counts and while doing the raindrops questions.

**Comment by tehsphinx** [comment]
Please close this one so we can focus on one issue.

**Comment by Sagr859** [comment]
Thanx Guys. I think its now working fine. My anti-virus finally reported the issue and I figured that some virus named 'gen : variant cerbu 70524' got into the build files. So I removed all the go updates reinstalled them. I did the same for the Exercism files and the build files in the Temp folder.

So now I'm closing all those issues links... Thank you guys!!
