### ISSUE TITLE
Dial failure on dual-stack networks without ipv6 route to internet

### ISSUE THREAD

**Issue by tydavis** [exercism/cli#931]
When on a dual-stack system with an incomplete or non-routing IPv6 stack, the first records returned are `AAAA`, forcing the client to use the ipv6 stack first. This causes a failure in the client like so:

```
$ exercism configure --token=...

Error: The base API URL 'https://api.exercism.io/v1' cannot be reached.
Get https://api.exercism.io/v1/ping: dial tcp: lookup api.exercism.io on [::1]:53: read udp [::1]:38502->[::1]:53: read: connection refused
```

This is due to the `Ping` function using an unconfigured HTTP Client (https://github.com/exercism/cli/blob/master/api/client.go#L20).

To fix this, add the [DualStack](https://golang.org/pkg/net/#Dialer) field to the DialContext in the Transport of the HTTP Client.

**Comment by Emiluren** [comment]
Thank you for finding what my problem was! :D

But the docs seem to say that DualStack is deprecated, right?

**Comment by tydavis** [comment]
DualStack is deprecated, but now we have confirmation that DualStack is enabled by default on newer compilers: https://golang.org/src/net/http/transport.go (Line 47)

**Comment by tydavis** [comment]
Latest release builds do not work out of the box, but building from source does. Please ensure your build environment is using the latest (1.15.6)

**Comment by kotp** [comment]
By latest release builds, I think you mean [v3.0.13](https://github.com/exercism/cli/tree/v3.0.13). I provide  this as a reference that is snapshot in time since "latest" can quickly become outdated in this reference.

**Comment by tydavis** [comment]
Yes, @kotp -- v3.0.13 still shows this particular issue, but recompiling from source does not.
