### ISSUE TITLE
Issue with submitting solution - javascript track

### ISSUE THREAD

**Issue by mxuan1998** [exercism/cli#937]
Armstrong Numbers 

I created my second solution named armstrongNumbers.js
![image](https://user-images.githubusercontent.com/49051621/81653517-ea226b80-9445-11ea-812a-dfb3b6a92eba.png)

cd into the folder and tried to submit. But it keeps showing an error message.
![image](https://user-images.githubusercontent.com/49051621/81653558-fc040e80-9445-11ea-89d9-f59a6989b934.png)

Can you please look into it and let me know if I'm doing something wrong?
Thank you.

**Comment by NobbZ** [comment]
What is the output of `exercism workspace`?

As you are on Mac, its default value is `~/Exercism`, not `~/exercism`. Even though both are the same from the filesystem point of view, it is a hard problem for the CLI to recognize this equivalence.

**Comment by mxuan1998** [comment]
Aha it worked. I used to submit with `~/exercism` and had no problem with it, only this time.
Alright, will remember to use `~/Exercism` instead.
Thank you @NobbZ for your help!
