### ISSUE TITLE
Provide a Flatpak

### ISSUE THREAD

**Issue by LongJohn-Silver** [exercism/cli#947]
I know you provide a Snap, which is similar product, but I believe that there are concrete evidences than flatpaks are a more robust and secure alternative, and also is becoming a more standardized option for non-based and Ubuntu based distributions alike, being adopted already by twenty five flavours of Linux, and some of them come with flatpak preinstalled out of the box (CentOS, ElementaryOS, EndlessOS, Fedora, Linux Mint, PureOS and ZorinOS).

One of the biggest advantages in contrast with snaps, is that flatpaks are sandboxed, and therefore this results in a more secure and private experience since it is harder for some kind of malware to attack the system, or for said application to retrieve user information without them knowing it.  Another good point is that everything that's uploaded to Flathub (Flatpak's centralized repository) is compiled by the same developers, and cannot be done by some random person on the internet which could lead to outdated packages, piracy, and whatnot. Just like snaps, Flatpaks are compatible with every distribution that supports it, so you don't have to be uploading a million different releases.

More information:

https://flathub.org/
https://flatpak.org/
https://flatpak.org/setup/
https://docs.flatpak.org/en/latest/

**Comment by ric2b** [comment]
Hey @LongJohn-Silver,

The project uses [GoReleaser](https://github.com/goreleaser/goreleaser) to generate the various release formats.

It's configured here: https://github.com/exercism/cli/blob/master/.goreleaser.yml

Unfortunately it looks like GoReleaser doesn't support generating Flatpacks yet.

**Comment by LongJohn-Silver** [comment]
@ric2b Oh, that's a bummer. Close the issue if you want, or leave it open in case someday it gets supported.

**Comment by ekingery** [comment]
I think this is best to close for now, given I'm not finding an [issue or mention of flatpak on the GoReleaser repo](https://github.com/goreleaser/goreleaser/search?q=flatpak) (which surprised me). I'd be glad to revisit if GoReleaser adds support. In the meantime, it's not likely to happen given we already struggle with the resources required to develop and maintain the existing CLI builds and releases. Thanks for the suggestion though, @LongJohn-Silver!

**Comment by jimafisk** [comment]
If folks have interest in flatpak support for Goreleaser, there's an issue that was closed because not enough people seemed to have interest: https://github.com/goreleaser/goreleaser/issues/2927. Maybe add a comment there!
