### ISSUE TITLE
Using exercism CLI with local served exercism website ?

### ISSUE THREAD

**Issue by 2ndTaleStudio** [exercism/cli#953]
Hi,

there is a good explanation how to serve the exercism website locally in the readme at https://github.com/exercism/website.
I was able to set this up successfully, however is there any way to also use the exercism CLI with this local setup ? I can't find any CLI option and was wondering if the exercism.io endpoints are hard coded or if there would be a possibility to use alternative endpoint urls.

Thanks.

**Comment by 2ndTaleStudio** [comment]
After further investigation I found the solution by myself :) 
```
exercism  configure
You have configured the Exercism command-line client:
Config dir:                       /Users/i077570/.config/exercism
Token:         (-t, --token)      0b83edc3-ab97-4ad0-b876-233f41a4f9b9
Workspace:     (-w, --workspace)  /Users/i077570/Exercism
API Base URL:  (-a, --api)        https://api.exercism.io/v1
```

**Comment by kotp** [comment]
You may want to change your token, as it should be treated as a password, and not exposed.

**Comment by 2ndTaleStudio** [comment]
Hi, thanks for the hint :) Did this already ;)

I'm facing a related issue now. I've configured a custom API Base URL and downloaded/submitted an exercise to this endpoint. However, even after re-configuring a different API Base URL - to point to the default one again - the `exercism` cli tool keeps trying to download new exercises from the previous stored api base url. When I check `exercism configure` it prints the new base url. Is there any other kind of *cache*  the download url is stored ?
