### ISSUE TITLE
i cant submit 

### ISSUE THREAD

**Issue by arydevy** [exercism/cli#954]
so i insatalled the cli from source but when i waht to submit i get a error
![image](https://user-images.githubusercontent.com/62546648/91258740-18009700-e73b-11ea-80d0-40f06e3bff66.png)

**Comment by kotp** [comment]
There should be no `hello.c` in the `~/bin` folder.  You will want to be in the location that the exercise was downloaded, the readme.md file resides (and presumably you have read) and the exercise file(s) are created, and the tests ran.

The error that you are getting makes sense, and it appears that perhaps you have installed correctly, but you will normally run the `exercism` executable without giving a relative or absolute path before the command.

Ensure that the `~/bin` folder is in your path, as described in Instructions that can be found at [exercism/cli/releases](https://github.com/exercism/cli/releases)

**Comment by kytrinyx** [comment]
I'm going to close this, as it's very old. If you need assistance in the future please open an issue in https://github.com/exercism/exercism/issues
