### ISSUE TITLE
autocompletion options Oh-my-Zsh error: "can't change type of autoloaded parameter"

### ISSUE THREAD

**Issue by allentiak** [exercism/cli#958]
I'm using Oh-my-Zsh, and I get the following error message when starting a terminal:

`~/.oh-my-zsh/custom/exercism_completion.zsh:local:6: options: can't change type of autoloaded parameter`

I'm using the default autocompletion script, and I can use the program without problems.

**Comment by haakonn** [comment]
I had the same problem, and solved it by following [these instructions](https://github.com/exercism/exercism/issues/5029#issuecomment-533019317).

**Comment by allentiak** [comment]
Thanks for the pointer, @haakonn !
I will monitor #881 .
