### ISSUE TITLE
aarch64 build - or instructions

### ISSUE THREAD

**Issue by jaredmoody** [exercism/cli#966]
Hi, I'm on an aarch64 architecture and so couldn't install the cli via either snap or by downloading from the releases page since there is no aarm64 release.

I was able to install go and build it myself, but it would be nice if there were an aarch64 release - or at least adding instructions for building to the README for architectures with no release.

Thanks!

**Comment by kotp** [comment]
Would you be interested in providing the release and/or the instructions?

**Comment by jaredmoody** [comment]
Yes - I can update that yaml file if that’s all it takes to add a release?

I can send a PR for updating the README with build instructions unless that would be better on the wiki?

**Comment by johankool** [comment]
Hi @jaredmoody, I'd be interested to read those build instructions. Did you share them somewhere yet?

**Comment by jaredmoody** [comment]
@johankool I didn't, and it's been a little while now since I did it, but IIRC it was pretty simple and boiled down to:

- Install go from golang.org or your favorite package manager
- Clone the repo and run `go build` which generated a binary
- Rename/move that binary to exercism and put it somewhere in your PATH

Hope that helps!

**Comment by t0xic0der** [comment]
I can help provide the binaries for I have an active `aarch64` installation lying around. Please tell me how I can assist you.

**Comment by t0xic0der** [comment]
Here's a binary for aarch64 that I built from the `master` branch of `exercism/cli`.
[exercism-aarch64-v3.0.13.zip](https://github.com/exercism/cli/files/6099201/exercism-aarch64-v3.0.13.zip)
