### ISSUE TITLE
Autodetect file to submit

### ISSUE THREAD

**Issue by NChechulin** [exercism/cli#975]
It's a little bit frustrating to type `exercism submit src/lib.rs` every time.
I guess it could be shortened to `exercism submit` by specifying the path to the solution file in `.exercism/metadata.json`.
Then the app will be able to find the file to submit automatically.

**Comment by shekari-ah** [comment]
it's a great idea. if it's possible, I like to implement that.

**Comment by brugnara** [comment]
Hi. 

Nice question.

This requires more than that in my opinion.

I myself sent solutions composed by many files so the CLI should be able to understand all the files composing the solution.

But you may also want to send just a part and not some temporary files you wrote or even you want to send a modified version of the tests.

It could be an option to the CLI, maybe, but not a default behaviour, in my opinion.

**Comment by shekari-ah** [comment]
> I think this might be solved in the future as we've started writing down which files we expect for each exercise 
by @SleeplessByte

**Comment by shekari-ah** [comment]
> Hi.
> 
> Nice question.
> 
> This requires more than that in my opinion.
> 
> I myself sent solutions composed by many files so the CLI should be able to understand all the files composing the solution.
> 
> But you may also want to send just a part and not some temporary files you wrote or even you want to send a modified version of the tests.
> 
> It could be an option to the CLI, maybe, but not a default behaviour, in my opinion.

`exercism submit` can do the default submitting, and `exercism submit src/lib.rs` will be available too

**Comment by pjmagee** [comment]
Each track should have default file extension submission options. For example if I submit a csharp  solution it should know to push `*.cs` and `*.csproj` and `*.sln`. A bit like how `.gitignore` works but on a `track` level.

**Comment by SleeplessByte** [comment]
Nah, it will likely work using the `config.json` file as you can see here: https://github.com/exercism/cli/issues/991

**Comment by pjmagee** [comment]
> Nah, it will likely work using the `config.json` file as you can see here: #991

Ah cool, kind of similar to what I was thinking, per my comment.

**Comment by SleeplessByte** [comment]
Yeah, good idea.

Closing in favour of #991
