### ISSUE TITLE
I CAN'T SUBMIT MY CODE

### ISSUE THREAD

**Issue by tashf33n** [exercism/cli#985]
![errOr](https://user-images.githubusercontent.com/22867010/109231251-067e7180-77e8-11eb-8820-0ab0e13fb2b7.PNG)
I am facing the issue while uploading my code. As per my understanding error shows that i have to upload the code by converting the path into the directory and put the FILENAME of it. Please let me know how should i do it.

Regards

**Comment by NobbZ** [comment]
You need to remove the space character between `…\src` and `\main.rs` to make the binary aware of it beeing a single path.

Though I also expect the solution to live in `src/lib.rs` for any given rust exercise.

**Comment by kotp** [comment]
Closing, as it's been 3 weeks without acknowledgement either way.
