### ISSUE TITLE
gem install minitest failing on Mac

### ISSUE THREAD

**Issue by thelmalu** [exercism/cli#994]
I'm on an iMac, running macOS Big Sur, v 11.2.3 I've used Homebrew to install Exercism (thanks to the Forum for quickly helping me to do this) and configured the CLI. I've joined the Ruby Track and downloaded its first exercise. I'm told that I'll soon need to access testing, so I need to install minitest. I tried to do this with an admin account and got
>>
macTRL ~/Exercism/ruby/hello-world/ Sun 2:51pm 23 May #30: gem install minitest
Fetching minitest-5.14.4.gem
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
>>
That Library dir. is restricted to accounts with root privileges or in the WHEEL group--I've never had an account with these privileges. Mac tech support would say only that I had to speak with the software 'manufacturer'.  Help, please?

**Comment by thelmalu** [comment]
Someone has solved this for me: Even though I was running the command from an admin account, I needed to prefix it with 'sudo'  to permit me to reach the Library directories.

**Comment by kytrinyx** [comment]
I'm glad you got the help you needed. In the future, if you need help please open an issue in https://github.com/exercism/exercism/issues, as this repository is specific to the command-line client for Exercism, not solving exercises in various languages.

**Comment by thelmalu** [comment]
I never made such a post.  Has this gone awry?

**Comment by thelmalu** [comment]
sorry: I just looked at the post--I made it so long ago and resolved
it so long ago that I don't remember anything about it.
