### ISSUE TITLE
Trying to get Exercism's CLI to run locally is not working

### ISSUE THREAD

**Issue by anthonygedeon** [exercism/cli#998]
I created a directory in my ~/.config file for testercism and copied my user.json but the error still happens.  Maybe the contributing.md needs to be updated

Here's the issue

After running:

`cd /path/to/the/development/directory/cli && go build -o testercism main.go` 

I get the resulting error:

`no required module provides package main.go; to add it:
	go get main.go
`

EDIT:
I changed dir into exercism and ran` go build -o testercism main.go ` and everything seems to work? Unsure if this is right though

**Comment by SleeplessByte** [comment]
cc @exercism/go

**Comment by fsmiamoto** [comment]
>  changed dir into exercism and rango build -o testercism main.go and everything seems to work? Unsure if this is right though

@anthonygedeon That should be it! Looks like the instructions for *nix got outdated, the Windows one looks right though:
```
go build -o testercism.exe exercism\main.go
```

**Comment by ekingery** [comment]
Closed by #1005, however we can't merge that because Travis... I don't think this is worth holding open, as the fix is above and in that PR.
